### ISSUE TITLE
ValueError: Segmentation output is not valid SEG format

### ISSUE THREAD

**Issue by wjaratlerdsiri** [etal/cnvkit#106]
Hello Author,

Could you suggest me with the following error?

Wrote FR0_hg38_reference.update.cnn
Running 1 samples in serial
Running the CNVkit pipeline on Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2.realigned2.NTrealign.bam ...
Processing reads in Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2.realigned2.NTrealign.bam
Time: 197230.233 seconds (9380 reads/sec, 74 bins/sec)
Summary: #bins=14619544, #reads=1849989201, mean=126.5422, min=0.0, max=127123.23 
Percent reads in regions: 114.215 (of 1619748618 mapped)
Wrote Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2.targetcoverage.cnn
Skip processing Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2.realigned2.NTrealign.bam with empty regions file empty.bed
Wrote Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2.antitargetcoverage.cnn
Processing target: Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2
Keeping 14523336 of 14619544 bins
Correcting for GC bias...
Correcting for density bias...
Weighting bins by relative coverage depths in reference
Weighting bins by coverage spread in reference
Processing antitarget: Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2
Wrote Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2.cnr
Segmenting cnvkitFR07887777_FR07887773.200.mHG38/Clean3_merged23_150913_FR07887777_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2.cnr ...
Dropped 2 outlier bins:
  chromosome      start        end     gene      log2    weight
0       chr3  195909159  195909359    PROS1 -3.513770  0.248502
1      chr17   44967967   44968167  MIR4522 -4.793657  0.270724
Traceback (most recent call last):
  File "cnvkit.py", line 5, in <module>
    pkg_resources.run_script('CNVkit==0.7.11', 'cnvkit.py')
  File "/usr/local/python/2.7.9/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 499, in run_script
  File "/usr/local/python/2.7.9/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 1239, in run_script
  File "/lib/python2.7/site-packages/CNVkit-0.7.11-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 11, in <module>
    args.func(args)
  File "/lib/python2.7/site-packages/CNVkit-0.7.11-py2.7.egg/cnvlib/commands.py", line 117, in _cmd_batch
    args.diagram, args.rlibpath, args.count_reads))
  File "/lib/python2.7/site-packages/CNVkit-0.7.11-py2.7.egg/cnvlib/parallel.py", line 14, in apply_async
    func(*args)
  File "/lib/python2.7/site-packages/CNVkit-0.7.11-py2.7.egg/cnvlib/commands.py", line 215, in batch_run_sample
    segments = segmentation.do_segmentation(cnarr, 'cbs', rlibpath=rlibpath)
  File "/lib/python2.7/site-packages/CNVkit-0.7.11-py2.7.egg/cnvlib/segmentation/__init__.py", line 58, in do_segmentation
    segarr = cnarr.as_dataframe(seg2cns(seg_out))
  File "/lib/python2.7/site-packages/CNVkit-0.7.11-py2.7.egg/cnvlib/segmentation/__init__.py", line 143, in seg2cns
    + seg_text)
ValueError: Segmentation output is not valid SEG format:
WARNING: ignoring environment value of R_HOME
"sampleName"	"chromosome"	"start"	"end"	"nbrOfLoci"	"mean"
"Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2"	"chr1"	10400	40010	146	0.261269921083404
"Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2"	"chr1"	40010	92027	242	-0.265592863407929
"Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2"	"chr1"	92027	142044	249	0.156494661443839
"Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2"	"chr1"	142044	154248	59	-0.440204366407358
"Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2"	"chr1"	154248	174454	99	-0.177414490636111
"Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2"	"chr1"	174454	178256	18	0.0516595860296953
"Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2"	"chr1"	178256	200463	111	0.41853174494091
"Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2"	"chr1"	200463	203264	14	0.159293774926751
"Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2"	"chr1"	203264	258065	23	-0.0203521925601479
"Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2"	"chr1"	258065	261257	16	0.501213680297145
"Clean3_merged23_150913_FR_hg38_fix_kmer_q15_TrimN_N0_L70_recal_sort2_dedup2"	"chr1"	261257	269437	38	0.873232771046872

I made BAM file with gatk hg38 (chr1 - chrM), but repeats have not soft-masked in that reference. I have changed and used ucsc hg38 (chrs + other scaffolds) to run cnvkit with the gatk BAM file. I am not sure whether this is a problem. Thankyou for your explanation

James

**Comment by etal** [comment]
R is unhelpfully inserting the "WARNING: ..." message into the same text stream as the expected segmentation output, so that extra initial line breaks parsing.

I'll see if I can fix CNVkit to skip that line if it appears. In the meantime, you can avoid the error by unsetting the environmental variable "R_HOME" in the shell where you're running CNVkit.

Globally:

    export R_HOME=""

Or, per command:

    R_HOME="" cnvkit.py segment Clean3.cnr

(If you have the .cnr files for all of your samples now, you don't need to re-run the `batch` command; the `segment` command shown above will run on the .cnr files. Also, consider the option `--drop-low-coverage` if these are tumor samples.)

**Comment by wjaratlerdsiri** [comment]
THX,

To be successful, I used:
$unset R_HOME
$cnvkit.py segment Clean3.cnr

James

**Comment by etal** [comment]
Thanks for letting me know. The code in GitHub should now handle this case even if the warning is present / `R_HOME` is still set.
