### ISSUE TITLE
Interest in conda travis grid?

### ISSUE THREAD

**Issue by kyleabeauchamp** [etal/cnvkit#109]
Is there any interest in me porting the conda-based travis CI code from bioconda and pysam?  I could easily test on a grid of [python2.7, python3.5] versus [pysam 0.8.5, pysam 0.9.0].  The downside is that we'd be testing only on anaconda python.

**Comment by etal** [comment]
Yes, definitely! I haven't been able to get CNVkit with Python 3 to install
cleanly on Travis CI via pip, so conda is the way to go.

**Comment by kyleabeauchamp** [comment]
Fixed in #110
