### ISSUE TITLE
CNV detected across the whole genome

### ISSUE THREAD

**Issue by JoKw** [etal/cnvkit#118]
Hi, I have sequenced a tumor/normal pair using a small capture panel and tried to call CNVs using the program. However, I got copy number gains in nearly every part of the genome. May I know how to fix it. Thanks

**Comment by etal** [comment]
You might be able to fix the problem by recentering the .cnr files before segmentation, or the .cns files after segmentation. You can use the `call` command to do this:

    cnvkit.py call Sample.cnr -m none --center biweight -o Sample.biweight.cnr
    cnvkit.py call Sample.cnr -m none --center mode -o Sample.mode.cnr

Use the `scatter` command to see whether either recentered version looks more correct, then use the best recentering method to finish the rest of your analysis.

If you're analyzing tumor samples, also try the `--drop-low-coverage` option when you run the `segment` command
