### ISSUE TITLE
Issue creating coverage file

### ISSUE THREAD

**Issue by murphycj** [etal/cnvkit#119]
After running

    python /Users/charlesmurphy/lib/cnvkit/cnvkit.py coverage ../BWAGATK/HL-WES-39/HL-WES-39.gatk.bam /Users/charlesmurphy/data/refdata/GRCm38/cnvkit/my_antitargets.bed -o HL-WES-39.antitargetcoverage.cnn

I get the following error message

    Traceback (most recent call last):
        File "/Users/charlesmurphy/lib/cnvkit/cnvkit.py", line 13, in <module>
            args.func(args)
        File "/Users/charlesmurphy/lib/cnvkit/cnvlib/commands.py", line 476, in _cmd_coverage
            pset = do_coverage(args.interval, args.bam_file, args.count, args.min_mapq)
        File "/Users/charlesmurphy/lib/cnvkit/cnvlib/commands.py", line 499, in do_coverage
            min_mapq)
        File "/Users/charlesmurphy/cnvkit/cnvlib/coverage.py", line 61, in interval_coverages
            meta_dict={'sample_id': fbase(bam_fname)})
        File "/Users/charlesmurphy/lib/cnvkit/cnvlib/gary.py", line 71, in from_rows
            table = pd.DataFrame.from_records(rows, columns=columns)
        File "/Users/charlesmurphy/lib/python2.7.8/lib/python2.7/site-packages/pandas/core/frame.py", line 981, in from_records
            coerce_float=coerce_float)
        File "/Users/charlesmurphy/lib/python2.7.8/lib/python2.7/site-packages/pandas/core/frame.py", line 5352, in _to_arrays
            dtype=dtype)
        File "/Users/charlesmurphy/lib/python2.7.8/lib/python2.7/site-packages/pandas/core/frame.py", line 5431, in _list_to_arrays
            coerce_float=coerce_float)
        File "/Users/charlesmurphy/lib/python2.7.8/lib/python2.7/site-packages/pandas/core/frame.py", line 5489, in _convert_object_array
            'columns' % (len(columns), len(content)))
    AssertionError: 6 columns passed, passed data had 5 columns

The first few lines of my_targets.bed

    1	3680570	3680912	-
    1	4344451	4344553	Rp1
    1	4344599	4344860	Rp1
    1	4344860	4345122	Rp1

The first few lines of my_antitargets.bed

    1	3000500	3227023	Background
    1	3227023	3453546	Background
    1	3453546	3680070	Background
    1	3681412	3902258	Background

First two reads in my bam file

    ST-K00128:79:H5V2KBBXX:4:2210:24890:15680	163	1	3006718	29	42M1D56M3S	=	3006834	217	AAAGGAAGAAATGATGCAATTATATTGTAATAAACAAAATAGAAAAAAAAAAAAAAAGAAAAACGGAATGGGAAAAAAAAAGAAAAAAAAAAAAAAAAAAA	>=<?==<?=>>,/>,/*=?9,<,<>+:<;><<,,6=???=<A???????????????-?+,>?*'=?<,.,,>>?@?@???.?@@.?@????.>>==<.8>	MC:Z:101M	BD:Z:KKFLNLLJJLEKMMLMMMLKJIKLKJKILKKLKEKHLEEKMMLMFFFFFFFFFFFFFLLMFFFLLLLMMNNGMNGGGGGGGMMNGGGGGGHHHHHHIFFFF	MD:Z:32T0C8^A17G0T24G6G5	PG:Z:MarkDuplicates	RG:Z:HL-WES-40	XG:i:1	BI:Z:MMIMNNMMKMHLMLMMMNLLILLLLIMLMKLLKHKKLHHMLNLMIIIIIIIIIIIIIMLMIIILMNMMMNMHMMIJIIJIINLMJJIIIIHHHIIJKIIII	AM:i:29	NM:i:7	SM:i:29	XM:i:6	XO:i:1	MQ:i:29	XT:A:M
    ST-K00128:79:H5V2KBBXX:4:2210:24890:15680	83	1	3006834	29	101M	=	3006718	-217	GAAAAAAAGCCCCCTTTTCCCCCTTTGATTTTTCTCCTTAAAATATTCGGGCAAGAAAGGATAGATAGAAAGGACATCAAAGTTCAGGTAACAAACTGTGT	>;::;<<?A????A????????A??@@=?????A??A?<====<=??=??A@=@@==@?@=<@@=<@@==@?@=@=?@==@@??@@?@<==@===A=@=?@	X0:i:1	X1:i:0	MC:Z:42M1D56M3S	BD:Z:KFFFHHMPNGGGNMGGNMGGGNMGNOOMGGGNMMMMMLJFFKLMLMNLGNNLKKKFKLMNLLKNLLKKFKLMMJNMNLFKLLMNNLMMKLKMGMOPLJIKK	MD:Z:101	PG:Z:MarkDuplicates	RG:Z:HL-WES-40	XG:i:0	BI:Z:NHHHJIMOMGGGMMIIMMHHHMMIMNNMIIIMLMMMMLMHHJMMMMONIOMMLLMGLLLMLMLMLMLMGLLLNLMMLMGLMKLLMLLMLLLNHMOOLLLMM	AM:i:29	NM:i:0	SM:i:29	XM:i:0	XO:i:0	MQ:i:29	XT:A:U

But I can avoid the error if I add the following to line 69 of the from_rows class method of GenomicArray class in gary.py

    if columns==('chromosome', 'start', 'end', 'gene', 'log2', 'ratio'):
        columns=('chromosome', 'start', 'end', 'gene', 'log2')

I did this because when I traced the contents of columns and rows in the from_rows method I saw the following example values for the rows and columns variables

    rows=[('1', 3000500, 3227023, 'Background', 0.0), ('1', 3227023, 3453546, 'Background', 0.0),...]
    columns=('chromosome', 'start', 'end', 'gene', 'log2', 'ratio')

**Comment by murphycj** [comment]
Never mind, I dimly downloaded the latest development version. I just downloaded the latest release instead (0.7.11) and now have no problems. So this is not an issue for me, but may nonetheless be to you. Close this if you want

**Comment by etal** [comment]
Thanks for the report and sorry for the trouble. I made some problematic changes in the repo this week that I've mostly reverted to maintain issues like this one. Enjoy v0.7.11, but feel free to try the development version and report any bugs you see in the future.
