### ISSUE TITLE
Parallelize segmentation across chromosomes

### ISSUE THREAD

**Issue by etal** [etal/cnvkit#123]
Segmentation is a bottleneck with CBS (especially) and deeply sequenced exomes or WGS. The segmentation methods generally segment each chromosome independently, so this could be done in parallel.

The R scripts for CBS and FusedLasso could be rewritten to do one segment instead of the whole genome. Alternatively, recent PSCBS does its own parallelization, which could be used to easily parallelize the "cbs" method but not "flasso".  (Haar does not use R, but is already fast.)

Note that in the unfortunate case of thousands of segments per chromosome, the real bottleneck may be in `transfer_names_weights` where the `GenomicArray.by_ranges` method is used to match up segments to the original probes. A workaround here would be to change the output of each of the segmentation methods to return the original probe array annotated with the assigned segments (e.g. an additional column enumerating the segments), which the calling function then squashes into one row per segment.

**Comment by brentp** [comment]
see #125
