### ISSUE TITLE
getting floats in bed output for start/end

### ISSUE THREAD

**Issue by brentp** [etal/cnvkit#127]
I have a line like this:
```
1	2.61344e+06	2692720	-	0.702974	59	38.7089
```
in a .cns output file that is messing up downstream tools trying to parse start,end as int.

**Comment by brentp** [comment]
maybe this can be resolved with:
```Patch
diff --git a/cnvlib/tabio/bedio.py b/cnvlib/tabio/bedio.py
index 6298b44..9dd120d 100644
--- a/cnvlib/tabio/bedio.py
+++ b/cnvlib/tabio/bedio.py
@@ -64,6 +64,8 @@ def read_bed6(infile):
 # _____________________________________________________________________
 
 def write_bed(dframe):
+    for c in (1, 2):
+        dframe.ix[:, c] = dframe.ix[:, c].astype(int)
     if len(dframe.columns) == 3:
         return write_bed3(dframe)
     elif len(dframe.columns) == 3:
```

**Comment by etal** [comment]
Ack, that should not be. I don't see this happening in my own files in general. Could you show me how to replicate it? Ideally the start and end columns will always be int, per GenomicArray._required_dtypes.

**Comment by brentp** [comment]
not sure how to recreate. I am using python2 with recent version. do_segmentation is not enforcing the int columns after getting the data back from R?

This might be something that I introduced with my recent parallelization changes.

**Comment by kyleabeauchamp** [comment]
Could this have to do with NAN's appearing somehow?  NANs in a DF will force cast from int to float.

**Comment by brentp** [comment]
I think it's somehwere in the text->int conversion. R will output 1600000 as 1.6e6 unless you specify some options.

**Comment by etal** [comment]
Could you try it again with the latest? This should force the coordinates back to integer types when the segment CopyNumArray is instantiated after running CBS.

**Comment by brentp** [comment]
I haven't seen this since I reported and then updated to 844bcf2

**Comment by etal** [comment]
Great, thanks!
