### ISSUE TITLE
mutect2 file error

### ISSUE THREAD

**Issue by ramaniak** [etal/cnvkit#130]
Hello,
I am trying to use CNVKit to generate input files for use with theta2:

I first ran cnvkit.py batch and got a my 'cnr' file which I then converted to a 'cns' file using cnvkit.py segment. (Is the batch code supposed to automatically convert 

When I try

```
 cnvkit.py export theta *cns 

```

I can generate the interval_count file but when trying to include the vcf as well (see below) I get an error.

```
cnvkit.py export theta A3.cns ../Homo_sapiens.GR7.cnn -v A3.concat.mutect2.vcf

Warning message:
In local({ : bytecode version mismatch; using eval
Error in nchar(.Library.site) : 
  4 arguments passed to .Internal(nchar) which requires 3
Error in .Internal(getOption(x)) : 
  there is no .Internal function 'getOption'
Error in .Internal(getOption(x)) : 
  there is no .Internal function 'getOption'
Second positional argument normal_reference is deprecated; use --reference instead.
Wrote A3.interval_count
Traceback (most recent call last):
  File "/hpf/tools/centos6/python/2.7.9/bin/cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.7.11', 'cnvkit.py')
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/setuptools-15.0-py2.7.egg/pkg_resources/__init__.py", line 723, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/setuptools-15.0-py2.7.egg/pkg_resources/__init__.py", line 1643, in run_script
    exec(script_code, namespace, namespace)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/CNVkit-0.7.11-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 11, in <module>

  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 1828, in _cmd_export_theta

  File "build/bdist.linux-x86_64/egg/cnvlib/vary.py", line 64, in read_vcf
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/vcf/parser.py", line 288, in __init__
    self._parse_metainfo()
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/vcf/parser.py", line 321, in _parse_metainfo
    key, val = parser.read_format(line)
  File "/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/vcf/parser.py", line 159, in read_format
    "One of the FORMAT lines is malformed: %s" % format_string)
SyntaxError: One of the FORMAT lines is malformed: ##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
```

Not sure if I am doing anything incorrectly here.

Thanks
Arun

**Comment by etal** [comment]
It looks like PyVCF does not like this VCF file. I've gotten the current development version of CNVkit (and therefore PyVCF) to load a VCF from MuTect2, so maybe updating your PyVCF installation would fix the problem.

Test your PyVCF installation in your Python interpreter like this:

    >>> import vcf
    >>> vr = vcf.Reader(filename="A3.concat.mutect2.vcf")
    >>> for line in vr: pass

The only unusual thing I see in the reported FORMAT line is "Number=R" -- in my MuTect2 VCF, the equivalent line defining the AD field has "Number=." instead. So if you can't get PyVCF by itself to read this VCF file as it is, try replacing the `R` with `.`.

**Comment by ramaniak** [comment]
Hi Eric,
Thanks for the quick response. I did try what you suggested and get the
following error:

>>> import vcf
>>> vr = vcf.Reader(filename="A3.concat.mutect2.vcf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/vcf/parser.py",
line 288, in __init__
    self._parse_metainfo()
  File
"/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/vcf/parser.py",
line 321, in _parse_metainfo
    key, val = parser.read_format(line)
  File
"/hpf/tools/centos6/python/2.7.9/lib/python2.7/site-packages/vcf/parser.py",
line 159, in read_format
    "One of the FORMAT lines is malformed: %s" % format_string)
SyntaxError: One of the FORMAT lines is malformed:
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the
ref and alt alleles in the order listed">

when I tried the same thing after replacing the "##FORMAT=<ID=AD,Number=R"
with  ##FORMAT=<ID=AD,Number=.", the second error went away.

I will try the rest with this and see if it works.

Thanks very much
Arun
