### ISSUE TITLE
Genotype inference in Mutect1.x generated VCF and LOH-plots

### ISSUE THREAD

**Issue by avalind** [etal/cnvkit#132]
Hello,

I've been trying to combine copy number data from cnvkit with .vcf-files of tumor/normal-pairs from MuTect1, but due to the fact that Mutect1 doesn't emit any meaningful genotype data for calls found to be non-somatic (all GT fields for the normal sample is simply 0) all variants get filtered by cnvkit as somatic.

A quick workaround is to remove the filtering of somatic variants (which of course will include true somatic variants into the LOH-plots. Of course  one could remove these from the .VCF-file prior to usage with cnvkit.)

I suppose there isn't much to do about this since the problem is with Mutect1 and that people are moving on to Mutect2. But I guess that it might be helpful if this issue is highlighted in the documentation.

Cheers,
Anders

**Comment by etal** [comment]
Thanks for letting me know. There is some code in CNVkit (see #102) for working around missing genotypes, but it's not directly usable from the command line. In Python, you can read the VCF file with `cnvlib.tabio.read(filename, "vcf")` and extract the SNVs that are heterozygous in the normal sample with the resulting object's method `.heterozygous(min_freq=.16, max_freq=.84)`, then see/use the implementations in `cnvlib.commands.do_*` to carry out the rest in Python. 

You could also work around it with PyVCF by assigning genotypes based on allele frequencies, then writing out an updated VCF to use with CNVkit. That might be quicker.

**Comment by etal** [comment]
The option to override the VCF genotypes is available on the command line now as `-z`/`--zygosity-freq` in the commands that use heterozygous SNPs. In the API it's the new method `VariantArray.zygosity_from_freq(het_freq=.25, hom_freq=.75)`.
