### ISSUE TITLE
cnn_updater.py not found

### ISSUE THREAD

**Issue by maojn** [etal/cnvkit#133]
Hi,

I have installed cnvkit package but found no cnn_updater.py in the bin dir. Please advise. Thanks.

**Comment by etal** [comment]
How did you install CNVkit, and can you confirm you have the latest version? With pip or conda, the script should be somewhere in your path -- not necessarily /usr/local/bin, but wherever cnvkit.py went.

If cnvkit.py works for you but cnn_updater.py is missing, you could try just going ahead without that script and rely on cnvkit.py to do the conversions on the fly -- please let me know if it fails to do so at any point.

**Comment by maojn** [comment]
Hi, I have successfully installed 0.8.0 finally. Conda install somehow pull down earlier version. But I managed to make it work. Thank you.

**Comment by etal** [comment]
Great, thanks for letting me know.
