### ISSUE TITLE
Consider samtools depth to replace bedcov

### ISSUE THREAD

**Issue by etal** [etal/cnvkit#134]
As discussed in chapmanb/bcbio-nextgen#1549, `samtools depth` can be used to quickly calculate coverage depths and, with @brentp's extensions in brentp/goleft, the reference genome's GC and RepeatMasked fractions.

In the latest samtools version 1.3.1, both `depth` and `bedcov` are lightly documented but present in the top-level listing of available commands.

**Comment by brentp** [comment]
I'm happy to help if you decide to try goleft depth.

**Comment by kyleabeauchamp** [comment]
FWIW, the latest pysam now has the helpful functions `count()` and `count_coverage()`, which return the per-base (ACGT) and per-read coverages:

http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile.count

http://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile.count_coverage

IMHO, it would be awesome to push improvements to these upstream to pysam and / or HTSLib.  E.g. something like generalizing to a list of regions, rather than a single region.

**Comment by kyleabeauchamp** [comment]
Although obviously `samtools` is fully upstream, I guess I'm thinking about more "programmatic" access...

**Comment by etal** [comment]
Thanks! I'm going to leave this open for a bit and see how chapmanb/bcbio-nextgen#1549 resolves, then it may be more clear how to take advantage of the available tools we have available.

It looks like `pysam.AlignmentFile.count(..., read_callback="all")` should be used in the implementation of `coverage --count` instead of iterating over the reads directly.

**Comment by etal** [comment]
It looks like `bedcov` is exactly the right thing to use in `coverage`; the pysam methods count reads that overflow the the region boundaries, which is not right. But I found a use for `samtools depth` in `scripts/guess_baits.py`, basically a peak caller that again has specific functionality that is almost-but-not-quite covered by goleft.

**Comment by brentp** [comment]
what is the functionality not covered by goleft?

**Comment by etal** [comment]
I might have misunderstood how goleft works. Does it attempt to pinpoint the enriched regions' boundaries at single-base resolution, or within fixed windows/bins?

`guess_baits.py` has 2 modes:
1. Guided: Take a BED of candidate targets, get the mean coverage in each bin with `bedcov`.
2. Unguided: Scan for depth one base at a time, not in a window; where depth pops above a given level, start recording depths within this enriched region; when depth falls below the level again, draw region boundaries where the coverage falls below 1/2 that region's peak, and emit that as a candidate bin.

Both modes then find the mode of the coverage distribution (above an initial lower bound, to avoid 0 or 1 from being the mode), and drop candidate bins with coverage below a given fraction of the mode.

Surely there are better peak finders (e.g. designed for ChIP-seq), but most seem a tad cumbersome for this use case and they mostly don't seem to attempt single-base resolution. I'm not sure if this is the sort of thing you'd like to include in goleft, but if so, I'd be happy to help porting/reviewing it and then just drop this script and point CNVkit users to goleft.

**Comment by etal** [comment]
Redirecting to #179, samtools depth is not the answer but imma follow up on goleft depth.
