### ISSUE TITLE
Wrong cns to seg format conversion

### ISSUE THREAD

**Issue by wjaratlerdsiri** [etal/cnvkit#137]
Hi Etal,

Could you check "cnvkit.py export seg"?

I have a weird result from it.

#My original file
chr10	135416969	135453969	NPY4R	0.160247	1	166.318
chr10	135453969	135473769	NPY4R	0.557949	7	46.108
chr10	135474369	135479369	NPY4R	0.13051	2	18.3423
chr10	135502567	135524547	-	0.231735	1	94.247
chr11	60199	68399	LINC01001	-0.109313	4	36.1146
chr11	68399	83399	LINC01001	0.155567	7	65.4562

#My seg file after conversion

UP2-T	10	146138020	146149021	5	0.483687
UP2-T	10	146149021	146172021	1	0.618827
UP2-T	10	146172021	146180421	4	0.575998
UP2-T	10	146180421	146227221	2	0.70452
UP2-T	10	146227221	146279421	2	0.825419
UP2-T	10	146279421	146301421	1	1.04315
UP2-T	11	42669510	42715110	2	0.225331
UP2-T	11	42715110	42732910	8	0.41549

I have checked hg19.dict and found that chr10 has LN=135534747bp. 

Do you have any idea for this? happy to give more info. Thanks

Cheers,
James

**Comment by etal** [comment]
Thanks for reporting. Are you using the latest version of CNVkit (0.8.0)? I just tried converting the lines posted here and it worked as expected.

Also strange, did "chr10" and "chr11" get converted to "10" and "11"? Are you sure the sample in the .cns file corresponds to the lines you're looking at in the SEG file? You might have picked up a different .cns file with `cnvkit.py export seg *.cns`, for example.
