### ISSUE TITLE
cnvkit batch parallelism

### ISSUE THREAD

**Issue by brentp** [etal/cnvkit#138]
Hi Eric,
I think there might be a problem with cnvkit batch. It seems like it's running too many jobs.

I think maybe the main batch command is running `batch_run_sample,` with `-p` processes and each of those is told to use -p processes. This leads to a huge propagation in the number of cnvkit.py procs that I can see running on the machine.

I would guess that line 115 of cnvlib/commands.py would need to send 1 as the number of processes to `batch_run_sample`. Or maybe send `len(args.bam_files) // args.processes`

**Comment by etal** [comment]
You're right, that was unwise of me. I'll change it to `max(1, args.processes // len(args.bam_files))` and/or see about reusing the worker pool in do_coverage and do_segment. In the meantime maybe use `-p [square root of the number of cores available]`.
