### ISSUE TITLE
AssertionError in pyfaidx

### ISSUE THREAD

**Issue by holtgrewe** [etal/cnvkit#141]
cnvkit hands in numpy integers and there are assertions `isinstance(start, int)` in `Faidx.from_file`...

**Comment by etal** [comment]
Which version of pyfaidx are you using, is this a new/recent release?

**Comment by holtgrewe** [comment]
Whatever comes when installing `pip cnvkit` with Python 3 at the moment. I think the problem might be Python 3.

- numpy integers are given into pyfaidx and cause an assertion error
- using `cnvkit.py access` also causes a problem because of the `== 'N'` comparison which has to be `== b'N'` in Python 3 for some reason

**Comment by etal** [comment]
This is fixed in the development version now. Thanks for reporting.
