### ISSUE TITLE
Recommendations for SNV VCF files

### ISSUE THREAD

**Issue by holtgrewe** [etal/cnvkit#142]
Hi,

what are good recommendations for VCF files to put into CNVkit? I did not find anything on this in the manual...
- Should I use the results of a somatic variant caller such as Mutect or rather "raw" variant calls of the tumor only?
- Should I prefilter this to high-confidence calls, e.g., remove off-target calls and those of low coverage or will cnvkit take care of this?

Thanks

**Comment by etal** [comment]
CNVkit tries to be flexible in the VCFs it accepts. Here are the general recommendations:
http://cnvkit.readthedocs.io/en/v0.8.0/fileformats.html#vcf

- If you use Mutect, give CNVkit the complete set of SNV calls including "rejects", not filtered for somatic SNVs.
- If the "SOMATIC" field isn't set in the VCF, then consider removing the "KEEP" records to retain only the germline SNVs.
- You'll see better b-allele frequency estimates from true germline SNPs, so filtering by quality score can help. In most CNVkit commands that take a VCF, e.g. `scatter`, there is a `-m/--min-variant-depth` option that you can use to filter out low-coverage calls on the fly.

If you see the current version of CNVkit fail to load the unmodified output of a popular SNV caller like Mutect or Mutect2, please let me know and I'll try to fix it.
