### ISSUE TITLE
Extract locus depths, allele freqs from bcftools VCF

### ISSUE THREAD

**Issue by jirianto** [etal/cnvkit#146]
Hi etal,

Thank you for this awesome algorithm, it worked well with our exome-seq data, really comparable to our aCGH data of the same sample!!

I was trying to check clonality of the sample, input as follow:
cnvkit.py export theta C1Ctrl.cns reference.cnn -o C1Ctrl.theta2.interval_count

I have my reference file as "reference.cnn"

But error came out:
usage: cnvkit.py [-h]
                 {batch,target,access,antitarget,coverage,reference,fix,segment,call,diagram,scatter,heatmap,breaks,gainloss,gender,metrics,segmetrics,import-picard,import-seg,import-theta,export,version}
                 ...
cnvkit.py: error: unrecognized arguments: reference.cnn

Ideas?

Thanks,
Jerome

**Comment by etal** [comment]
Sure, the command options just changed a little. Add `-r` before reference.cnn to use it:

     cnvkit.py export theta C1Ctrl.cns -r reference.cnn -o C1Ctrl.theta2.interval_count

**Comment by jirianto** [comment]
Worked like a charm!! Thank you Eric!!!

Another question, only if you have time ...
I'm planning to do theta2 analysis, but I don't have 'normal' sample to produce the VCF file in 'mpileup' ... Can I make a VCF file in 'mpileup' by using a human genome reference?
Or I should just do the theta2 without the optional SNP data?

Thank you,
Jerome

**Comment by etal** [comment]
THetA2 will work without the SNP data, but without it the runtime can be extremely long / effectively infinite for the full run (n=3). But in many cases it's fine without SNPs, and if you don't search for subclones (n=2) it's fast either way. Maybe try it and kill the program if the estimated run time is huge.

Using a reference genome as the paired normal might be fine. You can probably avoid repeating variant calling over the whole by downloading the reference calls from GIAB or 1000 Genomes and subsetting that to your exome / panel with bedtools.

**Comment by jirianto** [comment]
Thank you Eric, it works without the SNP data, took around 1.5 hrs on my laptop, provided n=2 data, but it only tell me % of regions that deviate from diploid ... I guess I need to look for different algorithm to tell the clonality of my sample.

Another question: We also ran aCGH on the samples that we submitted for WES. I ran CNVkit on these WES data, comparing it to "flat" reference. The copy number pattern from CNVkit resemble the aCGH data very nicely, but it's all shifted by -1 copy number. Such that, diploid in aCGH is represented as copy number 1 (or -0.5 in the log2 scale) in the CNVkit. The samples come from a cancer cell line that mostly have copy number 3-4, are there some corrections that I need to input maybe?

Thank you,
Jerome

**Comment by etal** [comment]
Hmm, the clonality percentages should be visible in THetA2's output, at least at the top of the generated PDF plots and in the tabular results file as the second column (iirc), listed as two numbers separated by commas. I recommend asking their Google Group if you're not seeing this. CNVkit's `import-theta` command will convert the resulting (filtered) segments to .cns but doesn't have a way to store the clonality fractions, so you'll have to save these numbers separately.

It sounds like your aCGH data might be off-center somehow. If so, you could possibly fix that with `cnvkit.py call -m none --center median`. Also consider using the `--drop-low-coverage` option in `segment` and elsewhere -- poorly captured bins can pull down the segment means. The average ploidy shouldn't matter until you attempt to call integer copy number, but at that point you might want to specify `--ploidy 4` and see how it goes.

**Comment by jirianto** [comment]
Hi Eric,

I'm trying to do theta export using the corresponding VCF file.

I ran mpileup with the following line:
samtools mpileup -ugf hg19.fa C1Ctrl.Aligned.out.bam | bcftools call -vmO z -o C1Ctrl.raw.vcf.gz

Then run theta export with the following line:
cnvkit.py export theta C1Ctrl.cns -r reference.cnn -v C1Ctrl.raw.vcf

Then get the error:
Wrote C1Ctrl.interval_count
Depth info not available for filtering
Loaded 216703 records; skipped: 0 somatic, 0 depth
Selected test sample C1Ctrl.Aligned.out.bam and control sample 
Traceback (most recent call last):
  File "/home/jerome/miniconda2/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/jerome/miniconda2/lib/python2.7/site-packages/cnvlib/commands.py", line 1875, in _cmd_export_theta
    tumor_snps, normal_snps = export.export_theta_snps(variants)
  File "/home/jerome/miniconda2/lib/python2.7/site-packages/cnvlib/export.py", line 477, in export_theta_snps
    table["ref_depth"] = (table[depth_key] - table[alt_key]).astype("int")
  File "/home/jerome/miniconda2/lib/python2.7/site-packages/pandas/core/generic.py", line 2950, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/home/jerome/miniconda2/lib/python2.7/site-packages/pandas/core/internals.py", line 2938, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/home/jerome/miniconda2/lib/python2.7/site-packages/pandas/core/internals.py", line 2890, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/jerome/miniconda2/lib/python2.7/site-packages/pandas/core/internals.py", line 434, in astype
    values=values, **kwargs)
  File "/home/jerome/miniconda2/lib/python2.7/site-packages/pandas/core/internals.py", line 477, in _astype
    values = com._astype_nansafe(values.ravel(), dtype, copy=True)
  File "/home/jerome/miniconda2/lib/python2.7/site-packages/pandas/core/common.py", line 1914, in _astype_nansafe
    raise ValueError('Cannot convert NA to integer')
ValueError: Cannot convert NA to integer


Not sure where the NA is located ...

Thank you,
Jerome Irianto

**Comment by etal** [comment]
It looks like CNVkit was not detecting the VCF's depth fields successfully, so it filled in NA values, which are only valid for the `float` type and not `integer`. I have a fix ready to avoid the crash, and I'll look into detecting the depths properly.

(Incidentally: when I run your samtools+bcftools command on another target panel BAM, I get about 800,000 variant calls, of which about 2,000 are probably real.)

**Comment by jirianto** [comment]
Thank you Eric!!! I should replace commands.py and exports.py with the ones you updated?

So it seems I also used the samtools+bcftools wrongly? I'll read more on this.

Thank you so much for your patient, I'm still at the trial and error stage ....

Thank you,
Jerome Irianto

**Comment by etal** [comment]
If you'd like to try the development version of CNVkit, I recommend using git to stay in sync, rather than replacing files individually. The latest commit doesn't recover the correct depth values, it just prevents a crash -- the output SNP files have value 0 for every site, so they won't be useful to you yet.
