### ISSUE TITLE
scatter: Allow coloring points by gain/loss 

### ISSUE THREAD

**Issue by etal** [etal/cnvkit#157]
Draw the scatter plot with bin-level point colors set differently if the points support a gain or loss, e.g. coloring gain-supporting points red and loss-supporting points blue. See also Control-FREEC plots.

Approaches:

1. By bin: use a hard threshold or two on the bin log2 values to extract subsets, then assign different colors to those subsets.
2. By segment: apply the threshold to segment log2 values instead to identify gain/loss regions, then select the points in those regions for colorization.
3. By segment `cn` value, set first by the `call` command.

Leaning toward 3 to keep the different concerns separate.

**Comment by lavv2** [comment]
Hi Eric,

Thanks for this great tool !

About colouring  by gain/loss. What is the argument for doing that? (or maybe it is done by default)

**Comment by etal** [comment]
This feature doesn't exist yet. It might be in the v0.9 release within the next couple of months.
