### ISSUE TITLE
question: how to qc runs?

### ISSUE THREAD

**Issue by dwaggott** [etal/cnvkit#160]
I'm calling germline samples using a reference that was built using a all 268 exomes in the cohort. There is some structure to the exomes i.e. some are 10GB vs 4GB and there likely was capture version change that corresponds with the depth. The reference doesn't take into account gender and females are about 20%.

Question:

1. What would you recommend for QC'ing runs? 

2. Does `--purity` default to 1 with `clonal` calling? The cn=3 calls below don't seem to translate from a direct integer rounding from the log2.

3. Gender also doesn't seem to be correct, I was expecting it would be off given the composite reference but mostly correct. The males get most of X called as cn=0

`cnvkit.py call some.cns -y -m clonal`

```
chromosome  start      end        log2         cn  depth        probes  weight
1           11980      25729384   -0.0653945   2   15.9367      8492    2835.62
1           25735099   25735511   -24.2118     0   0            2       0.468285
1           25737616   32849772   -0.0660045   2   15.6994      2467    831.859
1           32852111   32852611   -20.9951     0   0            2       0.147802
1           32859487   121484934  -0.0306153   2   15.4604      16849   5935.41
1           142535933  144158484  0.0542568    2   10.8732      60      24.3095
1           144158785  144363823  0.484623     3   33.9468      177     50.0161
1           144363822  147580267  0.0176151    2   23.629       1038    333.519
1           147580601  148593931  0.421916     3   34.3035      327     95.0254
1           148594247  249240121  -0.0402814   2   16.4251      23313   8091.87
2           10500      92267022   -0.0334403   2   15.3168      14302   5085.08
2           95326670   176860549  -0.0146701   2   15.6612      12026   4291.83
2           176866622  176867199  -21.2901     0   0            2       0.29987
2           176867698  243188873  -0.0310021   2   16.0711      13269   4687.03
3           60500      90311186   -0.0397676   2   15.1617      15201   5397.69
3           93519632   197955312  -0.0224123   2   15.6707      16751   5998.26
4           13322      49632814   -0.0275505   2   14.9362      6928    2498.11
4           52660616   190904242  -0.00891714  2   14.9944      15425   5746.15
4           190904241  191025802  -0.398984    2   117.79       65      15.3649
5           10500      45907753   -0.016674    2   14.2541      5052    1862.99
5           49555073   147550812  -0.0239906   2   15.6006      13777   4993.66
5           147553664  147554071  -24.0511     0   0            2       0.486158
5           147554794  180899528  -0.034745    2   15.5896      6587    2290.8
6           60500      58745455   -0.0434058   2   17.6806      13184   4576.41
6           61944507   171055167  -0.0166531   2   15.1902      13815   5071.24
7           21592      57938684   -0.0444952   2   14.4878      8805    3121.02
7           61525875   159128163  -0.0247907   2   16.1427      17259   6063.07
8           14932      43398986   -0.0414575   2   15.2951      7275    2560.46
8           47458040   146303522  -0.02934     2   14.6361      12349   4510.52
9           12093      47312613   -0.0174156   2   15.0604      5629    2034.96
9           65468178   141152931  -0.0455174   2   15.2352      15715   5476.34
10          60500      39076015   -0.0122739   2   14.871       5341    1936.85
10          42602609   135524247  -0.0364934   2   15.2695      16556   5793.39
```

**Comment by etal** [comment]
Q1. I recommend sorting out the two panels before any other troubleshooting. You can do this with the .targetcoverage.cnn files you already have:

- Load the targetcoverage.cnn files' `log2` columns into arrays (via `pandas.read_table` or `cnvlib.read`). Then calculate correlations between all pairs, or cluster them.
- And/or: Use `cnvkit.py metrics` with all of the targetcoverage.cnn files you have and one .cns file corresponding to a normal profile (e.g. run `segment` on the reference.cnn file). Look at the `metrics` output table to see if any two distinct groups stand out, e.g. one set of samples with distinctly higher MAD or IQR values. You can also use this approach to exclude low-quality samples from the reference once you've sorted out the panels. 

Q2. Yes. For a diploid genome, a copy number of 2 corresponds to log2 ratio 0.0, copy number 3 is log2(3/2) = 0.585, and the cutoff point for rounding is log2(2.5/2) = 0.322. In your data, the two segments on chromosome 1 with cn=3 have log2 values .48 and .42, above the cutoff.

Q3. Did you build the reference with the `-y` option? That option needs to match between `reference` and `call`. Also try the `gender` command to see what CNVkit thinks the gender of each sample is (for all .cnn, .cnr, .cns files).

**Comment by dwaggott** [comment]
What are the rounding cut points for deletions? The log2's just below -1 are getting pushed to a copy number of 0.

```
X       60500   2700280 -0.73249        1       52.3255 232     57.9176
X       2707503 58505576        -1.01751        0       20.9133 7821    2634.71
X       61960046        155257741       -1.01677        0       21.0887 11538   3914.18
and
X       60500   2712892 -0.829174       1       24.6135 235     59.9897
X       2715240 9753585 -1.1199 0       8.66897 558     202.378
X       9754084 9754712 -21.9512        0       0       2       0.377608
X       9755417 58505576        -1.04732        0       10.8222 7243    2490.4
X       61960046        155257741       -1.05862        0       10.6983 11519   4001.69
```

**Comment by dwaggott** [comment]
Also, are the threshold different for autosomes vs X/Y i.e. below the autosomes have lower log2 than X but higher copy number.

```
6       170893297       171055167       -1.18285        1       2.472   9       2.90949
4       9235977 9370746 -1.14698        1       8.96631 109     27.8188
X       60500   58505576        -1.08954        0       8.2282  8041    2752.54
X       61960046        155257741       -1.0848 0       8.15729 11519   4000.82
21      9411693 11185554        -0.173238       2       21.2144 77      29.7858
```

**Comment by etal** [comment]
It looks like this is a male sample, or CNVkit thinks it is. The sex chromosomes are called differently if they're haploid, so the cutoff point of half a copy (midway between 1 and 0 copies) vs. expected single-copy X is `log2(0.5 / 1.0) = -1.0`. The same goes for gains, e.g. `log2(1.5 / 1.0) = .58` is the cutoff to call copy number of 2 where the expected ploidy is 1.

**Comment by dwaggott** [comment]
Ah right that makes sense. I'm assuming the fact that males are registering as mostly 0 copies of chrX just at the threshold reflects the 30% use of females in the reference. I guess I could rerun altering the --purity just for chrX to reflect this.

**Comment by etal** [comment]
No, if you're using a recent version of CNVkit then it will automatically detect the chromosomal sex of each of the normal samples and adjust chrX and chrY to match the specified reference sex (i.e. XY with `-y` otherwise XX). So the reference log2 value for chrX will not be a mix of haploid and diploid; since you used `-y` it should be strictly haploid. Try plotting `cnvkit.py scatter reference.cnn` to confirm -- the chrX values should be close to -1 if you built the reference with `-y`, otherwise close to 0. Also try `cnvkit.py gender reference.cnn` to see the median chrX and chrY values and apparent reference sex.

If things look dubious you can also use `cnvkit.py gender` to verify the detected chromosomal sex of each of your input samples (targetcoverage.cnn and antitargetcoverage.cnn). The `reference` and `batch` commands will also report these calls when building the reference so you can see if/where CNVkit guessed incorrectly.

**Comment by etal** [comment]
I think you probably built a female reference by running `batch` or `reference` without the `-y` option. The male samples will then be expected to have chrX log2 values mostly near -1, and female samples mostly near 0. If that's the case, then run `call` without `-y` to match, and the `cn` values should be mostly sensible.
