### ISSUE TITLE
Use gene annotatation formats other than refFlat.txt

### ISSUE THREAD

**Issue by drmjc** [etal/cnvkit#163]
Hi,
I'm excited to test cnvkit for some targeted cancer sequencing datasets, anywhere from 105-400 genes. I'm using the dnanexus applet, and consistently getting the following error:

    ValueError: invalid literal for int() with base 10: 'exonCount'

This happens whether I upload a collection of normal_bam files with the goal of generating a reference, or with a single tumour-normal pair.

I thought the problem could relate to the small number of genes (105) & missing data on a chromosome, but I followed the manual steps here [http://cnvkit.readthedocs.io/en/stable/pipeline.html#batch] and successfully made a reference.cnn. 

Exact commands and output is below. Can you please help me get this over the line on DNAnexus?

cheers,
Mark

Set of normals:

    dx run /cnvkit_batch \
      -iis_male_normal=false \
      -ido_parallel=true \
      -iantitarget_avg_size=200000 \
      -itarget_avg_size=267 \
      -idrop_low_coverage=false \
      -inormal_bams=file-F0Fb1Y00g4j13V2Z35BK57zJ \
      -inormal_bams=file-F0Fb2V00666V1Fg4Gvf1Y0xZ \
      -inormal_bams=file-F0jkpPQ0z07b5xp000pgG58P \
      -inormal_bams=file-F0jkV5Q0V2y09KJg74pp5162 \
      -inormal_bams=file-F0jkk9Q0Kk1x3xP8KGyG9XfV \
      -inormal_bams=file-F0jkVgQ0zV22qXv1G4y8Jg08 \
      -inormal_bams=file-F0jkjJ00PBB49Xg23x8f0Q1J \
      -inormal_bams=file-F0jkgg009qpjY4jv5vpVbv93 \
      -inormal_bams=file-F0jkj100GY2Z2x686bb2bb49 \
      -ibaits=file-F08gFF00FgXgKPkyX9BPQFbV \
      -ifasta=file-F0qvz9Q0G1QvgQV84VV4kKp5 \
      -iannotation=file-BZFjVy00K74jV27PyJ4fb9jp \
      --yes --folder /CNV/V1 --watch
    # FAILED job-F0xgPPQ03Gvg0Gy1vVJYXyjQ
    # ...
    #2016-11-28 11:26:52 CNVkit STDOUT $ cnvkit.py batch --output-reference cnv-reference.cnn --antitarget-avg-size 200000 --target-avg-size 267 -n K1-blood.merged.dedup.realigned.bam K3-blood.merged.dedup.realigned.bam K5-blood.merged.dedup.realigned.bam K6-blood.merged.dedup.realigned.bam K7-blood.merged.dedup.realigned.bam K8-blood-H2O.merged.dedup.realigned.bam K9-blood.merged.dedup.realigned.bam K11-blood.merged.dedup.realigned.bam K15-blood-H2O.merged.dedup.realigned.bam -t MoSTv1_1_baits.b37.bed --split --short-names -f human_g1k_v37_decoy.fasta -g access-10k.bed --annotate refGene.b37.sorted.txt -p 0
    #2016-11-28 11:26:53 CNVkit STDERR Detected file format: BED
    #2016-11-28 11:26:53 CNVkit STDERR Applying annotations as target names
    #2016-11-28 11:26:53 CNVkit STDERR Shortening interval labels
    #2016-11-28 11:26:53 CNVkit STDERR Splitting large targets
    #2016-11-28 11:26:53 CNVkit STDERR Traceback (most recent call last):
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/local/bin/cnvkit.py", line 11, in <module>
    #2016-11-28 11:26:53 CNVkit STDERR     args.func(args)
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 96, in _cmd_batch
    #2016-11-28 11:26:53 CNVkit STDERR     args.processes, args.count_reads)
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 138, in batch_make_reference
    #2016-11-28 11:26:53 CNVkit STDERR     else {}))
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 327, in do_targets
    #2016-11-28 11:26:53 CNVkit STDERR     ['chromosome', 'start', 'end', 'name'])
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/gary.py", line 66, in from_rows
    #2016-11-28 11:26:53 CNVkit STDERR     table = pd.DataFrame.from_records(rows, columns=columns)
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 927, in from_records
    #2016-11-28 11:26:53 CNVkit STDERR     first_row = next(data)
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/target.py", line 287, in split_targets
    #2016-11-28 11:26:53 CNVkit STDERR     for chrom, start, end, name in region_rows:
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/target.py", line 209, in shorten_labels
    #2016-11-28 11:26:53 CNVkit STDERR     for row in interval_rows:
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/target.py", line 21, in assign_names
    #2016-11-28 11:26:53 CNVkit STDERR     ref_genes = read_refflat_genes(refflat_fname)
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/target.py", line 80, in read_refflat_genes
    #2016-11-28 11:26:53 CNVkit STDERR     name, _rx, chrom, strand, start, end, _ex = parse_refflat_line(line)
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/target.py", line 133, in parse_refflat_line
    #2016-11-28 11:26:53 CNVkit STDERR     assert len(exons) == int(exon_count), (
    #2016-11-28 11:26:53 CNVkit STDERR ValueError: invalid literal for int() with base 10: 'exonCount'
    #2016-11-28 11:26:53 CNVkit STDERR Traceback (most recent call last):
    #2016-11-28 11:26:53 CNVkit STDERR   File "/home/dnanexus/job-F0xgPPQ03Gvg0Gy1vVJYXyjQ", line 21, in <module>
    #2016-11-28 11:26:53 CNVkit STDERR     execfile(_code_filename)
    #2016-11-28 11:26:53 CNVkit STDERR   File "/home/dnanexus/job-F0xgPPQ03Gvg0Gy1vVJYXyjQ.code.py", line 251, in <module>
    #2016-11-28 11:26:53 CNVkit STDERR     dxpy.run()
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/share/dnanexus/lib/python2.7/site-packages/dxpy/utils/exec_utils.py", line 150, in run
    #2016-11-28 11:26:53 CNVkit STDERR     result = ENTRY_POINT_TABLE[job['function']](**job['input'])
    #2016-11-28 11:26:53 CNVkit STDERR   File "/home/dnanexus/job-F0xgPPQ03Gvg0Gy1vVJYXyjQ.code.py", line 56, in main
    #2016-11-28 11:26:53 CNVkit STDERR     drop_low_coverage, do_parallel)
    #2016-11-28 11:26:53 CNVkit STDERR   File "/home/dnanexus/job-F0xgPPQ03Gvg0Gy1vVJYXyjQ.code.py", line 119, in run_cnvkit
    #2016-11-28 11:26:53 CNVkit STDERR     sh(*command)
    #2016-11-28 11:26:53 CNVkit STDERR   File "/home/dnanexus/job-F0xgPPQ03Gvg0Gy1vVJYXyjQ.code.py", line 236, in sh
    #2016-11-28 11:26:53 CNVkit STDERR     subprocess.check_call(cmd, shell=True)
    #2016-11-28 11:26:53 CNVkit STDERR   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    #2016-11-28 11:26:53 CNVkit STDERR     raise CalledProcessError(retcode, cmd)
    #2016-11-28 11:26:53 CNVkit STDERR subprocess.CalledProcessError: Command 'cnvkit.py batch --output-reference cnv-reference.cnn --antitarget-avg-size 200000 --target-avg-size 267 -n K1-blood.merged.dedup.realigned.bam K3-blood.merged.dedup.realigned.bam K5-blood.merged.dedup.realigned.bam K6-blood.merged.dedup.realigned.bam K7-blood.merged.dedup.realigned.bam K8-blood-H2O.merged.dedup.realigned.bam K9-blood.merged.dedup.realigned.bam K11-blood.merged.dedup.realigned.bam K15-blood-H2O.merged.dedup.realigned.bam -t MoSTv1_1_baits.b37.bed --split --short-names -f human_g1k_v37_decoy.fasta -g access-10k.bed --annotate refGene.b37.sorted.txt -p 0 ' returned non-zero exit status 1
    #* CNVkit (cnvkit_batch:main) (failed) job-F0xgPPQ03Gvg0Gy1vVJYXyjQ
    #marcow 2016-11-28 11:18:06 (runtime 0:05:26)
    #AppInternalError: CalledProcessError: Command 'cnvkit.py batch --output-reference cnv-reference.cnn
    #  --antitarget-avg-size 200000 --target-avg-size 267 -n K1-blood.merged.dedup.realigned.bam
    #  K3-blood.merged.dedup.realigned.bam K5-blood.merged.dedup.realigned.bam
    #  K6-blood.merged.dedup.realigned.bam K7-blood.merged.dedup.realigned.bam
    #  K8-blood-H2O.merged.dedup.realigned.bam K9-blood.merged.dedup.realigned.bam
    #  K11-blood.merged.dedup.realigned.bam K15-blood-H2O.merged.dedup.realigned.bam -t
    #  MoSTv1_1_baits.b37.bed --split --short-names -f human_g1k_v37_decoy.fasta -g access-10k.bed
    #  --annotate refGene.b37.sorted.txt -p 0 ' returned non-zero exit status 1

Tumour-normal pair

    dx run /cnvkit_batch \
      -iis_male_normal=false \
      -ido_parallel=true \
      -iantitarget_avg_size=200000 \
      -itarget_avg_size=267 \
      -idrop_low_coverage=true \
      -itumor_bams=/alignments/K6-FFPE-SP-16-011864.merged.dedup.realigned.bam \
      -inormal_bams=/alignments/K6-blood.merged.dedup.realigned.bam \
      -ibaits=file-F08gFF00FgXgKPkyX9BPQFbV \
      -ifasta=file-F0qvz9Q0G1QvgQV84VV4kKp5 \
      -iannotation=file-BZFjVy00K74jV27PyJ4fb9jp \
      --yes --folder /CNV/V1 --watch
    # FAILED job-F0xgZJ803GvX3B6YykFJ13f1
    #2016-11-28 11:31:32 CNVkit STDOUT $ cnvkit.py batch K6-FFPE-SP-16-011864.merged.dedup.realigned.bam --scatter --diagram --output-reference cnv-reference.cnn --antitarget-avg-size 200000 --target-avg-size 267 -n K6-blood.merged.dedup.realigned.bam -t MoSTv1_1_baits.b37.bed --split --short-names -f human_g1k_v37_decoy.fasta -g access-10k.bed --annotate refGene.b37.sorted.txt -p 0
    #2016-11-28 11:31:32 CNVkit STDERR Detected file format: BED
    #2016-11-28 11:31:32 CNVkit STDERR Applying annotations as target names
    #2016-11-28 11:31:32 CNVkit STDERR Shortening interval labels
    #2016-11-28 11:31:32 CNVkit STDERR Splitting large targets
    #2016-11-28 11:31:32 CNVkit STDERR Traceback (most recent call last):
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/local/bin/cnvkit.py", line 11, in <module>
    #2016-11-28 11:31:32 CNVkit STDERR     args.func(args)
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 96, in _cmd_batch
    #2016-11-28 11:31:32 CNVkit STDERR     args.processes, args.count_reads)
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 138, in batch_make_reference
    #2016-11-28 11:31:32 CNVkit STDERR     else {}))
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 327, in do_targets
    #2016-11-28 11:31:32 CNVkit STDERR     ['chromosome', 'start', 'end', 'name'])
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/gary.py", line 66, in from_rows
    #2016-11-28 11:31:32 CNVkit STDERR     table = pd.DataFrame.from_records(rows, columns=columns)
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 927, in from_records
    #2016-11-28 11:31:32 CNVkit STDERR     first_row = next(data)
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/target.py", line 287, in split_targets
    #2016-11-28 11:31:32 CNVkit STDERR     for chrom, start, end, name in region_rows:
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/target.py", line 209, in shorten_labels
    #2016-11-28 11:31:32 CNVkit STDERR     for row in interval_rows:
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/target.py", line 21, in assign_names
    #2016-11-28 11:31:32 CNVkit STDERR     ref_genes = read_refflat_genes(refflat_fname)
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/target.py", line 80, in read_refflat_genes
    #2016-11-28 11:31:32 CNVkit STDERR     name, _rx, chrom, strand, start, end, _ex = parse_refflat_line(line)
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/local/lib/python2.7/dist-packages/cnvlib/target.py", line 133, in parse_refflat_line
    #2016-11-28 11:31:32 CNVkit STDERR     assert len(exons) == int(exon_count), (
    #2016-11-28 11:31:32 CNVkit STDERR ValueError: invalid literal for int() with base 10: 'exonCount'
    #2016-11-28 11:31:32 CNVkit STDERR Traceback (most recent call last):
    #2016-11-28 11:31:32 CNVkit STDERR   File "/home/dnanexus/job-F0xgZJ803GvX3B6YykFJ13f1", line 21, in <module>
    #2016-11-28 11:31:32 CNVkit STDERR     execfile(_code_filename)
    #2016-11-28 11:31:32 CNVkit STDERR   File "/home/dnanexus/job-F0xgZJ803GvX3B6YykFJ13f1.code.py", line 251, in <module>
    #2016-11-28 11:31:32 CNVkit STDERR     dxpy.run()
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/share/dnanexus/lib/python2.7/site-packages/dxpy/utils/exec_utils.py", line 150, in run
    #2016-11-28 11:31:32 CNVkit STDERR     result = ENTRY_POINT_TABLE[job['function']](**job['input'])
    #2016-11-28 11:31:32 CNVkit STDERR   File "/home/dnanexus/job-F0xgZJ803GvX3B6YykFJ13f1.code.py", line 56, in main
    #2016-11-28 11:31:32 CNVkit STDERR     drop_low_coverage, do_parallel)
    #2016-11-28 11:31:32 CNVkit STDERR   File "/home/dnanexus/job-F0xgZJ803GvX3B6YykFJ13f1.code.py", line 119, in run_cnvkit
    #2016-11-28 11:31:32 CNVkit STDERR     sh(*command)
    #2016-11-28 11:31:32 CNVkit STDERR   File "/home/dnanexus/job-F0xgZJ803GvX3B6YykFJ13f1.code.py", line 236, in sh
    #2016-11-28 11:31:32 CNVkit STDERR     subprocess.check_call(cmd, shell=True)
    #2016-11-28 11:31:32 CNVkit STDERR   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    #2016-11-28 11:31:32 CNVkit STDERR     raise CalledProcessError(retcode, cmd)
    #2016-11-28 11:31:32 CNVkit STDERR subprocess.CalledProcessError: Command 'cnvkit.py batch K6-FFPE-SP-16-011864.merged.dedup.realigned.bam --scatter --diagram --output-reference cnv-reference.cnn --antitarget-avg-size 200000 --target-avg-size 267 -n K6-blood.merged.dedup.realigned.bam -t MoSTv1_1_baits.b37.bed --split --short-names -f human_g1k_v37_decoy.fasta -g access-10k.bed --annotate refGene.b37.sorted.txt -p 0 ' returned non-zero exit status 1
    #* CNVkit (cnvkit_batch:main) (failed) job-F0xgZJ803GvX3B6YykFJ13f1
    #marcow 2016-11-28 11:28:37 (runtime 0:02:54)
    #AppInternalError: CalledProcessError: Command 'cnvkit.py batch K6-FFPE-SP-16-011864.merged.dedup.realigned.bam
    #  --scatter --diagram --output-reference cnv-reference.cnn --antitarget-avg-size 200000
    #  --target-avg-size 267 -n K6-blood.merged.dedup.realigned.bam -t MoSTv1_1_baits.b37.bed --split
    #  --short-names -f human_g1k_v37_decoy.fasta -g access-10k.bed --annotate refGene.b37.sorted.txt -p
    #  0 ' returned non-zero exit status 1
    
h2. Manual success

    cnvkit.py target baits.bed --split -o my_targets.bed
    cnvkit.py antitarget my_targets.bed --access access-10k.bed -o my_antitargets.bed
    
    for bam in *.bam; do
      cnvkit.py coverage $bam my_targets.bed -o ${bam/.bam/.targetcoverage.cnn}
      cnvkit.py coverage $bam my_antitargets.bed -o ${bam/.bam/.antitargetcoverage.cnn}
    done
    
    # With all normal samples...
    cnvkit.py reference *[Bb]lood*.bam -t my_targets.bed -a my_antitargets.bed \
        --fasta human_g1k_v37_decoy.fasta  -o my_reference.cnn
    # AssertionError: Give .cnn samples OR targets and antitargets.
    cnvkit.py reference --fasta human_g1k_v37_decoy.fasta  -o my_reference.cnn *.cnn
    # ...
    #Targets: 31 (1.4616%) bins failed filters:
    #MUTYH    1:45795727-45795750     coverage=-8.967  spread=7.406  rmask=nan
    #FANCD2   3:10073972-10074045     coverage=-26.037  spread=3.928  rmask=nan
    #"      3:10103824-10103905     coverage=-29.085  spread=0.626  rmask=nan
    #  ATR      3:142217961-142218044   coverage=-8.566  spread=2.642  rmask=nan
    #  PDGFRA   4:55106209-55106292     coverage=-17.996  spread=11.616  rmask=nan
    #  FAM175A  4:84401289-84401531     coverage=-28.715  spread=0.900  rmask=nan
    #  APC      5:112145812-112145862   coverage=-24.143  spread=1.701  rmask=nan
    #  RAD50    5:131928445-131928652   coverage=-12.509  spread=11.687  rmask=nan
    #  MET      7:116335800-116335863   coverage=-14.311  spread=13.560  rmask=nan
    #  MRE11A   11:94163066-94163162    coverage=-19.122  spread=10.907  rmask=nan
    #  SDHD     11:111963793-111963931  coverage=-18.550  spread=11.081  rmask=nan
    #    "      11:111978258-111978300  coverage=-18.556  spread=11.876  rmask=nan
    #"      11:111990004-111990025  coverage=-28.653  spread=0.737  rmask=nan
    #  MDM2     12:69209397-69209510    coverage=-28.757  spread=0.631  rmask=nan
    #  PTPN11   12:112895084-112895140  coverage=-28.629  spread=1.077  rmask=nan
    #  BRCA2    13:32949469-32949553    coverage=-27.565  spread=1.241  rmask=nan
    #    "      13:32970117-32970239    coverage=-28.267  spread=7.139  rmask=nan
    #RB1      13:48954178-48954230    coverage=-3.226  spread=1.160  rmask=nan
    #BUB1B    15:40458549-40458681    coverage=-26.217  spread=1.089  rmask=nan
    #FANCA    16:89829143-89829211    coverage=-28.538  spread=0.901  rmask=nan
    #"      16:89844754-89844880    coverage=-8.049  spread=2.252  rmask=nan
    #  TP53     17:7565246-7565342      coverage=-9.500  spread=1.449  rmask=nan
    #  ERBB2    17:37869395-37869532    coverage=-19.194  spread=11.202  rmask=nan
    #  BRCA1    17:41262541-41262607    coverage=-28.628  spread=0.728  rmask=nan
    #  RAD51C   17:56783839-56783979    coverage=-18.021  spread=11.542  rmask=nan
    #  BRIP1    17:59861236-59861278    coverage=-8.855  spread=5.047  rmask=nan
    #  ERCC2    19:45862107-45862180    coverage=-28.151  spread=6.921  rmask=nan
    #  CHEK2    22:29117577-29117629    coverage=-28.902  spread=0.884  rmask=nan
    #    "      22:29125298-29125374    coverage=-28.518  spread=0.898  rmask=nan
    #"      22:29126397-29126546    coverage=-28.744  spread=0.644  rmask=nan
    #    "      22:29133237-29133281    coverage=-28.887  spread=0.647  rmask=nan
    #Antitargets: 311 (1.0825%) bins failed filters
    #Wrote my_reference.cnn

**Comment by etal** [comment]
It looks like the file `refGene.b37.sorted.txt` contains a header row listing the column names, which is not part of the ["refFlat" format](https://genome.ucsc.edu/FAQ/FAQformat#format9) that CNVkit needs there.

If you've created a reference that you're happy with (including gene name annotations and a set of normal BAMs), you can use that file as input to the DNAnexus applet instead of reanalyzing the same normal BAMs. Or, if you have the annotated targets but need to process normal BAMs on DNAnexus to build your reference.cnn, you can use your annotated `my_targets.bed` as the baits BED file for the app and skip the refFlat annotation input.

**Comment by drmjc** [comment]
Thanks very much @etal ,
My file used the refGene table format (compatible with GATK DepthOfCoverage) & assumed it was the same as refFlat. Looks like I'm moving ahead now. I now have a reference.cnn & am processing some tumors now.

cheers,
Mark

**Comment by etal** [comment]
Good to hear. I agree the requirement of refFlat.txt as the gene annotation format is weird, so I've retitled this issue. The `--annotate` option should automatically detect whether the input is refflat, genepredext (e.g. refGene), GATK/Picard interval list or BED, and parse it accordingly. (Maybe also GFF in the future.)

**Comment by drmjc** [comment]
that would be awesome. congrats on a great tool too, it really just works. v impressive.
