### ISSUE TITLE
scatter -c -g options combi to label target gene in a range is not working

### ISSUE THREAD

**Issue by ThomasGro** [etal/cnvkit#164]
I am using CNVkit 0.8.1.
When running...
cnvkit scatter -s sample{s,r} -c 8:31000000-45000000 -g FGFR1
...all target genes in the region are shown, and not only FGFR1!
FGFR1 gene region is highlighted in yellow, but labels are shown for all genes in the region.
![cnvkit_gene_labels](https://cloud.githubusercontent.com/assets/18532193/20795171/021311d2-b7d0-11e6-9f8b-589d55a3bb85.jpg)

**Comment by etal** [comment]
Yowza. Could you show me the .cnr and .cns files (or just the relevant lines) so I can test?

**Comment by etal** [comment]
This looks like WGS. I'm not seeing the same issue with a target panel, so I suspect that CNVkit's annotation of genomic bins via refFlat.txt is retaining too many gene names from overlapping genic regions -- maybe transitively.

**Comment by ThomasGro** [comment]
You are right,
It is WGS data. I attached the first 100 rows of a cns and cnr files together with the chr8 part (zip), so that you can recapitulate my plot.


[chr8-part.cn8.gz](https://github.com/etal/cnvkit/files/630534/chr8-part.cn8.gz)
[chr8-part.cns.gz](https://github.com/etal/cnvkit/files/630535/chr8-part.cns.gz)

[head-100.cns.txt](https://github.com/etal/cnvkit/files/630541/head-100.cns.txt)
[head-100.cnr.txt](https://github.com/etal/cnvkit/files/630542/head-100.cnr.txt)

**Comment by etal** [comment]
Thanks for these files. When you ran `batch` or `target` to generate the original (subdivided, annotated) target BED file, did you use the `--short-name` option?

**Comment by etal** [comment]
I've tested re-annotating the WGS bins with refFlat.txt in the development version of CNVkit and it works properly now, with short, less-redundant labels.
