### ISSUE TITLE
what is log2 in a composite reference

### ISSUE THREAD

**Issue by dwaggott** [etal/cnvkit#165]
The log2 seems to translate in individual cnn files but not in one made as a composite normal. What's the interpretation of log2 in latter?

```
6       161067193       161067513       LPA     9.48097 714.591
vs
6       161065721       161065928       LPA     4.71115 411.406 0.454106                0.331492
```

**Comment by etal** [comment]
The log2 column in either format is the log2-scaled mean coverage depth. In the targetcoverage.cnn files the log2 value is just log2(depth), e.g. `log2(741.591) = 9.48`. In the reference.cnn files, as well as .cnr and .cns, this value is normalized to the overall median, so the neutral log2 value is 0.0. There, a log2 value of 4.7 indicates a bin's coverage is `2**(4.7)` -fold above neutral, or 26x.

**Comment by dwaggott** [comment]
Thanks!
