### ISSUE TITLE
cnvkit segment

### ISSUE THREAD

**Issue by ramaniak** [etal/cnvkit#166]
Hello Eric,

I have a question regarding the segmentation step carried out by cnvkit where I am seeing segments that are made up of regions that are not "uniform" in their copy number.

for example the segment below has a number of 'genes' making up the segment with a log2 CN of -0.0748348

```
2	10500	27677527	FAM110C,SH3YL1,ACP1,FAM150B,TMEM18,SNTG2,TPO,PXDN,MYT1L,TSSC1,TRAPPC12,ADI1,RNASEH1,RPS7,COLEC11,ALLC,DCDC2C,SOX11,CMPK2,RSAD2,RNF144A,LOC101929452,ID2,KIDINS220,MBOAT2,ASAP2,ITGB1BP1,CPSF3,IAH1,ADAM17,YWHAQ,TAF1B,GRHL1,KLF11,CYS1,RRM2,C2orf48,HPCAL1,ODC1,NOL10,ATP6V1C2,PDIA6,KCNF1,C2orf50,PQLC3,ROCK2,E2F6,GREB1,NTSR2,LPIN1,TRIB2,FAM84A,LOC653602,NBAS,DDX1,LOC101926966,MYCNOS,MYCN,FAM49A,RAD51AP2,VSNL1,SMC6,GEN1,MSGN1,KCNS3,RDH14,NT5C1B-RDH14,OSR1,TTC32,WDR35,LOC101928222,MATN3,LAPTM4A,SDC1,PUM2,RHOB,HS1BP3,GDF7,LDAH,APOB,TDRD15,KLHL29,ATAD2B,UBXN2A,MFSD2B,WDCP,FKBP1B,SF3B6,FAM228B,FAM228A,ITSN2,NCOA1,PTRHD1,CENPO,ADCY3,DNAJC27,EFR3B,POMC,DNMT3A,DTNB,ASXL2,KIF3C,RAB10,GAREM2,HADHA,HADHB,ADGRF3,SELENOI,DRC1,OTOF,C2orf70,CIB4,KCNK3,SLC35F6,CENPA,DPYSL5,MAPRE3,TMEM214,AGBL5,EMILIN1,KHK,CGREF1,ABHD1,PREB,PRR30,TCF23,SLC5A6,ATRAID,CAD,SLC30A3,DNAJC5G,TRIM54,UCN,MPV17,GTF3C2,EIF2B4,SNX17,ZNF513,PPM1G,NRBP1,KRTCAP3,IFT172	-0.0748348	1.13734	2366	1017.68
```

If I look at the log2 CN of some of the genes listed as part of the segment (based on their values in the cnr file it looks as follows.

```
FAM110C	-0.220167
SH3YL1	0.0471751
ACP1	-0.169516
LOC101929452	-0.355337

ID2	3.27702
KIDINS220	2.08776

MBOAT2	0.087067
LOC101926966	-0.0605195

MYCNOS	3.05635
MYCN	2.86244

FAM49A	-0.80534

```
based on these values, i would not expect the segmentation algorithm to combine them into one big segment. Instead, I would expect there to be at least 4 segments within this region. 

I have tried all three segmentation algorithms (cbs, haar and flasso) and get more or less the same results. Changing the thresholds does not seem to change this either. I have the intermediate R data frame written out and it looks like the whole region is indeed combined, but I am not sure how to change this behaviour. 

One thing that did help was to pre-filter the cnr file, i.e. remove all regions that are outside of a range of log2 values before feeding this to the segmentation algorithm. While this takes care of having cleaner segments, it does generate a lot of shorter segments. this is probably what the segmentation algorithm is meant to consider. 

Any thoughts from you will be much appreciated. 

thanks
Arun

**Comment by etal** [comment]
If there is a log of noise in the log2 signal then the segmentation algorithms may consider the fluctuations in the mean value to be spurious. The choice of reference can make a difference in reducing noise to help pick out real CNVs -- if you've used a pooled reference, you could try a flat reference and compare the results.

Other parameters in the `segment` command to consider: `--drop-outliers` for another smoothing method, and if you have tumor samples, try `--drop-low-coverage` and `--vcf` (to further segment on SNP allele frequencies). Check if the SNP allele frequencies support your additional segments with `scatter` and tune which SNPs are used with `--min-variant-depth` and, if you're using the development version of CNVkit, perhaps `--zygosity-freq`.

If you found your pre-filter helped the results, would you be interested in sharing it?

**Comment by ramaniak** [comment]
I will see if pooled vs flat reference makes a difference. 

For the segmentation itself, I have tried all three methods and added --drop-outliers and --drop-low-coverage. I have not tried the --vcf for further segmentation. I will also check with scatter.

I am happy to share my pre-filter results. Do you want me to upload the before/after cnr and cns files?

**Comment by etal** [comment]
Sure. Would you also be willing to share the script you used to filter the .cnr files?

**Comment by ramaniak** [comment]
It was just an awk one liner where you can set your high and low threshold for cnr values. 
```
awk '$5 > 1 || $5 <0.8 ' A2.cnr A2.filter.cnr
```
I have uploaded the before and after cnr and cns files. 
the segmentation was done with:
```
cnvkit.py segment A3.cnr --drop-low-coverage --drop-outliers 4 -o A3.cns
```

[A3.cnr.filter.zip](https://github.com/etal/cnvkit/files/652333/A3.cnr.filter.zip)

**Comment by etal** [comment]
It looks like this is a noisy dataset, and the amplifications of ID2 and MYCN (which look real to me in the scatter plots) are so narrow/focal that CBS does not see a strong enough signal to warrant the extra breakpoints. However, I tried the `haar` segmentation method and saw cleaner results:

    cnvkit.py segment A3.cnr --drop-low-coverage -m haar -o A3.haar.cns

Try that. You could also use the `gainloss` command with just the .cnr, not the .cns (or with and without .haar.cns), to detect amplified genes with higher sensitivity but lower specificity -- which pairs well with awk.
