### ISSUE TITLE
Scatter plot from WES data

### ISSUE THREAD

**Issue by gabeng** [etal/cnvkit#176]
Scatter plots from WES data result in huge PDF files. This does not seem to be a good format for this data. Is there a better way to visualize the result? I would like to have an overview by chromosome.

**Comment by etal** [comment]
You can use PNG as the output format if you specify an output filename ending with `png`. (I suppose that should be documented.)

Also, older versions of matplotlib used to generate bloated PDFs, but the output became much more efficient sometime before version 1.5 or so. We used to pass these bloated PDFs through ghostscript (`gs`) to reformat the files more efficiently, and it would help by about 10x -- but now the matplotlib PDFs are about the same size as ghostscript's, so we don't bother anymore. So if you're using an old version of matplotlib, it might help to update.

**Comment by gabeng** [comment]
If I provide a list of regions with `-l`, are several separate `pngs` created?

**Comment by etal** [comment]
No, not with `-l` -- that's always a multi-page PDF.

For PNG it would need to generate unique filenames. Maybe `{basename}.{chr:start-end}.png` if the `-o` suffix is not `pdf`. Alternatively you could script this with something like:

    import cnvlib
    import matplotlib.pyplot as plt
    cnr = cnvlib.read(cnr_fname)
    cns = cnvlib.read(cns_fname)
    for region in cnvlib.tabio.read_auto("region_list.txt").coords():
        do_scatter(cnr, cns, show_range=region)
        outfname = "{}.{}.png".format(cnr.sample_id, cnr.row2label(region))
        plt.savefig(args.output, format="png", bbox_inches="tight")

Or a shell script with a loop would do it, too.

**Comment by gabeng** [comment]
Thanks, I will put something like this into my makefile.
