### ISSUE TITLE
How to further increase targets

### ISSUE THREAD

**Issue by gabeng** [etal/cnvkit#177]
I am facing the rare situation that the data contained in targets is much noisier than the data in anti-targets (data from 100x avg WES samples). I would gladly sacrifice resolution for lower noise. I tried increasing target size to 500 with no visible effect. 
My next step would be to merge close target regions in the original `.bed` file. Or is there a way to tell cnykit to fuse regions that are close together?

**Comment by etal** [comment]
Yes, the exon boundaries are the problem. Larger antitargets should compensate to some extent, and different segmentation algorithms handle noise differently -- try `segment -m haar` if you haven't already.

CNVkit won't merge non-adjacent targets from the command line, but `bedtools merge` will work on the original target BED file, given the right options. If you want to modify the processed .cnn and .cnr files without rerunning `coverage`, try the `cnvlib` API: `import cnvlib; cnr = cnvlib.read(fname); merged = cnr.merge(bp=-25); cnvlib.tabio.write(merged, "merged.txt")`

**Comment by gabeng** [comment]
I used bedtools to merge target regions. The result improved, but the difference to higher coverage data is significant. I will see if I can get more samples to pool for reference. Thanks for your suggestions.
