### ISSUE TITLE
goleft and bcbio integration

### ISSUE THREAD

**Issue by etal** [etal/cnvkit#179]
The standalone tool [goleft](https://github.com/brentp/goleft) has a fast `depth` command that calculates binned coverage depths, GC content and repeat-masked fractions similarly to CNVkit's `coverage` command. Let's avoid repeating this calculation in pipelines like bcbio.

Tasks & questions:

- [ ] How are the regions shown in `.depth.bed` defined? Looks like mostly fixed-sized windows, but not always.
- [ ] Coerce goleft's `.depth.bed` output into CNVkit's `.cnn` format -- either via a new `import-goleft` command in CNVkit, or a simple series of shell commands that can be used in bcbio and elsewhere.
- [ ] Determine how to use goleft's `.callable.bed` output to replace CNVkit's `guess_baits.py` script, and/or coordinate with @brentp to ensure this can be done and will work well for this use case.
- [ ] Look into interoperability with other goleft commands.

**Comment by etal** [comment]
See also: chapmanb/bcbio-nextgen#1731

**Comment by brentp** [comment]
Hi Eric, I'd be very interested to help with this as I'm interested in making goleft widely useful. 

> How are the regions shown in .depth.bed defined? Looks like mostly fixed-sized windows, but not always.

if no --bed argument is given, these are fixed-length windows with length decided by --window.
if --bed is specified, then the regions specified in the bed are split into --window size regions with the ends of the regions smaller.
It would be good to get your input on what is useful here as I'm not sure if that's the best way to do it.

> Coerce goleft's .depth.bed output into CNVkit's .cnn format -- either via a new import-goleft command in CNVkit, or a simple series of shell commands that can be used in bcbio and elsewhere.

if you let me know how goleft is different, I can attempt to reconcile.

> Determine how to use goleft's .callable.bed output to replace CNVkit's guess_baits.py script, and/or coordinate with @brentp to ensure this can be done and will work well for this use case.

this could probably work as-is or with very minor post-processing.
 
> Look into interoperability with other goleft commands.
 
:+1: +1

**Comment by etal** [comment]
The .cnn format just adds column headers as the first row:
- https://cnvkit.readthedocs.io/en/stable/fileformats.html#target-and-antitarget-bin-level-coverages-cnn
- https://github.com/etal/cnvkit/blob/master/test/formats/reference-tr.cnn (from `reference`, not `target`, but same concept)

The first 4 columns are like BED4, as in goleft, and the order of the remaining columns is mostly alphabetical. CNVkit doesn't care about column order, and relies on the header row to figure it out. 

Matching up the bins/windows is the part I'm less sure about. The `target` and `antitarget` commands use the [subdivide](https://github.com/etal/cnvkit/blob/master/cnvlib/genome/subdivide.py) method to create bins of equal size and *roughly* the requested size within a targeted or sequencing-accessible off-target region. The bins are not a fixed width and there are no "remainder" bins within a BED region.

Given that, I'm not sure which (if any) of these options makes sense in a pipeline:
1. Using BED files from `cnvkit.py target` and `antitarget` (or just `target` for WGS), run goleft with a window size larger than the largest `antitarget` bin, so goleft doesn't divide any of the bins itself.
2. Use those same BED files, run goleft with a window size of 1 or 2 and merge the emitted windows in a post-processing step or as a new option within goleft.
3. Port CNVkit's subdivide method to goleft and make it available as another option, so window size is treated as a suggestion and the output essentially matches CNVkit's.

As for `guess_baits.py`, the main issue is that a hard lower limit doesn't reflect baited regions very well. (Comparing guessed baits to the known target panel on some samples with `bedtools jaccard`.)
1. Expected on-target coverage and enrichment over off-target coverage is not known up front, though `coverage_bin_size.py` / `indexcov` could help with that.
2. For any lower limit chosen to find captured regions with good sensitivity, most targets will be captured with much better coverage than that, and so the region with depth above this threshold will be much wider than the baited region -- by about half the sequence fragment size, for paired-end reads. The read depth at the true baited region edges is about half the peak read depth in the middle of that region, so `guess_baits.py` finds the peak and trims the detected region's boundaries to where read depth reaches half that value ([see here](https://github.com/etal/cnvkit/blob/master/scripts/guess_baits.py#L116)).

**Comment by etal** [comment]
bcbio-nextgen now calculates read depths separately with mosdepth, so this ticket is obsolete.
