### ISSUE TITLE
CNVkit parsing MuTect2 vcf

### ISSUE THREAD

**Issue by pschaughency** [etal/cnvkit#184]
I am not sure if I am running this correctly but I have run this command:

cnvkit.py call 207_bwa_hg19_RG_markDup_sorted.cns -y -m clonal -v ../MuTect2/normal_vs_tumor_patient_207_mutect2.vcf -o 207.call.cns

And go this output:

Selected test sample TUMOR and control sample NORMAL
Loaded 0 records; skipped: 6424 somatic, 1226 depth
Kept 0 heterozygous of 0 VCF records
Calling copy number with clonal ploidy 2
Wrote 207.call.cns with 123 regions

Is this correct? It seems to be skipping all of the variant calls in the vcf.

I am running CNVkit version 0.8.3 and MuTect2 v3.6

**Comment by etal** [comment]
Try adding the `-z` option:

cnvkit.py call 207_bwa_hg19_RG_markDup_sorted.cns -y -z -m clonal -v ../MuTect2/normal_vs_tumor_patient_207_mutect2.vcf -o 207.call.cns 

Mutect2 does not call genotypes for SNPs in the normal sample, so the `--zygosity-freq` option is needed to override the bogus 0/0 genotypes and instead determine zygosity from allele frequency.

**Comment by pschaughency** [comment]
Thanks for your quick response. I just got back to this. With the -z option, it still seems to not be parsing the VCF from MuTect2. Could this be a bug specifically with MuTect2?

cnvkit.py call 207.cns -y -z -m clonal -v ../MuTect2/normalvstumor.vcf -o 207.call.cns
Selected test sample TUMOR and control sample NORMAL
Loaded 0 records; skipped: 6424 somatic, 1226 depth
Kept 0 heterozygous of 0 VCF records
Calling copy number with clonal ploidy 2
Wrote 207.call.cns with 123 regions

Thanks for you help

**Comment by etal** [comment]
"Bug" is a hazy concept when it comes to Mutect2. I think this can be addressed in CNVkit when the VCF is parsed:

- [ ] Take `zygosity_freq` as a parser option
- [ ] If `zygosity_freq` is given, apply genotypes based on allele frequency during parsing.
- [ ] Also use the zygosity-based genotypes to infer somatic status, or disable it. (Currently CNVkit marks records with normal genotype 0/0 as somatic, then filters them out, hence the problem here.)
- [ ] Drop the method `VariantArray.zygosity_from_freq`, maybe.

**Comment by etal** [comment]
I pushed a fix; are you able to try the development version? The same command you used before should work now, with or without `--zygosity-freq`.

**Comment by pschaughency** [comment]
I will test it out today. Thank you.

**Comment by pschaughency** [comment]
I think it is working now:

Selected test sample TUMOR and control sample NORMAL
Loaded 11021 records; skipped: 0 somatic, 1203 depth
VCF normal sample's genotypes are all 0/0 or missing; inferring genotypes from allele frequency instead
Skipping 73 additional somatic record based on T/N genotypes
Kept 15 heterozygous of 10948 VCF records

**Comment by etal** [comment]
That's about as expected. 15 SNPs is too few to be very useful, though. To keep more you could try lowering the `--zygosity-freq` value below the default 0.25, e.g. `call -z 0.15`.

I think Mutect2 must be omitting most of the true SNPs and only including borderline-somatic SNVs in the output VCF. If that's the case I'd look for an [option in Mutect2](https://software.broadinstitute.org/gatk/guide/tooldocs/org_broadinstitute_gatk_tools_walkers_cancer_m2_MuTect2.php), maybe `--max_alt_allele_in_normal_fraction`, to include the SNPs that appear in both the tumor and normal. If there's no way to do this, then Mutect2 VCFs just shouldn't be used for this purpose. (It's beta software and I'm not using it in production yet, myself.)
