### ISSUE TITLE
Sample IDs do not match

### ISSUE THREAD

**Issue by holtgrewe** [etal/cnvkit#187]
I'm using the most current cnvkit from PyPi.

I'm getting an error `"ValueError: Sample IDs do not match:'cnvkit.coverage.target.bwa.SAMPLE (target) vs. 'cnvkit.coverage.antitarget.bwa.SAMPLE' (antitarget)` with the following call.

What am I doing wrong?

```
cnvkit.py fix \
work/cnvkit.coverage.target.bwa.SAMPLE/out/cnvkit.coverage.target.bwa.SAMPLE.cnn \
work/cnvkit.coverage.antitarget.bwa.SAMPLE/out/cnvkit.coverage.antitarget.bwa.SAMPLE.cnn \
work/cnvkit.reference.bwa/out/cnvkit.reference.bwa.cnn \
-o work/cnvkit.fix.bwa.SAMPLE/out/cnvkit.fix.bwa.SAMPLE.cnr
```

**Comment by etal** [comment]
Yes, you'll need to rename the files:

- `cnvkit.coverage.target.bwa.SAMPLE.cnn` -> `cnvkit.bwa.SAMPLE.targetcoverage.cnn` (or whatever-you-want.targetcoverage.cnn)
- `cnvkit.coverage.antitarget.bwa.SAMPLE.cnn` -> `cnvkit.bwa.SAMPLE.antitargetcoverage.cnn` (or whatever-you-want.antitargetcoverage.cnn, as long as whatever-you-want is identical in both filenames)

**Comment by lmanchon** [comment]
yes, it's a stupid error I've encountered too, and I've wasted a lot of time trying to solve it.
