### ISSUE TITLE
bin size for amplicon based targeted sequencing

### ISSUE THREAD

**Issue by LyLeif** [etal/cnvkit#189]
Hi!
We have an average amplicon size of 150 bp for ffpe -DNA.
Do I need to adjust the average bin size for CNVkit?
And if I have to, what would be the best new average bin size?

**Comment by etal** [comment]
The best bin size is a function of the coverage depth and target width (after merging overlapping amplicons). In CNVkit v0.8.3 you can use the bundled script `coverage_bin_size.py` to estimate bin size from a given sample BAM and target BED file.

Typically, a bin size of 100 is good for ultra-deep targeted amplicon sequencing. Try 200 or leave the default if that's too noisy. Also, don't mark duplicates in your BAM, or CNVkit will ignore most of your reads and infer very low coverage depth.

**Comment by LyLeif** [comment]
Thank you very much!
