### ISSUE TITLE
error when using provided bed file

### ISSUE THREAD

**Issue by neilihrke** [etal/cnvkit#192]
I have a user who keeps getting an error while using a provided bed file.  The command being used is:
cnvkit.py coverage Sample.bam my_targets.bed -o Sample.targetcoverage.cnn

the error is:

File "/data5/bsi/bictools/src/cnvkit/0.8.4/cnvlib/coverage.py", line 219, in detect_bedcov_columns
    firstline = text[:text.index('\n')]
ValueError: '\n' is not in list

We tried commenting out the if, esle block around line 219 and left the return statement to see what new error we would get, and we got this:

File "/data2/external_data/Yan_Huihuang_m105265/s202078.epiSign/CLL_PD_ALL/CNVkit_fold/cnvkit/0.8.4/cnvlib/coverage.py", line 213, in bedcov
    table = pd.read_table(StringIO(raw), names=columns, usecols=columns)
TypeError: must be string or buffer, not list

**Comment by etal** [comment]
Summarizing from our e-mails:

- Check the line ending format in `my_targets.bed` -- it may be `\r` / CR / carriage return, a.k.a. the classic Mac OS style still used in MS Excel on OS X. Use the Unix command `file` to verify. If it's CR line endings, try reformatting with `sed -e 's/\r/\n/g' my_targets.bed > my_targets.unix-eol.bed`
- I've updated the TravisCI configuration to run the standard unit tests with the recently released Pysam 0.10.0. We'll see how that works in a few minutes.
- (For me to do) Change the function `coverage.detect_bedcov_columns` to safely handle CR line endings.

**Comment by shulanmayo** [comment]
Hi Eric,

After the recommended " sed -e 's/\r/\n/g' my_targets.bed > my_targets.unix-eol.bed ", the same error message still occur:

coverage.py", line 219, in detect_bedcov_columns
    firstline = text[:text.index('\n')]
ValueError: '\n' is not in list

thanks

**Comment by etal** [comment]
From your traceback, it looks like pysam.bedcov is splitting the command's output into lines by itself, which was done automatically in some pysam versions between 0.9.0 and 0.9.1.3 or so, but is not done by default in the versions CNVkit requires, pysam 0.9.1.4 or 0.10.0.

The Travis build with pysam 0.10.0 passed, so I think your CNVkit installation is picking up an older version of pysam, not the pysam 0.10.0 you installed separately.

You can edit `coverage.py` line 225 to add the argument `split_lines=False`, and see if that works. But I also recommend sorting out the installation paths, and using `conda` if possible.

**Comment by shulanmayo** [comment]
Thanks. It is the pysam version issues. I forced the script to call the right version and now worked!
Shulan

**Comment by GuoFengWang** [comment]
> Travis

Hi  shulanmayo,
I came across the same issue, could you tell me how to forced the script to call the right version ?

thanks

**Comment by shulanmayo** [comment]
Set up the correct python path, something like:
export PYTHONPATH=......your python library....:$PYTHONPATH
