### ISSUE TITLE
Amplicon mode

### ISSUE THREAD

**Issue by tamaraprieto** [etal/cnvkit#194]
Hi, 

I am running the following command and I get *.cns files among other output files. 

`cnvkit.py batch -m amplicon -y -p 0 -n *Normal.bam -f Hg19IonTorrentDefault.fa -t IAD111561_166_Designed.bed *Tumor.bam
`

According to the documentation, cnvkit.py batch -m amplicon should run just until cnvcopy.py fix (cnvcopy.py segment should not be run). Is the program ignoring the "-m amplicon" option?How can I generate a log file with commands?

Thanks in advance, 

Tamara

**Comment by etal** [comment]
No, the amplicon mode also does segmentation. The `batch` command uses the API, not shell commands, but you can see the progress of the analysis printed on the console (stderr).

If the command ran successfully you should see .cnr and .cns file. The .cnr files are the output of `fix`, and .cns are from `segment`.

**Comment by tamaraprieto** [comment]
Thank you
