### ISSUE TITLE
Support Mutect2 VCFs, detecting tumor/normal samples reliably

### ISSUE THREAD

**Issue by Strausyatina** [etal/cnvkit#195]
I'm running `export theta` on batch output files and VCF files:
`~/cnvkit-0.8.3/cnvkit.py export theta Tumor.cns -r my_reference.cnn -v Sample_Paired.vcf`

On VCF file obtained by mutect1 it raises an error:
```
Traceback (most recent call last): 
  File "/home/asya/cnvkit-0.8.3/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/asya/cnvkit-0.8.3/cnvlib/commands.py", line 1870, in _cmd_export_theta
    raise ValueError("VCF contains no usable SNV records")
ValueError: VCF contains no usable SNV records
```
On  VCF file from TCGA ( mutect2 ) it goes without errors, but the output is still incorrect, because sample and normal columns are swapped.
Moreover, if one changes the header in mutect2 VCF file correspondingly (swapping the references to sample and normal data), it fails with the same error as mutect1.

I was able to find with debugger that the problem probably arises in the function `_parse_records` from the file `cnvlib/tabio/vcfio.py`
where all the rows became somatic, while VCF file contains both somatic and germline data.
This would explain how mutect2 input passes without errors.

```
> /home/asya/cnvkit-0.8.3/cnvlib/tabio/vcfio.py(237)_parse_records()
-> start = record.start
(Pdb) l
232                     alt_count = 0
233                     zygosity = 0.0
234  
235             # Split multiallelics?
236             # XXX Ensure sample genotypes are handled properly
237  ->         start = record.start
238             for alt in record.alts:
239                 if alt == '<NON_REF>':
240                     # gVCF placeholder -- not a real allele
241                     continue
242                 end = _get_end(start, alt, record.info)
(Pdb) sample_id
'NORMAL'
(Pdb) normal_id
'TUMOR'
```

I use cnvkit-0.8.3 on Ubuntu 16.04.

**Comment by etal** [comment]
Could you update to the most recent CNVkit version 0.8.4 and try it again? Mutect parsing and Theta export have both improved since 0.8.3.

**Comment by Strausyatina** [comment]
Thanks for the suggestion. Unfortunately, `export theta` still does not work. Now both mutect 1 and mutect 2 inputs fails with the same error:
```
Traceback (most recent call last):
  File "/home/asya/TOOLS/cnvkit-0.8.4/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/asya/TOOLS/cnvkit-0.8.4/cnvlib/commands.py", line 1387, in _cmd_export_theta
    table = export.export_theta(tumor_cn, normal_cn)
  File "/home/asya/TOOLS/cnvkit-0.8.4/cnvlib/export.py", line 373, in export_theta
    ref_means, nbins = ref_means_nbins(tumor_segs, normal_cn)
  File "/home/asya/TOOLS/cnvkit-0.8.4/cnvlib/export.py", line 399, in ref_means_nbins
    subarrs = [subarr for _seg, subarr in normal_cn.by_ranges(tumor_segs)]
  File "/home/asya/TOOLS/cnvkit-0.8.4/cnvlib/genome/gary.py", line 261, in by_ranges
    mode, keep_empty):
  File "/home/asya/TOOLS/cnvkit-0.8.4/cnvlib/genome/intersect.py", line 29, in by_ranges
    subranges):
  File "/home/asya/TOOLS/cnvkit-0.8.4/cnvlib/genome/intersect.py", line 89, in iter_ranges
    ) and not table.end.is_monotonic_increasing:
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 2672, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'is_monotonic_increasing'
```

**Comment by etal** [comment]
Sorry for the trouble. You also need to update the dependency `pandas` to the latest version 0.19.2. This should happen automatically with `conda` or `pip`, depending on your configuration.

**Comment by Strausyatina** [comment]
Thank you for the answer! I've updated the packages. But mutect2 still swaps the columns, see the debugger log:

```
Selected test sample NORMAL and control sample TUMOR
> /home/asya/TOOLS/cnvkit-0.8.4/cnvlib/tabio/vcfio.py(184)_parse_records()
-> cnt_reject = 0  # For logging
(Pdb) s
> /home/asya/TOOLS/cnvkit-0.8.4/cnvlib/tabio/vcfio.py(185)_parse_records()
-> for record in records:
(Pdb) l
180         flag, or the SOMATIC info field.
181         """
182         import pdb; pdb.set_trace()
183  
184         cnt_reject = 0  # For logging
185  ->     for record in records:
186             if (skip_reject and record.filter and len(record.filter) > 0
187                 and len(set(record.filter) - {'PASS', '.'})):
188                 cnt_reject += 1
189                 continue
190  
(Pdb) sample_id
'NORMAL'
(Pdb) normal_id
'TUMOR'
```

For mutect1 input, this error does not happen.

**Comment by etal** [comment]
Thanks for letting me know. I don't use Mutect2 myself; is there any consistent labeling in the Mutect2-generated VCF that indicates which of the two samples is normal vs. tumor?

If not, you can always directly specify the tumor and normal sample IDs with the command line options `-i`/`--sample-id` and `-n`/`--normal-id`, respectively. (And if that isn't working properly, please let me know.)

**Comment by Strausyatina** [comment]
Thank you for mentioning the flags! I've tried running the command specifying normal and tumor id-s on mutect2.
The output contained the lines:
```
Selected test sample TUMOR
Loaded 4044 records; skipped: 0 somatic, 785 depth
```
i.e. it skipped the `NORMAL` column and `... .normal.snp_formatted.txt` file is empty (only header is present).

The reason why the command may fail is a strange header format of mutect2-generated VCF (taken from TCGA), for example it contains such a line:
```
##SAMPLE=<ID=NORMAL,SampleName=TCGA-06-0221-10A-01D-1491-08,File=/var/lib/cwl/job813710125_input_9hTmgb/C484.TCGA-06-0221-10A-01D-1491-08.5_gdc_realn.bam>
```
Also mutect2 has another notation for somatic events, 
```
##FILTER=<ID=germline_risk,Description="Evidence indicates this site is germline, not somatic">
```
they have `germline_risk` flag in the filter column for non-somatic mutations.
Also it is impossible to distinguish the columns by TCGA id-s since the header has the structure:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NORMAL  TUMOR
```
and GATKCommandLine doesn't contain id's too.

But the header structure of mutect2-generated VCF should probably be more convenient to you, since you have no need to search for normal and tumor id and just use the corresponding column names. It would be wonderful if you could consider the option of supporting mutect2 format in your project. Anyway, thank you for your tool! I consider the issue closed, indeed, because mutect1 seems to work just fine.

**Comment by etal** [comment]
Just getting back to this, sorry. I would like to support Mutect2 VCFs in CNVkit if that's possible.

Is it true that Mutect2 VCF headers always uses the sample IDs "TUMOR" and "NORMAL"? That seems... curious, but I haven't seen any example files that are different.

**Comment by lbeltrame** [comment]
As a user of MuTect2, not necessarily, as far as I can remember. However, I get my result through bcbio, which may rename them.

**Comment by etal** [comment]
OK, I've added a check for the presence of columns named TUMOR and NORMAL in VCFs from Mutect2.

Another possibly useful flag to try here is `-z`, to select heterozygous SNPs based on allele frequency rather than the called genotype, which with Mutect2 is always 0/0 for the normal sample. But it remains true that Mutect2 drops most germline SNPs from the output, at least in the output VCFs I've seen, so these VCFs do not contain much information that CNVkit could use to detect LOH.

**Comment by cjhong** [comment]
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="Accept as a confident somatic mutation">
##FILTER=<ID=REJECT,Description="Rejected as a confident somatic mutation">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=BQ,Number=A,Type=Float,Description="Average base quality for reads supporting alleles">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=FA,Number=A,Type=Float,Description="Allele fraction of the alternate allele with regard to reference">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##FORMAT=<ID=SS,Number=1,Type=Integer,Description="Variant status relative to non-adjacent Normal,0=wildtype,1=germline,2=somatic,3=LOH,4=post-transcriptional modification,5=unknown">
##INFO=<ID=DB,Number=0,Type=Flag,Description="dbSNP Membership">
##INFO=<ID=MQ0,Number=1,Type=Integer,Description="Total Mapping Quality Zero Reads">
##INFO=<ID=SOMATIC,Number=0,Type=Flag,Description="Somatic event">
##INFO=<ID=VT,Number=1,Type=String,Description="Variant type, can be SNP, INS or DEL">
##contig=<ID=1,length=249250621,assembly=hg19>
##contig=<ID=2,length=243199373,assembly=hg19>
##contig=<ID=3,length=198022430,assembly=hg19>
##contig=<ID=4,length=191154276,assembly=hg19>
##contig=<ID=5,length=180915260,assembly=hg19>
##contig=<ID=6,length=171115067,assembly=hg19>
##contig=<ID=7,length=159138663,assembly=hg19>
##contig=<ID=8,length=146364022,assembly=hg19>
##contig=<ID=9,length=141213431,assembly=hg19>
##contig=<ID=10,length=135534747,assembly=hg19>
##contig=<ID=11,length=135006516,assembly=hg19>
##contig=<ID=12,length=133851895,assembly=hg19>
##contig=<ID=13,length=115169878,assembly=hg19>
##contig=<ID=14,length=107349540,assembly=hg19>
##contig=<ID=15,length=102531392,assembly=hg19>
##contig=<ID=16,length=90354753,assembly=hg19>
##contig=<ID=17,length=81195210,assembly=hg19>
##contig=<ID=18,length=78077248,assembly=hg19>
##contig=<ID=19,length=59128983,assembly=hg19>
##contig=<ID=20,length=63025520,assembly=hg19>
##contig=<ID=21,length=48129895,assembly=hg19>
##contig=<ID=22,length=51304566,assembly=hg19>
##contig=<ID=X,length=155270560,assembly=hg19>
##contig=<ID=Y,length=59373566,assembly=hg19>
##contig=<ID=MT,length=16571,assembly=hg19>
##reference=file:///fs/ess/scratch/PCCF0022/refdata/wes/hg19/hg19_nochr.fa
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  G232TgP0        G232NgP0
1       38411543        .       A       G       .       PASS    SOMATIC;VT=SNP  GT:AD:BQ:DP:FA:SS       0/1:71,6:36:77:0.078:2  0:56,0:.:56:0.00:0
----------------
cnvkit.py export theta -r ${ind}/cnvgst.reference.cnn -v ${mutec_vcfd}/${sample_id}.vcf -i G232TgP0 -n G232NgP0 -z ${ind}/${sample_id}.s3.recal.realigned.cns
---------------
Wrote ***/G232TgP0
Selected test sample G232TgP0 and control sample G232NgP0
Loaded 0 records; skipped: 160 somatic, 2 depth
Kept 0 heterozygous of 0 VCF records
Traceback (most recent call last):
  File "/users/PCCF0022/hongc2/miniconda3/bin/cnvkit.py", line 9, in <module>
    args.func(args)
  File "/users/PCCF0022/hongc2/miniconda3/lib/python3.8/site-packages/cnvlib/commands.py", line 1747, in _cmd_export_theta
    raise ValueError("VCF contains no usable SNV records")
ValueError: VCF contains no usable SNV records
-------------
Any suggestion?
