### ISSUE TITLE
heatmap: give some control to figure size / font

### ISSUE THREAD

**Issue by lbeltrame** [etal/cnvkit#196]
While I wouldn't want to have full parameters for figure drawing, heatmap can get a little cramped due to font size when many samples are plotted (I did 48, and unfortunately I need all of them in the same image).

An alternative would be a code snippet to do the same via cnvlib.

**Comment by etal** [comment]
Good point. The quick workarounds are:

A. Run the `heatmap` command without `-o` to generate an interactive plot, then expand that plot to the full size of your screen and use the plot window's save button to save the plot in your preferred format.

B. Use a [matplotlibrc](https://cnvkit.readthedocs.io/en/stable/plots.html?highlight=matplotlibrc#customizing-plots) file to change the default font size.

C. Use `cnvlib.do_heatmap` to generate an interactive plot, then get the current axis and modify the font size with `matplotlib.pyplot` (and change anything else you like). The ipython/jupyter notebook is handy for this.

The documentation could be more clear on this.
