### ISSUE TITLE
SEG export generates files with overlapping segments

### ISSUE THREAD

**Issue by lbeltrame** [etal/cnvkit#197]
This is a problem because GISTIC will refuse to analyze them. My guess again is about zero vs 1-based coordinates and open vs close ended.

Example:

```
LC0050_VES-UT-POUCH-cnvkit-call.cns.fixed 1 16332626  18809551  361 -0.284919
LC0050_VES-UT-POUCH-cnvkit-call.cns.fixed 1 18809550  55571936  5433  0.238265
```

**Comment by etal** [comment]
Are you using the latest version of CNVkit (either 0.8.4 or development)? I thought I fixed this recently.

**Comment by lbeltrame** [comment]
```
In [2]: cnvlib.__version__
Out[2]: '0.8.4'
```

I'll double check by regenerating the SEG file, and report back.

**Comment by lbeltrame** [comment]
Reproduced. I'll test now with the latest git checkout.

**Comment by etal** [comment]
OK, thanks for investigating. It sounds like I missed this part of the code in my last attempt to sort out 1-based SEG vs. 0-based CNVkit internals.
