### ISSUE TITLE
diagram, scatter: Remove alt contigs before rendering

### ISSUE THREAD

**Issue by matthdsm** [etal/cnvkit#209]
Hi Eric,

I've just succesfully ran a cnvkit analysis using bcbio. so far, the results are looking good, but there's still an issue with the visualisations. Due to the set of alternate chromosomes in hg38, and the fixed size of the plots, the visualisations are way too compressed.

Would it be possible to make the size of the visualisation more dynamic, so all data fits? Alternatively, perhaps the alternate chromosomes could be parsed out during the creation of the images?

Thanks a lot
M

**Comment by etal** [comment]
Are the alternate chromosomes useful at all for CNV calling? If not, as a workaround you can delete those lines from the .cnn, .cnr and .cns files.

I'll look into making it easier to strip out these chromosomes automatically in the pipeline.

**Comment by matthdsm** [comment]
Hi Eric,
In our case we only need the canonical chromosomes (e.g. 1-22,X and Y). Currently we do make it work by removing the unneeded lines from the results, but it would be nice to have have "pre-cleaned" outputs, especially when using the "batch" option.

Thanks!
M
