### ISSUE TITLE
Germline CNAs in reference

### ISSUE THREAD

**Issue by lima1** [etal/cnvkit#210]
Hi Eric,

I'm using cnvkit in version 0.8.5. Do you have any recommendations on how to deal with germline CNAs in the reference pool?  I for example frequently get deletion calls with very low log-ratio (<20) even in low purity samples because of germline deletions (also appearing in a significant portion of normal controls).  A quick and dirty fix would be to exclude targets with 0 coverage in a certain fraction of normal samples, but there are probably cleaner ways of generating germline blacklists. One approach we followed was to weight targets by inverse of variance in the pool of normals, which seem to work fairly well. Not sure if this is something you looked into already.

Thanks for a great tool,
Markus

**Comment by etal** [comment]
Hi Markus, thanks for letting me know.

CNVkit tries to do [most of this automatically](http://cnvkit.readthedocs.io/en/stable/pipeline.html#how-it-works), and should do better when a pool of normals is used for the reference:

- Bin "log2", "depth", and "spread" are calculated by biweight methods, which attempt to ignore outliers like homozygous deletions in the germline.
- After that, bins where the calculated "spread" is too high, or "log2" is too far from the global average, are masked out and will not be included in the .cnr files generated by the `fix` command.
- Bin weights are derived from "spread" and "depth" values, so noisy bins are downweighted for segmentation.

Some regions of the genome are just difficult, but if you know where they are, you can use `access --exclude` to ensure they are not included in the off-target bins (by providing the generated access.bed  file to `antitarget`).

Looking at the code again, I think the `reference` command could do more to identify per-sample outlier bins specifically and mask them out.

If you find any other approaches that work, I'd be more than happy to include them in CNVkit.

**Comment by lima1** [comment]
Thanks Eric. Yes, filtering common germline CNAs from the baits BED file and then use access --exclude is probably the cleanest way of doing it.
