### ISSUE TITLE
Depth for PCR based amplicons(overlap) 

### ISSUE THREAD

**Issue by tiehan** [etal/cnvkit#212]
I have many overlap amplicons.
Through the bam file , I can get the pair reads start and end . The pair reads' start and end is completely match to one of amplicons' start and end . I want get every amplicon's real depth to evaluate every amplicon's performance.
Can cnvkit calculate it?

**Comment by etal** [comment]
CNVkit will give you the depths in each targeted region, but won't distinguish between amplicons by read pair start/end coordinates.
 
I think you can do this analysis with [Pysam](https://pysam.readthedocs.io/en/latest/). Sort the BAM file by read name (not coordinates), then do something like:

    from __future__ import print_function
    import collections, pysam

    amplicons = collections.defaultdict(int)
    all_reads = pysam.Samfile(bam_filename, 'rb').fetch()
    for read in all_reads:
        mate = next(all_reads)
        if read.is_proper_pair():
            if read.reference_start < mate.reference_start:
                coords = (reference_name, read.reference_start, mate.reference_end)
            else:
                coords = (reference_name, mate.reference_start, read.reference_end)
            amplicons[coords] += 1

    # Print the read counts for each amplicon to standard output
    for (refname, start, end), count in sorted(amplicons.iteritems()):
        print(refname, start+1, end, count, sep='\t')

(Untested code written quickly. If you aren't able to get this to work, try searching/asking [Biostars](https://www.biostars.org/) for help.)

**Comment by tiehan** [comment]
Thanks,etal.
