### ISSUE TITLE
Cant run segment function on my data

### ISSUE THREAD

**Issue by pradyumnasagar** [etal/cnvkit#213]
I have exome sequencing data, when I try to run segment function 

` ./cnvkit.py segment /home/mlscl3/cnv/002.cnr -o /home/mlscl3/cnv/plots/002.cns`
it run into the following error

```

 Traceback (most recent call last):
  File "./cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/mlscl3/tools/cnvkit-master/cnvlib/commands.py", line 599, in _cmd_segment
    processes=args.processes)
  File "/home/mlscl3/tools/cnvkit-master/cnvlib/segmentation/__init__.py", line 32, in do_segmentation
    skip_outliers, save_dataframe, rlibpath)
  File "/home/mlscl3/tools/cnvkit-master/cnvlib/segmentation/__init__.py", line 117, in _do_segmentation
    sample_id=cnarr.sample_id)
  File "/home/mlscl3/tools/cnvkit-master/skgenome/tabio/__init__.py", line 80, in read
    dframe = reader(infile, **kwargs)
  File "/home/mlscl3/tools/cnvkit-master/skgenome/tabio/seg.py", line 72, in read_seg
    raise IndexError("No sample ID '%s' found in SEG file" % sample_id)
IndexError: No sample ID '002' found in SEG file
```

Any solution?

**Comment by pradyumnasagar** [comment]
file size is around 50 GB

**Comment by etal** [comment]
Thanks for reporting. It looks like the SEG parser isn't handling integer sample IDs properly.

The development version of CNVkit is a little unstable right now. Can you try the stable version 0.8.5 to see if it works there? Either check out `v0.8.5` if you cloned the git repo, or use pip/conda to install `cnvkit=0.8.5`.

**Comment by etal** [comment]
Also, that's a huge file size (for the .cnr, I assume). I usually see around 15-20 MB, not GB. At 50GB, you might run out of memory, but even for human WGS I wouldn't expect the file size to be much more than ~4GB even with 10bp bins.

How many lines is your .cnr file? If it's around 200k-300k, which is typical for exomes, then maybe the gene labels are very long, or the bin size is very small.

**Comment by etal** [comment]
As a workaround, you could modify your sample filenames so that they are not an integer with leading zeros -- e.g. rename from `001.cnr` to `c001.cnr`.

**Comment by etal** [comment]
This is fixed in the development version now, if you'd like to try it out.

**Comment by pradyumnasagar** [comment]
Sorry the file size is bam file size i mean, cnr file is around 40 mb. I will try the development version as you suggested.
Thank you.

**Comment by pradyumnasagar** [comment]
Thanks for the fix, Itis just working fine now.
