### ISSUE TITLE
batch stopped after generating reference.cnn

### ISSUE THREAD

**Issue by igordot** [etal/cnvkit#214]
I was running `cnvkit.py batch`. It looks like it stopped right after `reference`:
```
Relative log2 coverage of chrX=-0.753, chrY=-12.5 (maleness=0.373 x 0.926 = 0.345) --> assuming female
Correcting for GC bias...
Correcting for RepeatMasker bias...
Calculating average bin coverages
Calculating bin spreads
Targets: 7310 (2.0645%) bins failed filters:
  WASH7P                                              chr1:14621-14712           log2=-3.343  spread=2.505  rmask=nan
  -                                                   chr1:65510-65625           log2=-27.158  spread=0.051  rmask=nan
...
...
    "                                                 chrX:155235012-155235183   log2=-26.883  spread=0.074  rmask=nan
    "                                                 chrX:155237268-155237368   log2=-26.703  spread=0.044  rmask=nan
Antitargets: 572 (1.4543%) bins failed filters
Wrote ./reference.cnn with 393412 regions
```
I was able to run `fix` manually and it worked, so it doesn't seem like there is a problem with the files generated up to that point. Should I be concerned that `batch` ended abruptly? Was that an error or did it run into some problem?

**Comment by etal** [comment]
I haven't seen this happen at that point in the pipeline. It used to be that the pipeline would silently halt during segmentation if the R subprocess crashed, but `fix` doesn't use any subprocesses or parallelization.

Which version of CNVkit were you using? Could you show me the full `batch` command line you used?

**Comment by igordot** [comment]
This is the command I used:
```
cnvkit.py batch \
--processes 8 \
--diagram --scatter \
--fasta /path/genome.fa \
--annotate ../refFlat.txt \
--access ./access-5k-mappable.hg19.bed \
--targets ../regions.bed \
--output-dir . \
--normal normal.bam \
tumor.bam
```
I also tried a different one with multiple tumor BAMs and that had the same problem.

I later realized I was missing some R packages, but installing them did not solve this.

**Comment by etal** [comment]
Try it with the tumor BAM filename before the `--normal` flag, instead of after:

```
cnvkit.py batch \
tumor.bam \
--normal normal.bam \
--processes 8 \
--diagram --scatter \
--fasta /path/genome.fa \
--annotate ../refFlat.txt \
--access ./access-5k-mappable.hg19.bed \
--targets ../regions.bed \
--output-dir .
```

Any number of filenames can come after `--normal` to specify a pool of normal samples (and I agree this is not intuitive or obvious). So, in your command line both `normal.bam` and `tumor.bam` are interpreted as normal samples, and there are no tumor samples, so a reference is built but no samples are processed any further than that.

**Comment by igordot** [comment]
Thanks for the quick response!

I am used to putting all the parameters first. I didn't realize it would be unclear where normals ended and tumors began. I fixed the order and everything is fine now.

I guess one suggestion would be to check that any tumors are present. When some of the parameters are missing, the corresponding errors are very clear.

**Comment by etal** [comment]
Thanks for the suggestion, it's in the development version now.
