### ISSUE TITLE
batch wgs: -n/--normal and -t/--targets (at least) must be given

### ISSUE THREAD

**Issue by igordot** [etal/cnvkit#216]
According to the docs (http://cnvkit.readthedocs.io/en/stable/nonhybrid.html), this should be the command for WGS:
```
cnvkit.py batch -m wgs -g data/access-5kb-mappable.hg19.bed --annotate refFlat.txt *.bam
```
But when I do that, I get an error:
```
Options -n/--normal and -t/--targets (at least) must be given to build a new reference if -r/--reference is not used.
```
Is that expected?

**Comment by etal** [comment]
Well, for some value of "expected", but I agree it's a mistake in the code -- the `wgs` mode can theoretically run without targets as long as a reference genome FASTA sequence is given.

**Comment by etal** [comment]
I should clarify that in the docs. The `batch` command wants the `-n` flag with zero or more normal sample BAMs after it to indicate whether you want a flat, paired or pooled reference. You don't necessarily need a normal sample, you can just add the `-n` flag with nothing after it to tell CNVkit you want a flat reference. (Unless you do want a paired or pooled reference, in which case, give it your normal samples there.)

Are you using version 0.8.5 or the development version from GitHub?

**Comment by igordot** [comment]
Thanks for clarifying!

I see the normals is already addressed in the help:
```
  -n [NORMAL [NORMAL ...]], --normal [NORMAL [NORMAL ...]]
                        Normal samples (.bam) to construct the pooled
                        reference. If this option is used but no files are
                        given, a "flat" reference will be built.
```
I was wondering why someone would that parameter with no arguments. Now it makes sense.

I am using 0.8.5.

**Comment by etal** [comment]
The `wgs` mode didn't actually require `-t` in the code, but the error message for missing `-n` and `-t` (for only `amplicon` and `hybrid`) was misleadingly combined. The error messages are now more specific to the actual problem. I also added a bit more detail to the `-n` option's help text.
