### ISSUE TITLE
Documentation: clarify the output of breaks

### ISSUE THREAD

**Issue by lbeltrame** [etal/cnvkit#220]
The documentation does not tell precisely what the headings in `breaks` are and the headings themselves aren't self-explanatory:

`gene    chromosome    location    change    probes_left    probes_right`

For example the meaning of  `change` isn't exactly clear. I assume `probes_left` and `probes_right` are the number of probes on the two sides of the break?

Lastly, sometimes the gene column contains a generic `Y_RNA` (at least on the data we ran it on). What does that mean?

cc @LMannarino who found out this.

**Comment by etal** [comment]
OK, I'll update the docs:

- `change` is the difference between the log2 values of the left and right segments on either side of the breakpoint.
- `probes_left` and `probes_right` are the number of probes on the two sides of the break.
- `Y_RNA` is just a gene label that appears in your data, I think. It might be a database's genomic annotation that's reused at several locations in the genome.
