### ISSUE TITLE
fail to build docker image

### ISSUE THREAD

**Issue by kumakiwami** [etal/cnvkit#221]
I try to build a docker image from the dockerfile but get such error massage

"""

TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
INFO[0041] The command [/bin/sh -c pip install -U futures pandas pyfaidx pysam] returned a non-zero code: 2

"""

I guess maybe something wrong with "pip" utility

**Comment by etal** [comment]
Could you show the rest of the log messages? The command worked for me earlier. Might be a temporary network error, guessing from the error message here.

**Comment by kumakiwami** [comment]
@etal Thanks, it was a network error, indeed.
