### ISSUE TITLE
Suppress Y axis labels in heatmap

### ISSUE THREAD

**Issue by patidarr** [etal/cnvkit#233]
Hi,

Is it possible to suppress Y Axis (Sample Names) labels in heatmap? its overplotting when I have >100 samples.

Thanks,
Rajesh

**Comment by etal** [comment]
Only through the Python API (cnvlib) at the moment. The development version of the docs shows an example that you can adapt:
https://cnvkit.readthedocs.io/en/master/plots.html#customizing-plots
