### ISSUE TITLE
Diseased Samples in Reference?

### ISSUE THREAD

**Issue by charliecurnin** [etal/cnvkit#240]
Hi Eric, 

While trying to assemble a reference from about 557 samples, I discovered an unfortunately surprise. 

```
sample1.targetcoverage.cnn bins do not match those in sample2.targetcoverage.cnn
```

Just looking at the number of lines in each file (226627 to 226869), I can tell it's true. Of the 557 samples, 169 have 226627 lines—the rest have 226869.

Then I realized something—and I felt very silly. All 169 of those samples are diseased in some way (41 that have the right number of lines are also diseased, though). Should I be keeping them out of the reference?

I thought about this for a split second and thought that it would be OK to include them, because even if one had a copy number change in one direction (e.g., a gain) another might have a copy number change in the other (e.g., a loss)—and anyway, given that I'm using almost 557 samples, any abnormalities at a particular locus will be buried by more than 500 samples that are probably normal there.

But, does this mean I should be keeping all diseased samples out of the reference?

Also, will this cause problems downstream, if I try to call some of the diseased samples against a pooled reference that has different bins?

Thanks for your help.

**Comment by charliecurnin** [comment]
I see clearly in the readthedocs 

>**Compile a copy-number reference from the given files or directory (containing normal samples).** 

So I guess that settles question 1. 

As for question 2, I assume that it'll be pretty much fine to call diseased samples against the normal reference since that's basically what this library is for. 

Unless you want to confirm, I'll close this soon.

**Comment by etal** [comment]
Typically, you would build a reference from a pool of normal samples, then use that reference to call CNVs in tumor samples. If you know your data well and take responsibility for handling anomalies manually, CNVkit will let you bend the rules and e.g. build a reference from a large pool of possibly aneuploid samples. The reference-building procedure will also try to identify and discard outlier datapoints, e.g. rare CNVs in the reference pool.

But the number of bins in your .cnn files must match. If your disesase/test/tumor samples have a different number of bins than the normal samples, then the reference won't work on those test samples. Did you use a different capture panel for those samples, or did something else go wrong?

If the sequencing protocols were different for the two groups of samples, you have 2 options:
1. Use a generic or "flat" reference, i.e. don't use the normal samples, just analyze the test samples in isolation.
2. Take the intersection of targeted regions in both panels as your targets. Take the symmetric difference in targeted regions in both panels as your "excluded" regions to use with `access -x`. Then the number of bins ought to match, and you can proceed with your analysis. But watch out for anomalies in your data.
