### ISSUE TITLE
Fix with Whole Genome Samples

### ISSUE THREAD

**Issue by charliecurnin** [etal/cnvkit#242]
From what I understand, fix is usually run like `cnvkit.py fix Sample.targetcoverage.cnn Sample.antitargetcoverage.cnn Reference.cnn -o Sample.cnr`. 

So what I should I do when I want to call `fix` on a whole genome sample that doesn't have a `.antitargetcoverage.cnn` file? Can I simply omit the antitarget argument?

**Comment by etal** [comment]
Yes, this should work in the current version of CNVkit.

In earlier versions, the workaround for WGS was to create a blank file called `Sample.antitargetcoverage.cnn` and use that to fool the `fix` command. That shouldn't be necessary anymore, though.

**Comment by charliecurnin** [comment]
Cool. Thank you.
