### ISSUE TITLE
Y Coverage for Female Samples

### ISSUE THREAD

**Issue by charliecurnin** [etal/cnvkit#244]
I noticed that a few of my `.call.cns` files for female samples have rows for chromosome Y (the copy number throughout Y is zero though many have one small bin at the end where `cn`is 1; `cn` in chromosome X is mostly 2). 

I then noticed that in some of `.targetcoverage.cnn` files for female samples, there were scattered small bins that had a small, non-zero coverage, typically in the last bin around (58819861,59033549). Does this point to something being wrong with my BAM files?

**Comment by etal** [comment]
No, it's normal for a small number of reads to be mapped to the Y chromosome in female samples. The X and Y chromosomes share some regions with similar sequences (e.g. pseudoautosomal regions). And, reads from regions with repetitive sequences can be mapped arbitrarily to any region of the genome sharing that repetitive sequence, which can include parts of chromosome Y. Sequence repeats are common near the ends of chromosomes, which may explain why the spurious cn=1 segment appears at the end of Y.

**Comment by charliecurnin** [comment]
Thank you!
