### ISSUE TITLE
Use dask or koalas for distributed processing

### ISSUE THREAD

**Issue by etal** [etal/cnvkit#245]
Parallelization is currently done with built-in multiprocessing and manual chunking. Perhaps [Dask](https://dask.org/) or [Koalas](https://github.com/databricks/koalas) could help us do better and open up some new opportunities while keeping the currently simplicity of single-node installation and processing.

See also:
- [hail](https://hail.is/)
- [ADAM](https://github.com/bigdatagenomics/adam)
- [scikit-allel](https://scikit-allel.readthedocs.io/en/latest/)

**Comment by kyleabeauchamp** [comment]
I'm a fan of Snakemake, although it's more CLI-based than a python library.  An embeddable Snakemake python API would be a great way to implement the cnvkit workflow if the Snakemake author could be convinced to support it.

**Comment by etal** [comment]
Good to know, is there a roadmap for a proper Snakemake API? It looks the current API is a function that loads an existing snakemakefile.

The idea with using Dask here, and with skgenome in general, is to provide a Pythonic API for genomic intervals, in line with R/Bioconductor's GenomicRanges where you handle genomic data through a sort of enhanced dataframe. It's orthogonal to pysam and meant to let you tweak the dataset more directly than tabix/bedtools/pybedtools can support through the shell. I don't know how well it works within a reusable, portable library as opposed to a standalone application (where the user can specify the available RAM, CPUs, chunk sizes, etc.).

In the current pandas implementation the entire dataset is loaded in memory, and in some procedures a lot of intermediate copying is done. I'm hoping that Dask, if used properly and probably with some API changes in CNVkit, can help use memory more efficiently and make more of the API process in parallel automatically. It could also coordinate the pipeline in the `batch` command, and maybe help resolve #48 cleanly.

**Comment by kyleabeauchamp** [comment]
There's no immediate roadmap for the snakemake API AFAIK.  And you're right that your particular use case is more in line with dask.

**Comment by etal** [comment]
See also [PyArrow](https://arrow.apache.org/docs/python/pandas.html#pandas) and the incipient pandas2.
