### ISSUE TITLE
Segmetrics Confidence Interval

### ISSUE THREAD

**Issue by charliecurnin** [etal/cnvkit#247]
Hi Eric, 

I'm trying to understand the confidence interval calculated by `segmetrics`. 

I have two questions:

- What's the actual percentage likelihood that the `log2` value falls between `ci_lo` and `ci_hi`?
- How can I find the actual integer copy number that `ci_lo` and `ci_hi` correspond to?

For example, I'm looking at a segment with `log2` of `-0.51003 `, `ci_lo` of `-0.584272`, and `ci_hi` of `-0.421133`.

Running `call` calculated a `cn` for this segment of `1`. But wondering whether `ci_lo` and `ci_hi` correspond to a `cn` of `1` also, or something different. Basically, I'm looking to find a confidence interval on `cn`.

**Comment by etal** [comment]
By default the confidence intervals are calculated with alpha=0.05, so these are 95% confidence intervals.

One way to look at it is that the correspondence of log2 ratios to integer `cn` values is fixed, e.g. for autosomes, log2=0.0 -> cn=2, log2=0.58 -> cn=3, etc. (see [here](https://cnvkit.readthedocs.io/en/stable/calling.html) and [here](https://cnvkit.readthedocs.io/en/stable/pipeline.html#calling-methods)). The CI for the segment mean, in log2 scale, might overlap one or more of those fixed values, indicating that the integer copy numbers within the CI are all plausible.
- If the CI includes log2=0.0, it's plausible that the segment's copy number is neutral.
- If the CI /only/ includes 0.0 but not -1.0 (cn=1) or +0.58 (cn=3), then cn=2 is the only plausible value (given the data).
- If `ci_lo` is below 0.0 and `ci_hi` is above +0.58, then both cn=2 and cn=3 are plausible values for the underlying copy number, given the data. In that case maybe SNP allele frequencies (`call -v`) will help support one possibility over the other.
