### ISSUE TITLE
Combine CNV data for two different panels

### ISSUE THREAD

**Issue by JoKw** [etal/cnvkit#249]
Hi, I have targeted seq data with each sample run on two different capture panels. Since the two panels have multiple genes in common, how should I call the CNV for each sample? Thanks

**Comment by etal** [comment]
Does this mean you sequenced several samples, with some using one capture panel and the rest using another?

If so, do you have at least one normal/control sample sequenced on each panel?

If yes to both, then I recommend building two reference profiles (.cnn), one for each panel, and using each profile to analyze the test samples sequenced on each respective panel separately. In practice, this means running the `batch` command twice, treating the two panels as separate cohorts for the two analyses. Just use the same reference genome and gene annotation (i.e. gene names in the target BED files).

After segmentation, the .cns files are then comparable across the two panels -- you can see if the same gene was altered in samples from either panel, for example. But if you try mixing the panels before that point in the analysis you will have problems.

If either panel (or both panels) does not have any normal samples to use as a control, proceed as above, but with no normals where they're unavailable, i.e. use a "flat" reference there. If the test/tumor samples were all on one panel and the normal/control samples were all on another, then the normals are not usable for CNV analysis and you should proceed with a "flat" reference.

**Comment by JoKw** [comment]
Sorry for the unclarity of my original post. I only have tumor samples and all tumor samples were on both panels. The two panels have multiple genes in common. So how should I call the CNV for each sample? Thanks
