### ISSUE TITLE
cnvkit.py batch: Document that --output-reference ignored --output-dir [SUGGESTION]

### ISSUE THREAD

**Issue by HenrikBengtsson** [etal/cnvkit#25]
I just ran `cnvkit.py batch` outputting to a subdirectory, but noticed that all files but the "copy number reference profile *.cnn file was still outputted to the working directory.  I can see how this design/behavior makes sense.  However, may I suggest that it's documented, e.g. "(Ignores -o/--output-dir option)":

```bash
cnvkit.py batch --help
...
  --output-reference OUTPUT_REFERENCE
                        Output filename for the new reference file being
                        created. (Ignores -o/--output-dir option)
...
```

**Comment by etal** [comment]
Gotcha. Thanks for noticing this.

**Comment by HenrikBengtsson** [comment]
Your update makes it is even more informative. Thxs.
