### ISSUE TITLE
why is --annotate option mandatory for -wgs ?

### ISSUE THREAD

**Issue by rbatorsky-claritas** [etal/cnvkit#250]
As part of my workflow I'll be annotating cnv calls with my own gene database and do not need to annotate as part of the CNVkit pipeline. I noticed that the -annotate option is mandatory for -wgs. Why is this the case? First, I'd like to save time by not annotating segments, but more importantly I want to make sure that gene definitions are not built in to the workflow in some hidden way. Thanks for any clarification!

**Comment by etal** [comment]
An empty file might work. If it doesn't, try a file with one line (e.g. "chr1:1-2"), or a BED file with one line per chromosome with the chromosome name (or whatever) as the label in the fourth column.

The pipeline doesn't use gene names (really, arbitrary region labels) in any specific way, but the downstream commands for plotting will use gene labels to summarize the data being shown, and behavior there can be surprising if the regions of interest don't have distinct labels. (The bundled script `cnn_annotate.py` is there to help users who skipped the annotation step and later regret it.)

**Comment by etal** [comment]
This is fixed in the development version now. Does the latest from GitHub work all right on your data?

Please feel free to recommend other features that would help with WGS analysis, or point out deficiencies you see in your own benchmarking, as I don't work with WGS data very often myself.
