### ISSUE TITLE
conda build errors on travis

### ISSUE THREAD

**Issue by micknudsen** [etal/cnvkit#254]
There seems to be some problems installing _cnvkit_ using _conda_. It just hangs indefinitely.

```
[micknudsen@work:~]$ conda create -n test cnvkit
Fetching package metadata ...............
Solving package specifications: .
```

Removing **conda-forge** from the list of channels allows me to install _cnvkit_ (but it then fails at runtime). Any clue what could be wrong?

**Comment by etal** [comment]
Sorry, I'm not sure what's causing it to hang for so long. I saw your pull request to bioconda: bioconda/bioconda-recipes#5926

I've noticed that sometimes this command takes a ludicrously long time, but does eventually complete. Maybe up to 90 minutes, going by the TravisCI build logs in the linked issue. Is there a way to make conda emit more debugging info when resolving package dependencies, so I can see which dependency is causing problems?

As a workaround, specifying `cnvkit=0.8.5` ought to retrieve the last known-good conda build. As another workaround, you can install CNVkit's dependencies in a conda environment, then use `pip install -e .` in a clone of the GitHub repo to install the development version within the same conda environment.

When you drop the conda-forge channel, which version of CNVkit do you get?

**Comment by micknudsen** [comment]
I will try and let it run and see what happens. Didn't expect it to take *that* long. Installing without **conda-forge**

`conda create --override-channels -c defaults -c bioconda -c r -n test cnvkit`

installs `0.8.6a0-py36_2`, but then

```
(test) [michaelk@fe1 ~]$ cnvkit.py version
Traceback (most recent call last):
  File "/home/michaelk/anaconda/envs/test/bin/cnvkit.py", line 8, in <module>
    from cnvlib import commands
  File "/home/michaelk/anaconda/envs/test/lib/python3.6/site-packages/cnvlib/__init__.py", line 2, in <module>
    from .cmdutil import read_cna as read
  File "/home/michaelk/anaconda/envs/test/lib/python3.6/site-packages/cnvlib/cmdutil.py", line 7, in <module>
    from skgenome import tabio
  File "/home/michaelk/anaconda/envs/test/lib/python3.6/site-packages/skgenome/__init__.py", line 1, in <module>
    from . import tabio
  File "/home/michaelk/anaconda/envs/test/lib/python3.6/site-packages/skgenome/tabio/__init__.py", line 17, in <module>
    from . import bedio, genepred, gff, picard, seg, tab, textcoord, vcfio
  File "/home/michaelk/anaconda/envs/test/lib/python3.6/site-packages/skgenome/tabio/vcfio.py", line 11, in <module>
    import pysam
  File "/home/michaelk/anaconda/envs/test/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

I will investigate whether it is possible to make _conda_ more verbose to track down what is taking so long.

**Comment by etal** [comment]
A couple updates:

1. CBS segmentation now uses the 'DNAcopy' package directly, which removes a lot of R dependencies.
2. I'm now seeing a strange build error in TravisCI:

```
ERROR:conda.core.link:An error occurred while installing package 'R::r-base-3.2.2-0'.

PaddingError: Placeholder of length '80' too short in package /home/travis/miniconda3/conda-bld/cnvkit_1507163698892/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/Rscript.

The package must be rebuilt with conda-build > 2.0.

Attempting to roll back.

Build prefix failed with prefix length 255

WARNING:conda_build.environ:Build prefix failed with prefix length 255

Error was: 

WARNING:conda_build.environ:Error was: 

Placeholder of length '80' too short in package /home/travis/miniconda3/conda-bld/cnvkit_1507163698892/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/Rscript.

The package must be rebuilt with conda-build > 2.0.
...
```

Can you decipher what's going on with R and conda-build? Is this anything I can fix from the CNVkit side?

**Comment by kyleabeauchamp** [comment]
No idea.  Possibly ask @bjorngruening on the bioconda tracker.  It may have to do with the fact that R packages have been re-built recently, so maybe this is grabbing an older R package from the wrong channel somehow?

**Comment by etal** [comment]
Is there a way to disable the `r` channel for the Travis build? I think it's unnecessary now. With `git grep` I'm not seeing anything that specifies the conda channels / packaging mechanism other than the README.

**Comment by kyleabeauchamp** [comment]
Here are some instances of R channel leakage, may just need to disable those:

https://github.com/etal/cnvkit/blob/master/.travis.yml#L11

**Comment by kyleabeauchamp** [comment]
Here is the recommended order (https://bioconda.github.io/):

```
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
```

**Comment by etal** [comment]
After removing the R channel from the build process on TravisCI, the conda build continues to fail under all configurations: https://travis-ci.org/etal/cnvkit

@bgruening would you mind taking a look? Does this look like a bug in the bioconda recipe or dependency chain?

**Comment by etal** [comment]
@kyleabeauchamp @bgruening @daler It looks like this error might be related to recent R work. Could any of you please take a look or point me in the right direction? This isn't my code, and I don't understand what's going wrong.

The relevant log messages under every configuration look like:

```
The following NEW packages will be INSTALLED:

    ... [some core packages] ...

ERROR:conda.core.link:An error occurred while installing package
'defaults::r-base-3.2.2-0'.

PaddingError: Placeholder of length '80' too short in package
/home/travis/miniconda3/conda-bld/cnvkit_1508175312761/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/Rscript.

The package must be rebuilt with conda-build > 2.0.

Attempting to roll back.

... [some repetitive bits] ...

WARNING:conda_build.environ:Placeholder of length '80' too short in package /home/travis/miniconda3/conda-bld/cnvkit_1508175312761/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/Rscript.

The package must be rebuilt with conda-build > 2.0.

One or more of your package dependencies needs to be rebuilt with a longer prefix length.

WARNING:conda_build.environ:One or more of your package dependencies needs to be rebuilt with a longer prefix length.

Falling back to legacy prefix length of 80 characters.

WARNING:conda_build.environ:Falling back to legacy prefix length of 80 characters.

Your package will not install into prefixes > 80 characters.

WARNING:conda_build.environ:Your package will not install into prefixes > 80 characters.

The following NEW packages will be INSTALLED:

    ... [many more packages, including R and Python packages] ...

CondaValueError: Could not find environment:
/home/travis/miniconda3/conda-bld/cnvkit_1508175312761/_test_env_placehold_place

Tests failed for cnvkit-dev-py35h6bc3a71_0.tar.bz2 - moving package to
/home/travis/miniconda3/conda-bld/broken

WARNING:conda_build.build:Tests failed for cnvkit-dev-py35h6bc3a71_0.tar.bz2 -
moving package to /home/travis/miniconda3/conda-bld/broken

removing: cnvkit-dev-py35h6bc3a71_0.tar.bz2

TESTS FAILED: cnvkit-dev-py35h6bc3a71_0.tar.bz2

```

**Comment by bgruening** [comment]
@etal I think it is related to this bug: https://github.com/conda/conda/issues/5536. Removing the default channel should hoefully work.
