### ISSUE TITLE
cnvkit for whole genome sequencing non tumor data without reference annotation files (refFlat.txt)

### ISSUE THREAD

**Issue by bhuwankhatri11** [etal/cnvkit#255]
Hi, 
Can cnvkit be used for finding CNV in whole genome sequencing normal data which does not have reference annotation file (refFlat.txt file cannot be found in UCSC)? If it can be used, what will be basic command lines for such type of analysis? I am new to this, I am looking for your help. Thank you!

**Comment by etal** [comment]
If you create an empty file and use that in place of refFlat.txt, that should work.

See also #250 . Now that I understand the problem, I'll make this argument optional in the next release of CNVkit.

**Comment by etal** [comment]
This is fixed in the development version now. Can you pull the latest from GitHub and try it on your data?
