### ISSUE TITLE
Reference file return values

### ISSUE THREAD

**Issue by davisem** [etal/cnvkit#256]
`cnvlib.core.ensure_path` moves a file if that file already exists.
This means that any `output_reference` names returned from line 152 in `cnvlib.batch.batch_make_reference` will no longer be valid, as each new reference returned will point to `reference.cnn`, and never a `reference.cnn.1` or `reference.cnn.2`. Could you expose some file output params, so API consumers can control this behavior?  Thanks.

**Comment by etal** [comment]
There should only be one reference returned by `batch`, the newly created one, right? If you're using `batch` in a loop then it's best to specify a unique filename for the generated reference in each iteration, or else it will move out from under you in the next iteration.

I see you closed the issue, did you find a solution you're happy with?

**Comment by davisem** [comment]
Hi!
Thanks for the reply. You guessed what I was trying to do. I almost thought this was a bug at first, but now I see the utility in always keeping the most recent output as the un-suffixed name. As it turned out I needed to separate some of the calls in batch anyway for the purpose of parallelization on a hpc cluster. So I just did the IO handling myself. It's really humming along now!

**Comment by davisem** [comment]
Oops this was 8 days ago. Sorry for my late reply! In the gitlab world mostly these days...
