### ISSUE TITLE
cnvkit.py: How to get version?

### ISSUE THREAD

**Issue by HenrikBengtsson** [etal/cnvkit#26]
Is it possible to get the version of CNVkit installed?  I think it would be useful for reproducibility and giving feedback.  I've tried:
```bash
$ cnvkit.py --version
usage: cnvkit.py [-h]
                 {batch,target,antitarget,coverage,reference,fix,segment,cbs,diagram,scatter,loh,heatmap,breaks,gainloss,gender,metrics,import-picard,import-seg,import-theta,export}
                 ...
cnvkit.py: error: too few arguments
```

```bash
$ cnvkit.py -v
usage: cnvkit.py [-h]
                 {batch,target,antitarget,coverage,reference,fix,segment,cbs,diagram,scatter,loh,heatmap,breaks,gainloss,gender,metrics,import-picard,import-seg,import-theta,export}
                 ...
cnvkit.py: error: too few arguments
```

```bash
$ cnvkit.py batch --version
usage: cnvkit.py [-h]
                 {batch,target,antitarget,coverage,reference,fix,segment,cbs,diagram,scatter,loh,heatmap,breaks,gainloss,gender,metrics,import-picard,import-seg,import-theta,export}
                 ...
cnvkit.py: error: unrecognized arguments: --version
```

```
$ cnvkit.py batch -v
usage: cnvkit.py [-h]
             {batch,target,antitarget,coverage,reference,fix,segment,cbs,diagram,scatter,loh,heatmap,breaks,gainloss,gender,metrics,import-picard,import-seg,import-theta,export}
                 ...
cnvkit.py: error: unrecognized arguments: -v
```

**Comment by etal** [comment]
It's not built in, but I agree it should be.

If your CNVkit installation is controlled under pip (maybe conda, too), this will show you the version you have installed:

    pip list | grep CNVkit

**Comment by etal** [comment]
These will work now -- on the command line:

    cnvkit.py version

In Python:

    import cnvlib
    print cnvlib.__version__

**Comment by roryk** [comment]
Hi Eric, thanks for adding this these little tweaks make life a lot easier.

**Comment by HenrikBengtsson** [comment]
Thanks.

Q: Acknowledging that I don't fully know the various channels/repositories that Python package can be distributed, how is CNVkit released?  When you're saying "will work now", does that mean that CNVkit is pushed out through these channels (e.g. Anaconda etc.) straightaway, or do you mean "will work now [if you install from git source]"?

**Comment by etal** [comment]
@HenrikBengtsson - At the moment it will work if you install from git source. The next release (v0.4.1, soon) will be tagged in git and uploaded to PyPI, the central repository for Python packages, and that will be what you get if you do "pip install -U cnvkit". That will be the first release to include this change.

I actually don't know how/when @chapmanb is updating the conda package at https://binstar.org/bcbio/cnvkit, but if it's not automated then he seems to be doing it very quickly after each PyPI upload.

**Comment by HenrikBengtsson** [comment]
On Wed, Apr 29, 2015 at 10:17 AM, Eric Talevich
<notifications@github.com> wrote:
>
> @HenrikBengtsson - At the moment it will work if you install from git source. The next release (v0.4.1, soon) will be tagged in git and uploaded to PyPI, the central repository for Python packages, and that will be what you get if you do "pip install -U cnvkit". That will be the first release to include this change.
>
> I actually don't know how/when @chapmanb is updating the conda package at https://binstar.org/bcbio/cnvkit, but if it's not automated then he seems to be doing it very quickly after each PyPI upload.

Thanks for these clarifications; very helpful.

**Comment by chapmanb** [comment]
Eric -- thanks for adding these. I manually roll out conda packages after releases so will update whenever you get the new release pushed.
