### ISSUE TITLE
batch command problem

### ISSUE THREAD

**Issue by lituan** [etal/cnvkit#260]
I put this in a nextflow, then got an error,  "N1.rmd.bam: command not found"
"""
    cnvkit.py batch N1.rmd.bam -n \
              --targets $baits_bed \
              --annotate $refFlat \
              --fasta $hg19 \
              --access $access_bed \
              --output-reference my-reference.cnn \
"""

**Comment by etal** [comment]
The command line syntax is right. The problem is probably the way you're using nextflow.
