### ISSUE TITLE
Build a different reference for each sex grouping of the samples

### ISSUE THREAD

**Issue by fbrundu** [etal/cnvkit#261]
Hi,
I am running cnvkit on exome data, with tumor and normal samples.
Do I have to build a different reference for male and female cases?
I read [reference](http://cnvkit.readthedocs.io/en/stable/pipeline.html#reference) and [sex](http://cnvkit.readthedocs.io/en/stable/sex.html), and also searched on google but I didn't find the best way to run cnvkit in this case.

Thanks,
Francesco

**Comment by etal** [comment]
You can probably mix the male and female samples together in a single reference. CNVkit will try to detect the chromosomal sex automatically from X and Y coverages -- these will be printed for each sample as it runs, so check these to make sure there were no mistakes.

If your samples have noisy coverages, are from a tiny panel, or for some other reason CNVkit's guesses are wrong, you can build separate male and references using the `reference -x` option. But typically this isn't necessary.

**Comment by fbrundu** [comment]
Cool thank you!
