### ISSUE TITLE
How to check if the sex inference worked when calling cnvkit with more than 1 process

### ISSUE THREAD

**Issue by fbrundu** [etal/cnvkit#263]
Hi,
I called cnvkit with option `-p 18`. Reading from the log I am unable to understand if sex inference was done correctly. I have this log:

```
Relative log2 coverage of X=-0.635, Y=-6.13 (maleness=24.6 x 0.356 = 8.77) --> assuming male
Relative log2 coverage of X=-0.585, Y=-5.91 (maleness=14 x 0.515 = 7.19) --> assuming male
Relative log2 coverage of X=-0.614, Y=-6.49 (maleness=15.7 x 0.164 = 2.57) --> assuming male
Relative log2 coverage of X=0.396, Y=-21.5 (maleness=0.0413 x 0.829 = 0.0342) --> assuming female
Relative log2 coverage of X=-0.775, Y=-6.12 (maleness=9.79 x 1.8 = 17.7) --> assuming male
Relative log2 coverage of X=0.211, Y=-14.6 (maleness=0.0467 x 0.798 = 0.0373) --> assuming female
Relative log2 coverage of X=-0.781, Y=-6.13 (maleness=14.1 x 1.62 = 22.8) --> assuming male
Relative log2 coverage of X=-0.784, Y=-6.09 (maleness=14.6 x 3.89 = 56.8) --> assuming male
Relative log2 coverage of X=0.0998, Y=-14.4 (maleness=0.0106 x 0.756 = 0.008) --> assuming female
Relative log2 coverage of X=-0.871, Y=0.527 (maleness=1.84 x 12 = 22.1) --> assuming male
Relative log2 coverage of X=-1.2, Y=0.982 (maleness=2.77 x 8.14 = 22.5) --> assuming male
Relative log2 coverage of X=-1.16, Y=0.258 (maleness=2.92 x 14.6 = 42.5) --> assuming male
Relative log2 coverage of X=0.194, Y=-5.99 (maleness=0.00451 x 0.367 = 0.00166) --> assuming female
Relative log2 coverage of X=-0.973, Y=-0.475 (maleness=1.24e+03 x 3.28 = 4.07e+03) --> assuming male
Relative log2 coverage of X=-0.0065, Y=-4.3 (maleness=0.000396 x 0.19 = 7.53e-05) --> assuming female
Relative log2 coverage of X=-0.906, Y=-0.49 (maleness=12.7 x 2.95 = 37.4) --> assuming male
Relative log2 coverage of X=-0.923, Y=-0.475 (maleness=14.6 x 3.28 = 47.9) --> assuming male
Relative log2 coverage of X=-0.128, Y=-4.03 (maleness=0.0527 x 0.219 = 0.0116) --> assuming female
```

How can I understand which sample is inferred male and which female?

Thanks,
Francesco

**Comment by etal** [comment]
Hmm, I should change the log message to also show the sample ID, and/or reorganize logging for multiple processes.

You can use the `sex` command to see which chromosomal sex CNVkit would have inferred on each of your .cnr files (or .cnn, or .cns):

    cnvkit.py sex *.cnr [-y]

It prints a table of its inferences and some supporting info. This is the same mechanism/statistic used throughout the pipeline, so a .cnr will have the same inference by `sex` as in any other step.

However, the .cnn, .cnr, and .cns files for a single sample can theoretically have different inferred sex if the statistic is borderline. Usually it's the .cnr file being tested, but you can check for conflicts by running all files at once:

    cnvkit.py sex *.cnn *.cnr *.cns [-y]

(The -y is optional, in case you used it in `reference` or `batch`.)
