### ISSUE TITLE
Annotate with refFlat after reference building

### ISSUE THREAD

**Issue by fbrundu** [etal/cnvkit#264]
Hi,
I've built a reference and I forgot to annotate using gene annotations.
Can the annotation been done afterwards, for example reusing the reference and adding the `--annotate` option to the batch command?

Thanks,
Francesco

**Comment by fbrundu** [comment]
Reading from [the docs](http://cnvkit.readthedocs.io/en/stable/pipeline.html) it seems that the annotation is done at the beginning of batch. So I should need to rebuild the reference, right?

```
cnvkit.py target baits.bed --split [--annotate refFlat.txt --short-names] -o my_targets.bed
cnvkit.py access baits.bed --fasta hg19.fa -o access.hg19.bed
cnvkit.py antitarget my_targets.bed --access access.hg19.bed -o my_antitargets.bed

# For each sample...
cnvkit.py coverage Sample.bam my_targets.bed -o Sample.targetcoverage.cnn
cnvkit.py coverage Sample.bam my_antitargets.bed -o Sample.antitargetcoverage.cnn

# With all normal samples...
cnvkit.py reference *Normal.{,anti}targetcoverage.cnn --fasta hg19.fa [--male-reference] -o my_reference.cnn

# For each tumor sample...
cnvkit.py fix Sample.targetcoverage.cnn Sample.antitargetcoverage.cnn my_reference.cnn -o Sample.cnr
cnvkit.py segment Sample.cnr -o Sample.cns

# Optionally, with --scatter and --diagram
cnvkit.py scatter Sample.cnr -s Sample.cns -o Sample-scatter.pdf
cnvkit.py diagram Sample.cnr -s Sample.cns [--male-reference] -o Sample-diagram.pdf
```

**Comment by etal** [comment]
No, there's a script to save you. It's called `cnn_annotate.py` or `cn_annotate.py` in recent releases and `cnv_annotate.py` in the current development codebase:

- https://cnvkit.readthedocs.io/en/stable/scripts.html
- https://github.com/etal/cnvkit/blob/master/scripts/cnv_annotate.py
