### ISSUE TITLE
Analysis of scatter

### ISSUE THREAD

**Issue by fbrundu** [etal/cnvkit#266]
Hi,
I am analyzing some of the results provided by cnvkit. I searched in the original publication and online but I was unable to find a complete description of the scatter plot (I attached an example). Where can I find a complete description of it?

In particular, I would like to know the meaning of the horizontal segments (I assume they were the bins/segments computed by cnvkit) and the circles (how is circle's size computed?). I assumed that the vertical band identifies the location of the explored gene.

Thanks,
Francesco

![cnvkit](https://user-images.githubusercontent.com/697622/31790475-94a5b53e-b4e3-11e7-949c-66222590b960.png)

**Comment by etal** [comment]
Here's the online documentation: https://cnvkit.readthedocs.io/en/stable/plots.html#plots-and-graphics

The option descriptions you see with `cnvkit.py scatter -h` are comprehensive. Generally, just try some options that you think should work, and see what happens.

The orange lines are segment means (from .cns), circles are bin-level log2 ratios (from .cnr), and circle diameter indicates weight (also .cnr). The golden stripe indicates the selected gene, and there can be more than one.
