### ISSUE TITLE
chrY masked pseudoautosomal regions PAR1/2

### ISSUE THREAD

**Issue by gabeng** [etal/cnvkit#267]
How should I create a reference from samples where PAR1/2 were masked with N on chrY? This is the case e. g. for GRCh37 (1kG version) or hg38. All reads in male and female are then aligned to PAR1/2 on chrX. 
With a female reference (reference sex not specified) the result is that PAR1/2 have an average log2 value of -1 in both males and females. In my opinion this should be 0. Am I doing something wrong?

**Comment by etal** [comment]
In `batch` without a user-provided "access" BED file, CNVkit will scan the FASTA reference genome you provide, notice the N-masked regions on chrY, and exclude them from the analysis (at least in WGS mode, and the antitargets in hybrid capture mode). So the log2 ratios on chrX (and everywhere else) should correspond to BAM coverage, and if PAR1/2 on chrY were masked out in the FASTA you fed to CNVkit, those regions should just be missing from the .cnn and .cnr files. (Unless there's a bug.)

In your BAM files, is the coverage depth on the chrX PAR1/2 about the same as in neutral regions on autosomes?

**Comment by gabeng** [comment]
I am not using the batch mode, but doing it step by step. I exclude PAR1/2 on chrY in `cnvkit.py access` using an appropriate bed file. This works well and there are no target/antitarget regions in PAR1/2 on chrY.
Since all reads in PAR1/2 are aligned on chrX, coverage is higher in these regions compared to before, without masking. All samples in the reference are processed the same was (same genome build). 
I have two different examples: a small panel (1Mb) and a large panel (14Mb).

## Large panel
* in males, coverage in PAR1/2 on chrX is now about twice as high as in other regions of chrX compared to non-masking. Coverage is comparable to autosomes. PAR1/2 on chrX are indicated as `log2=-1` on average as is the rest of chrX. 
* in females, there is no change (compared to non-masking) and coverage is comparable to autosomes. PAR1/2 on chrX are now displayed as `log2=-1` as well. The rest of chrX is `log2=0`. This is what I do not understand at all. **It looks like PAR1/2 are deleted in females.**

## Small panel
The small panel looks different. 
* in males PAR1/2 on chrX appear duplicated, as expected.
* in females, chrX is `log2=0` everywhere as expected.

So why is there an issue with the large panel (a clinical exome)?
Sex determination works fine compared to other genome builds.

**Comment by etal** [comment]
That's odd. I wonder if the automatic sex inference was wrong on the female samples. That still doesn't explain what you see on the large panel, though.

Does this happen on all female samples? Are you using a pooled reference? Do the 'depth' and 'log2' columns in the reference show the same inconsistency?

Could you share the targetcoverage.cnn and antitargetcoverage.cnn files for a female sample where this happened? (E-mail/dropbox is fine.)

**Comment by gabeng** [comment]
I'll send you a PM with a link to the data of two individuals. I am using a pooled reference. I also provided you with the `reference.cnn`. Let me know if you need anything else to debug this.
This data is from a pool of 72 individuals, 31 of which are female.

**Comment by etal** [comment]
I haven't forgotten about this issue, I'm just not sure what to do about it. The log2 values in the PAR1/2 regions of the female sample's .cnr file are not -1, but more like -.6, which is not perfect support for the idea that CNVkit erroneously subtracted 1 there. Could there be a batch effect in your reference pool? For example, with a reference built from only the male control samples, or only female, would the same effect appear? Cryptic batch effects for coverage profiles do occur even in process-matched pools, and they can be curiously focal to specific genomic regions.

**Comment by gabeng** [comment]
I do not quite understand what "batch effect" means. An effect arising from a specific configuration of female/male samples? I have seen the issue in many different mixed reference pools. I will try to run an only femal/only male analysis. Thanks for your feedback.

**Comment by etal** [comment]
A couple of CNV callers' papers describe the cryptic batch effect and how to handle it:
- [ExomeDepth](https://academic.oup.com/bioinformatics/article/28/21/2747/236565)
- [CANOES](https://academic.oup.com/nar/article/42/12/e97/1097604)

In [a PCA plot](https://academic.oup.com/view-large/figure/19819588/gku345fig1.tiff/CANOES%3A%20detecting%20rare%20copy%20number%20variants%20from%20whole%20exome%20sequencing%20data), the read depth profiles of the process-matched input reference samples form distinct clusters. Why do the read depth profiles of some subsets of these samples correlate well with each other? No way to know, apparently; they just do. But given that PAR1/2 are sex-related genomic regions, grouping by sex might resolve it at least partially.
