### ISSUE TITLE
CNVkit gender log2 values

### ISSUE THREAD

**Issue by ferenju1** [etal/cnvkit#270]
The CNVkit notes say that with a male reference, females will show log2 around +1 for X, and males around 0. Which makes sense. I'm using a male reference, and I've attached plots of a typical male and female normalised against this reference. I think it isn't working as documented.

The Y interpretation is as expected - males show log2 of around 0. Females show very negative log2.
The X interpretation is not as expected though - the log2 values are relative to ploidy 2, not ploidy 1. Females show 0, males -1.

I've ran hundreds of samples through this, and created multiple references, and they all show the same issue. It's totally interpretable, but isn't consistent with the CNVkit documentation. As far as I can tell, the only difference in the output with a male or female reference relates to the Y chromosome, X is treated as an autosome.

Any comment?

(The top image is female, the bottom male).
![female](https://user-images.githubusercontent.com/22363969/31968046-91c948b8-b95b-11e7-9970-5063c3057cc5.png)
![male](https://user-images.githubusercontent.com/22363969/31968047-91f086c6-b95b-11e7-92e3-a6190718b3fb.png)

**Comment by etal** [comment]
Thanks for reporting. Which version of CNVkit are you using?

**Comment by ferenju1** [comment]
Not at all. Thanks for producing such a great piece of software. I did try to look into the code to source the issue myself, but I’m not familiar with it and thought it would make more immediate sense to you.

We’re running version 0.8.3.

**Comment by etal** [comment]
Could you try the most recent version, 0.9.0, to see if it's still present there?

**Comment by ferenju1** [comment]
Apologies Eric, the problem wasn't with cnvkit; --male-reference wasn't
being set when creating the reference in our wrapper code. It works as you
have documented. Sorry for the red herring...!

**Comment by etal** [comment]
Thanks for letting me know!
