### ISSUE TITLE
Unlisted dependency on PSCBS?

### ISSUE THREAD

**Issue by datakid** [etal/cnvkit#271]
On of my users came across this error:
```
b'Error in library("PSCBS") : there is no package called \xe2\x80\x98PSCBS\xe2\x80\x99\nExecution halted\n'
```
Is there an unlisted dependency on the PSCBS package in R?

**Comment by etal** [comment]
In the development version, no. In previous versions PSCBS was a listed dependency. If one of your users had loaded PSCBS in their R startup environment earlier, and since then the paths have gotten strange, that could lead to an error like this, I imagine.
