### ISSUE TITLE
Visualisation without a GUI

### ISSUE THREAD

**Issue by datakid** [etal/cnvkit#272]
We have installed CNVkit on our cluster for batch processing of large numbers. 

How do we go about visualising that data without X11? Is there an output file that we can copy to local machine and use Jupyter?

**Comment by etal** [comment]
If you install CNVkit on your local machine you can use it within Jupyter for plotting (via cnvlib).

With batch processing on a cluster, you should still be able to generate image files with the `scatter`, `diagram` and `heatmap` commands by specifying an output filename with the `-o` option. The default format is PDF, but with `scatter` and `heatmap` you can use any file format supported by matplotlib by using the appropriate file extension, e.g. "-o my_custom_plot.png" to save a PNG. This should work without X11.
