### ISSUE TITLE
Different segments within the same gene

### ISSUE THREAD

**Issue by wclee47** [etal/cnvkit#276]
Hi, this program seems to work well, but I have some difficulties of interpreting the result.

We are analyzing gene target panel data consisting of 2Mb with 500 genes.
After running CNVkit, we would like to assign segments' log2 values to the genes within them.
However, very often different exons from the same gene belong to different segments, which makes us hard to assign the log2 value to the genes.

We acknowledge that sample quality is not that good, but also think that segmentation is so sensitive with default setting. I tried options like --drop-outliers, --drop-low-coverage, -t 1e-06, but they did not help much.

Any experience or suggestions?

Thanks,

Won-Chul

**Comment by etal** [comment]
You can use the `gainloss` command with the .cnr file, but leave out the .cns file, to get the weighted average log2 value for each gene.

The `--drop-low-coverage` option is good to use with tumor samples, but will lose homozygous deletions in germline samples. See the commands `segmetrics --ci` and `call --filter ci` to help remove spurious calls.

Also consider using the `autobin` command to see if your on- and off-target bin sizes were appropriate for this analysis; your results might look better with a larger bin size if these samples are very degraded.

**Comment by wclee47** [comment]
Hi Eric,

Wow, they are perfect answers!
Let me try them and let you know.
Thanks very much!

Won-Chul

**Comment by wclee47** [comment]
Hi Eric,

(1) I tried "autobin" and found that it takes similar running times when I used one bam file or multiple bam files (n=200). I guess that it picks up one bam file with median size according to your script. Is that right?

(2) You mentioned in one of the previous posts that this can run for "normal/control" bam files. Am I correct?

(3) A fundamental nature of the dataset we have is that the target depth of samples is dramatically varying (e.g. 100x to 1000x) both for tumor samples and normal samples. I guess that recommended value by autobin can be changed in a wide range if we run autobin with individual bam files. Do you have any workaround in your mind for this scenario?

Your help will be much appreciated.

Thanks,

Won-Chul

**Comment by etal** [comment]
1. Yes
2. Yes, that's the idea -- use autobin to determine reasonable bin sizes for a "typical" coverage profile.
3. The bin sizes don't need to be exact for CNVkit to work well, `autobin` is just intended to reduce reliance on hard-coded parameters and ensure bin sizes are at least within an order of magnitude of optimal. If your test samples vary in coverage by an order of magnitude, you can be "safe" and feed autobin a normal sample with ~200x coverage. Then neither the 100x nor 1000x samples will be too far off from optimal. However, if your samples are part of two clusters/batches/cohorts, with ~100x and ~1000x coverage respectively, then it might be better to create two separate pooled references and process the two batches separately.
