### ISSUE TITLE
Low mappability regions for GRCh38

### ISSUE THREAD

**Issue by bishwaG** [etal/cnvkit#287]
How can I get or produce low mappability regions (excludes.bed) from GRCh38?

**Comment by etal** [comment]
I'd try the UCSC Genome Browser for tracks that define low-mappability or low-complexity regions in any given reference genome.

**Comment by bishwaG** [comment]
I tried to download low-complexity region from UCSC Table browser, but I got little lost. Do I need to select `group: Repeats `and `track: RepeatMasker` ?

**Comment by etal** [comment]
Any BED file of problematic genomic regions will do. Try the SV Blacklist from 10x Genomics:
http://cf.10xgenomics.com/supp/genome/GRCh38/sv_blacklist.bed
