### ISSUE TITLE
DNAnexus app usage

### ISSUE THREAD

**Issue by MojganBabanejad** [etal/cnvkit#288]
Hi,

I would like to give CNVkit a try by whole exome sequencing data but have not been able to run an analysis successfully. In the DNAnexus wrapper environment, I have the following inputs:

Tumor sample mapped reads (BAM) (tumor_bams): 60845.bam
Normal sample mapped reads (BAM) (normal_bams): IPe1003_sorted_Dup_Filtered_realign_recal.bam
Baited regions (baits): S04380110_AllTracks.bed
Reference genome (FASTA) (fasta): ucsc.hg19.fasta
Male reference? true
Drop low-coverage bins? (drop_low_coverage): true

  | Sequencing method: wgs

I am actually getting the same error. The error I am receiving is: 
**CalledProcessError: Command 'dx-docker run -v /home/dnanexus:/workdir -w /workdir etal/cnvkit:0.9.0 cnvkit.py batch -m hybrid 60845.bam --scatter --diagram --output-reference cnv-reference.cnn -n IPe1003_sorted_Dup_Filtered_realign_recal.bam -t S04380110_AllTracks.bed --short-names -f ucsc.hg19.fasta -p 8 ' returned non-zero exit status 1**
Would you please let me know how I could fix it.
Also for output folder, is there any specific pathway? or only we should name it for example:60845

**Comment by etal** [comment]
For "sequencing method", instead of "wgs" try "hybrid" -- your whole exome sequencing method is probably hybrid capture.

If you look further up in your DNAnexus job log, you'll see that the CNVkit app rejects the input because "baits" shouldn't be given as input if the sequencing method is "wgs" (i.e. whole-genome sequencing, no target selection/capture).

**Comment by MojganBabanejad** [comment]
Thank you very much for your reply.
I changed sequencing method to hybrid but unfortunately got the below errors:
**CalledProcessError: Command 'dx-docker run -v /home/dnanexus:/workdir -w /workdir etal/cnvkit:0.9.1 cnvkit.py batch -m hybrid 60845.bam --scatter --diagram --output-reference cnv-reference.cnn -n IPe1003_sorted_Dup_Filtered_realign_recal.bam -t S04380110_AllTracks.bed --short-names -f ucsc.hg19.fasta -p 8 -y' returned non-zero exit status 1** 
Would you please let me know how  could fix it.
Thanks in advanced.

**Comment by etal** [comment]
Could you check the job log and see the full traceback above the error message? The `batch` command itself should have emitted another traceback before the one from the CalledProcessError.

**Comment by MojganBabanejad** [comment]
Thank you very much dear Eric.
Since Iam not familiar with programing languages, I can not find the problem and fix it.
Below is log info:
**Logging initialized (priority)
CPU: 10% (8 cores) * Memory: 901/30158MB * Storage: 144GB free * Net: 0↓/0↑MBps
dxpy/0.240.1 (Linux-4.4.0-101-generic-x86_64-with-Ubuntu-14.04-trusty)
Downloading bundled file resources.tar.gz
>>> Unpacking resources.tar.gz to /
Downloading bundled file etal%cnvkit#0.9.1.tar.gz
>>> Unpacking etal%cnvkit#0.9.1.tar.gz to /
tar: Removing leading `/' from member names
Installing apt packages poppler-utils
dxpy/0.240.1 (Linux-4.4.0-101-generic-x86_64-with-Ubuntu-14.04-trusty)
/usr/sbin/sshd already running.
Invoking main with {u'is_male_normal': True, u'do_parallel': True, u'drop_low_coverage': False, u'tumor_bams': [{u'$dnanexus_link': u'file-F8JB0xQ0bKK09Qj14fF80qV8'}], u'normal_bams': [{u'$dnanexus_link': u'file-F8KX64j0bKK1J4kjBzvgk4Py'}], u'baits': {u'$dnanexus_link': u'file-F8V66f80bKK8qqj7B1vBfXBj'}, u'fasta': {u'$dnanexus_link': u'file-F8V4PJj0bKKPkxJFB1V63F1x'}, u'method': u'hybrid'}
Downloading file inputs to the local file system
$ mkdir -p /workdir
Running the main CNVkit pipeline
$ dx-docker run -v /home/dnanexus:/workdir -w /workdir etal/cnvkit:0.9.1 cnvkit.py batch -m hybrid 60845.bam --scatter --diagram --output-reference cnv-reference.cnn -n IPe1003_sorted_Dup_Filtered_realign_recal.bam -t S04380110_AllTracks.bed --short-names -f ucsc.hg19.fasta -p 8 -y
Image Repo	etal/cnvkit
Image Tag	0.9.1
Image Size	934M
Image ID	0030e89f02e043bb31b9a193df8289e8fba2076f7f06c0778482c5e66c81971f
Parent ID	944458ec4c22cb897d6b6619cc72c6b9b4595256b2c91191a3f3dc5a8d085868
Last Updated	2017-11-15T23:20:48Z (19d 6h ago)
Default CMD	["bash"]
proot warning: can't sanitize binding "/var/run/dbus/system_bus_socket": No such file or directory
CNVkit 0.9.1
Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 108, in _cmd_batch
    args.count_reads, args.method)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/batch.py", line 89, in batch_make_reference
    bait_arr = tabio.read_auto(target_bed)
  File "/usr/local/lib/python2.7/dist-packages/skgenome/tabio/__init__.py", line 108, in read_auto
    fmt = sniff_region_format(infile)
  File "/usr/local/lib/python2.7/dist-packages/skgenome/tabio/__init__.py", line 253, in sniff_region_format
    % (fname, ', '.join(format_patterns.keys()), line))
ValueError: File 'S04380110_AllTracks.bed' does not appear to be a recognized format! (Any of: text, tab, interval, refflat, gff, bed)
First non-blank line:
browser position chr1:65510-65625
Not file: /home/dnanexus/etal/cnvkit:0.9.1
Not file: /home/dnanexus/cnvkit.py
File: /home/dnanexus/60845.bam
Not file: /home/dnanexus/cnv-reference.cnn
File: /home/dnanexus/IPe1003_sorted_Dup_Filtered_realign_recal.bam
File: /home/dnanexus/S04380110_AllTracks.bed
File: /home/dnanexus/ucsc.hg19.fasta
Traceback (most recent call last):
File "/home/dnanexus/job-F8Y34yQ0bKK4J8XpB2G659k8", line 21, in <module>
    execfile(_code_filename)
  File "/home/dnanexus/job-F8Y34yQ0bKK4J8XpB2G659k8.code.py", line 309, in <module>
    dxpy.run()
  File "/usr/share/dnanexus/lib/python2.7/site-packages/dxpy/utils/exec_utils.py", line 150, in run
    result = ENTRY_POINT_TABLE[job['function']](**job['input'])
  File "/home/dnanexus/job-F8Y34yQ0bKK4J8XpB2G659k8.code.py", line 56, in main
    target_avg_size, purities, ploidies, do_parallel)
  File "/home/dnanexus/job-F8Y34yQ0bKK4J8XpB2G659k8.code.py", line 141, in run_cnvkit
    cnvkit_docker(*command)
  File "/home/dnanexus/job-F8Y34yQ0bKK4J8XpB2G659k8.code.py", line 304, in cnvkit_docker
    sh(*(docker_prefix + list(args)))
  File "/home/dnanexus/job-F8Y34yQ0bKK4J8XpB2G659k8.code.py", line 281, in sh
    raise exc
subprocess.CalledProcessError: Command 'dx-docker run -v /home/dnanexus:/workdir -w /workdir etal/cnvkit:0.9.1 cnvkit.py batch -m hybrid 60845.bam --scatter --diagram --output-reference cnv-reference.cnn -n IPe1003_sorted_Dup_Filtered_realign_recal.bam -t S04380110_AllTracks.bed --short-names -f ucsc.hg19.fasta -p 8 -y' returned non-zero exit status 1**

Best regards, Mojgan

**Comment by etal** [comment]
Here's the relevant part of the log file:

```
ValueError: File 'S04380110_AllTracks.bed' does not appear to be a recognized format! (Any of: text, tab, interval, refflat, gff, bed)
First non-blank line:
browser position chr1:65510-65625
```

It looks like your .bed file is not correctly formatted. It should be 4 columns, separated by tabs, see [examples here](https://cnvkit.readthedocs.io/en/stable/quickstart.html#download-the-reference-genome) and [precise descriptions here](https://cnvkit.readthedocs.io/en/stable/fileformats.html#bed-and-gatk-picard-interval-list).
