### ISSUE TITLE
CNVkit seems can't recognize simplest bed format

### ISSUE THREAD

**Issue by MajoroMask** [etal/cnvkit#293]
I'm using version 0.9.2dev0 (should be the latest one). Running autobin **with** "-g" option and .bed file generated by access.
`cnvkit.py access ./genome.fna -o ./cnvkit_access.bed`
`cnvkit.py autobin *.bam --method wgs -b 50000 -g ./cnvkit_access.bed --annotate ./anno.gff > autobin.txt`
And I recieved error massage:

> Traceback (most recent call last):
>   File "/home/sn/software/conda/bin/cnvkit.py", line 13, in <module>
>     args.func(args)
>   File "/home/sn/software/conda/lib/python3.6/site-packages/cnvlib/commands.py", line 341, in _cmd_autobin
>     access_arr = read_regions(args.access)
>   File "/home/sn/software/conda/lib/python3.6/site-packages/cnvlib/commands.py", line 333, in read_regions
>     regions = tabio.read_auto(bed_fname)
>   File "/home/sn/software/conda/lib/python3.6/site-packages/skgenome/tabio/__init__.py", line 108, in read_auto
>     fmt = sniff_region_format(infile)
>   File "/home/sn/software/conda/lib/python3.6/site-packages/skgenome/tabio/__init__.py", line 253, in sniff_region_format
>     % (fname, ', '.join(format_patterns.keys()), line))
> ValueError: File './cnvkit_access.bed' does not appear to be a recognized format! (Any of: text, tab, interval, refflat, gff, bed)
> First non-blank line:
> NC_002663.1     0       2257487

I also tried split the one line bed into two lines like: 
> NC_002663.1     0       2200000
> NC_002663.1     2200001       2257487

Then I received the same error.
And I also recieved the same kind of error when using `cnvkit.py antitarget`, since it calls the `-g` flag, too.

I know that standard .bed format need only three columns like `cnvkit.py access`  generated. So I'm pretty sure it is a little bug within CNVkit. Hope this post can be helpful. Forgive my poor English writing.

**Comment by etal** [comment]
Are the columns separated by spaces instead of tabs? That would cause an error like this.

**Comment by MajoroMask** [comment]
@etal No, it's tab separated.

**Comment by MajoroMask** [comment]
>ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/006/825/GCF_000006825.1_ASM682v1/GCF_000006825.1_ASM682v1_genomic.fna.gz

This is the fasta file I've been using in `cnvkit.py access`, can this be the source of the problem?

**Comment by etal** [comment]
Thanks for catching this. The problem was the decimal in the chromosome name, which tripped up the regex used to detect the file format. I just pushed a fix that worked with the example you posted. Can you pull the latest with git and see if this fixes both of the issues you saw?

The `batch` command doesn't include the `call` command in its workflow, so the `--ploidy` option isn't needed there. You can use `cnvkit.py call --ploidy 1` afterward to get integer copy number calls that make sense for a haploid genome, but even without it the .cns and .cnr files from `batch` should be valid for your genome/samples.

**Comment by MajoroMask** [comment]
That worked! You can close this one now. And I'll try `batch` plus `call` as you instructed, much obliged for this.
