### ISSUE TITLE
Convenient way of specifying multiple bam files in different folders?

### ISSUE THREAD

**Issue by EmilChris** [etal/cnvkit#297]
Hi! 

Very satisfied with CNVkit so far!

I am however wondering if there is a clever way of specifying multiple bam files. Currently, I have a large number of bam files in different folders and to specify them all I have to do the following:
/pathtobams/{sample1path/sample1,sample2path/sample2,sample3path/sample3}*.bam
The sample-specific paths are unfortunately rather specific and long and when dealing with +100 tumor and normal bam files, the process is fairly tedious. 
I have tried specifying lists of bam files, but cnvkit does not seem to understand this format. 

Is there a more clever way than manually setting up all the locations of the bam files?

Any advice is highly appreciated!

Kind regards
Emil Christensen

**Comment by etal** [comment]
You can list the BAM paths in a file, one per line, and then read out the file onto the command line with `cat` as an argument to the `batch` command.

In Bash (/bin/bash):

    cnvkit.py batch $(cat tumor_bam_list.txt) -n $(cat normal_bam_list.txt) --fasta hg38.fasta ...

Or in classic Bourne shell (/bin/sh):

    cnvkit.py batch `cat tumor_bam_list.txt` -n `cat normal_bam_list.txt` --fasta hg38.fasta ...

You can also use the Unix command `find` to list `*.bam` files in subdirectories.

**Comment by EmilChris** [comment]
Thanks for your quick input! It works great using cat *.list.
However, a colleague pointed out I needed the bam files separated by spaces instead of  \n.
