### ISSUE TITLE
Problem with guess_baits.py

### ISSUE THREAD

**Issue by AlessandroGorohovski** [etal/cnvkit#301]
Hi CNVkit team,
I tried to make my_baits.bed file with guess_baits.py as described in the manual cnvkit.pdf (CNVkit Documentation, Release 0.9.2.dev0):

guess_baits.py my.realigned.bam -t UCSC_exons_modif_canonical.bed -o my_baits.bed

but unfortunately I get an error message:
---------------------------------------------------------
Detected file format: bed
Evaluating targets in my.realigned.bam
Processing reads in my.realigned.bam
Time: 810.061 seconds (27 reads/sec, 239 bins/sec)
Summary: #bins=193613, #reads=21813, mean=0.1127, min=0.0, max=3.57471264368
Percent reads in regions: 0.034 (of 63616785 mapped)
Traceback (most recent call last):
  File "/home/morgensternlab/alessandro/bin/guess_baits.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.9.2.dev0', 'guess_baits.py')
  File "/data/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1531, in run_script
    exec(script_code, namespace, namespace)
  File "/home/morgensternlab/alessandro/lib/python2.7/site-packages/CNVkit-0.9.2.dev0-py2.7.egg/EGG-INFO/scripts/guess_baits.py", line 229, in <module>

  File "/home/morgensternlab/alessandro/lib/python2.7/site-packages/CNVkit-0.9.2.dev0-py2.7.egg/EGG-INFO/scripts/guess_baits.py", line 49, in filter_targets

ValueError: operands could not be broadcast together with shapes (201704,) (193613,) (201704,)
---------------------------------------------------------

Of course, previously I created the UCSC_exons_modif_canonical.bed file as:
1---
Download a bed file for the canonical transcripts (UCSC_canonical.bed)                              
using UCSC Table Browser:                                                                                                                              
https://genome.ucsc.edu/cgi-bin/hgTables?command=start 

$ head -5 UCSC_canonical.bed                                                                        
#hg19.knownCanonical.chrom  hg19.knownCanonical.chromStart  hg19.knownCanonical.chromEnd    hg19.knownCanonical.transcript  hg19.kgXref.geneSymbol
chr1    11873   14409   uc010nxq.1  DDX11L1                                                         
chr1    14361   19759   uc009viu.3  WASH7P                                                          
chr1    14406   29370   uc009viw.2  WASH7P                                                          
chr1    34610   36081   uc001aak.3  FAM138F

2---
Download a bed file for all UCSC exons (UCSC_exons.bed) using UCSC Table Browser again.
$ head -5 UCSC_exons.bed                                                                            
chr1    12189   12227   uc010nxq.1_cds_0_0_chr1_12190_f 0   +                                       
chr1    12594   12721   uc010nxq.1_cds_1_0_chr1_12595_f 0   +                                       
chr1    13402   13639   uc010nxq.1_cds_2_0_chr1_13403_f 0   +                                       
chr1    69090   70008   uc001aal.1_cds_0_0_chr1_69091_f 0   +                                       
chr1    138529  139696  uc021oeg.2_cds_0_0_chr1_138530_r    0   -

3---
Next step was modify the file to separate the transcript name of the rest of information:                         
                                                                                                   
    awk '{split ($4,a,"_"); {print $1"\t"$2"\t"$3"\t"a[1]"\t"a[3]"\t"$6}}' UCSC_exons.bed > UCSC_exons_modif.bed

The file UCSC_exons_modif.bed:                                                                      
$ head -5 UCSC_exons_modif.bed                                                                      
chr1    12189   12227   uc010nxq.1  0   +                                                           
chr1    12594   12721   uc010nxq.1  1   +                                                           
chr1    13402   13639   uc010nxq.1  2   +                                                           
chr1    69090   70008   uc001aal.1  0   +                                                           
chr1    138529  139696  uc021oeg.2  0   -

4---
Final step was join the sorted files based on the transcript identificator:

join -1 4 -2 4 <(sort -k4 UCSC_exons_modif.bed ) <(sort -k4 UCSC_canonical.bed) | awk '{print $2"\t"$3"\t"$4"\t"$10"\t"$5"\t"$6}' | bedtools sort -i "-" > UCSC_exons_modif_canonical.bed
                                                                                                    
The final file contains exons of the canonical transcripts:                                         
$ head -5 UCSC_exons_modif_canonical.bed                                                            
chr1    12189   12227   DDX11L1 0   +                                                               
chr1    12594   12721   DDX11L1 1   +                                                               
chr1    13402   13639   DDX11L1 2   +                                                               
chr1    69090   70008   OR4F5   0   +                                                               
chr1    138529  139696  LOC729737   0   -

Thank you in advance for any suggestions!

**Comment by etal** [comment]
Thanks for reporting! I'll look into it. This error may have been a warning in earlier versions of numpy; the most recent numpy release is more strict with array broadcasting.

**Comment by etal** [comment]
Does your BED file have multiple tracks, or lines with identical coordinates (considering only the first 3 columns)? And can you count the number of lines in the BED file with `wc -l`? It looks like some lines of the BED file are being dropped by either CNVkit (the skgenome.tabio BED parser) or samtools.

**Comment by AlessandroGorohovski** [comment]
Hi Eric,
I'm very grateful for your time.

Yes, I got it. Sounds good to me.
$ cut -f1-3 UCSC_exons_modif_canonical.bed | uniq -d | wc -l
123

Then 5th step:
$ cut -f1-3 UCSC_exons_modif_canonical.bed | sort -t\t -k 1,1V -k 2,2n -k 3,3n | uniq > UCSC_exons_modif_canonical.uniq.bed

and 6th step:
$ guess_baits.py my.realigned.bam -t UCSC_exons_modif_canonical.uniq.bed -o my_baits.bed
all the same, it ends in failure
-----------------------------------------------
Detected file format: bed
Evaluating targets in my.realigned.bam
Processing reads in my.realigned.bam
Time: 827.580 seconds (995 reads/sec, 234 bins/sec)
Summary: #bins=193502, #reads=823766, mean=4.2571, min=0.0, max=1061.71264368
Percent reads in regions: 1.295 (of 63616785 mapped)
Traceback (most recent call last):
  File "/home/morgensternlab/alessandro/bin/guess_baits.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.9.2.dev0', 'guess_baits.py')
  File "/data/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1531, in run_script
    exec(script_code, namespace, namespace)
  File "/home/morgensternlab/alessandro/lib/python2.7/site-packages/CNVkit-0.9.2.dev0-py2.7.egg/EGG-INFO/scripts/guess_baits.py", line 229, in <module>

  File "/home/morgensternlab/alessandro/lib/python2.7/site-packages/CNVkit-0.9.2.dev0-py2.7.egg/EGG-INFO/scripts/guess_baits.py", line 49, in filter_targets

**Comment by AlessandroGorohovski** [comment]
Please, perhaps you have any correct **baits.bed** file or requirements for its format

**Comment by etal** [comment]
Sorry for the trouble. I'm updating the `guess_baits.py` script now. In the meantime, you can get roughly the same result by running the `coverage` and `reference` commands with your all-exon BED file, then running the script `reference2targets.py` on the resulting pooled reference. No need to use your complete pool of normal samples, just a few should be enough.

**Comment by AlessandroGorohovski** [comment]
Hi Eric,
Sorry for not replying sooner.
Yes, I'm very grateful for your time.

I have updated CNVkit to 30 January,2018 from Git:
$ git clone https://github.com/etal/cnvkit
$ cd cnvkit
$ python2.7 setup.py install --prefix=$HOME

and updated NumPy the same way too.
$ git clone https://github.com/numpy/numpy.git                                                    
$ cd numpy                                                                                        
$ python2.7 setup.py install --prefix=$HOME

$ python2.7 -c 'import numpy; numpy.test()'
Ran 4919 tests in 64.216s                                                                           
OK (KNOWNFAIL=12, SKIP=13)

$ python2.7 -c 'import numpy; print(numpy.__version__)'                                           
1.15.0.dev0+c3fd791

But unfortunately, guess_baits.py script still does not work and ends with the **same error message**.
Apparently, there is need some other magic
:(
Then I tried to do what you suggested.
7)
$ cnvkit.py coverage my.realigned.bam UCSC_exons_modif_canonical.final.bed -o my.targetcoverage.cnn
$ head -5 my.targetcoverage.cnn
chromosome      start   end     gene    depth   log2
chr1    12189   12227   -       5       2.32193
chr1    12594   12721   -       7.48819 2.90462
chr1    13402   13639   -       4.09705 2.03458
chr1    69090   70008   -       0.602397        -0.731215

Chek:
$ cut -f1-3 AC3_gDNA.targetcoverage.cnn | diff UCSC_exons_modif_canonical.final.bed - | wc -l
8089
Yes, at this step, the number of bins has decreased significantly.

8)
    $ cnvkit.py reference my.targetcoverage.cnn -f $HOME/genomes/Human/hg19.fa -o my.reference.cnn
    $ head -5 my.reference.cnn
chromosome      start   end     gene    log2    depth   gc      spread
chr1    12189   12227   -       0.706219        5       0.473684        1.09799
chr1    12594   12721   -       0.880234        7.48819 0.606299        1.35598
chr1    13402   13639   -       0.434151        4.09705 0.582278        0.69462
chr1    69090   70008   -       -0.862007       0.602397        0.428105        1.22706

9)
    $ reference2targets.py my.reference.cnn
Wrote my.reference.target.bed with 193502 regions
Wrote my.reference.antitarget.bed with 0 regions

  $ head -5 my.reference.target.bed
chr1    12189   12227   -
chr1    12594   12721   -
chr1    13402   13639   -
chr1    69090   70008   -
chr1    138529  139696  -

Check:
 $ cut -f1-4 my.targetcoverage.cnn | diff my.reference.target.bed -
 0a1
 > chromosome    start   end     gene

I.e. actually reference2targets.py returned me the original my.targetcoverage.cnn
:)
Therefore it was possible to make simply after 7th step:
  $ cut -f1-4 my.targetcoverage.cnn > ...

or maybe I do not understand something.

Sorry,
Can I use my.targetcoverage.cnn file as a  my_baits.bed ?
Perhaps you have any correct baits.bed file or requirements for its format.
Could you show it ?

Thanks in advance,
Alessandro

**Comment by etal** [comment]
Some thoughts regarding the various workarounds:

1. The `target` command will merge and potentially re-subdivide overlapping BED regions, e.g. overlapping exons. You can use that to ensure a valid BED file to use as input to `coverage` or `guess_baits.py`.
2. I'll take a look at `coverage` to see how it could have modified the input regions.
3. If you run `coverage` on multiple normal samples and pool them together with `reference`, it will look at the spread in coverages at each target region among the input samples and reject the bins with too much variability. It's also supposed to remove bins with coverage too far above or below the global average, so for your case that might work if you're guessing the baits for an exome kit, but not a target panel.

With the file my.targetcoverage.cnn, try manually filtering out rows with the 'depth' column value less than e.g. 5. Then you can use that resulting file as my_baits.bed. If you build a pooled reference with that set of guessed baits, then the baits will be filtered some more when you run `reference`.

**Comment by AlessandroGorohovski** [comment]
Hi Eric,
Thank you very much for your response!
I think, it really helped me to understand what is happening and choose my strategy.

I had to analyze my exons file more thoroughly for the overlapping regions
and was found a lot of such cases.
10)
Then I removed these overlapping regions from my `UCSC_exons_modif_canonical.final.bed` as:
`./overlapping_regions.pl UCSC_exons_modif_canonical.final.bed UCSC_exons_modif_canonical.filtered.bed`

But, unfortunately, when using `UCSC_exons_modif_canonical.filtered.bed` with `guess_baits.py`, the same error was repeated.

11)
Then I repeated the creation of `targetcoverage.cnn` file:

`cnvkit.py coverage my.realigned.bam UCSC_exons_modif_canonical.filtered.bed -o my.targetcoverage.cnn`

`head -5 my.targetcoverage.cnn`
chromosome      start   end     gene    depth   log2
chr1    12189   12227   DDX11L1 5       2.32193
chr1    12594   12721   DDX11L1 7.48819 2.90462
chr1    13402   13639   DDX11L1 4.09705 2.03458
chr1    69090   70008   OR4F5   0.602397        -0.731215

12) and filtered it in the 'depth' column value >= 5 hits:
`perl -lane 'print if $F[4] >= 5' my.targetcoverage.cnn | cut -f1-4 > my.5depth.baits.bed`

and with this file I did CNV analysis:
`python2.7 ./cnvkit.py batch my.realigned.bam \`
`           -n --targets my.5depth.baits.bed -f hg19.fa \`
`           --annotate hg19.refFlat.bed \`
`           --access ./data/access-5k-mappable.hg19.bed \`
`           --output-reference my.flat_reference.cnn \`
`           --output-dir ./CNV_results`
and
`python2.7 ./cnvkit.py batch my.realigned.bam \`
`           --r my.flat_reference.cnn --scatter  -diagram \`
`           --output-dir ./CNV_results`

Yes, here my.realigned.bam is actually a Tumor.bam file,
i.e. I have not real Normal.bam file for it.
Now I'm trying to understand how to correctly interpret the results. I would be very grateful if you could give an example of such an interpretation.

Regards,
Alessandro

**Comment by etal** [comment]
All right, glad to hear the workaround was successful.

In future, you can ensure your input intervals are in the non-overlapping, 4-column BED format that `guess_baits` expects by running your candidate exons (from UCSC) through `cnvkit.py target` or the new script `skg_convert.py`. For the latter, run it like:

    skg_convert.py ucsc_exons.bed --to bed4 --flatten -o ucsc_exons_nonoverlapping.bed

Which outputs are you trying to interpret? Here's the documentation for [plots](http://cnvkit.readthedocs.io/en/stable/plots.html), CNV [calling](http://cnvkit.readthedocs.io/en/stable/calling.html), and potential [export formats](http://cnvkit.readthedocs.io/en/stable/importexport.html#export).

**Comment by AlessandroGorohovski** [comment]
Hello Eric,
Many thank for your response!
It's very interesting and I'll try to use your new script skg_convert.py

Alessandro
