### ISSUE TITLE
bin mismatch

### ISSUE THREAD

**Issue by davisem** [etal/cnvkit#306]
```
Traceback (most recent call last):
  File "/home/edavis5/.local/bin/cnvkit.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/research/rgs01/home/clusterHome/edavis5/cnvkit/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/research/rgs01/home/clusterHome/edavis5/cnvkit/cnvlib/commands.py", line 501, in _cmd_reference
    args.do_rmask)
  File "/research/rgs01/home/clusterHome/edavis5/cnvkit/cnvlib/reference.py", line 55, in do_reference
    do_gc, do_edge, False)
  File "/research/rgs01/home/clusterHome/edavis5/cnvkit/cnvlib/reference.py", line 239, in combine_probes
    % (fname, filenames[0]))
RuntimeError: out.anticoverage.cnn bins do not match those in outblah.targetcoverage.cnn
```
I cannot make the reference file stepwise as shown in the instructions. What does this error mean, exactly? It should be noted that I'm doing coverage using a scatter-gather operation by chunking the targets file.

**Update:**
Figured it out. The files need to be named the same way. So like `out.anticoverage.cnn` & `out.coverage.cnn` is fine.` out.anticoverage.cnn` & `outblah.coverage.cnn` is no Bueno, and causes the crash.

**Comment by etal** [comment]
If this came from the `reference` command, you've probably mixed up samples from different target panels.

The `fix` command does require the input .cnn files to be named the same way by default (unless you specify `--sample-id`), but that's a different command and a different error.  Similar solution, use `out.coverage.cnn` instead of `outblah.coverage.cnn`.
 
Is there a different way to phrase that error message that would make troubleshooting easier?

**Comment by davisem** [comment]
Right. So, I only had one sample I was running. One target and one antitarget file. They both had the `.targetcoverage.cnn` and `.antitargetcoverage.cnn` suffix, but the prefixes were slightly different, so I guess it didn't know how to group them. Makes sense for when you're running batches of files now that I think about it. I suppose the error message did have me looking at the input file content and format. Maybe have it say `Name your files right` :) Thanks.

**Comment by etal** [comment]
OK, I see why it was confusing. That deserves a note in the docs, at least. Also potentially relevant: #304
