### ISSUE TITLE
Incorrect baseline

### ISSUE THREAD

**Issue by ferenju1** [etal/cnvkit#314]
Hi,

We've run CNVkit on around 400 targeted panel datasets. Generally it does a great job of segmenting the data, however occasionally it appears to put the baseline (log2=0) in the wrong place. I've attached a plot of an example, annotated with where I think the true baseline is (blue), ploidy 1 (orange line) and ploidy 0 (red line) plus ploidy 3,4,5, etc. With the baselines shifted as shown here, the VAFs of the mutations and ploidy of the genes are line up correctly, we've validated this and similar cases by FISH for a number of cases where it was doubtful. It seems on the surface as though the algorithm is stuck between deciding which of the two main clusters is actually the true zero, and plumps for the middle of the two. 

At the moment we're trying to automate purity estimation using PureCN, with segmentation input from CNVkit, and this automates very well except for these cases where the baseline is wrong.

Is this something you're aware can happen? I am not familiar with the algorithm well enough to know why it happens and whether there is anything I can do it improve it, but if you have any insight into how to improve/correct this I'd be very grateful for your opinion!

Thanks,

John

![example](https://user-images.githubusercontent.com/22363969/35664252-54765b46-0775-11e8-83fd-3d43aff3cf1d.png)

**Comment by etal** [comment]
I think you're doing everything correctly, but the genome you've showed here is a weird one where less than half the genome has neutral copy number, so the methods CNVkit uses to find a center value are not stable.

I suggest that in these cases, if you doing mind doing some scripting, you can use the allele frequencies to identify the segments with truly neutral copy number, calculate the mean or median log2 value of just those segments (or any one that looks good), then re-center at that value with the [call](https://cnvkit.readthedocs.io/en/latest/pipeline.html#transformations) command, e.g.:

    cnvkit.py call Sample.cns -m none --center-at 0.2 -o Sample.recentered.cns

**Comment by lima1** [comment]
PureCN expects the log-ratio mean centered and *should* recenter automatically. It might not work correctly. Feel free to send me an example segmentation, it shouldn’t be necessary to send the VCF if you can’t share.

**Comment by ferenju1** [comment]
Thanks to you both for the replies. Eric, the re-centering you've suggested is what we've been doing manually until now, so we'll work on developing that into an automated methodology.

I'll also respond regarding the integration with PureCN elsewhere Markus - I was initially following out of date instructions for integrating with CNVkit output, then accidentally followed instructions for the development version , which are both different from the instructions for the current release version.
