### ISSUE TITLE
CNVkit diagram with male reference returns chrX in homozygous deletion

### ISSUE THREAD

**Issue by LMannarino** [etal/cnvkit#316]
cc @lbeltrame

Hi,
 i have run CNVkit in two independent analyses using either a commercial reference or the matched blood sample, both are male and diploid. In both cases, samples analyzed versus the reference are male. To plot chromosomes ideograms I have used these options:
`-y --sample-sex Male`

In each case whole chromosome X results in homozygous deletion. I was wondering if it is biologically expected or it is just something related to case I am studying.

Thanks

**Comment by etal** [comment]
That's the expected behavior, and if you run the sample through `call` you'll see it's not marked as a homozygous deletion. See here:
https://cnvkit.readthedocs.io/en/latest/sex.html

**Comment by etal** [comment]
Fixed downstream in chapmanb/bcbio-nextgen#2267.
