### ISSUE TITLE
segment calls the wrong Rscript installation?

### ISSUE THREAD

**Issue by GiacoCorle** [etal/cnvkit#317]
Dear all,
it is a long time I am getting this annoying error and I do not understanding what is causing it.
I just run the make in the /test folder and the I get:

`python ../cnvkit.py segment -p 2 --drop-low-coverage -t .01 build/p2-5_5.cnr -o build/p2-5_5.cns
Segmenting with method 'cbs', significance threshold 0.01, in 2 processes
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/giacomino/anaconda/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/giacomino/anaconda/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/Users/giacomino/anaconda/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/Users/giacomino/Tools/cnvkit/cnvlib/segmentation/__init__.py", line 84, in _ds
    return _do_segmentation(*args)
  File "/Users/giacomino/Tools/cnvkit/cnvlib/segmentation/__init__.py", line 155, in _do_segmentation
    seg_out = core.call_quiet('Rscript', '--vanilla', script_fname)
  File "/Users/giacomino/Tools/cnvkit/cnvlib/core.py", line 36, in call_quiet
    % (' '.join(args), err))
RuntimeError: Subprocess command failed:
$ Rscript --vanilla /var/folders/2h/x5z9htsd2rn8083vf2khd0lw0000gp/T/tmpfpt158to

b'Error in library("DNAcopy") : there is no package called \xe2\x80\x98DNAcopy\xe2\x80\x99\nExecution halted\n'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../cnvkit.py", line 13, in <module>
    args.func(args)
  File "/Users/giacomino/Tools/cnvkit/cnvlib/commands.py", line 619, in _cmd_segment
    processes=args.processes)
  File "/Users/giacomino/Tools/cnvkit/cnvlib/segmentation/__init__.py", line 59, in do_segmentation
    for _, ca in cnarr.by_arm())))
  File "/Users/giacomino/anaconda/lib/python3.6/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/Users/giacomino/anaconda/lib/python3.6/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/Users/giacomino/anaconda/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
RuntimeError: Subprocess command failed:
$ Rscript --vanilla /var/folders/2h/x5z9htsd2rn8083vf2khd0lw0000gp/T/tmpfpt158to

b'Error in library("DNAcopy") : there is no package called \xe2\x80\x98DNAcopy\xe2\x80\x99\nExecution halted\n'
make: *** [build/p2-5_5.cns] Error 1
`

Can you help me with this? 
Best

**Comment by etal** [comment]
D you have the R package "DNAcopy" installed on your system? You can confirm by launching R (in the same environment as you're running CNVkit) and running the command `library("DNAcopy")`.

**Comment by GiacoCorle** [comment]
Yes, absolutely both DNAcopy and cghLasso work fine when I call them directly from R environment.

I think the problem is  related to the call that CNVkit does which seems to be not correct, I also add the direct path to the package but without any luck.

**Comment by etal** [comment]
Thoughts:
- How did you install CNVkit? If it's from source, there could be a lot of possible issues with paths. Which version are you using -- is it the very latest from GitHub? Did earlier versions work for you? The safest way to install the source is to install the stable `cnvkit` package in a clean `conda` environment, then install the source version (pulled from git) in the same environment with `pip -e .`.
- Could there be two installations of R on your system, one via conda and another installed separately? In that case, one has DNAcopy installed, the other does not, and the Rscript instance used by CNVkit is the one that does not. The `--rlibpath` option should point to the parent directory containing all of the "correct" R installation's packages, not just the DNAcopy package's top-level directory.
- The error message shows some odd bytes vs. unicode string formatting. Does the same error appear with Python 2.7? This was fine on Python 3.5 last I checked, but maybe something changed in Python 3.6. Does a conda-installed version work in a Python 3.6 environment?

**Comment by etal** [comment]
If you're able to edit and run the CNVkit source code, could you try hard-coding the path to Rscript in `cnvlib/segmentation/__init__.py` as @MajoroMask demonstrated here:
https://github.com/etal/cnvkit/pull/321/files

**Comment by etal** [comment]
I've added the option ``--rscriptpath`` to the 'batch' and 'segment' commands in the development version, if you'd like to try it out now.
