### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nriddiford** [etal/cnvkit#319]
I am running a clean install via conda: 

```
conda create -n cnvkit python
source activate cnvkit
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
conda install cnvkit
```

After successfully installing packages up to `matplotlib-2.1` prints:
...

> dbus post-link :: /etc/machine-id not found ..
> dbus post-link :: .. using /proc/sys/kernel/random/boot_id

Running `cnvkit.py` fails with:
...
> Traceback (most recent call last):
>   File "nriddiford/miniconda2/envs/cnvkit/bin/cnvkit.py", line 8, in <module>
>     from cnvlib import commands
>   File "nriddiford/miniconda2/envs/cnvkit/lib/python2.7/site-packages/cnvlib/__init__.py", line 5, in <module>
>     from .commands import *
>   File "nriddiford/miniconda2/envs/cnvkit/lib/python2.7/site-packages/cnvlib/commands.py", line 18, in <module>
>     from matplotlib import pyplot
>   File "nriddiford/miniconda2/envs/cnvkit/lib/python2.7/site-packages/matplotlib/pyplot.py", line 116, in <module>
>     _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
>   File "nriddiford/miniconda2/envs/cnvkit/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
>     [backend_name], 0)
>   File "nriddiford/miniconda2/envs/cnvkit/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
>     from .backend_qt5 import (
>   File "nriddiford/miniconda2/envs/cnvkit/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 18, in <module>
>     import matplotlib.backends.qt_editor.figureoptions as figureoptions
>   File "nriddiford/miniconda2/envs/cnvkit/lib/python2.7/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
>     import matplotlib.backends.qt_editor.formlayout as formlayout
>   File "nriddiford/miniconda2/envs/cnvkit/lib/python2.7/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
>     from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
>   File "nriddiford/miniconda2/envs/cnvkit/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
>     from PyQt5 import QtCore, QtGui, QtWidgets
> ImportError: /lib/libpthread.so.0: version `GLIBC_2.12' not found (required by nriddiford/miniconda2/envs/cnvkit/lib/python2.7/site-packages/PyQt5/../../.././libglib-2.0.so.0)

Is this a known problem? 

I am running on `Debian GNU/Linux 6.0.10 (squeeze)`

**Comment by etal** [comment]
It looks like the dependencies of matplotlib 2.1 are not being installed correctly -- more specifically, your OS does not have glibc 2.12 (Debian 6 probably packages an earlier version of glibc), which matplotlib 2.1 seems to indirectly require. Could you downgrade matplotlib to 2.0 in your environment and see if that fixes the issue? Otherwise, do you have a way of updating glibc on your system?

**Comment by nriddiford** [comment]
Thanks. Uninstalling `matplotlib 2.1` and re-installing `matplotlib to 2.0` worked.
