### ISSUE TITLE
Inline Plots in ipython notebook

### ISSUE THREAD

**Issue by rpadmanabhan** [etal/cnvkit#32]
Hey, 
Is there a way to get inline plots(the log2 coverage ones) in ipython notebook ? I tried %matplotlib inline, but it doesnt seem to solve it. 

Thank You

**Comment by etal** [comment]
I tried it and saw the same odd behavior -- `do_scatter` doesn't display a plot by itself, and if you add `pyplot.show()` afterward, the plot shows up in a new window.

Something like this worked exactly once for me, but not repeatably:

    import cnvlib
    from cnvlib.commands import do_scatter
    from matplotlib import pyplot
    pyplot.ion()

    cnr = cnvlib.read("~/code/cnvkit-examples/build/TR_95_T.cnr")
    cns = cnvlib.read("~/code/cnvkit-examples/build/TR_95_T.cns")
    do_scatter(cnr, cns, show_chromosome="chr12")

    pyplot.show()

**Comment by etal** [comment]
The following now work for me in IPython Notebook 2.3 (though I can't say which change fixed it since the initial bug report):

    %pylab inline
    from cnvlib import commands
    commands.create_heatmap("test/formats/amplicon.cns")
    show()

(shows the heatmap inline in the notebook)

    import cnvlib
    commands.do_scatter(cnvlib.read("test/formats/amplicon.cnr"), cnvlib.read("test/formats/amplicon.cns"))
    show()

(shows the scatter plot)

Can you, or anyone else, confirm that this is OK now?

**Comment by rpadmanabhan** [comment]
Sorry for the late reply. Both plots seem to be working well for me in ipython notebooks.

**Comment by etal** [comment]
Great to hear. Thanks!
