### ISSUE TITLE
How to choose refFlat.txt?

### ISSUE THREAD

**Issue by Tina9** [etal/cnvkit#320]
Hi author,

Thanks for your good tool to call copy number variations. However, I have a question about cnvkit batch. I want to user cnvkit batch to call cnv. But I am not sure whether to use refFlat.txt or not? My command is as follows:

cnvkit.py batch *Tumor.bam --normal *Normal.bam \
    --targets my_baits.bed \
    --fasta hg19.fasta \
    --output-reference my_reference.cnn --output-dir results/ \
    --diagram --scatter .

I didn't use _--annotate refFlat.txt_ , but I can still get a result. So could you please tell me whether the result can be used or not? What results can refFlat.txt affect?

My second question is still about refFlat.txt. Can I use the same refFlat.txt(https://cnvkit.readthedocs.io/en/stable/quickstart.html) when I deal with the data whatever it is wgs data or wes data?

Thanks for your help.
Tina

**Comment by etal** [comment]
1. If your my_baits.bed file already has 4 columns, and the 4th column lists gene names (or region labels, whatever you want to see in the plots), then you don't need to re-annotate the BED regions.
2. The same gene annotations are fine for WGS, WES, or any target panel. Just make sure the reference genome versions match, e.g. hg19, GRCh37, or GRCh38.

If you skip the `--annotate` option but then decide later that you would like to re-annotate the genes, you can use the script `cnv_annotate.py` to apply the refFlat.txt gene labels to existing .cnn, .cnr, and .cns files.

**Comment by Tina9** [comment]
Thanks for your help again.

Tina

**Comment by qindan2008** [comment]
My reference fasta  was from ensembl hg19, then can I still use hg19 refFlat.txt from UCSC?
