### ISSUE TITLE
Different between diagram & cns & bed

### ISSUE THREAD

**Issue by haoziyeung** [etal/cnvkit#323]
Hello @etal ,i'm using cnvkit in T/N pair panel liquid biospy data,my command is here:
cnvkit.py batch 17k1683CFD1.T.merge.bam --normal NA12878-DFN-1.N.merge.bam --targets cnvkit.baits.bed --annotate /gpfs/users/yanghao/database/bundle/b37.refFlat.txt --fasta /gpfs/users/yanghao/database/ref/b37/human_g1k_v37_decoy.fasta --access /gpfs/users/yanghao/software/cnvkit/data/access-5k-mappable.grch37.bed --output-reference my_reference.cnn --output-dir . --diagram --scatter -p --drop-low-coverage

cnvkit.py segmetrics -s 17k1683CFD1.T.merge.cn{s,r} --ci

cnvkit.py call --purity $C 17k1683CFD1.T.merge.segmetrics.cns --filter ci -o 17k1683CFD1.T.merge.calls.cns

cnvkit.py export bed 17k1683CFD1.T.merge.calls.cns --show variant -y -o 17k1683CFD1.T.merge.cnv.export.bed

is my command wrong ?
here i got a diagram pdf ::
![met-amp](https://user-images.githubusercontent.com/16606564/36780421-eea1b592-1cad-11e8-8529-834302651080.png)
in fact ,this sample is c-MET-amp ,so this pdf is all right,
but i can't get the result from *cns file(cns file have many false positive)

[yanghao@io03 17k1683CFD1-NA12878-DFN-1]$ wc -l *.cns
   49 17k1683CFD1.T.merge.calls.cns
   62 17k1683CFD1.T.merge.cns
   62 17k1683CFD1.T.merge.segmetrics.cns
  173 total

also,i can't get MET-amp from bed ::

[yanghao@io03 17k1683CFD1-NA12878-DFN-1]$ cat 17k1683CFD1.T.merge.cnv.export.bed
13      110434339       110438450       17k1683CFD1.T.merge.calls       1
14      19057400        20484252        17k1683CFD1.T.merge.calls       4
15      20044632        22595693        17k1683CFD1.T.merge.calls       4

i'm wondering how to get the result like diagram pdf ? many thanks

**Comment by haoziyeung** [comment]
make myself clear,i found 2 CNVs in diagram pdf,but i found many CNVs in cns or bed,and not match perfectlly,i want get a txt version of CNVs like diagram show,how do i do ? thanks a lot..

**Comment by etal** [comment]
Try the `gainloss`/`genemetrics` command:
https://cnvkit.readthedocs.io/en/stable/reports.html#genemetrics

The `diagram` labels are for genes in segments with log2 ratios above 0.5 or below -0.5, so use `genemetrics -t 0.5` to get the same results in tabular form. (In CNVkit versions below 0.9.2, the same command is called `gainloss`.)

**Comment by haoziyeung** [comment]
Here is my genemetrics command:
cnvkit.py genemetrics -t 0.5 17k1683CFD1.T.merge.cnr -s 17k1683CFD1.T.merge.cns -o genemetrics.txt

**Comment by haoziyeung** [comment]
Hello,etal,i've found the command using:
cnvkit.py call  genemetrics.txt

Many thanks ,Hope you have a great day.i'm closing this issue.
