### ISSUE TITLE
Aggragation of cnr values

### ISSUE THREAD

**Issue by tushardave26** [etal/cnvkit#324]
Thanks for the tool.

It works like a charm. However, I would like to ask few questions about the functionality.First, the tool doesn't preserve the sample name and just use the basename of the input file to create cnr and cns file names. If we run the tool on multiple samples either I have to put sample identifier within the input file name or figure out some other solution. Is there any easy fix for this? Second, the tool produces sample specific cnr and cns files. Does there any aggregation script in the pipeline which I can use to aggregate all the results and make gene by sample matrix for the analysis.

Thanks.

**Comment by etal** [comment]
From the command line, the sample IDs come from the input BAM filenames and dictate the output filenames, as you've seen. The `fix` command lets you specify the sample ID used in the output .cnr filename, giving you some flexibility in naming the input target and antitarget coverage .cnn files, in case you prefer to calculate binned read depths via mosdepth or another tool.

The cnvlib API will let you arbitrarily load a pandas DataFrame from a file and connect a sample ID to the GenomicArray or CopyNumArray wrapper class using the `.meta` attribute. If you stick to instances of those classes you can run the pipeline without writing intermediate files to disk, reducing the need for specific filenames.

The .cnr and .cns files are just TSV dataframes that you can load in pandas or R with default options. With .cnr files the bin coordinates will match across a cohort, so you can do a join on the first three columns if you want to aggregate the samples into one big dataframe. With .cns files the segment coordinates generally will not match, so a join would be tricky. You can use `cnvlib.read` or `skgenome.tabio.read` to load the dataframes into the aforementioned wrapper classes which support some interval arithmetic (intersect, merge, flatten, etc.).

**Comment by tushardave26** [comment]
Thanks @etal
