### ISSUE TITLE
v0.9.2 'segmetrics' crashes in most cases

### ISSUE THREAD

**Issue by vfunari** [etal/cnvkit#325]
while 9.2 is brilliant, We rolled back to 8.5 and segmentation commands work fine there.
in 9.2 segmentation command is recognized (e.g cnvkit.py segmentation) but when parameters/options are passed it crashes.

MACBOOK:cnvkit-0.8.5$ cnvkit.py segmetrics /Users/Desktop/ashion/NTP19-000370.cnr -s /Users/Desktop/results/NTP19-000370.cns --iqr --ci -o /Users/Desktop/results/NTP19-000370.segmetrics
Traceback (most recent call last):
  File "/Users/miniconda2/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/Users/miniconda2/lib/python2.7/site-packages/cnvlib/commands.py", line 1259, in _cmd_segmetrics
    args.interval_stats, args.alpha, args.bootstrap)
  File "/Users/miniconda2/lib/python2.7/site-packages/cnvlib/segmetrics.py", line 42, in do_segmetrics
    for statname in location_stats:
**TypeError: 'NoneType' object is not iterable**

**Comment by etal** [comment]
Ouch, thanks for reporting this. There is a unit test in place for the `segmetrics` command, but it's not comprehensive and doesn't cover the CLI. It looks like the crash will occur unless at least one of the options `--mean`, `--median`, and `--mode` is used. Alternatively, if you run `cnvlib.do_segmetrics` through the Python API, it should also avoid the crash.

**Comment by etal** [comment]
The fix is now available in version 0.9.3 on PyPI.
