### ISSUE TITLE
Missing name field in bedcov

### ISSUE THREAD

**Issue by johnmu** [etal/cnvkit#33]
line:
https://github.com/etal/cnvkit/blob/2d43983e15690e37c6bcd8f502e049ce81471351/cnvlib/coverage.py#L125

`samtools bedcov` doesn't return a "name" fields as far as I know. Where does this name field come from?

**Comment by etal** [comment]
Sure it does, at least if the input BED file also contains a "name" field in the 4th column.

    $ more some-targets.bed 
    chr1	30330	30540	MIR1302-10
    chr1	35051	35290	FAM138A
    chr1	35290	35529	FAM138A
    chr1	35623	35833	FAM138A
    chr1	69039	69294	OR4F5
    chr1	69294	69549	OR4F5
    chr1	69549	69804	OR4F5
    chr1	69804	70059	OR4F5
    chr1	367618	367873	OR4F16
    chr1	367873	368128	OR4F16

    $ samtools bedcov -Q 1 some-targets.bed some-reads.bam 
    chr1	30330	30540	MIR1302-10	0
    chr1	35051	35290	FAM138A	0
    chr1	35290	35529	FAM138A	50
    chr1	35623	35833	FAM138A	0
    chr1	69039	69294	OR4F5	0
    chr1	69294	69549	OR4F5	1228
    chr1	69549	69804	OR4F5	748
    chr1	69804	70059	OR4F5	0
    chr1	367618	367873	OR4F16	0
    chr1	367873	368128	OR4F16	0


    $ samtools 

    Program: samtools (Tools for alignments in the SAM format)
    Version: 0.1.19-44428cd
    ...

**Comment by johnmu** [comment]
Ah I see, yeah my BED file was missing the 4th column. Thanks!
