### ISSUE TITLE
Y-chromosome in pooled reference set

### ISSUE THREAD

**Issue by nfarnoud** [etal/cnvkit#331]
Hello,
I have a problem in understanding how the reference coverage is calculated for **Y-chromosome**. 
To give you a background, I am running CNVkit on targeted data using a **pooled normal reference set** consisting of 24 MALE and 24 FEMALE samples. 
I understand that the pooled reference set is built as XXY, but when we look at CN scatter plots of MALE samples, we observe a relative amplification of Y-chr, such as shown below by the red arrow. 
I appreciate if you tell me how to interpret this observation.

Thanks a lot in advance for your time,
nfarnoud

![75175](https://user-images.githubusercontent.com/29715882/37170623-5379b31c-22d9-11e8-95d7-414cd056204f.png)

**Comment by etal** [comment]
Thanks for letting me know.

- Which version of CNVkit are you using?
- Do you see the Y gain at the same level (log2 value) in every male sample?
- In the reference.cnn file, what is the average or typical log2 value in the same region? (You can visually skim that file at the start of Y, or run the reference.cnn file through `segment` to get the true average value.)

**Comment by nfarnoud** [comment]
Thanks for your prompt response! Here are the answers:

- CNVKIT 0.8.5
- Not exactly the same value. I tested it for 8 known MALE samples and the Y gain is present at all of them but with **median** log2 value of +0.63 ranging between 0.46 and 0.65.
- for the reference.cnn I browsed the log2 values and the mean is ~ -0.786 (median is ~ -0.8, ranging between -1.4 to +1.9).

**Comment by nfarnoud** [comment]
Hello,  I was wondering if you have any updates regarding the above issue? 
Thanks
