### ISSUE TITLE
Target seems to annotate with RefFlat only for genes on the + strand

### ISSUE THREAD

**Issue by OgnjenSB** [etal/cnvkit#333]
As the title says, target.py seems to annotate with RefFlat only for genes on the + strand. Please check if this is an issue with Tabio.

It is possible that default gene name '-' clashes with the same symbol for the strand.

**Comment by etal** [comment]
Thanks for letting me know, I'll look into it.

**Comment by etal** [comment]
I'm not able to replicate this -- could you tell me more about how you found the issue?

I extracted the refflat exons as BED3, then re-annotated that exon BED with the original refflat file, and both the + and - strand genes appear in the output (e.g. DDX11L1 and WASH7P on chr1).

I also see that `skgenome.tabio.read("refFlat.txt", "refflat").data.head()` shows rows with both strands, and the script `skg_convert.py`  keeps both strands.
