### ISSUE TITLE
Duplicate Sample ID Error

### ISSUE THREAD

**Issue by tushardave26** [etal/cnvkit#337]
I am running CNVKit on the normal samples against a pool of normals. The normal sample is a superset and the pool of normals derived from it. The issue I am experiencing is that when CNVKit identifies the same sample id in normal sample pool and pool of normals, its complaint about the Duplicate Sample ID and failed on me. Is there any workaround other than changing one of the file names. I hope this makes sense. Following the error message that I am getting:

`Duplicate sample ID '6109_b' (from /data/6109_b.bam and /data/6109_b.bam)`

Thanks.

**Comment by etal** [comment]
It sounds like you're running the `batch` command with some overlap between the "test" samples and the `-n` pool of normals. There's a known issue with that (#48), and the workaround is to first run `batch` with just the pool of normals, no test samples, to generate a reusable pooled reference. Then, run `batch` again with the pooled reference you've just generated as the `-r` input, and provide the test samples (which can include the same "normal" samples) as inputs as usual.

Does that work for you?

To avoid duplicating computation, you can also run the individual commands `fix` and `segment` using the pooled reference and reusing the (anti)targetcoverage.cnn files that were already generated for the normal samples. If you have many samples, it's best to orchestrate that through a shell script or Makefile.
