### ISSUE TITLE
errors report:  

### ISSUE THREAD

**Issue by WinterLi1993** [etal/cnvkit#339]
HI,

when I run cnvkit ,got the following errors : 
             libmkl_vml_avx2.so: undefined symbol: mkl_serv_getenv

any help will be welcome !

**Comment by etal** [comment]
This sounds like an installation issue where the conda packages (maybe numpy or pandas) were compiled for Intel CPUs that support "MKL" instructions, but some dependency is missing or unavailable for your current hardware. I'm not sure how to fix that within conda, but doing a fresh installation with plain `pip` and your system's `apt` or `yum` packages for numpy, scipy, and pandas might work.
