### ISSUE TITLE
Error with import-rna function

### ISSUE THREAD

**Issue by doncarlos999** [etal/cnvkit#345]
I was getting the following error:

Traceback (most recent call last):
  File "/home/carl/miniconda3/envs/py2/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/carl/miniconda3/envs/py2/lib/python2.7/site-packages/cnvlib/commands.py", line 1443, in _cmd_import_rna
    args.normal)
  File "/home/carl/miniconda3/envs/py2/lib/python2.7/site-packages/cnvlib/import_rna.py", line 19, in do_import_rna
    gene_count_fnames = sorted(set(gene_count_fnames) + set(normal_fnames))
TypeError: unsupported operand type(s) for +: 'set' and 'set'

When running the following command:
cnvkit.py import-rna -f 'rsem' -g /mnt/c/Shared/hv_sequencing/CNV/ensembl-gene-info.hg38.tsv -n /mnt/c/Shared/hv_sequencing/RSEM/C11-L..genes.results -d /mnt/c/Shared/hv_sequencing/CNV -o summary /mnt/c/Shared/hv_sequencing/RSEM/*.genes.results 

I fixed it by changing line 19 of import-rna.py from:
 gene_count_fnames = sorted(set(gene_count_fnames) + set(normal_fnames))

to:
gene_count_fnames = sorted(set(gene_count_fnames + normal_fnames))

This avoids addition of sets.
I don't know if this was just a problem for me or a general one.
Hope it helps any others who hit the same problem.

**Comment by etal** [comment]
Thanks for letting me know. Are you using the current version of CNVkit? I see this at import_rna.py line 19:

    gene_count_fnames = sorted(set(list(gene_count_fnames) + list(normal_fnames)))

which works on Pythons 2 and 3.

**Comment by etal** [comment]
Yes, it looks like I fixed that error after the 0.9.2 release. Sorry for the trouble, but it should be fixed in the next release, and you can also get the fix early if you install from the Github source (`cd cnvkit/ && pip install -e .`).

**Comment by trodriguez2011** [comment]
Given a 2-column input .tsv (from kallisto abundance.tsv or abundance.h5 processed by sleuth), import-rna generates a .cnr with zero log fold-change for every gene. If normalization is excluded from the code then input-rna returns non-zero values. 

I would appreciate any insight as to why values may be thrown out at the quantile step of normalization.
