### ISSUE TITLE
export seg function not outputting start and end coordinates

### ISSUE THREAD

**Issue by stacyhung** [etal/cnvkit#347]
Hi, I'm interested in viewing the SEG file for my 95 samples in IGV.  I am applying the "export seg" function as specified in the CNVkit docs -- this produces an output file that appears to be missing the "loc.start" and "loc.end" values for all rows.  I'm not sure if this is a bug, or if I am doing something incorrectly.  My *cns files are not modified and contain the start and end locations.  Any feedback would be greatly appreciated.

**Comment by etal** [comment]
Can you post the command line you used, and the header and first few lines of the SEG output?

If those columns are just missing, it's probably a bug.

**Comment by stacyhung** [comment]
`cnvkit.py export seg cns/drop_low_coverage/*cns -o igv/all_samples-default_thresholds-drop_low_coverage.seg`

The first 5 lines of the output file:

ID      chrom   loc.start       loc.end num.mark        seg.mean
PA001   1                       18721   -0.005844
PA001   1                       64      0.686
PA001   1                       2689    0.0025282
PA001   1                       17498   -0.00710432

**Comment by etal** [comment]
I'm not able to reproduce this with my own files.
- Is there anything unusual about your .cns files?
- Are you using the latest version of CNVkit? Which version of pandas?
- Do you see this issue with all of your .cns files, or just some?
- Does it still happen when only one .cns file is given as input?

**Comment by etal** [comment]
I saw this issue happen with CNVkit version 0.9.1, and confirmed that it's gone in the development version. Not sure if it's OK in 0.9.3, but in case it's not, the next release will include the fix.
