### ISSUE TITLE
Visualizing aggregated CNVs across all samples

### ISSUE THREAD

**Issue by stacyhung** [etal/cnvkit#348]
Hi, can you please suggest a tool or methodology for visualizing copy number data obtained from CNVkit aggregated across multiple samples (e.g. n=95)?  This is the style of plot where genomic amplifications are in red and genomic deletions are in blue, with height indicating the number of samples having genomic aberrations. An example plot (but based on array CGH data) has been attached.  Any ideas would be greatly appreciated!

![cn_genome_wide_view-example](https://user-images.githubusercontent.com/5245887/39538792-cb72b29e-4df2-11e8-97d8-639bfaa5cbd8.jpg)

**Comment by etal** [comment]
Personally, I use the `heatmap` command to look at all samples at once, and if there are tons of samples, edit the output PDF in Inkscape to remove sample labels on the y-axis and add any relevant annotations manually.

I know this type of plot, and I think there are R packages that will generate it -- you can probably extract the data you need from the .cnr or .cns files treating them as plain dataframes. It would be nice to have the same function built into CNVkit. Is there a name for this style of plot in the software you used to create the example? I think it's sometimes referred to as a "profile plot", which isn't very informative for naming a new command in CNVkit.

**Comment by lbeltrame** [comment]
You can do this type of plot if you export the data to `seg`  and then you can use the `copynumber` package from Bioconductor to do this type of plot.

**Comment by stacyhung** [comment]
Thanks @lbeltrame!  It looks like the cnvkit `export seg` function doesn't produce exactly the input for use in the `copynumber` package (e.g. missing start, end, and chromosome arm), but filling these in is relatively straightforward and otherwise exactly what I was looking for.
