### ISSUE TITLE
import-rna error(s)

### ISSUE THREAD

**Issue by sxv** [etal/cnvkit#351]
Hi I'm trying to run import-rna with counts rather than RSEM data. A couple problems:

1) It looks like python doesn't allow the + operator for two sets. Is this just a bug in the code or am I doing something wrong here?

$ cnvkit.py import-rna counts/*.txt -n normal.txt --gene-resource ensembl-gene-info.hg38.tsv --correlations tcga-skcm.cnv-expr-corr.tsv --output out-summary.tsv --output-dir output

> Traceback (most recent call last):
>   File "/usr/local/bin/cnvkit.py", line 13, in <module>
>     args.func(args)
>   File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1438, in _cmd_import_rna
>     args.normal)
>   File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/import_rna.py", line 22, in do_import_rna
>     gene_count_fnames = sorted(set(gene_count_fnames) + set(normal_fnames))
> TypeError: unsupported operand type(s) for +: 'set' and 'set'

2) To get past this, I modified the offending line from:
`gene_count_fnames = sorted(set(gene_count_fnames) + set(normal_fnames))`
to
`gene_count_fnames = sorted(set(gene_count_fnames).union(set(normal_fnames)))`
Then the script runs further but I encounter:

> Dropping 45909 / 58037 rarely expressed genes from input samples
> Loading gene metadata and TCGA gene expression/CNV profiles
> Loaded ensembl-gene-info.hg38.tsv with shape: (221323, 9)
> Traceback (most recent call last):
>   File "/usr/local/bin/cnvkit.py", line 13, in <module>
>     args.func(args)
>   File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/commands.py", line 1438, in _cmd_import_rna
>     args.normal)
>   File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/import_rna.py", line 38, in do_import_rna
>     gene_info = rna.load_gene_info(gene_resource_fname, correlations_fname)
>   File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/rna.py", line 81, in load_gene_info
>     corr_table = load_cnv_expression_corr(corr_fname)
>   File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/cnvlib/rna.py", line 113, in load_cnv_expression_corr
>     table = (pd.read_table(fname, dtype={shared_key: str}, na_filter=False)
>   File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 709, in parser_f
>     return _read(filepath_or_buffer, kwds)
>   File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 455, in _read
>     data = parser.read(nrows)
>   File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 1069, in read
>     ret = self._engine.read(nrows)
>   File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py", line 1839, in read
>     data = self._reader.read(nrows)
>   File "pandas/_libs/parsers.pyx", line 902, in pandas._libs.parsers.TextReader.read
>   File "pandas/_libs/parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory
>   File "pandas/_libs/parsers.pyx", line 978, in pandas._libs.parsers.TextReader._read_rows
>   File "pandas/_libs/parsers.pyx", line 965, in pandas._libs.parsers.TextReader._tokenize_rows
>   File "pandas/_libs/parsers.pyx", line 2208, in pandas._libs.parsers.raise_parser_error
> pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 878, saw 5

Any idea what's going on here?

Thanks!

**Comment by etal** [comment]
Also reported in (1) #355 and (2, possibly) #356
