### ISSUE TITLE
Slow cnvkit.py reference runtimes from warn_bad_bins

### ISSUE THREAD

**Issue by chapmanb** [etal/cnvkit#354]
Eric;
I've been getting reports of slower runtimes from `cnvkit.py reference` when building the background CNN and am tracing some of the issues to the output from `warn_bad_bins`:

https://github.com/etal/cnvkit/blob/c1fc4b5ccb3fce56cc41924909216a5f21fe712b/cnvlib/reference.py#L265

When it fails the checks with a message like:
```
[2018-05-15T17:40Z] r3356: Targets: 1026872 (8.2927%) bins failed filters:
```
It then proceeds to write all of these bins to `logging.info`. For a `cnvkit.py reference` run that takes 3:27, the writing of the filters takes 2:22.

Is this number of failed bins an indication of problem we should be addressing. If so, happy to tackle that issue. If not, is it possible to make the writing of the individual bins optional? I'm not sure if it's the logging or CNVkit being slow through this loop but I'd like to try to avoid either way and want to do the right thing. Thanks as always for all the help.

**Comment by etal** [comment]
Thanks for flagging this, I agree it's not helpful to print this info to the console for anything but a target panel. You can extract the same list of samples from the reference.cnn file by filtering for bins where `depth == 0`, `log2 < -5`, or `spread > 1`. I'll change this log message to just print the filters that were applied, rather then the list of bins that were filtered out.

For WGS, it's not too surprising that 8.3% of the genome's coverage is too low or variable across samples to be suitable for CNV calling. Those bins would be a reasonable candidate list for `access --exclude` regions, for example, if this is a pooled reference with a good number of representative normal samples.

**Comment by chapmanb** [comment]
Eric -- thanks so much for the explanation and the quick fix. I pushed a new bioconda package with this and will give it a test on some WGS samples. Thanks again.
