### ISSUE TITLE
Heatmap matrix

### ISSUE THREAD

**Issue by JImenaParedes** [etal/cnvkit#365]
Hi! 
I just wanted to know how to build a matrix from the output files to plot a heatmap. I mean, I need to build the matrix because I need to plot the heatmap with R but I don't know how to do so.
I know that CNVkit is for python mainly,but, I wanted to know if it's posible to do it with R.
Hope you can help.
Thank you in advance

**Comment by etal** [comment]
You can get a matrix of log2 ratios from the commands `export cdt` and `export jtv` -- either will work. There will be an extra header row and first column, but those are easy enough to handle in R.
