### ISSUE TITLE
Access files availability in Docker image

### ISSUE THREAD

**Issue by tushardave26** [etal/cnvkit#366]
Hello @etal,

Recently, I decided to use Docker image for `CNVkit`. I successfully download the image from `DockerHub` and can run the image without any issue. However, I do have a question about the `access` files which usually available under the `data/` directory of standard `CNVkit` distribution. For example, I do use `access-5k-mappable.hg19.bed` in my command line. I have two questions:

1. Do the Docker images include the access files?
2. If yes, then where are those being stored on the image?

Thank you for your help.

Best,
Tushar

**Comment by etal** [comment]
The access*.bed files are not included in the Docker image. You can get them from the source repo here on GitHub.

**Comment by tushardave26** [comment]
Thank you @etal for a prompt response. That's what I thought too. I will do that.
