### ISSUE TITLE
genemetrics on wgs

### ISSUE THREAD

**Issue by andyjslee** [etal/cnvkit#367]
It seems that CNVkit produces cnr files without any gene annotation for (whole genome sequence) wgs samples. The gene column in all wgs cnr files is empty (marked with a hyphen '-'). This seems to be the reason why genemetrics finds no gains and losses at gene-level for wgs samples. How can I call genemetrics on wgs samples? Thanks!

**Comment by etal** [comment]
You can provide gene annotations as a separate file: `cnvkit.py batch --annotate refFlat.txt ...`

See the "quick start" section on reference genome annotations:
https://cnvkit.readthedocs.io/en/stable/quickstart.html#download-the-reference-genome

If you've already run the pipeline without gene annotations, you can add gene labels to the output files with the script cnv_annotate.py:
https://cnvkit.readthedocs.io/en/stable/scripts.html

**Comment by andyjslee** [comment]
I get the following error when I run cnv_annotate.py:

>  File "/home/user/anaconda2/bin/cnv_annotate.py", line 35, in <module>
>     main(AP.parse_args())
>   File "/home/user/anaconda2/bin/cnv_annotate.py", line 18, in main
>     cnarr = read_cna(args.cn_file)
> AttributeError: 'Namespace' object has no attribute 'cn_file'
>

**Comment by etal** [comment]
Sorry, fixed in the development version now.
