### ISSUE TITLE
Segmentation fault error 

### ISSUE THREAD

**Issue by Rmulet** [etal/cnvkit#372]
Hi,

Every time I run cnvkit.py batch I get a segmentation fault error once the program starts processing the target. To exclude it was a sample-specific thing, I have tried with some data that I already analyzed with cnvkit.py in the past, but I also got an error. Please note that the last time I used cnvkit.py was on a different machine and another version, so plenty of things have changed.

That said, this is the command I have used (I don't have normals so I just provide `-n`):
```
cnvkit.py batch 05H002149_150430_SN583_0139_AC5WGDACXX.bam 06H007226_150430_SN583_0139_AC5WGDACXX.bam 07H002058_161012_SN583_0216_BC9LEHACXX.bam 07H007673_161012_SN583_0216_BC9LEHACXX.bam -n --targets ../metadata/V3_capture_HG19.bed --annotate /genomes/hg19/hg19refFlat.txt --fasta /genomes/hg19/hg19.fa --output-reference reference_V3.cnn --output-dir results_cnvkit_V3 --diagram --scatter --access /tools/cnvkit/data/access-5k-mappable.hg19.bed
```
And this is the last part of the output, including the error I get:

```
Summary: #bins=18808, #reads=21665931, mean=1151.9530, min=24.0099009901, max=45979.0693069 
Percent reads in regions: 31.198 (of 69446560 mapped)
Wrote results_cnvkit_V3/05H002149_150430_SN583_0139_AC5WGDACXX.antitargetcoverage.cnn with 18808 regions
Processing target: 05H002149_150430_SN583_0139_AC5WGDACXX
Segmentation fault (core dumped)
```

I am using `cnvkit version 0.9.3` installed with pip.

**Comment by etal** [comment]
Can you try updating pysam? The log message suggests this is happening when CNVkit calls out to pysam.bedcov to calculated read depths. The likely problem is a mismatch between compiled C libraries/objects (which pysam uses directly), so reinstalling an up-to-date pysam may fix it.

Otherwise, reinstalling CNVkit and its dependencies in a clean `conda` environment, using `conda` for all package installation, should solve the problem since conda packages are precompiled.

**Comment by Rmulet** [comment]
Thanks for your prompt reply. I was already using the latest version of pysam, but I reinstalled it anyway (with `--forced-reinstall`). Unfortunately it made no difference and CNVkit crashed anyway at that point.

On the contrary, reinstalling CNVkit via `conda` worked perfectly. I will stick to this in the future...
