### ISSUE TITLE
CNVkit skipped all VarScan somatic variants

### ISSUE THREAD

**Issue by weishwu** [etal/cnvkit#373]
I wanted to run CNVkit call with VarScan somatic variants to get LOH, however it skipped all my variants:

> Selected test sample TUMOR and control sample NORMAL
> Loaded 0 records; skipped: 1986628 somatic, 43981 depth
> Kept 0 heterozygous of 0 VCF records
> Calling copy number with thresholds: -1.1 => 0, -0.25 => 1, 0.2 => 2, 0.7 => 3
> Wrote Sample_4099_recal_Tumor_withVarScanVCF_recall.cns with 696 regions

My command-line is:

`${cnvkit} call Sample_${f}_recal_Tumor.cns -y -v ${varscanDir}/forCNVkit/Sample_${f}_vs_C57BL6NJ_VarScan_PASS.vcf -i TUMOR -n NORMAL -z -o Sample_${f}_recal_Tumor_withVarScanVCF_recall.cns`

A couple of lines from my VCF:

> 1       6842463 .       T       C       .       PASS    DP=88;SOMATIC;SS=2;SSC=75;GPV=1E0;SPV=3.1185E-8 GT:GQ:DP:RD:AD:FREQ:DP4 0/0:.:60:60:0:0%:28,32,0,0      0/1:.:28:15:13:46.43%:10,5,8,5
> 1       6844221 .       G       A       .       PASS    DP=95;SOMATIC;SS=2;SSC=79;GPV=1E0;SPV=1.243E-8  GT:GQ:DP:RD:AD:FREQ:DP4 0/0:.:66:66:0:0%:23,43,0,0      0/1:.:29:15:13:46.43%:9,6,6,7

I also tried running it without "-z" but it still skipped everything.

The version is 0.9.4.dev0.

Any help? Thanks.

**Comment by etal** [comment]
In those example lines the variant is marked as somatic, and the allele frequency in the normal sample is 0%, so those variants would always be excluded even with `-z`. If all of the germline variants have been filtered out then you'll need to either find the original VCF, or recover the SNP allele frequencies another way, see #374
