### ISSUE TITLE
Are germline variants necessary to include?

### ISSUE THREAD

**Issue by weishwu** [etal/cnvkit#374]
I ran cnvkit.py call with a Mutect2 somatic vcf to calculate "baf" and "cn" to deduce LOH. The cnvkit manual says:

> Include both germline and somatic variants (if any) in the VCF file. (For MuTect, this means keeping the “REJECT” records.) Mark somatic variants with the “SOMATIC” flag in the INFO column.

However I've used the latest version of Mutect2 which only emits somatic calls. Is it OK to just give cnvkit somatic variants?

Thanks.

**Comment by etal** [comment]
Nope, you need SNPs. See here: http://cnvkit.readthedocs.io/en/stable/baf.html

You can call SNP sites in the tumor with samtools and an example VCF file. The development version of CNVkit bundles a script to do this. It is not well tested, but you can use it for guidance: https://github.com/etal/cnvkit/blob/master/scripts/snpfilter.sh

The script requires another VCF file as input, ideally dbSNP or 1000 Genomes common variant sites. Alternatively, you can use this example germline VCF file from the repo if your reference genome is hg19: https://github.com/etal/cnvkit/blob/master/test/formats/na12878_na12882_mix.vcf

**Comment by weishwu** [comment]
OK, thanks!
