### ISSUE TITLE
cnvkit.py -a doesn't create split targets into specified size

### ISSUE THREAD

**Issue by yisu-li** [etal/cnvkit#375]
Hi there, 

I tried to split my bins with -a 100 but it didn't split any of my targets even though I have target exons >400bp. 
Please advice.
btw, I am using cnvkit  0.9.4.dev0.

Thanks,
Yisu

**Comment by etal** [comment]
Can you show me the full command you used? With `cnvkit.py target -a`, the target BED file will be split in the output, but the input file is not modified, and the log messages will show which targets were split.

**Comment by yisu-li** [comment]
Hi @etal,
Here is how my input file looks like.
`
10	104155706	104155747	NFKB2-Exon1	0	+
10	104155999	104156101	NFKB2-Exon3	0	+
10	104156195	104156256	NFKB2-Exon4	0	+
...
` 
The following is my command.
`$ cnvkit.py target -a 100 -otargets_100bp.bed targets.bed
$ diff <(sort targets_100bp.bed) <(cut -f1-4 targets.bed|sort )
`
The output file is identical to the input file for target regions.

**Comment by Marmach** [comment]
Hi, actually I have a similar (?) problem?

Or maybe I don't understand how "target" works?

Initially I thought that CNVkit would automatically split any provided target bed to an appropriate size, but I started digging after I got >1500bp fragments in target.bed generated with autobin for one of my targets. I guess it was my fault to assume, that even when not using "batch" command I'll get properly cut target, but even when I try any of those:
`target sometarget_hg19_annot.bed --split -o 267.bed`
`target sometarget_hg19_annot.bed --avg-size 267 --split -o 267.bed`
i get a split bed file indeed, but neither median, max nor average sizes of bins are 267bp.

Obviously, multiple bins are less than 267bp from the beginning, so median and average sizes can't reach exactly 267bp. However, assuming that only regions equal or larger than 2x267bp are split, I should (?) get multiple bins up to 533bp, while in reality I get bins up to ~400bp.

BTW, documentation specifies "--average-size" parameter which is not recognized by CNVkit 0.9.5 (--avg-size instead)

**Comment by etal** [comment]
It looks like `target --split` is not happening when it should. I'm investigating. It might be related to #302 internally.

@Marmach The max bin size in `autobin` is effectively the maximum *average bin size* that will be passed to the `target` command. If you know the bin size you want, you can skip `autobin` and give the value to `target --split --avg-size=<that-value>`, where it will/should subdivide any targeted regions more than 1.5x the specified average size.

**Comment by yisu-li** [comment]
Hi @etal,

This problem seems resolved in v0.9.6dev0.

**Comment by etal** [comment]
Thanks for letting me know. I've added a unit test to confirm that this is fixed in the current development version.
