### ISSUE TITLE
Summarizing .cns files

### ISSUE THREAD

**Issue by andyjslee** [etal/cnvkit#378]
Is there a script or a command that summarizes multiple cns files at once?

For example, for each interval (chrom, start, end), I would like to know the percentage of samples (as well as which samples - .cns file names) that have gains and deletions.

I know that a simple script can be written to achieve this at the gene level but I was wondering if there is one for .cns files.

Thanks!

**Comment by etal** [comment]
Sort of. The `heatmap` plot will show you the large-scale alterations in a cohort, and `export bed --show variant` with multiple .cns files as input will output a single BED file of the copy number alterations in all .cns files, with the sample name in the 4th column by default.
