### ISSUE TITLE
error: unrecognized arguments:  --output-reference my_reference.cnn

### ISSUE THREAD

**Issue by stevelu08** [etal/cnvkit#381]
Hi, I am new to cnvkit and am currently trying to build a reference and infer tumor copy ratios. My current command is: 

cnvkit.py batch Tumor.bam --normal Normal.bam \
    --targets my_baits.bed --fasta hg19.fasta \
    --output-reference my_reference.cnn --output-dir example/

However it is giving me the error of unrecognized arguments for --output-reference my_reference.cnn. Have the commands changed? Thanks!

**Comment by etal** [comment]
No, this hasn't changed in awhile. Are you using the latest CNVkit version, v0.9.5? (See `cnvkit.py version`)

If this is still a problem, can you show me the full log, including the traceback and any log messages that were printed before it?

**Comment by brewert2** [comment]
I come across a similar issue. 
My command : 
cnvkit.py batch *T.bam -n *Bld.bam \
    -t path.to.bed \
    -f path.to.19fasta \
    --annotate path.to.refFlat.txt \
    --access data/access-5kb-mappable.hg19.bed \
    --output-reference cnvkit.reference.cnn -d ./


Error : 
cnvkit.py: error: unrecognized arguments:
cnvkit.batch.sh: line 13: -f: command not found


Would you please give me inputs how to fix this issue? 

Thank you.
