### ISSUE TITLE
Default segmentation produces weird segments in v0.9.5

### ISSUE THREAD

**Issue by tskir** [etal/cnvkit#383]
Hi Eric,

When I run `cnvkit.py segment -o bug.cns bug.cnr`, it produces this really strange segment (second in the list, from 20609931 to 24381809):

```
chromosome	start	end	gene	log2	depth	probes	weight
chr22	16050500	20508931	IL17RA,ADA2,SLC25A18,PEX26,TUBA8,DGCR6,PRODH,DGCR5,DGCR2,DGCR14,SLC25A1,CLTCL1,HIRA,MRPL40,UFD1,GP1BB,TBX1,GNB1L,TXNRD2,COMT,ARVCF,DGCR8,ZDHHC8,RTN4R	-0.0236046	24.9615	314	193.188
chr22	20609931	24381809	SCARF2,PI4KA,SNAP29,CRKL,MAPK1,VPREB1,BCR,IGLL1,SMARCB1,MIF,GSTT1	-0.561491	24.7861	106	62.7058
chr22	24384062	51244066	GSTT1,CABIN1,GGT5,SPECC1L-ADORA2A,UPB1,PIWIL3,CRYBB3,CRYBB2,GRK3,MYO18B,HPS4,CRYBB1,CRYBA4,MIAT,MN1,CHEK2,XBP1,EWSR1,NEFH,NIPSNAP1,NF2,LIF,TCN2,DRG1,SLC5A1,FBXO7,SYN3,LARGE1,HMOX1,MCM5,APOL3,APOL1,MYH9,TXN2,CACNG2,NCF4,CSF2RB,TST,MPST,TMPRSS6,RAC2,LGALS2,TRIOBP,SOX10,PICK1,PLA2G6,CSNK1E,DMC1,SUN2,APOBEC3B,APOBEC3G,APOBEC3H,PDGFB,SYNGR1,ADSL,MKL1,MCHR1,SLC25A17,XPNPEP3,EP300,ACO2,XRCC6,SREBF2,TNFRSF13C,NAGA,NDUFA6,CYP2D6,CYB5R3,A4GALT,TSPO,SULT4A1,PNPLA3,UPK3A,SMC1B,FBLN1,ATXN10,PPARA,TRMU,CELSR1,BRD1,ALG12,IL17REL,MLC1,TUBGCP6,SBF1,SCO2,TYMP,CHKB-CPT1B,ARSA,SHANK3	-0.0397827	24.912	1473	917.039
```

When I plot log2 values from CNR file which correspond to this segment (which got –0.56 value, like a pretty significant deletion), this is what I get:
![bug](https://user-images.githubusercontent.com/10669118/44864127-8ebb4480-ac87-11e8-9684-f591edfe1e38.png)

It seems like CBS segmentation method (which I believe is used by default?) gets distracted by the really huge drop due to GSTT1 homozygous deletion at the end of the region and produces this strange segment.

Test files to reproduce the behaviour: [bug.zip](https://github.com/etal/cnvkit/files/2336911/bug.zip)

**Comment by etal** [comment]
If you try segmentation with a less stringent p-value, e.g. `cnvkit.py segment -t .001`, does it still combine these two regions? You might also try another segmentation method like `-m flasso`.

**Comment by tskir** [comment]
Yes, indeed, I was able to solve this specific problem by raising p-value
by 5 or 10 times (don't recall exactly) from its default value.  I was
wondering, though, if this problem perhaps might have a more universal and
straightforward solution. After all, even though I can't attach any
statistical rigor to it, this segment produced by default settings just
_feels_ wrong; there must be some way to detect and fix such occurrences
somehow.

**Comment by etal** [comment]
I agree. I'm hoping to get the new HMM-based segmentation methods to perform at least as well as CBS in general and to handle focal alterations like this better. Feel free to try `-m hmm` or `-m hmm-germline` to see if the current implementation is useful on your samples.
