### ISSUE TITLE
different result for diagram with and without cns file

### ISSUE THREAD

**Issue by sky-peng** [etal/cnvkit#387]
Hello
    i'm using cnvkit to call CNV, but i find there is a big difference in the result for diagram when with and without cns file. The command and result is:
with cns file:
`cnvkit.py diagram P10_7056_1.tumor.cnr -s P10_7056_1.tumor.cns -o test.pdf`
![image](https://user-images.githubusercontent.com/34478536/45612168-c18d7700-ba94-11e8-9ceb-efaa4f8b2d12.png)
without cns file
`cnvkit.py diagram P10_7056_1.tumor.cnr -o test1.pdf`
![image](https://user-images.githubusercontent.com/34478536/45612246-fd284100-ba94-11e8-8349-d4023daca9d3.png)

i want to  know if the cns file is must be used?
what' more, when i want to export the result of diagram by commands:
`cnvkit.py genemetrics -s P10_7056_1.tumor.cns P10_7056_1.tumor.cnr -t 0.5 --drop-low-coverage -o test.txt`
i find the result in txt file is different with the result of _diagram.

**Comment by etal** [comment]
The .cns file isn't mandatory. (Neither is the .cnr.)
- With the .cns, the segment means are visualized on the left half of each chromosome image, and the gene labels show the (targeted/annotated) genes on each segment with a mean above some threshold (default 0.5). The same labels will be shown if you provide only the .cns, without .cnr.
- With .cnr but without .cns, there are no segments to visualize so you see only the bin-level log2 ratio values on each chromosome. The gene labels are based on each gene's average log2 ratio, which allows more noise to pass through.

**Comment by sky-peng** [comment]
Thanks for your answer. I have a new question. When i export the result with command ``

**Comment by sky-peng** [comment]
Thanks for your answer. I have two new questions. When i export the result with command ```cnvkit.py genemetrics```
i) I find there are some repeat region with different gene name,such as:
```
patient3        USP17L25        chr4    9326885 9365917 0.663211        350.632 9.10561 52      13.3738 74
patient3        USP17L30        chr4    9326885 9365917 0.663211        350.632 9.10561 52      13.3738 74
patient3        USP17L26        chr4    9326885 9365917 0.663211        350.632 9.10561 52      13.3738 74
patient3        USP17L27        chr4    9326885 9365917 0.663211        350.632 9.10561 52      13.3738 74
patient3        USP17L28        chr4    9326885 9365917 0.663211        350.632 9.10561 52      13.3738 74
patient3        USP17L24        chr4    9326885 9365917 0.663211        350.632 9.10561 52      13.3738 74
patient3        USP17L29        chr4    9326885 9365917 0.663211        350.632 9.10561 52      13.3738 74
```
I want to know how can i filter those result?
ii) there is another stranger things in the result file, for example
```
patient3        FLG     chr1    152278121       152287932       -0.915115       106.2   6.96053 33      7.44269 34
patient3        FLG-AS1 chr1    152285888       152287932       -0.915115       69.7709 1.00763 4       7.44269 34
```
FLG-AS1 is a non-coding RNA and it's region(chr1:152285888-152287932) belongs to FLG(chr1:152278121-152287932), i can't understand why FLG-AS1 should be exported by ```genemetrics``` ?
