### ISSUE TITLE
Wrote access.bed with 0 regions

### ISSUE THREAD

**Issue by tongta** [etal/cnvkit#388]
Hi,
I'm just trying to use CNVkit to call CNV in A.fumigatus with wgs mode. I found that after using
cnvkit.py access reference.fasta -o access.bed

The result file is empty with this message were showing up
"Wrote reference/Af293_access-10kb.bed with 0 regions"

Do you have any idea about that ?

Thanks guys in advances,
Tongta

**Comment by etal** [comment]
Sorry for the trouble, it sounds like CNVkit was too aggressive in filtering out odd-looking contig names. I'll see about a fix.

**Comment by tongta** [comment]
Thanks Etal, for your reply. Please let me know, if I should do something to fix this problem. :)

**Comment by etal** [comment]
I just pushed a possible fix. If you're able to run the current development version from GitHub, could you try it now?
