### ISSUE TITLE
no chrX found in antitarget files

### ISSUE THREAD

**Issue by ganzj** [etal/cnvkit#389]
this is my command
cnvkit.py reference *coverage.cnn -f /workstation/database/Homo_sapiens/UCSC/hg38/hg38.fa -o reference.cnn
this is report
Number of target and antitarget files: 2, 2
Relative log2 coverage of chrX=-0.0795, chrY=-0.127 (maleness=0.00175 x 58.7 = 0.103) --> assuming female
Relative log2 coverage of chrX=-0.315, chrY=-0.255 (maleness=0.13 x 9.14 = 1.19) --> assuming male
No chrX found in sample; is the input truncated?
No chrX found in sample; is the input truncated?
Loading sample_NF.targetcoverage.cnn
Calculating GC and RepeatMasker content in /workstation/database/Homo_sapiens/UCSC/hg38/hg38.fa ...
Extracting sequences from chromosome chr1
Extracting sequences from chromosome chr2
Extracting sequences from chromosome chr3
Extracting sequences from chromosome chr4
Extracting sequences from chromosome chr5
Extracting sequences from chromosome chr6
……
Extracting sequences from chromosome chr22_KI270876v1_alt
Extracting sequences from chromosome chr22_KI270877v1_alt
Extracting sequences from chromosome chr22_KI270878v1_alt
Extracting sequences from chromosome chr22_KI270879v1_alt
Extracting sequences from chromosome chr22_KI270928v1_alt
Correcting for GC bias...
Correcting for density bias...
Loading target sample_NM.targetcoverage.cnn
Traceback (most recent call last):
  File "/home/ganzj/anaconda3/envs/cnvkit/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/ganzj/anaconda3/envs/cnvkit/lib/python2.7/site-packages/cnvlib/commands.py", line 514, in _cmd_reference
    args.do_rmask)
  File "/home/ganzj/anaconda3/envs/cnvkit/lib/python2.7/site-packages/cnvlib/reference.py", line 55, in do_reference
    do_gc, do_edge, False)
  File "/home/ganzj/anaconda3/envs/cnvkit/lib/python2.7/site-packages/cnvlib/reference.py", line 237, in combine_probes
    % (fname, filenames[0]))
RuntimeError: sample_NM.targetcoverage.cnn bins do not match those in sample_NF.targetcoverage.cnn

could you help me if you have any ideas, thank you !!!

**Comment by etal** [comment]
- How were these samples sequenced -- whole genome, exome, or target panel?
- Were these samples all originally process with the same BED file when you ran `cnvkit.py coverage`?
- Which version of CNVkit are you using?
- Have you tried the `batch` command? It's usually the quickest way to [get started](https://cnvkit.readthedocs.io/en/stable/quickstart.html).
