### ISSUE TITLE
Anconda3 installation error

### ISSUE THREAD

**Issue by xiucz** [etal/cnvkit#394]
hi, etal

After my installation,
```
$ conda create -n cnvkit cnvkit
$ source activate cnvkit
```

Error stills:
```
(cnvkit)$ cnvkit.py 
~/software/Anaconda3/envs/cnvkit/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

Traceback (most recent call last):
  File "~/software/Anaconda3/envs/cnvkit/bin/cnvkit.py", line 13, in <module>
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```
In readme document, I find python3 is attainable to cnvkit installation. But in my situation, it is not.
Can you help me ?

**Comment by etal** [comment]
Is this with Python 3.7 inside Anaconda?

**Comment by xiucz** [comment]
Hi,
Yes, I used Python 3.7.And more, I tried with python2 , this error also appears.

If I type ```$ cnvkit.py ```, it will throw an error likes above. But if I add some parameters, eg.```$ cnvkit.py  -h``` or ```$ cnvkit.py batch []```, it works.

Thank you @etal, and I will close it.
