### ISSUE TITLE
genemetrics error?

### ISSUE THREAD

**Issue by andyjslee** [etal/cnvkit#395]
I ran the genemetrics command using cnvkit. I get multiple rows for the same gene. The problem is that I get different copy numbers ('cn' column) for different parts of the gene. Is this the correct behavior from CNVkit? From what I understand, there should only be one row for each gene. Thank you for your clarification/help as always.

**Comment by etal** [comment]
If you provide a .cns file as input to `genemetrics`, you'll see multiple lines for a gene if segmentation put one or more breakpoints within the gene -- a separate line for each segment overlapping that gene. That's realistic if e.g. a few exons of the gene were deleted, but not the whole gene.

To ignore segmentation get just an average copy ratio across the gene, run `genemetrics` with just the .cnr input, not the .cns.
