### ISSUE TITLE
Increase of antitarget regions when provide access bed.

### ISSUE THREAD

**Issue by thisisi3** [etal/cnvkit#396]
When provide access bed, antitarget gives more regions than not provide access.

Here is the test
test.bed
chr1    100000  200000
chr1    1000000 1200000
chr1    2000000 2300000

test.access.bed
chr1    500000  1100000
chr1    1400000 1600000
chr1    3000000 3500000

cnvkit.py antitarget test.bed --access test.access.bed -o test.access.antitarget.bed

test.access.antitarget.bed
chr1    500500  666833  Antitarget
chr1    666833  833166  Antitarget
chr1    833166  999500  Antitarget
chr1    1400500 1599500 Antitarget
chr1    3000500 3166833 Antitarget
chr1    3166833 3333166 Antitarget
chr1    3333166 3499500 Antitarget

It adds regions beyond 3000000 which is not included in the antitarget of original test.bed. 

Notice that I am using release version 0.9.5 to produce this result, the most recent commit gives a different result but with similar issue.

**Comment by etal** [comment]
Thanks for letting me know, I'll look into it.

**Comment by thisisi3** [comment]
After looked at source code and did some tests, it seems the definition of antitarget is "any region that is accessible and not within target". Correct me if I am wrong.

**Comment by etal** [comment]
Yes, that's right.
