### ISSUE TITLE
Pipeline documentation: `batch` doesn't include `access`

### ISSUE THREAD

**Issue by romagnolid** [etal/cnvkit#399]
I think this passage from https://cnvkit.readthedocs.io/en/v0.9.5/pipeline.html#batch is a little misleading:
> The pipeline executed by the batch command is equivalent to:
> 
>     cnvkit.py access hg19.fa -o access.hg19.bed
>     cnvkit.py autobin *.bam -t baits.bed -g access.hg19.bed [--annotate refFlat.txt --short-names]
>
>     # For each sample...
>     cnvkit.py coverage Sample.bam baits.target.bed -o Sample.targetcoverage.cnn
>     cnvkit.py coverage Sample.bam baits.antitarget.bed -o Sample.antitargetcoverage.cnn
and so on.

For what I understood users can optionally create the access BED file and pass it to `batch` with `-g/--access FILENAME` but simply running `batch` will not include the accessible region file.

**Comment by etal** [comment]
If you run `batch` with a reference genome FASTA sequence, but no access BED, then it will internally run `access` on the fly using the given FASTA and treat the result of that step as the access BED.

Running `access` separately gives you the option to exclude additional BED regions, and tweak some other parameters. In absence of that, `batch` generally does the reasonable thing given the information it's been given.

**Comment by romagnolid** [comment]
Oh I see, thanks for the clarification then
