### ISSUE TITLE
Which annotation tool can I use to annotate the found variants?

### ISSUE THREAD

**Issue by cnizo** [etal/cnvkit#400]
I would like to annotate any variants found after running cnvkit.py with my samples. At first, I used cnvScan (https://github.com/PubuduSaneth/cnvScan) but the output is a little odd and I thought that it might not be suitable for cnvkit.

Does anyone know if I can use cnvScan with cnvkit? And if not, which tool is recommended?

**Comment by etal** [comment]
I'm not familiar with cnvScan, but someone else on Biostars might be:
https://www.biostars.org/
