### ISSUE TITLE
female samples still plot Y chromosome

### ISSUE THREAD

**Issue by mheskett** [etal/cnvkit#405]
cnvkit prints "treating sample X as female" but then still includes Y chromosome on heatmap plots. We know that Y chromosome reads in a female sample are spurious so the Y should be excluded from the plot.

**Comment by mheskett** [comment]
cnvkit.py heatmap -x female should not include Y.
XXY is called Klinefelter Syndrome which happens in males not females, and
this is a rare disease in the population. In a cancer study where I know
there is a female patient we should exclude Y from the plot.

**Comment by etal** [comment]
In this case where you know the sample is strictly XX, and you're only plotting XX samples together in this heatmap, then I'd recommend filtering out the chrY lines in the .cns file before plotting. You can do this with e.g. `grep -v '^chrY' < sample.cns > sample.no-y.cns`.

In general I would not recommend dropping chrY without having looked at the sample first, but for creating the final figure, feel free to manipulate the .cns files however you need, and CNVkit will plot what you give it.
