### ISSUE TITLE
question about count-reads argument

### ISSUE THREAD

**Issue by desnar** [etal/cnvkit#411]
Hi,
    I find the results are different in some regions with/without count-reads argument. when I check the source code at cnvlib/coverage.py, the difference may be caused by using query_length instead of query_alignment_length to calculate read depth in region_depth_count function.  After I use the query_alignment_length, the results are similar. It seems that query_length  is wrong for reads with softclips.

**Comment by etal** [comment]
Thanks for investigating this. The count-reads option was originally a fallback for when samtools bedcov wasn't available, so I hadn't benchmarked it much. I'll change it as you suggested.
