### ISSUE TITLE
rmask column not present in reference.cnn

### ISSUE THREAD

**Issue by Marmach** [etal/cnvkit#414]
Hi

I have a short question regarding .cnn reference file. Is it possible, that in some cases the "rmask" column would be automatically removed (or rather: not included in) from the reference.cnn?

In all my references (custom and exome panels) rmask has any data only for rows for _antitarget_ regions. Since I wanted to compare segmentation for samples sequenced with multiple panels, I created a bed file with shared coordinates and I manually removed antitarged regions before using _reference_ function (because otherwise the targeted regions would be treated as part of antitarget). The resulting reference.cnn obviously has no antitarget regions, still has _gc_ column, but _rmask_ column is absent. This is logical, given that the column would be empty anyway (since only _antitarget_ rows have data for _rmask_), but still it's a bit surprising.

So I just wanted to ask whether this is normal or not and whether it might have some negative impact on the results...

Thanks

**Comment by etal** [comment]
Yes: The `rmask` value is only calculated for off-target bins. In target panels, the targets are usually so small that the `rmask` value would always be either 0.0 or 1.0 (all bases repeat-masked or none), which was not helpful for normalization. So if you removed off-target bins, or ran an amplicon sequencing sample through CNVkit without any off-target bins to begin with, you'd see an empty or missing `rmask` column. CNVkit knows about this possibility and will handle it safely, but it could complicate your own scripts a little.
