### ISSUE TITLE
CNVkit.py v0.9.6.dev0 Overlapping bins and segments

### ISSUE THREAD

**Issue by cplaisier** [etal/cnvkit#416]
Using version 0.9.6.dev0 and with exome sequencing data aligned with BWA to hg19. Then used retrieved the bait sequences from Agilent directly. Then used the access-5k-mappable.hg19.bed from the CNVkit data directory. Also used refFlat.txt for hg19. And the fasta file from the BWA alignment.

The issue is that when I try to use the segmented files for GISTIC2 analysis it tells me there are 2770 overlaps. And give me the point where the first overlap occurred. The segmentation gives me overlapping segments like this:

5141273TUMOR_sorted	chr4	70491972	80857752	1191	0.314406
5141273TUMOR_sorted	chr4	80828353	82088528	77	-0.0356951

Which corresponds to these bins in the '.cnr' file:

chr4	80328133	80328415	GK2	210.773	0.334783	0.607423
chr4	80328415	80328696	GK2	158.384	0.098299	0.627247
chr4	80328696	80328978	GK2	162.709	0.23058	0.626979
chr4	80329016	80329337	GK2	160.202	0.261431	0.65096
chr4	80407337	80557475	Antitarget	0.714529	0.161566	0.53985
chr4	80557475	80707614	Antitarget	0.0996144	-0.21541	0.37313
chr4	80707614	80857752	Antitarget	0.551613	0.41329	0.503544
chr4	80828352	80828748	ANTXR2	122.121	0.00975948	0.710582
chr4	80857752	81007890	Antitarget	4.88554	0.0312667	0.388514
chr4	80898603	80898882	ANTXR2	92.2545	-0.245449	0.664513
chr4	80898882	80899161	ANTXR2	99.3728	0.224468	0.701616
chr4	80899161	80899441	ANTXR2	155.311	0.000773197	0.61125
chr4	80904874	80905241	ANTXR2	111.153	0.355338	0.706001

Saw previous issues with potential overlapping baits in the bait bed file and so ran bedtools merge on the file. Reran the whole pipeline and same issue. So I don't think it will be that easy of a fix. This seems programmatic to me. Also tried running --split on the cnvkit.py target generation step, and that output file looks exactly like the "target" file in the output directory. So don't think that will help either.

It seems to me like there is an exon overlap between the segments. Think that somehow the segmentation software has an off by one issue, or a padding issue. Can you please advise?

**Comment by cplaisier** [comment]
Just downgraded to 0.9.5 to see if the same issue continues. Installed via conda install using python 2.7.

**Comment by cplaisier** [comment]
Full command used is:

cnvkit.py batch bam/*TUMOR_sorted.bam --normal bam/*NORMAL_sorted.bam --targets S04380110_Padded_merged.bed --annotate refFlat.txt --fasta ../bwaHg19/hg19.fa --access access-5k-mappable.hg19.bed --output-reference hg19_Bueno.cnn --output-dir CNVkit_merged_0.9.5 --diagram --scatter -p 12 --drop-low-coverage

**Comment by etal** [comment]
Thanks for the details. This might be related to issue #375 , where the `target --split` step wasn't doing anything. I'll investigate.

**Comment by etal** [comment]
It looks like this is fixed in the current development version. I've added a unit test to confirm.
