### ISSUE TITLE
Naive question about normalization for varying  total reads

### ISSUE THREAD

**Issue by jeremy9959** [etal/cnvkit#417]
I am trying to analyze a large group of low-coverage WG sequences from single cells, in order to use copy number to cluster them.  I'd like to understand how cnvkit normalizes for the differences in total reads among the various samples.  Probably this is obvious but I would appreciate a tip on where to look.

**Comment by etal** [comment]
In short, the read depths are binned into roughly equal-sized genomic regions, and each bin's depth is divided by the genome-wide average depth to get a ratio (which is then converted to log2 scale for convenience). There are more normalization step after that, so the initial calculation of log-ratio coverage depths is a minor detail in most of the descriptions you see.

Full details in the paper: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004873

**Comment by jeremy9959** [comment]
OK I think I was making this more complicated than it actually is, thanks.
