### ISSUE TITLE
Question regarding CNVkit's handling of segment re-centering after CBS

### ISSUE THREAD

**Issue by MUppal** [etal/cnvkit#418]
I had a question regarding CNVkit's use of CBS as implemented by DNAcopy. I have been using DNAcopy in a workflow including VarScan's copynumber and copyCaller commands. The instructions for that tool, when integrated with DNAcopy, suggest visualization and manual readjustment of the segments output by CBS should the values show systematic deviation from 0.0 (http://varscan.sourceforge.net/copy-number-calling.html). I was wondering if CNVkit included an automatic re-centering in these situations. I read through the docs for your tool, but did not come across any language that explicitly answered this question.

**Comment by etal** [comment]
The basic pipeline run by the `batch` command does not re-center the segments; it centers the probes before segmentation and so it's possible in samples with skewed noise for the segments to be systematically off-center. In these cases (and pretty much all cases) you can use the `call --center` command to re-center the segments.

Some details here: https://cnvkit.readthedocs.io/en/stable/pipeline.html#transformations

**Comment by MUppal** [comment]
@etal , sorry for re-opening the issue. Thank you very much for letting me know about the call --center feature. I'm looking to export segments from CNVkit to Gistic. I am using the following three commands:

cnvkit.py batch $tumor --normal $normal --targets Haloplex_Regions.b37.txt --annotate refFlat.txt --fasta $ref --output-reference my_reference.cnn --output-dir results/ --diagram --scatter --access access-5k-mappable.grch37.bed
cnvkit.py call -m none tumor.cns --center mode
cnvkit.py export seg *.cns -o gistic.segments

Is this appropriate to apply to each sample? Even if a sample has minimal to zero skewed noise, the call --center command shouldn't alter the segments substantially, correct? Therefore, the above 3 commands ought to suffice to obtain single-sample segments that are centered and ready to be fed into GISTIC?

**Comment by etal** [comment]
It is fine to run those steps on every sample, although `--center mode` is a little risky to do unsupervised. (What if small deletions are very common?) I recommend `--center median` as a safer option.

**Comment by MUppal** [comment]
Hi @etal, quick follow-up question regarding the call command. I obtain a .cns file with absolute copy number estimation using the following command: cnvkit.py call tumor.call.cns -o tumor.call.cn.cns

The resulting file gives the "cn" column, with integer values >= 0. Am I correct in assuming this means the ploidy of that segment? Like cn =1 for a segment corresponds to a haploid segment, cn = 2 is normal diploid, cn = 3 is a copy number gain, etc.? I ask because other tools my group have used report gains, deletions, or normal ploidy as as +1, -1, or 0, etc.

**Comment by etal** [comment]
Yes, that's the ploidy of each segment. This way, CNVkit's results are meaningful for non-diploid cells/organisms, too.
