### ISSUE TITLE
R Installation Instructions Outdated

### ISSUE THREAD

**Issue by DarioS** [etal/cnvkit#419]
Bioconductor has deprecated the `biocLite` function as the method of package installation, It's now

```r
library(BiocManager) # Get it from CRAN.
install(c("DNAcopy", "cghFLasso"))
```

The README file ought to be changed.

**Comment by DarioS** [comment]
Also, the installation of cghFLasso fails because it has been abandoned by its developer and CRAN has removed it from its web service.

>Warning message:
package ‘cghFLasso’ is not available (for R version 3.5.2)

> Package ‘cghFLasso’ was removed from the CRAN repository.

**Comment by etal** [comment]
Good to know, thanks.

I'll remove `cghFlasso` from the next release. It may still be available through `conda`, I haven't checked that recently.

**Comment by elcinchu27** [comment]
Hi @etal can you please update the documentation of the available segmentation methods?
The stable version shows the [flasso](https://cnvkit.readthedocs.io/en/stable/pipeline.html#segmentation-methods)
Maybe like write a warning that the package is no longer available in newer versions?
Thanks
