### ISSUE TITLE
Selecting reference samples for germline hybrid capture sequencing data

### ISSUE THREAD

**Issue by ahwanpandey** [etal/cnvkit#422]
Hello,

Thanks so much for CNVkit! I am hoping I can use the tool as intended for a large project that we are commencing at the lab.

The project is a long running one and will have thousands of samples, all female, that will be sequenced in batches as the data is collected. They will all be blood and the library prep and target enrichment is done using [Agilent-SureSelectXT-HS] for a panel of just over a hundred genes. 

So far we have collected about 600 samples. The coverage is quite variable per run and looks like the following:
![image](https://user-images.githubusercontent.com/8450532/53844675-95da5b00-3ffa-11e9-86f8-df041b356cbf.png)

Do you have any suggestions on how we should go about selecting samples for the reference? What are the main sample statistics that we should look at and what would be a typical workflow from reference generation to copy number calling? Also, there will be many more runs in the future and we will probably need to update the reference occasionally?

Thanks so much for your advice!

**Comment by ZKai0801** [comment]
Sorry to barge in your questions... @ahwanpandey 
Actually, I have a similar problem regarding coverage differences between normal and tumour samples.
 
So I got a bunch of matched normal/tumour pairs, and the normal samples had very low sequence depth compared with tumour samples. Is there a good way to compensate this differences when I make the reference?

Thank you suggestion in  advance! @etal

**Comment by ahwanpandey** [comment]
Hi @etal ,

I was wondering if I could get some pointers from you about this?

Thanks.

**Comment by etal** [comment]
See pointers for reference construction [here](https://cnvkit.readthedocs.io/en/stable/pipeline.html#paired-or-pooled-normals). If you see outliers under any of the statistics reported by the `metrics` command, and you have samples to spare, then I suggest removing those from your reference pool. Otherwise leave them all in.

Some variation in overall coverage across control samples and between control vs. test samples is fine. CNVkit normalizes the samples before pooling to create the reference profile. As for how much variation/difference is too much, the only way to know for sure is to try it and see. Processing doesn't take that long, and you will eventually need to validate your assay in any case.

**Comment by ahwanpandey** [comment]
Hi @etal . Sorry for this long post, but I just wanted to make sure that I am not missing anything.

**Here are some facts about the data:**

1) The capture kit is [Agilent-SureSelectXT-HS] panel with 150 genes.
2) Some genes, like BRCA1 have extra probes on them for higher coverage.
3) These are all blood samples.
4) We are interested in single EXON-LEVEL germline copy number.

A test sample we have out of the 647 samples has a germline BRCA1 exon3 deletion that we can check. So far, I have also run the zscore test script and this exon is not detected even for varying values of alpha.

![image](https://user-images.githubusercontent.com/8450532/54648397-300dc900-4afa-11e9-9761-c1000988266f.png)

**I have done the following steps using all the defaults:**

1) generate target coverage per sample
2) generate antitarget coverage per sample
3) generate reference using all samples
4) fix and  segment data
5) generate metrics

I have 647 samples from different runs but using the same library prep and capture kit. If I sort the metrics data using stddev, the scatter of the lowest and the highest valued samples look like the following:

**LOWEST**

segments | stdev | mad | iqr | bivar
-- | -- | -- | -- | --
54 | 0.209352 | 0.186273 | 0.251355 | 0.196288

![image](https://user-images.githubusercontent.com/8450532/54647586-22a30f80-4af7-11e9-91a5-a44ea9dc876f.png)

**HIGHEST**

segments | stdev | mad | iqr | bivar
-- | -- | -- | -- | --
107 | 3.4125 | 1.54813 | 2.09103 | 1.42854

![image](https://user-images.githubusercontent.com/8450532/54647741-d6a49a80-4af7-11e9-96ae-c6db3f02e853.png)

**And something in between**

segments | stdev | mad | iqr | bivar
-- | -- | -- | -- | --
81 | 0.54073 | 0.388812 | 0.528219 | 0.408786

![image](https://user-images.githubusercontent.com/8450532/54647786-08b5fc80-4af8-11e9-9469-86e383a3a32e.png)

**I have also generated a plot that contains every possible metric I could think of across the runs:**

![image](https://user-images.githubusercontent.com/8450532/54647882-5468a600-4af8-11e9-8182-72a9bf7883a1.png)

**Also, here are the ranges of the different metrics:**

```
> range(data_$stdev)
[1] 0.209352 3.412500

> range(data_$mad)
[1] 0.183033 1.548130

> range(data_$iqr)
[1] 0.246978 2.091030

> range(data_$bivar)
[1] 0.196288 1.428540

> range(data_$MEAN_COVERAGE)
[1]   37.89 2846.62
```

### Finally, about off target bin size:

For all the analysis so far I have stuck with the defaults of the tools. But I was also checking what bin size would be appropriate for my data. I found this on the tutorial:

> An appropriate off-target bin size can be computed as the product of the average target region size and the fold-enrichment of sequencing reads in targeted regions, such that roughly the same number of reads are mapped to on– and off-target bins on average — roughly proportional to the level of on-target enrichment. The autobin command (below) can quickly estimate these values, but you are free to specify your own.

So running autobin gives:

```
# Detected file format: bed
# Detected file format: bed
# Estimated read length 74.0
# Wrote /tmp/tmpVP3Tkn.bed with 100 regions
# Limiting est. bin size 1156805 to given max. 500000
# Splitting large targets
# Wrote biol_probes_3141871.target.bed with 3295 regions
# Wrote biol_probes_3141871.antitarget.bed with 6507 regions
                # Depth   Bin size
# Target:         788.795 127
# Antitarget:     0.086   500000

```

**Also, for a few samples, here is the output of the coverage command using defaults:**

```
TARGET: Summary: #bins=2045, #reads=2825429, mean=1381.6280, min=0.0, max=7779.743243243243
TARGET: Percent reads in regions: 26.374 (of 10712779 mapped)
ANTITARGET: Summary: #bins=18964, #reads=2089127, mean=110.1628, min=0.0, max=91489.95945945945
ANTITARGET: Percent reads in regions: 19.501 (of 10712779 mapped)

TARGET: Summary: #bins=2045, #reads=2706443, mean=1323.4442, min=0.0, max=7405.324324324324
TARGET: Percent reads in regions: 26.724 (of 10127522 mapped)
ANTITARGET: Summary: #bins=18964, #reads=1886862, mean=99.4971, min=0.0, max=77186.2972972973
ANTITARGET: Percent reads in regions: 18.631 (of 10127522 mapped)

TARGET: Summary: #bins=2045, #reads=2793443, mean=1365.9870, min=0.0, max=6948.472972972973
TARGET: Percent reads in regions: 26.640 (of 10486063 mapped)
ANTITARGET: Summary: #bins=18964, #reads=1910998, mean=100.7698, min=0.0, max=85616.6081081081
ANTITARGET: Percent reads in regions: 18.224 (of 10486063 mapped)

TARGET: Summary: #bins=2045, #reads=2094141, mean=1024.0298, min=0.0, max=5031.324324324324
TARGET: Percent reads in regions: 23.425 (of 8939731 mapped)
ANTITARGET: Summary: #bins=18964, #reads=1855452, mean=97.8408, min=0.0, max=55791.22972972973
ANTITARGET: Percent reads in regions: 20.755 (of 8939731 mapped)

TARGET: Summary: #bins=2045, #reads=2023046, mean=989.2649, min=0.0, max=5941.648648648648
TARGET: Percent reads in regions: 27.894 (of 7252746 mapped)
ANTITARGET: Summary: #bins=18964, #reads=1480135, mean=78.0498, min=0.0, max=43359.04054054054
ANTITARGET: Percent reads in regions: 20.408 (of 7252746 mapped)

TARGET: Summary: #bins=2045, #reads=1546452, mean=756.2115, min=0.0, max=4485.189189189189
TARGET: Percent reads in regions: 42.136 (of 3670133 mapped)
ANTITARGET: Summary: #bins=18964, #reads=1120630, mean=59.0925, min=0.0, max=19327.067567567567
ANTITARGET: Percent reads in regions: 30.534 (of 3670133 mapped)

TARGET: Summary: #bins=2045, #reads=1149241, mean=561.9761, min=0.0, max=3564.689189189189
TARGET: Percent reads in regions: 52.116 (of 2205159 mapped)
ANTITARGET: Summary: #bins=18964, #reads=490095, mean=25.8435, min=0.0, max=13804.472972972973
ANTITARGET: Percent reads in regions: 22.225 (of 2205159 mapped)

TARGET: Summary: #bins=2045, #reads=1881543, mean=920.0700, min=0.0, max=6480.986486486487
TARGET: Percent reads in regions: 50.251 (of 3744281 mapped)
ANTITARGET: Summary: #bins=18964, #reads=692698, mean=36.5270, min=0.0, max=23899.64864864865
ANTITARGET: Percent reads in regions: 18.500 (of 3744281 mapped)

TARGET: Summary: #bins=2045, #reads=1388869, mean=679.1536, min=0.0, max=4914.527027027027
TARGET: Percent reads in regions: 44.267 (of 3137478 mapped)
ANTITARGET: Summary: #bins=18964, #reads=815881, mean=43.0226, min=0.0, max=16487.054054054053
ANTITARGET: Percent reads in regions: 26.004 (of 3137478 mapped)

TARGET: Summary: #bins=2045, #reads=1086280, mean=531.1885, min=0.0, max=3924.891891891892
TARGET: Percent reads in regions: 49.296 (of 2203600 mapped)
ANTITARGET: Summary: #bins=18964, #reads=603980, mean=31.8488, min=0.0, max=14028.662162162162
ANTITARGET: Percent reads in regions: 27.409 (of 2203600 mapped)
```

As you can see, if I use the formula (target_mean/antitarget_mean), the factor would be more than 10x and the effective antitarget size would be 150,000 * 10 = 1,500,000. This seems too large and I haven't seen an example anywhere yet that uses such a large antitarget region.

Do you see any caveats about the type of data I have and the analysis I have done? I think my next step is to remake the reference using "good" samples based off of all the metrics. I am leaning towards anything with (stddev < 0.5) which would give me (278/647 samples) to work with.

Any input from you regarding the analysis of these samples would be very appreciated.

**Comment by etal** [comment]
@ahwanpandey, what you are experiencing here is perfectly normal and in general you seem to be on the right track. Your assay has unusually high capture efficiency, so there aren't many off-target reads to work with. You could try an off-target bin size of 1MB or 1.5MB just to see how it goes; it might work all right. This isn't a critical parameter because CNVkit automatically down-weights antitarget bins if they generally are more variable than the on-target bins, i.e. the effect is similar to if you had subdivided the regions more finely to get a larger number of noisier bins, versus coarse binning to get a smaller number of less-noisy bins. If you use `scatter -c` to look at a smaller chromosomal region you may be able to see whether on- and off-target bins have similar variability.

If you are launching a larger genomic testing service and would like some direct assistance, I can't provide that here, but it can be reasonably efficient to go through [my employer](http://go.dnanexus.com/l/457982/2018-05-23/6v4h43) for consulting.

**Comment by etal** [comment]
For single-exon testing, I suggest looking at the script `cnv_ztest.py`. There are some improvements in the development version of CNVkit that you may find useful.
