### ISSUE TITLE
Calculating p-value from z-score (cnvkit_ztest.py)

### ISSUE THREAD

**Issue by YiJessePi** [etal/cnvkit#429]
I'm afraid that there is a bug in calculating p values from z-score.
I suspect that in ztest,py line 53 should be 
p = 2. * norm.cdf(-abs(z)) 
instead of 
p = 2. * norm.cdf(z)
To cover well the cases that z score is positive.
Can you check this out?

Additionally, I'll be very grateful if you could please explain why does the sd is  sqrt(1 - weight)

 Thanks

**Comment by etal** [comment]
Thanks for catching that! I've fixed it in the code.

The weights are initially set to be approximately `1 - variance`, using a few different [approaches to estimate variance](https://github.com/etal/cnvkit/blob/master/cnvlib/fix.py#L253), under the assumption that read depths are Poisson distributed (so approximately log-normal for reasonable sequencing depths, so log-ratios are approximately normal). It gets a little hacky to deal with some edge cases and practicalities, but that's the underlying rationale. Therefore `sd = sqrt(1 - (1 - variance))`.

**Comment by etal** [comment]
Since you mentioned it, I've adjusted the rest of the weight calculation to be more consistent in maintaining the `weight = 1-variance` interpretation. This may improve the results downstream if you run the latest development version of CNVkit.
