### ISSUE TITLE
Should I use the precomputed “access” file?

### ISSUE THREAD

**Issue by FrankFeng** [etal/cnvkit#432]
I am using cnvkit on human WGS tumor samples, in which there are known very large CNVs (e.g. the CNV of a whole chromosome or chromosome arm). The main purpose of using cnvkit is to confirm and prove the existence of those very large CNVs. In my case, should I use the access-5k-mappable.grch37.bed file provided by cnvkit with low-mappability regions excluded? If using that precomputed “access” file, will it break a large CNV into too many relatively small calls?

Many thanks!

**Comment by etal** [comment]
Using the precomputed access BED file for your reference genome won't break the CNVs into small calls. Instead, it will just ignore the masked-out regions, and copy number segments will generally span across the gaps.
