### ISSUE TITLE
cap/ceiling issue with log2 ratio 

### ISSUE THREAD

**Issue by laopp** [etal/cnvkit#433]
Hi, 

I used the 'rna-import' function to predict CNV on RNA expression data, and below is the code:
cnvkit.py import-rna *.txt -n ./normal/*.txt --gene-resource ensembl-gene-info.hg38.tsv --correlation tcga-skcm.cnv-expr-corr.tsv --output out-summary.tsv --output-dir .

The scatter plot looks like there is a cap at log2 ratio of 3 at the top, and a lot bins have around -5.5 log2 ratio at the bottom. I tried removing -n normalization, and the cap is still there. The RNA input is a simple 2-column, tab-delimited file with Ensembl IDs and per-gene read counts. I checked the genes/bins that have log2 ratio of 3, it seems that they are not specific to one sample, but rather present in most samples. And they are evenly distributed on the genome. Our RNA expression data is generated by 3'-end sequencing, in which sequencing will proceed directionally toward the poly-A tail. Any ideas of why it happens?

thanks!
Peipei
![image](https://user-images.githubusercontent.com/39168066/55919730-e91c6c00-5bab-11e9-8d5b-5a8ffdc1c674.png)

This is the distribution of the RNA expression data. x-axis is the read counts. A large amount of genes have 0 count. 
![image](https://user-images.githubusercontent.com/39168066/55919720-e3268b00-5bab-11e9-8421-fbf2b9762fbc.png)

**Comment by etal** [comment]
Yes, you can change this with the option `cnvkit.py import-rna --max-log2` (e.g. give it a larger number to remove the cap). The default cap is there to limit the impact a single highly expressed gene can have on the result, since this method is meant to find large, multi-gene CNAs. It's more likely that a gene's high expression >8x above baseline is due to that gene's regulation rather than being part of a multi-gene CNA.

**Comment by laopp** [comment]
thanks for your quick response! That makes sense. Can I also set a cap for the min-log2? Some segments are driven by the very low expression as well.

**Comment by etal** [comment]
If the option is present in CNVkit 0.9.5, then it should work the same there. Otherwise, you can edit the currently installed code on your own system here:
https://github.com/etal/cnvkit/blob/master/cnvlib/commands.py#L1561
