### ISSUE TITLE
Support CRAM input

### ISSUE THREAD

**Issue by etal** [etal/cnvkit#434]
Ensure all parts of CNVkit can accept CRAM files wherever BAM is currently used/specified.

HTSlib/samtools/pysam can handle CRAM already, so no major internal changes should be needed.

However, ".bam" and ".bai" suffixes are hard-coded in some places, for example, and these should be generalized to accept and use .cram + .crai equivalently.

**Comment by fgvieira** [comment]
It would be really nice if CNVkit would support CRAM files.
Do you have any plans for implementing it anytime soon?
thanks,

**Comment by etal** [comment]
Done in #495 -- thanks to @sridhar0605
