### ISSUE TITLE
kmax parameter in cbs methods in segment functionality

### ISSUE THREAD

**Issue by EwaMarek** [etal/cnvkit#435]
Hi,

I was wondering if there is a possibility to add kmax parameter to the cbs algorithm in cnvkit.py segment functionality, so that a user can choose different than default one?

Best wishes,
Ewa

**Comment by etal** [comment]
Maybe, what does that parameter do and what other value do you want to use there?

If you're not sure it will be useful and just want to see what happens, try modifying the source code here to add that parameter:
https://github.com/etal/cnvkit/blob/master/cnvlib/segmentation/cbs.py#L21-L24

**Comment by EwaMarek** [comment]
Sorry for late answer. It seems that playing around this parameter may increase CNV call sensitivity. DNAcopy documentation says that kmax is _"the maximum width of smaller segment for permutation in the hybrid method"_. 

However, after digging a little bit more one may find an article: 
Venkatraman, E. S., and Adam B. Olshen. "A faster circular binary segmentation algorithm for the analysis of array CGH data." Bioinformatics 23.6 (2007): 657-663. 
in which authors say that _"We recommend that k be set at 25 for m smaller than 1000 and be increased in increments of 5 as the number of markers doubles."_

After reading this article, for me it seems that changing this kmax parameter may affect how the p-value is calculated. It doesn't seem to be the best idea to increase sensitivity cause obviously it will decrease the specificity. Sorry for the confusion, I believe that this issue may be closed now.
