### ISSUE TITLE
add purity into wgs data

### ISSUE THREAD

**Issue by wentgithub** [etal/cnvkit#438]
hi, thanks for your powerful software.
you give a detail description of how to use cnvkit for hybrid capture and Targeted Amplicon Sequencing (TAS), it has a good relationship with the THetA, I mean it can merge purity data.

but it seems that for wgs data, there is not a example how to connect to THetA, can there has an example, thanks a lot

**Comment by wentgithub** [comment]
another question,
do you recommend use other software to calculate purity. 
and use the batch mode to do wgs TAS hybrid data, then use cnvkit.py call -p purity
to do the task.

thanks a lot

**Comment by etal** [comment]
1. I think the approach for feeding CNVkit segments to THetA should work for WGS, too. Is there a reason it doesn't work?
2. I recommend [PureCN](https://github.com/lima1/PureCN) for estimating purity and ploidy. The resulting estimates from PureCN will work with CNVkit's `call` command for post-processing.
