### ISSUE TITLE
GitHub description out of date(?)

### ISSUE THREAD

**Issue by HenrikBengtsson** [etal/cnvkit#440]
Page https://github.com/etal/cnvkit says "Copy number variant detection from **targeted** DNA sequencing" at the very top.  Maybe update this to "CNVkit: Genome-wide copy number from high-throughput sequencing" to align with https://cnvkit.readthedocs.io/en/stable/.

**Comment by etal** [comment]
Thanks, it now says: "A command-line toolkit and Python library for detecting copy number variants
and alterations genome-wide from high-throughput sequencing."
