### ISSUE TITLE
genemetrics- difference between versions etc.

### ISSUE THREAD

**Issue by YiJessePi** [etal/cnvkit#441]
Hi,
I've used genemetrics in order to identify targeted genes with copy number gain or loss. I do have some issues and questions and will be very grateful if you could please help me solve them:

1) I find huge differences in the number of reported genes when using the last cloned github version and the pip version (47 genes in the pip version vs 2 in the git version). Even when modifying the thresholds (-t and -m) to zero the pip version reports all the 150 genes in my panel but the last git version reports only 7. I have to say that  I prefer to use the last git version since the modifications in bin test and the weights.

2) I want to use the copy-number estimation in the gene level. Is there any problem to pipe the genemetrics output to  the call command. Something like:
cnvkit.py genemetrics sample.cnr -s sample.cns | cnvkit.py call /dev/stdin -o genemetrics.call.txt

3) When calling the bintest command it somehow outputs the cns file and not the bins file with p value. (which seems to work fine when sending it only the cnr file).

4) Is there a way to annotate also the anti-targets by the ref-flat file ( I can annotate them by myself but wondering how it will affect downstream analysis), or maybe just adding the annotation of genes per segments?

Best!

**Comment by etal** [comment]
1. To confirm, is the development code on git giving more correct results than the stable pip version? There have been some major changes in the development version that I hope to tidy up and release soon.
2. The `genemetrics` command is not yet quite up to parity with `call`, but I do plan to add those features (e.g. #278). For now I think you would have to compare the gene-level log2 values to the [`call` cutoffs](https://cnvkit.readthedocs.io/en/stable/pipeline.html#calling-methods) with your own code, or manually.
3. Do you have the very latest code from github? This changed a couple of times during development.
4. I think annotating the final segments the better approach; the "Antitarget" label is handled specially in the pipeline up to that point. The [script `cnv_annotate.py`](cnv_annotate.py
) might do it.
