### ISSUE TITLE
all targeted regions have log2 values less than -5 after run the command cnvkit.py reference

### ISSUE THREAD

**Issue by fyymxb** [etal/cnvkit#443]
Hello，
After i run the command: _cnvkit.py reference *targetcoverage.cnn and*antitargetcoverage.cnn --fasta ucsc.hg19.fasta_, I get a my_reference.cnn file. In this file, all regions have log2 values less than -5 and be filtered, such as:
chromosome      start   end     gene    log2    depth   spread
chr1    11167490        11167610        MTOR    -5.39196        5031.44 0.183657
chr1    11168230        11168350        MTOR    -5.73116        3144.07 0.319241
chr1    11169327        11169447        MTOR    -5.54446        4072.66 0.0424394
chr1    11169686        11169806        MTOR    -5.76796        2987.72 0.373801
chr1    11172881        11173001        MTOR    -5.70061        3280.11 0.273947
chr1    11174330        11174570        MTOR    -5.40291        4955.7  0.167423
chr1    11174847        11174967        MTOR    -5.65666        3486.07 0.208787
But if i randomly choosed some lines of *antitargetcoverage, for example the first 10000 lines, and used this as the new *antitargetcoverage.cnn file, and run the command  _cnvkit.py reference *targetcoverage.cnn and*antitargetcoverage.cnn --fasta ucsc.hg19.fasta_, i can get a proper  my_reference.cnn file, such as:
chromosome      start   end     gene    log2    depth   gc      rmask   spread
chr1    11167490        11167610        MTOR    0.1216  5031.44 0.4
chr1    11168230        11168350        MTOR    -0.0995 3144.07 0.491667
chr1    11169327        11169447        MTOR    0.0333  4072.66 0.416667
chr1    11169686        11169806        MTOR    -0.22085        2987.72 0.441667
chr1    11172881        11173001        MTOR    -0.0123 3280.11 0.508333
chr1    11174330        11174570        MTOR    0.1094  4955.7  0.5375
chr1    11174847        11174967        MTOR    -0.12575        3486.07 0.408333
Is there something wrong?

Best!

**Comment by etal** [comment]
Did you see any warnings when you ran the `reference` command the first time?
