### ISSUE TITLE
log2 ratio cutoff for copy number integers

### ISSUE THREAD

**Issue by weishwu** [etal/cnvkit#444]
Hi,

The ranges of log2 ratios of each category of segments from my running of CNVkit call are as follow:
cn<=1: [-25.477500, -0.250407]
cn=2: [-0.249509,  0.199906]
cn>=3: [0.20009, 3.48201]

However, based on the formula log2((copy_nums+.5) / 2, the cutoffs should be:
cn<=1: log ratio <= -0.4150375
cn==2: log ratio = 0.3219281
cn>=3: log ratio >= 0.8073549

Why are my cutoffs shifted?

My command line to run CNVkit call is:

`cnvkit.py call Sample_${f}.cns -y -v ${hapcDir}/nonSomatic.vcf -i sample_${f} -n C57BL_6NJ -z 0.25 -o Sample_${f}_recall.cns`

One line of the outputs:

> 6	131020494	131967271	**_0.20009_**	0	**_3_**	3	0	37.2703	1036	983.507

The log ratio is 0.20009. Why is the inferred copy number 3?

When I pick up amplification and deletion CNVs, should I use both inferred cn value and the log2 values? And what should be the recommended cutoffs?

Thanks,

**Comment by weishwu** [comment]
I see it's because the default setting assumes low tumor purity.

**Comment by etal** [comment]
The `call` command with `-m` unspecified defaults to a hard-coded set of cutoffs that are more appropriate for solid tumor samples. The math you're expecting is appropriate for cell lines and germline samples; you can choose those cutoffs with the option `call -m clonal`.
https://cnvkit.readthedocs.io/en/stable/pipeline.html#calling-methods
