### ISSUE TITLE
Usage in single cell RNA-sequencing data?

### ISSUE THREAD

**Issue by HaotengYan** [etal/cnvkit#445]
Hi, 

I'm not sure whether CNVkit-RNA, the new functionalities within the software package CNVkit
, could enable copy number inference from **single cell** RNA-sequencing data. Did anybody try this?

Haoteng Yan

**Comment by etal** [comment]
I did try the `import-rna` command on what was essentially scRNA data, and it worked pretty well. The results were clearer than with bulk tumor tissue. For segmentation and post-processing, you'd be able to use germline methods there because you can assume integer ploidy.
