### ISSUE TITLE
CNVlib python library issue - create_diagram

### ISSUE THREAD

**Issue by audyavar** [etal/cnvkit#446]
Hello - 

I used CNVkit in my exomeSeq pipeline (using hg38) to compute the copy number alterations as well as structural variants. I am trying to use cnvlib and cnvkit as python modules to make some plots in a markdown report. I imported the cns and cnr files. 
cns = skgenome.tabio.read_auto('pact1-cnvkit.cns')
cnr = skgenome.tabio.read_auto('pact1-cnvkit.cnr')
I want to make 2 genome-wide plots highlighting all the chomosome-level changes in a given sample - scatter and diagram plot. 
p = cl.scatter.genome_scatter(cnr, segments=cns, variants=None, do_trend=True, y_min=None, y_max=None, title=pt_id, segment_color='darkorange')
p.savefig('test.pdf')
p2 = cl.diagram.create_diagram(cnr, cns, threshold=0.5, outfname='test2.pdf', title=pt_id, cnarr_is_seg = True)

My genome-wide scatter plot for a patient looks extremely cluttered and has too many dots. Also hg38 gives me additional chromosomes (ChrM, ChrUnk, etc) that I want to filter out to make the plot more readable. 

Questions: 
1. How do I go about filtering the chromosomes to just showing the 22 chromosomes and X/Y on both these plots? 
2. I used the threshold of 0.5 to highlight only significant copy number alterations in my sample. I did not specify any min_probes and it gives me an error to specify min_probes. When I do specify it to min_probes = 2 or 3, it says "AttributeError: 'GenomicArray' object has no attribute 'by_gene'". Please advise.

**Comment by etal** [comment]
For copy number it's probably best to remove the alternative contigs from your reference genome at the read mapping stage, well before running CNVkit. That's not mandatory, though. The most recent version of CNVkit (v0.9.6) should [remove the alt contigs on the fly](https://github.com/etal/cnvkit/blob/master/cnvlib/antitarget.py#L49) when you run the `batch` command -- are you using the latest version?

For 2, how did you run this step?
