### ISSUE TITLE
import-rna input: Do I need to do normalization on the gene counts?

### ISSUE THREAD

**Issue by laopp** [etal/cnvkit#447]
Hi, 

I am doing CNV calling on RNA data. My input file is a simple two-column tab file. The gene counts were generated using featureCounts function. I wonder if I need to normalize the gene counts using e.g. DESeq2 to accounts for size factors before putting into import-rna function?

Thanks!
Peipei

**Comment by etal** [comment]
No, I think the counts alone should be enough. The import-rna pipeline uses transcript lengths to normalize the counts internally.
