### ISSUE TITLE
cnvkit directory

### ISSUE THREAD

**Issue by dongleihu** [etal/cnvkit#449]
Hi,

I am new to cnvkit so apologize if this issue has been discussed before.  I have followed the instruction to install cnvkit using anacoda 3.  I have also run configuration with
~
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
~
Then I ran
conda install cnvkit

After this part, I can't test the installation.  Is there supposed to be a directory "cnvkit"?  I don't see it in my home directory.

Any help is appreciated!

**Comment by etal** [comment]
It does not create the `cnvkit` directory in your home directory. Instead, the package is downloaded and installed in the anaconda or miniconda path on your system. Generally you don't need to worry much about where this is, you can just use the `cnvkit.py` command like any other installed command-line program.
