### ISSUE TITLE
How to combine the log2 of the same gene in multiple bins into one log2

### ISSUE THREAD

**Issue by Tinalxt** [etal/cnvkit#456]
Hi, I wonder how to combine the log2 of the same gene in multiple regions into one log2?
Can you implement related commands?
I had used cnvkit.py gainloss,  but it only reported very few genes. I hope to get all the genes’ gain or loss.

**Comment by etal** [comment]
The `genemetrics` command (formerly `gainloss`) has some options you can use to print more genes. Try reducing `-t` to a smaller value like 0.1 or even 0.0.
