### ISSUE TITLE
gender missidentification issues when creating a male reference 

### ISSUE THREAD

**Issue by duartemolha** [etal/cnvkit#459]
Hi... I believe there is a bug on the reference.py script that causes cnvkit to missidentify input reference gender when creating a male reference set

To test I have run the same command on a set of female control samples :

`./cnvkit.py reference -o test  -f /mnt/c/fasta/hg38-noalt.fa  /mnt/c/female_controls/*
`

> Number of target and antitarget files: 4, 4
> Relative log2 coverage of chrX=-0.00981, chrY=-22.7 (maleness=0.000906 x 0.678 = 0.000614) --> assuming female
> Relative log2 coverage of chrX=-0.0236, chrY=-23.8 (maleness=0.000987 x 0.678 = 0.000669) --> assuming female
> Relative log2 coverage of chrX=-0.0135, chrY=-25.7 (maleness=0.000221 x 0.827 = 0.000183) --> assuming female
> Relative log2 coverage of chrX=-0.0146, chrY=-23.5 (maleness=0.000843 x 0.743 = 0.000626) --> assuming female
> Relative log2 coverage of chrX=-0.218, chrY=-4.89 (maleness=0.0534 x 0.204 = 0.0109) --> assuming female
> Relative log2 coverage of chrX=-0.174, chrY=-5.21 (maleness=0.033 x 0.301 = 0.00993) --> assuming female
> Relative log2 coverage of chrX=-0.189, chrY=-4.8 (maleness=0.0404 x 0.263 = 0.0106) --> assuming female
> Relative log2 coverage of chrX=-0.347, chrY=-5.49 (maleness=0.0675 x 0.176 = 0.0118) --> assuming female

In this case the script correctly identifies the sex of the control samples.

when trying to create a male reference from the same exact iput files
`./cnvkit.py reference -y -o test  -f /mnt/c/fasta/hg38-noalt.fa  /mnt/c/female_controls/*
`

> Number of target and antitarget files: 4, 4
> Relative log2 coverage of chrX=-0.00981, chrY=-22.7 (maleness=1.68e+03 x 0.678 = 1.14e+03) --> assuming male
> Relative log2 coverage of chrX=-0.0236, chrY=-23.8 (maleness=1.57e+03 x 0.678 = 1.07e+03) --> assuming male
> Relative log2 coverage of chrX=-0.0135, chrY=-25.7 (maleness=6.96e+03 x 0.827 = 5.76e+03) --> assuming male
> Relative log2 coverage of chrX=-0.0146, chrY=-23.5 (maleness=1.77e+03 x 0.743 = 1.31e+03) --> assuming male
> Relative log2 coverage of chrX=-0.218, chrY=-4.89 (maleness=18.7 x 0.204 = 3.8) --> assuming male
> Relative log2 coverage of chrX=-0.174, chrY=-5.21 (maleness=24.1 x 0.301 = 7.25) --> assuming male
> Relative log2 coverage of chrX=-0.189, chrY=-4.8 (maleness=24.2 x 0.263 = 6.36) --> assuming male
> Relative log2 coverage of chrX=-0.347, chrY=-5.49 (maleness=21.1 x 0.176 = 3.7) --> assuming male

I beleive the issue in this case has to do with providing the infer_sexes method with the male_reference flag here: 

   ```
 if female_samples is None:
        # NB: Antitargets are usually preferred for inferring sex, but might be
        # empty files, in which case no inference can be done. Since targets are
        # guaranteed to exist, infer from those first, then replace those
        # values where antitargets are suitable.
        sexes = infer_sexes(target_fnames, **male_reference**)
        if antitarget_fnames:
            a_sexes = infer_sexes(antitarget_fnames, **male_reference**)
            for sid, a_is_xx in a_sexes.items():
                t_is_xx = sexes.get(sid)
                if t_is_xx is None:
                    sexes[sid] = a_is_xx
                elif t_is_xx != a_is_xx and a_is_xx is not None:
                    logging.warning("Sample %s chromosomal X/Y ploidy looks "
                                    "like %s in targets but %s in antitargets; "
                                    "preferring antitargets",
                                    sid,
                                    "female" if t_is_xx else "male",
                                    "female" if a_is_xx else "male")
                    sexes[sid] = a_is_xx
    else:
        sexes = collections.defaultdict(lambda: female_samples)
```

sexes = infer_sexes(target_fnames, **male_reference**)
a_sexes = infer_sexes(antitarget_fnames, **male_reference**)

For normal female reference creation the male_reference is set to False
Bu it is set to true when creating a male reference set 

 cnarr.guess_xx(is_haploid_x) is set to cnarr.guess_xx(TRUE) for every input reference sample which obviously is wrong if you are trying to create a MALE reference set from a set of controls samples of mixed genders

I believe those 2 lines need to be corrected to 

sexes = infer_sexes(target_fnames, **False**)
a_sexes = infer_sexes(antitarget_fnames, **False**)

Best regards

Duarte

**Comment by etal** [comment]
Thanks for reporting and investigating. I've merged your PR, so the fix is now in the codebase and will be in the next stable release.
