### ISSUE TITLE
cnvkit sample.cns results, one gene for several segments and log2 ratio

### ISSUE THREAD

**Issue by Hang0918** [etal/cnvkit#468]
chromosome    start   end     gene    log2    depth   probes  weight
    chr1    143118261       154132647       MCL1,TPM3       0.213545        230.321 77      51.5803
    chr1    154132647       154138724       TPM3    -0.642539       1029.55 18      5.25011
    chr1    154139591       243708286       TPM3,PRCC,FCGR2A,FCGR3A,FCGR2B,DDR2,PBX1,MDM4,SLC45A3,PARP1,SDCCAG8,AKT3,AKT3   0.12537 170.938 681     510.339

Hi,there, 
I am running CNVkit in a tumor-normal pair mode, my data is targeted panel sequencing, and some result from sample.cns file was like the above, for one gene(TPM3 for example) lies in many segments with different log2 ratio, even for amplication and deletion. What i am looking for is GENE-level amplication and deletion, I don't know which one to pickup as the confidence segment and log2 ratio (assuming i use 0.2 as the gain threshold and -0.6 for the cnv loss)

**Comment by etal** [comment]
As an alternative to segmentation, particularly when your panel is relatively small (i.e. not whole exome), you can use the `genemetrics` command with the .cnr file alone to get per-gene summary statistics, including average log2 value. That would help find a focal amplification if segmentation didn't pick it up.
