### ISSUE TITLE
PSCBS 0.45.0 breaks probe segmentation

### ISSUE THREAD

**Issue by tskir** [etal/cnvkit#47]
Hi Eric,

PSCBS R package version 0.45.0 was released yesterday (2015-09-11) and apparently it breaks probe segmentation in CNVKit. Perhaps it introduces some backwards incompatible syntax changes, or maybe it's just a regression in PSCBS itself—I unfortunately don't have enough time at the moment to investigate further into this. Judging from the error message, it has something to do with namespace conflicts. I will for now stick with using version 0.44.0, which works fine, but since 0.45.0 is now installed by default, it might be inconvenient and confusing to some users. An error trace from running `make` in `test` directory is below.

Please let me know if you need more information on this, and thank you for your work on CNVKit!

Yours
Kirill

```
python ../cnvkit.py segment build/p2-5_5.cnr -o build/p2-5_5.cns
Traceback (most recent call last):
  File "../cnvkit.py", line 9, in <module>
    args.func(args)
  File "/mnt/tmp/cnvkit/cnvlib/commands.py", line 625, in _cmd_segment
    args.rlibpath)
  File "/mnt/tmp/cnvkit/cnvlib/segmentation/__init__.py", line 45, in do_segmentation
    seg_out = ngfrills.call_quiet('Rscript', script_fname)
  File "/mnt/tmp/cnvkit/cnvlib/ngfrills/__init__.py", line 41, in call_quiet
    % (' '.join(args), err))
RuntimeError: Subprocess command failed:
$ Rscript /tmp/tmp6dlQOh

PSCBS v0.45.0 (2015-09-11) successfully loaded. See ?PSCBS for help.

Attaching package: ‘PSCBS’

The following objects are masked from ‘package:base’:

    append, load

Loading probe coverages into a data frame
Pre-processing the probe data for segmentation
Segmenting the probe data
Error: !hasWeights || !is.null(fit$data$w) is not TRUE
Execution halted
```

**Comment by etal** [comment]
Thanks for reporting this problem. I'm looking into it.

**Comment by etal** [comment]
@henrikbengtsson, does this look like new code in PSCBS v.0.45.0? The R command triggering the error is:

    fit = segmentByCBS(cna, alpha=0.0001, undo=0, min.width=2,
                   joinSegments=FALSE, knownSegments=knownsegs, seed=0xA5EED)

**Comment by HenrikBengtsson** [comment]
Yes,
```
Error: !hasWeights || !is.null(fit$data$w) is not TRUE
```
is part of new [sanity checks](https://github.com/HenrikBengtsson/PSCBS/blob/master/R/segmentByCBS.R#L390) (or [here](https://github.com/HenrikBengtsson/PSCBS/blob/master/R/segmentByCBS.R#L390)) to make sure weights are correctly used/recorded.  If I could get hold tabular data that generates this error, I can investigate asap.

Thanks for the report.

**Comment by etal** [comment]
Thanks, Henrik. I've sent an example file that triggers this issue to your UCSF e-mail (I think).

**Comment by HenrikBengtsson** [comment]
I've identified and fixed the problem observed in PSCBS 0.45.0.  It happened when `knownSegments` specifies segments with zero data points (e.g. a centromere).  Before I submit 0.45.1 to [CRAN](cran.r-project.org/web/package=PSCBS), could you please confirm that my fix solves your problem.

Install PSCBS 0.45.0-1 (to become 0.45.1) as:
```r
source("http://callr.org/install#HenrikBengtsson/PSCBS@hotfix/bug-weights")
```
You can verify you've installed the new version by (in a fresh R session):
```r
> packageVersion("PSCBS")
[1] '0.45.0.1'
```
Please report back here.  If we have a success, I'll submit to CRAN asap.

**Comment by etal** [comment]
Yes, this fix works. Thanks!

**Comment by HenrikBengtsson** [comment]
PSCBS 0.45.1 in now on [CRAN](https://cran.r-project.org/package=PSCBS).
