### ISSUE TITLE
Determine estimated copy numbers

### ISSUE THREAD

**Issue by kvaldez** [etal/cnvkit#470]
Hi etal,

I am attempting to obtain estimated copy numbers (without rounding to the nearest integer) to use with the expands package.  

Using log2 values, is (2^x)*2 the correct way to determine estimates?  And if so, am I multiplying by 2 because of the assumed diploid genome?

Thanks,
Kristin

**Comment by etal** [comment]
Yes, that'll work. Some details here: https://cnvkit.readthedocs.io/en/stable/calling.html

E.g.

    log2  | ploidy
    -1    | 1
    0     | 2
    +.58  | 3
    +1    | 4
