### ISSUE TITLE
Germline Copy Number Variation calling by cnvkit from Whole genome sequencing

### ISSUE THREAD

**Issue by xysj1989** [etal/cnvkit#484]
Hallo,

I am going to conduct germline CNV analysis for our healthy population cohort based on whole genome sequencing. Is it possible to make this by cnvkit? Or would you have a step by step pipeline example to describe command parameters just like for cancer somatic CNV calling?

Best regards.

**Comment by xysj1989** [comment]
I don't have bam file from case/control sample group. All my samples are normal germline samples.  I am trying to run the command as following,

cnvkit.py batch 1-Samtools/SB9_Germline1.bam 1-Samtools/SB9_Germline2.bam   1-Samtools/SB9_Germline3.bam  -m wgs -f /data/1-hg19/Homo_sapiens_assembly19.fasta --annotate refFlat.txt

But the the error is:
Option -n/--normal must be given to build a new reference if -r/--reference is not used.

Would you like to tell me how to deal with this problem?

**Comment by etal** [comment]
Sure, you can use `-n` with no BAM files following it to do control-free CNV calling.

For germline, I suggest using the most recent release with the `hmm` segmentation method to find smaller alterations.

**Comment by hongmzha** [comment]
Dear Eric,
per your suggestion, could I input,
cnvkit.py batch 1-Samtools/SB9_Germline1.bam 1-Samtools/SB9_Germline2.bam 1-Samtools/SB9_Germline3.bam -n \    (#with no BAM files following it to do control-free CNV calling.)
-m wgs -f /data/1-hg19/Homo_sapiens_assembly19.fasta --annotate refFlat.
cnvkit.py cnvkit.py segment -m hmm-germline 1-Samtools/SB9_Germline*.cnr -o 1-Samtools/SB9_Germline*.cns 

Alternativel,
cnvkit.py reference -o FlatReference.cnn -f ucsc.hg19.fa -t hg19.target.bed -a hg19.antitarget.bed \
cnvkit.py batch SB9_Germline*.bam -r FlatReference.cnn -d results

might you correct me ?
thanks for your time !
HM

**Comment by etal** [comment]
@hongmzha , your first set of commands should work -- use the `batch` command as usual with `-m wgs`, and then repeat segmentation with `-s hmm-germline` or just `-s hmm` for better sensitivity to smaller-scale CNVs. Also consider the `bintest` command in the pre-release version 0.9.7-beta, which should be more accurate overall too.

**Comment by hongmzha** [comment]
Thanks for your quick answer, it's valued for me. stay healthy and happy, Eric !

**Comment by yr542** [comment]
Could there be an example of how to feed this back into the batch command?
