### ISSUE TITLE
Incorrect CN call from log2 ?

### ISSUE THREAD

**Issue by ashbig** [etal/cnvkit#488]
Recently I encountered a false negative cn when using cnvkit 0.9.3. Here are the values as called output by genemetrics: 

gene    chromosome      start   end     log2    cn      depth   weight  n_bins
EGFR    chr7    55086960        55273320        3.90765 5       19632.8 17.4239 30

A log2 of 3.9 would correspond to roughly ~30 copies no? Is this a known bug, is there something I am overlooking in the docs? The input to genemetrics in terms of this gene is a .cns file and can be found below. This in no way should be a CN of 5 from what I can infer. 

chromosome      start   end     gene    log2    cn      depth   weight
chr7    55086960        55087068        EGFR    1.25201 5       2990.54 0.537694
chr7    55209968        55210140        EGFR    3.33051 20      10324.8 0.696251
chr7    55210987        55211191        EGFR    4.01739 32      25619.2 0.669614
chr7    55214288        55214443        EGFR    2.77477 14      3567.54 0.531276
chr7    55218976        55219065        EGFR    3.57548 24      11835.7 0.563099
chr7    55220228        55220367        EGFR    2.60521 12      13352.3 0.64075
chr7    55221693        55221855        EGFR    3.78039 27      21407.2 0.68822
chr7    55223512        55223649        EGFR    3.22142 19      14410   0.65473
chr7    55224215        55224362        EGFR    3.43147 22      13459.3 0.636907
chr7    55224441        55224546        EGFR    3.11097 17      6807.47 0.568302
chr7    55225345        55225456        EGFR    4.61731 49      12822.4 0.422531
chr7    55227821        55228041        EGFR    3.86221 29      18483.4 0.679796
chr7    55229181        55229334        EGFR    4.05164 33      4352.29 0.0428994
chr7    55231415        55231526        EGFR    4.00412 32      18886.5 0.585584
chr7    55232962        55233140        EGFR    5.41496 85      39929.8 0.534065
chr7    55236205        55236232        EGFR    4.73797 53      5859.89 0.472073
chr7    55237989        55238247        EGFR    4.64329 50      52932.8 0.696669
chr7    55238857        55238916        EGFR    3.79342 28      34143.8 0.53456
chr7    55240665        55240827        EGFR    4.32214 40      30416.3 0.677234
chr7    55241603        55241746        EGFR    3.89248 30      20298.1 0.665638
chr7    55242404        55242523        EGFR    4.70255 52      12939.3 0.527382
chr7    55248975        55249181        EGFR    5.11873 69      8999.72 0.320801
chr7    55259401        55259577        EGFR    4.1223  35      27015.9 0.670807
chr7    55260448        55260544        EGFR    4.31147 40      17332.9 0.56646
chr7    55266399        55266566        EGFR    3.89153 30      23163.6 0.638571
chr7    55267998        55268116        EGFR    3.5362  23      23489.2 0.585461
chr7    55268870        55269058        EGFR    5.05863 67      21165.8 0.580508
chr7    55269417        55269485        EGFR    4.46201 44      9670.26 0.527296
chr7    55270199        55270328        EGFR    4.4024  42      21130   0.552891
chr7    55272938        55273320        EGFR    4.15386 36      25716.5 0.955861

**Comment by etal** [comment]
Thanks for reporting this. Does the same inconsistency show up in CNVkit v0.9.6 or the latest v0.9.7b?

**Comment by ashbig** [comment]
Opened a new issue with stable release. search for "CN from log2" in issues.
