### ISSUE TITLE
import-rna AssertionError line 310

### ISSUE THREAD

**Issue by dwkarjosukarso** [etal/cnvkit#489]
Hi, I would like to do CNV analysis on bulk RNA-seq data from cancer cell lines. I made the correlation file I used the following code: /home/karjosukarso/anaconda3/envs/CNV/bin/cnvkit.py import-rna -f counts -g /home/karjosukarso/CNVkit/ensembl-gene-info.hg38.tsv -c /home/karjosukarso/DK-53/CNV/tcga-hnsc.cnv-expr-corr.tsv -o output.txt *.txt

But, I got the following error:

Dropping 369445 / 369445 rarely expressed genes from input samples Loading gene metadata and TCGA gene expression/CNV profiles Loaded /home/karjosukarso/CNVkit/ensembl-gene-info.hg38.tsv with shape: (221323, 9) Loaded /home/karjosukarso/DK-53/CNV/tcga-hnsc.cnv-expr-corr.tsv with shape: (20309, 4) Resetting 2844 ambiguous genes' correlation coefficients to default 0.100000 Trimmed gene info table to shape: (63966, 13) Aligning gene info to sample gene counts Weighting genes with below-average read counts /home/karjosukarso/anaconda3/envs/CNV/lib/python2.7/site-packages/cnvlib/rna.py:269: FutureWarning: clip_upper(threshold) is deprecated, use clip(upper=threshold) instead weights = [np.sqrt((gene_counts / gene_counts.quantile(.75)).clip_upper(1))] Calculating normalized gene read depths Traceback (most recent call last): File "/home/karjosukarso/anaconda3/envs/CNV/bin/cnvkit.py", line 13, in <module> args.func(args) File "/home/karjosukarso/anaconda3/envs/CNV/lib/python2.7/site-packages/cnvlib/commands.py", line 1462, in _cmd_import_rna args.normal, args.do_gc, args.do_txlen, args.max_log2) File "/home/karjosukarso/anaconda3/envs/CNV/lib/python2.7/site-packages/cnvlib/import_rna.py", line 39, in do_import_rna gene_info, sample_counts, tx_lengths, normal_ids) File "/home/karjosukarso/anaconda3/envs/CNV/lib/python2.7/site-packages/cnvlib/rna.py", line 274, in align_gene_info_to_samples normal_ids) File "/home/karjosukarso/anaconda3/envs/CNV/lib/python2.7/site-packages/cnvlib/rna.py", line 310, in normalize_read_depths assert sample_depths.values.sum() > 0 AssertionError

Could anyone help me what could have gone wrong? Thank you.

Greetings, Dyah

**Comment by etal** [comment]
It looks like the gene counts may not have been loaded properly. Which version of CNVkit are you using? Does the same issue happen in the latest release, v0.9.7b?

**Comment by dwkarjosukarso** [comment]
Ah thank you, I managed to fix it by remaking the count tables.
