### ISSUE TITLE
Threshold calling does not take ploidy of sex chromosomes into account

### ISSUE THREAD

**Issue by tskir** [etal/cnvkit#49]
Hi Eric,

It appears to me that `call -m threshold` always treats sex chromosomes as though they were diploid. Here's a small use case which results took me completely by surprise. I had 15 samples, all male; I built a reference and run all samples against it using these standard commands using CNVKit 0.7.0:

```
./cnvkit.py reference --male-reference -o reference.cnn -f hg19.fa samples/*.cnn
./cnvkit.py fix sample1.targetcoverage.cnn sample1.antitargetcoverage.cnn reference.cnn \
-o sample1.cnr
./cnvkit.py segment sample1.cnr -o sample1.cns
./cnvkit.py call --male-reference -m threshold -t=-1.1,-0.4,0.3,0.7 -o sample1.call.cns \
sample1.cns
./cnvkit.py export bed --male-reference sample1.call.cns -o sample1.bed
./cnvkit.py export bed --male-reference sample1.call.cns --show-neutral -o sample1.all.bed
```

For all of the samples I noticed an apparent miscalculation of copy numbers in sex chromosomes. The table below reflects the average log2 values for reference (column 2) and across all of the samples (columns 3-5), absolute copy numbers (column 6), as well as whether those copy numbers are considered neutral by `export bed` command (column 7). Since all numbers in columns 2-4 were very close to integers, I rounded them for the sake of readability:

chr | reference.cnn | sample.cnn | cnr, cns | call.cns | abs CN | CN neutral?
---|---|---|---|---|---|---
autosomes | 0 | 0 |  0 | 0 | 2 | yes
chrX | −1 | −1 | 0 | **+1** | **2** | yes
chrY | −1 | −1 | 0 | **+1** | **2** | yes

Note that chrX and chrY went from 0 in `sample.cns` to +1 in `sample.call.cns`, which was then reinterpreted as 2 absolute copies by `export bed` command (and, interestingly enough, still considered neutral, although for sex chromosomes that would be an alteration). After inspecting the code, I discovered that this happens in `cnvlib.call.absolute_threshold()`: a cycle assigns absolute copy numbers without looking at whether the segment in question comes from autosome or sex chromosome. In this case, it assigns both chrX and chrY an absolute copy number of 2.

I realize that this method is *supposed* to be really simple, since it only applies fixed thresholds, but intuitively I still expected it to somehow handle autosomes and allosomes differently. If this is indeed by design, and not a bug, then I believe it would be helpful to describe this detail of `call -m threshold` in the documentation.

Also, a quick related question: since the threshold method is not usable for sex chromosomes, it is OK if I just always use `call -m clonal -purity 1` for germline samples? It seems to handle this situation well so far.

Cheers
Kirill

**Comment by etal** [comment]
Thanks for the detailed report. I agree it's a bug, and I can fix it.

As a workaround you could split the .cns files by chromosome (`grep -v chrY`) and do threshold calling on each piece separately, specifying `--ploidy 1` for the chrY pieces, then recombine.

For `call -m clonal`, if purity isn't specified then no rescaling is done, i.e. the default purity is effectively 1, so you don't need to specify it. If that works well for you on germline samples, (a) great!, and (b) in theory that should be fine.

To address different use cases the `export bed` behavior needs another option to distinguish neutral meaning matching the specified ploidy vs. matching the expected or reference ploidy on sex chromosomes. Currently it emits the non-diploid segments by default, or all segments with `--show-neutral`. This is what FreeBayes' `--cnv-map` argument expects, I think. The VCF export behaves more like what you'd expect, emitting the segments that differ from the expected copy number depending on the sample gender.

**Comment by qindan2008** [comment]
Hi Etal,
As the above, I split the .cns files output from segmetrics command  by chromosome (grep -v chrY) and do threshold calling on each piece separately, specifying --ploidy 1 for the chrY pieces. Then I found all samples'  chrY log2 values turned to be -8.96578, and cn value to be 0, no matter the real gender is male or female. 
Show 2 samples here:

python   cnvkit-0.9.5/cnvkit.py  call   --filter  ci      -m threshold          --purity    0.2  --ploidy    1       S1.segmetrics.cns   -i   S1  -g       Male  --drop-low-coverage    -o       S1.segmetrics.filterCi.cns

python    cnvkit-0.9.5/cnvkit.py  call   --filter  ci      -m threshold          --purity    0.2  --ploidy    1       S2.segmetrics.cns   -i   S2  -g       Female  --drop-low-coverage    -o       S2.segmetrics.filterCi.cns

Output:

chrY    2643470 10139865        -8.96578        0       60.4666 143     74.9826
chrY    13007098        14106468        -8.96578        0       52.2671 17      9.36832
chrY    14106968        28494814        -8.96578        0       50.947  345     172.352
chrY    28495314        59105939        -8.96578        0       4.95144 5       3.9505

And 

chrY    2643470 10139865        -8.96578        0       21.1763 86      53.1744
chrY    13007098        13924251        -8.96578        0       7.53367 11      6.45748
chrY    13924251        59105939        -8.96578        0       3.23157 141     101.472

This seemed to be strange, how to interpret the results?

Thank you.
