### ISSUE TITLE
export gistic not working

### ISSUE THREAD

**Issue by thesushantpatil** [etal/cnvkit#498]
Hello,

I am using version 0.9.6 of CNVkit and trying to export markers files to be used for gistic analysis. However, "export gistic" doesn't seem to be recognized -

[sushantp@c6145-2-8 CNVkit_out]$ singularity exec -B /datastore /datastore/nextgenout5/share/labs/bioinformatics/sushantp/tools/cnvkit-8Oct19.simg cnvkit.py export gistic *.cnr -o gistic.markers
usage: cnvkit.py export [-h]
                        {bed,seg,vcf,theta,nexus-basic,nexus-ogt,cdt,jtv} ...
cnvkit.py export: error: invalid choice: 'gistic' (choose from 'bed', 'seg', 'vcf', 'theta', 'nexus-basic', 'nexus-ogt', 'cdt', 'jtv') 

[sushantp@c6145-2-8 CNVkit_out]$ singularity exec -B /datastore /datastore/nextgenout5/share/labs/bioinformatics/sushantp/tools/cnvkit-8Oct19.simg cnvkit.py export -h
usage: cnvkit.py export [-h]
                        {bed,seg,vcf,theta,nexus-basic,nexus-ogt,cdt,jtv} ...

positional arguments:
  {bed,seg,vcf,theta,nexus-basic,nexus-ogt,cdt,jtv}
                        Export formats (use with -h for more info).
    bed                 Convert segments to BED format. Input is a
                        segmentation file (.cns) where, preferably, log2
                        ratios have already been adjusted to integer absolute
                        values using the 'call' command.
    seg                 Convert segments to SEG format. Compatible with IGV
                        and GenePattern.
    vcf                 Convert segments to VCF format. Input is a
                        segmentation file (.cns) where, preferably, log2
                        ratios have already been adjusted to integer absolute
                        values using the 'call' command.
    theta               Convert segments to THetA2 input file format
                        (*.input).
    nexus-basic         Convert bin-level log2 ratios to Nexus Copy Number
                        "basic" format.
    nexus-ogt           Convert log2 ratios and b-allele freqs to Nexus
                        "Custom-OGT" format.
    cdt                 Convert log2 ratios to CDT format. Compatible with
                        Java TreeView.
    jtv                 Convert log2 ratios to Java TreeView's native format.

optional arguments:
  -h, --help            show this help message and exit

Has anyone else faced a similar issue? @etal I'd appreciate if you could look into this.

**Comment by etal** [comment]
Indeed, `gistic` is not a supported output format. However, you can try `export seg` format -- it looks like GISTIC will accept the SEG format as input.

**Comment by zhangyz1997** [comment]
> Indeed, `gistic` is not a supported output format. However, you can try `export seg` format -- it looks like GISTIC will accept the SEG format as input.

By the way, I wonder whether I should use "call.cns" file generated by the call command or the original "cns" file for exporting to a seg file?
