### ISSUE TITLE
Export to VCF

### ISSUE THREAD

**Issue by etal** [etal/cnvkit#5]
In the "export" command, implement converting segmented CNVs to VCF format.

See: http://www.1000genomes.org/wiki/Analysis/Variant%20Call%20Format/VCF%20%28Variant%20Call%20Format%29%20version%204.0/encoding-structural-variants

**Comment by etal** [comment]
I think this is ready for testing. Anyone care to try it out?

    cnvkit.py call Sample.cns -o Sample.call.cns
    cnvkit.py export vcf Sample.call.cns -o Sample.vcf

**Comment by xiucz** [comment]
@etal hi,

Why some segments  line showed in the .cns file were filterd， they are not included in vcf file anymore.

Thank you .
xiucz.

**Comment by etal** [comment]
The segments that represent neutral copy number (log2 ratio near 0.0) are not shown in the VCF file -- only the variant regions are exported.

**Comment by xiucz** [comment]
@etal 
Thanks for your quick reply, and I want to ask one question more,  what thresholds were used to filter the segments before the exportation? Or can we keep all the segments in the vcf file?


Thank you verg much.
