### ISSUE TITLE
gc correct formula

### ISSUE THREAD

**Issue by Xiaohuaniu0032** [etal/cnvkit#501]
Hi:
 I am not very understand the 162 line `df['log2'] -= biases` in fix.py, can you give me some details why do this process (v0.9.6)? Thank you very much.

**Comment by etal** [comment]
The code before that line calculates the difference in observed log2-ratio coverage depths versus the expectation accounting for GC content and other known biases. Then this line subtracts that difference so that the `log2` value at each locus is closer to the true log2-ratio copy number.

**Comment by Xiaohuaniu0032** [comment]
I see the code that the `biases` is calculated by the rolling median method, this method is a kind of smoothing method and just returns the median value of a fixed window. I do not known why the median value is the `bias`? I see the code that the `corrected_value = origin_value - bias`. I want to know what is the `observed_value` and what is the `expected_value`? I see the code that the rolling median does not do any `observed_value - expected_val` procedure to calculate the `difference, aka bias`? Many thanks.
