### ISSUE TITLE
Deprecated pandas operations

### ISSUE THREAD

**Issue by lculibrk** [etal/cnvkit#502]
Hi,

It looks like export theta is no longer functional with pandas >= 1.0, as I get this error when trying to run cnvkit.py export theta:

`
KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'
`

downgrading pandas to 0.25.3 seems to be a workaround, although it seems that the conda recipe will automatically install the most recent pandas that it can find.

**Comment by etal** [comment]
Thanks, looks like the pandas 1.0 release happened while I was out on leave and broke this feature.

However, there are better methods for tumor purity estimation available now -- I recommend [PureCN](https://github.com/lima1/PureCN), which can take CNVkit's .cnn and .cnr files directly as input.

**Comment by tohsumi-repare** [comment]
Greetings.   I was wondering if the theta export function could be updated so it works with the latest Panda?   I am interested in running THetA using the output of CNVkit.    Thank you very much!

**Comment by etal** [comment]
I've updated the pandas .loc calls for `export theta` here: f7bb71a 

I see there are some other `.loc[:, ...]` calls elsewhere in the codebase that should probably be replaced, too.
