### ISSUE TITLE
release cnvkit 0.9.7 please

### ISSUE THREAD

**Issue by naumenko-sa** [etal/cnvkit#509]
Hi Eric @etal!

Thanks for maintaining CNVkit!

I have a tumor-normal pair WES sample which fails with cnvkit 0.9.6, but luckily runs well with cnvkit 0.9.7b, so I won't even describe the issue.

In bcbio we are installing cnvkit via conda, and we are receiving cnvkit 0.9.6:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/cnvkit/meta.yaml

Do you think 0.9.7 is mature enough to release it and to update the bioconda recipe?

Thanks!
Sergey

**Comment by etal** [comment]
Sure, I see some open bugs but if they're small I can sort them out and roll a proper release. Have you tried benchmarking 0.9.7 on your own data?

**Comment by naumenko-sa** [comment]
Thanks @etal! That would be fantastic!

No, I have not done validation of 0.9.7.
You've seen my previous validations based on huref benchmark deletions.
https://github.com/naumenko-sa/bcbio_validations/tree/master/huref_sv

I could apply them to 0.9.7, but there is no much sense in that test (it is WGS germline DEL test).
Its niche is mostly for split-reads SV calling methods and just to show the big picture, that the method is alive. 

Currently, the main use case of CNVkit for us in bcbio is that it is calling T/N CNV in WES. 

If you or anybody else knows a good benchmark (truth set CNV + WES T/N) for the use case, I'd be happy to run it with bcbio+cnvkit and publish the validation in bcbio or cnvkit docs.

But it is a longer story. 

Currently, having a more stable cnvkit 0.9.7 in bcbio even without rigorous validation would be super helpful and we may try to get the feedback from users who are actually running it and bumping into some issues.

S.

**Comment by etal** [comment]
Is the issue that bioconda has a policy against distributing beta releases? If not, would it suffice to update the bioconda meta.yaml to specify version `0.9.7.b1` in the first line? I think that's now the default version at least through some distribution channels.

**Comment by naumenko-sa** [comment]
yeah, unfortunately, bioconda discourages distributing betas.

**Comment by Zymergen-phaverty** [comment]
Releasing 0.9.7 would really be great. Using 0.9.7 limits us to Biopython <= 1.75 as they have since dropped their python2 support as well (https://github.com/biopython/biopython/issues/2420). Are there things I could help with? I'm relatively new to Python, but I've used the wrapped R tools for ages.

**Comment by serge2016** [comment]
+1

**Comment by etal** [comment]
All right, I've uploaded a fresh 0.9.7 stable release to PyPI. Will that work with bioconda?

**Comment by Zymergen-phaverty** [comment]
Excellent, thanks so much! I'm excited to try it out. Will bioconda pick up the new version from PyPI?

**Comment by Zymergen-phaverty** [comment]
I see 0.9.7 on bioconda now. Thanks!

**Comment by Stikus** [comment]
Hello @etal, any reason why `latest release` pointing here https://github.com/etal/cnvkit/releases/tag/v0.9.7.b1 and not here https://github.com/etal/cnvkit/releases/tag/v0.9.7? On releases page.

**Comment by etal** [comment]
@Stikus , thanks for pointing it out. I've added the 0.9.7 tag to the releases page so it should show up as the latest release now.
