### ISSUE TITLE
CNVkit  call   --filter  usage

### ISSUE THREAD

**Issue by qindan2008** [etal/cnvkit#512]
**How to use cnvkit  call  --filter command?**
**step1**.  "cnvkit.py  segmetrics    -s        P1.cn{s,r}    --ci   --pi    --sem    --drop-low-coverage".
 here, the P1.cn{s,r} were generated from cnvkit batch command.
**step2**. "cnvkit.py   call   --filter   ci      -m  threshold 	  -t=-1.1,-0.4,0.3,0.7     --purity  	0.3	     P1.segmetrics.cns     	   --drop-low-coverage     -o    	P1.segmetrics.filterCi.cns" 
**step3**. "cnvkit.py  call   --filter  cn      -m threshold    -t=-1.1,-0.4,0.3,0.7    --purity  	0.3	        P1.segmetrics.filterCi.cns    -i     Tumor     -n      Normal   --drop-low-coverage    -o      P1.segmetrics.filterCi_Cn.cns"

Is it right?  Or avoid -t=* when adding purity parameter?
Thank you very much !

**Comment by etal** [comment]
With `--purity`, you don't need the `-t` parameter. Usually you don't need to specify `-t` at all; the defaults are reasonable for good-quality solid tumor and potentially mosaic germline samples.

**Comment by qindan2008** [comment]
ok, thank you.
