### ISSUE TITLE
[RNA] CNVkit - Assertion Error

### ISSUE THREAD

**Issue by ReWeda** [etal/cnvkit#515]
Dear Developer,

**first of all, thank you for your work and support.**

I'm struggling on making cnvkit running. As pointed out by the title of the issue, I'm working with RNA expression data.

_(!) I'm running cnvkit (and rsem tools) in a dedicate conda environment._

Running the following command:
```
cnvkit.py import-rna /path/to/rsem.genes.results \
  --gene-resource /path/tp/gene.resource \
  --correlations /path/to/correlations.file \
  --output /path/to/outDir/output_summary.tsv' \
  --output-dir /path/to/outDir
```

I got the following error :
```
/home/davide/anaconda2/envs/cnvkit/lib/python3.7/site-packages/skgenome/intersect.py:15: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import Int64Index
Dropping 56843 / 56843 rarely expressed genes from input samples
Loading gene metadata and TCGA gene expression/CNV profiles
Loaded /mnt/NAS163/references/hg38/cnvKit_support/ensembl-gene-info.hg38.renamed.tsv with shape: (249701, 9)
Loaded /home/davide/projects/pr002_ImmInfiltr/LIPO/tmp_cnv/tcga-sarc.cnv.expr-corr.tsv with shape: (18774, 4)
Resetting 2671 ambiguous genes' correlation coefficients to default 0.100000
Trimmed gene info table to shape: (67139, 13)
Aligning gene info to sample gene counts
Weighting genes with below-average read counts
Calculating normalized gene read depths
Traceback (most recent call last):
  File "/home/davide/anaconda2/envs/cnvkit/bin/cnvkit.py", line 13, in <module>
    args.func(args)
  File "/home/davide/anaconda2/envs/cnvkit/lib/python3.7/site-packages/cnvlib/commands.py", line 1462, in _cmd_import_rna
    args.normal, args.do_gc, args.do_txlen, args.max_log2)
  File "/home/davide/anaconda2/envs/cnvkit/lib/python3.7/site-packages/cnvlib/import_rna.py", line 39, in do_import_rna
    gene_info, sample_counts, tx_lengths, normal_ids)
  File "/home/davide/anaconda2/envs/cnvkit/lib/python3.7/site-packages/cnvlib/rna.py", line 274, in align_gene_info_to_samples
    normal_ids)
  File "/home/davide/anaconda2/envs/cnvkit/lib/python3.7/site-packages/cnvlib/rna.py", line 310, in normalize_read_depths
    assert sample_depths.values.sum() > 0
AssertionError
```
So, at that point, I supposed that the _AssertionError_ was due to the fact that **all the genes are dropped**.

But.. Why?

Checking Biostar and other issues, this error was caused by a bug related to the format of the provided file for the gene counts. Solution was simply switch to the rsem format.
[Biostar-415581](https://www.biostars.org/p/415581/)

I'm already using the rsem for
[Uploading issue.genes.results…]()
mat so that solution won't work for me

After further inspection, I found a [GitMemory](https://www.gitmemory.com/issue/etal/cnvkit/499/614118360) that gave me renewed hopes.

So I modified my command as follow:
```
cnvkit.py import-rna --format rsem /path/to/rsem.genes.results \
  --gene-resource /path/tp/gene.resource \
  --correlations /path/to/correlations.file \
  --output /path/to/outDir/output_summary.tsv' \
  --output-dir /path/to/outDir
```
**But the Assertion Error persists despite the fact that the only some of the genes were dropped this time**
`[..]Dropping 19171 / 56843 rarely expressed genes from input samples[..]`

_Can you help me making cnvkit running?_

___

In order to provide a full pov, I'd like to point out what follow:

**Correlations File** has been generated by dedicated cnvkit script using input data downloaded from cBioportal (TCGA-SARC project in GDC Data portal). It's formatted as follow:
```
Entrez_Gene_Id	hugo_gene	kendall_t	pearson_r	spearman_r
1	A1BG	0.05973424949494993	0.06726729876977292	0.0744741221448616
2	A2M	0.0	0.07128319403550804	0.0
[...]
```

Genes Resource File has been downloaded from BioMart and it's formatted as follow:
```
Gene stable ID	Gene % GC content	Chromosome/scaffold name	Gene start (bp)	Gene end (bp)Gene name	NCBI gene ID	Transcript length (including UTRs and CDS)	Transcript support level (TSL)
ENSG00000210049	40.85	MT	577	647	MT-TF		71	tslNA
ENSG00000211459	45.49	MT	648	1601	MT-RNR1		954	tslNA
[...]
```

I calculated the rsem genes results running:
```
rsem-prepare-reference \
  --gtf /path/tp/gtf \
  --transcript-to-gene-map /path/to/knownIsoform \
  --bowtie2 \
  --bowtie2-path /path/to/bowtie2 \
  -p $nthreads \
  $chromosomes_directory \
  '/path/to/ref/hg38_rsem_bowtie2'
```
while GTF file is formatted:
```
chr1	ensGene	transcript	11869	14409	.	+	.	gene_id "ENSG00000223972"; transcript_id "ENST00000456328";  gene_name "ENSG00000223972";
chr1	ensGene	exon	11869	12227	.	+	.	gene_id "ENSG00000223972"; transcript_id "ENST00000456328"; exon_number "1"; exon_id "ENST00000456328.1"; gene_name "ENSG00000223972";
[...]
```

and KnownIsoform (downloaded from ucsc repo) is formatted:
```
1	ENST00000373020
1	ENST00000494424
[...]
```

then I calculated rsem genes results with the command:
```
 rsem-calculate-expression \
  --paired-end \
  -p $nthreads \
  --bowtie2 \
  --bowtie2-path $bowtie2_path \
  $fqForward \
  $fqReverse \
  '/path/to/ref/hg38_rsem_bowtie2' \
  '/path/to/output/output'
```

I attach my genes results file too
[issue.genes.results.txt](https://github.com/etal/cnvkit/files/4577637/issue.genes.results.txt)

**Comment by etal** [comment]
How many samples did you use as input? If it's only 1 sample, then it would have been normalized against itself, leaving log2 values of 0 across the board.

**Comment by ReWeda** [comment]
Yeah, that was the problem.
I figured out what was causing that error but I forgot about this opened issue.

So, for sake of clarification, the error I reported was due to the fact that I was running the tool over only one sample. 
Providing as input more samples solved the issue

```
cnvkit.py import-rna --format rsem /path/to/rsem.genes/*.results \
  --gene-resource /path/tp/gene.resource \
  --correlations /path/to/correlations.file \
  --output /path/to/outDir/output_summary.tsv' \
  --output-dir /path/to/outDir
```

Again, thanks for the support!
