### ISSUE TITLE
rna-import requires old pandas version

### ISSUE THREAD

**Issue by adamp83** [etal/cnvkit#523]
cnvkit.py raises an issue 

AttributeError: 'Series' object has no attribute 'clip_upper'

when running rna-import. This occurs on a fresh install on MacOS, and also affects the docker container. It seems to be related to pandas, which removed the clip_upper method in their 1.0 release in Jan 2020 (https://pandas.pydata.org/docs/whatsnew/v1.0.0.html#removal-of-prior-version-deprecations-changes). Reverting to pandas 0.25 fixes it. Specifying the dependency version or updating the clip_upper method to clip(upper=threshold) here: https://github.com/etal/cnvkit/blob/fa86632a5731ebbefb0092069c8031f806c8b611/cnvlib/rna.py#L267 (as described here: https://pandas.pydata.org/pandas-docs/version/0.24.2/reference/api/pandas.Series.clip_upper.html) should sort this. 

Hope this helps.

**Comment by etal** [comment]
Thanks, looks like an easy fix.

**Comment by etal** [comment]
Fixed on git just now: 0860c97

**Comment by harbourlab** [comment]
I still have this issue. Works with down-grading Pandas.
