### ISSUE TITLE
scatter displaying incorrect data

### ISSUE THREAD

**Issue by vschulz** [etal/cnvkit#535]
When I make a scatter plot of a deletion region on chromosome 11, I get an incorrect plot that does not show the deletion.  
`cnvkit.py scatter -s QR1_55.cn{s,r} -c 11:5000000-6200000  -g HBE1  --y-min -3 --y-max 3 -o wholegenome_chr11del.png`
It appears to me that there is some kind of indexing problem, since if I remove the -g option, it displays genes on chromosome 1, not 11.  If I change the region to just -c 11, the deletion shows up properly.  If I make a subset of cns and cnr files using 
![chr1_11del](https://user-images.githubusercontent.com/6390490/91474262-fa7d1b80-e867-11ea-871e-7c2cfd202868.png)
![chr11del](https://user-images.githubusercontent.com/6390490/91474265-fb15b200-e867-11ea-9f41-9889a4851325.png)

`egrep '^chromosome|^11' QR1_55.cnr > chr11_QR1_55.cnr`
This gives me the correct plot.  If I make a subset file containing just chr 1 and 11 (or 2 and 11, 10 and 11) I get an incorrect plot.  1 and 12 gives the correct plot.  I attached plots of correct chr11 alone and incorrect 1 plus 11 (same as whole genome version). 

This may be related, I can't produce B-allele files using whole genome vcf files, or I get IndexError: Boolean index has wrong length: 2873 instead of 50461
The problem is fixed using a chromosome 11 only vcf file.

I am using version 0.9.7 and python version 3.7.8

**Comment by tskir** [comment]
This looks to me like it could be the same issue as #457. It is already fixed in the master branch (see #536) and will be fixed in the next CNVkit release.

**Comment by ferenju1** [comment]
I have tested this with the latest master branch, there are still issues. If you plot a gene it will plot correctly, so that is fixed. But if you specify a chromosome without a co-ordinate range it will fail.

e.g.
cnvkit.py scatter -s data/20191216-MoST-SA-TSO500/K1954.cn{s,r} -c 9:0-200000000
will work but 
cnvkit.py scatter -s data/20191216-MoST-SA-TSO500/K1954.cn{s,r} -c 9

fails with IndexError: positional indexers are out-of-bounds.

**Comment by tskir** [comment]
@ferenju1 Indeed, thank you for your report. I investigated and found that this can be fixed by a single line change, see: https://github.com/etal/cnvkit/pull/541
