### ISSUE TITLE
wrong plot when using scatter command to plot chromosome sub-region

### ISSUE THREAD

**Issue by shanshenbing** [etal/cnvkit#566]
I run paired WES samples with batch command. when I used all chromosome to run scatter command like this:  cnvkit.py scatter -s /path to/result/BT1807130531LNC.Tumor.cn{s,r} -c chr12 -g KRAS -v /path to/BT1807130531LNC.germline.snp.pass.vcf -i BT1807130531LNCTX -n BT1807130531LNCBE -o ./BT1807130531LNC.KRAS.pdf, it got right plot.
![SL{2DX_}I0P${Q)3JS~E~LV](https://user-images.githubusercontent.com/42245493/105469455-37dcbc80-5cd3-11eb-9bca-fb6878b378e5.png)
 However, when I using sub-region of the chromosome,  cnvkit.py scatter -s /path to/result/BT1807130531LNC.Tumor.cn{s,r} -c chr12:10000000-60000000 -g KRAS -v /path to/BT1807130531LNC.germline.snp.pass.vcf -i BT1807130531LNCTX -n BT1807130531LNCBE -o ./BT1807130531LNC.KRAS.pdf, I got thtis plot.
![EORZ7TUF(PKK9NH9D87~`7N](https://user-images.githubusercontent.com/42245493/105470032-044e6200-5cd4-11eb-9f0d-01a4a1cc4647.png)

I don't think the second plot is the same as the subset of the first-one. I do not know what goes wrong.

**Comment by tskir** [comment]
@shanshenbing Hi! Could you please confirm which version of CNVKit you're using (output of `cnvkit.py version`)? Some plotting functionality was very recently fixed in v0.9.8.

**Comment by shanshenbing** [comment]
thess plots were generated by v0.9.7, I'll try 0.9.8 and see what happens.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kirill Tsukanov"<notifications@github.com&gt;; 
发送时间: 2021年1月31日(星期天) 上午9:30
收件人: "etal/cnvkit"<cnvkit@noreply.github.com&gt;; 
抄送: "单申兵"<1186426740@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [etal/cnvkit] wrong plot when using scatter command to plot chromosome sub-region (#566)





 
@shanshenbing Hi! Could you please confirm which version of CNVKit you're using (output of cnvkit.py version)? Some plotting functionality was very recently fixed in v0.9.8.

**Comment by shanshenbing** [comment]
when I using v0.9.8, I got this plot. The new version of cnvkit now has right cnv  plot, but I found the scale in VAF plot is not a region of chromosome, but a whole chromosome, so the 'KRAS' is labeled with wrong position in VAF plot.
![V)UP_S{ME8YHY`ET51_VUES](https://user-images.githubusercontent.com/42245493/106839747-cd1b8000-66d9-11eb-87d0-6b06be606ede.png)

**Comment by tskir** [comment]
@shanshenbing I've tried to reproduce this using some CNVKit test files, but with no luck—plotting appears to work fine in v0.9.8:

### Whole chromosome
```
./cnvkit.py scatter test/formats/p2-20_1.cnr -c chr12 -g KRAS -v test/formats/na12878_na12882_mix.vcf -i NA12878 -n NA12882 -o test1.png
```
![image](https://user-images.githubusercontent.com/10669118/108504500-e31a6a80-72ad-11eb-877b-c70b248b8e46.png)

### Subregion of the chromosome
```
./cnvkit.py scatter test/formats/p2-20_1.cnr -c chr12:10000000-60000000 -g KRAS -v test/formats/na12878_na12882_mix.vcf -i NA12878 -n NA12882 -o test2.png
```
![image](https://user-images.githubusercontent.com/10669118/108505115-d5191980-72ae-11eb-96e6-1ce5f4a9b481.png)

As you can see, the second plot is a faithful reproduction of the selected subregion, both for the copy numbers and for the VCF plot.

**Comment by tskir** [comment]
@shanshenbing Could you please try re-running your commands on CNVKit 0.9.8 for the whole chromosome _and_ the subregion, and posting both commands and both plots?

Looking a bit more carefully into your plot number 3, it looks to me that the VAF subscaling works—note, for example, highly concordant lack of data for both CN & VAF around 37Mb, which is presumably a centromere region. However, it looks possible that either the VCF or the samples used in plot number 3 are not the same as in plot number 1, causing the discrepancy you observe. Hence it would be useful if you could re-run the commands to see if this could be the case.

**Comment by shanshenbing** [comment]
I had a two-week vacation. And I'm sorry for a long time to answer your questions. I checked my data and found that it  was the old version of cnvkit0.9.7 which had a wrong scale in VAF of plot num 1. As you can see, the centromere region in chrom12(37Mb) in plot num1 has many snv points. I also plotted the whole chrom12 and got the following figure. Indeed, the figure is matching with the sub-region plot num 3. Thank you for your 
![56K(V6M%J~~A0%N8RX0LIZN](https://user-images.githubusercontent.com/42245493/110431716-20be2680-80e9-11eb-8ded-0cb4132640a0.png)
help.

**Comment by tskir** [comment]
@shanshenbing You're welcome! If you don't have further questions, could you please close this issue? (I don't have read access to this repo as I'm just a volunteer.)

**Comment by shanshenbing** [comment]
OK, Thank you
