### ISSUE TITLE
Can't install cnvlib

### ISSUE THREAD

**Issue by Josephhungyi** [etal/cnvkit#572]
Hello, I'm trying to find the possible bait file, so I used the guess_bait.py command. However, it reported the error: "ModuleNotFoundError: No module named 'cnvlib'". I could not install the cnvlib with pip or conda command. Can anyone give me any suggestions?

Thanks

**Comment by tskir** [comment]
Hi! cnvlib is a core part of CNVKit, it should have been installed alongside with it. Does cnvkit.py itself run fine for you? Which version are you using (`cnvkit.py version`)?

**Comment by tskir** [comment]
Hi @Josephhungyi, are you still having this issue? I'll be happy to help if this is the case

**Comment by Josephhungyi** [comment]
I have not exactly solved it, but I use it on docker to replace it on my server. 

Thanks

**Comment by tskir** [comment]
Thanks @Josephhungyi! I'm going to go ahead and close this issue for now; if you have any other problems please feel free to either reopen it, or submit a new one
