### ISSUE TITLE
bcbio channel installing old cnvkit by default?

### ISSUE THREAD

**Issue by mcast** [etal/cnvkit#60]
Hi,

In short: could you check please, that following the conda instructions for the bcbio channel actually give the latest version?  Or add some extra information on how to choose which version it will install?

Details: I'm afraid I'm submitting this issue for one of my users, I'm not experienced with `conda` and I don't know exactly what happened, but...

Judging from his `.bash_history`, he ran the advertised
```
conda config --add channels https://conda.binstar.org/bcbio
conda install cnvkit
```
and he got `cnvkit-0.2.5`.  Then he ran into various problems which have long been fixed.  I solved it by removing the installed copy, downloading the 0.7.3 zipfile and building that with `setup.py`.

I tried to ask conda what it would install, and (after I un-mangled the pasted terminal transcript) this is what it said

```
(cnvkit_env)mibxxxxxxi:1112_CNVkit hl11$ conda search cnvkit
Fetching package metadata: ......
cnvkit                    .  0.2.5                np19py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.3.1a               np18py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.3.2                np18py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.3.2                np19py27_1	https://conda.binstar.org/bcbio/osx-64/
                             0.3.5                np19py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.3.5                np19py27_1	https://conda.binstar.org/bcbio/osx-64/
                             0.3.5                np19py27_2	https://conda.binstar.org/bcbio/osx-64/
                             0.3.5                np19py27_3	https://conda.binstar.org/bcbio/osx-64/
                             0.3.5                np19py27_4	https://conda.binstar.org/bcbio/osx-64/
                             0.4.0                np19py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.4.0                np19py27_1	https://conda.binstar.org/bcbio/osx-64/
                             0.4.1                np19py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.4.1                np19py27_1	https://conda.binstar.org/bcbio/osx-64/
                             0.4.1                np19py27_2	https://conda.binstar.org/bcbio/osx-64/
                             0.4.1                np19py27_3	https://conda.binstar.org/bcbio/osx-64/
                             0.4.1                np19py27_4	https://conda.binstar.org/bcbio/osx-64/
                             0.5.0                np19py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.5.1                np19py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.6.1                np19py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.6.2a               np19py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.6.2a               np19py27_1	https://conda.binstar.org/bcbio/osx-64/
                             0.6.2a               np19py27_2	https://conda.binstar.org/bcbio/osx-64/
                             0.7.0.dev0           np19py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.7.0                np19py27_2	https://conda.binstar.org/bcbio/osx-64/
                             0.7.1.dev0           np19py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.7.1                np19py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.7.2                    py27_0	https://conda.binstar.org/bcbio/osx-64/
                             0.7.3dev0                py27_0	https://conda.binstar.org/bcbio/osx-64/

```

Thanks,
Matthew (for Henry )

**Comment by etal** [comment]
Thanks for reporting this. Excellent question -- I don't know how/why conda would install the oldest version by default instead of the newest. Is there a chance this user's conda installation is configured unusually?

@chapmanb maintains the bcbio channel on binstar for use in bcbio-nextgen -- Brad, have you seen this issue before? Is there anything I can add to CNVkit's installation instructions to make sure it doesn't happen?

**Comment by chapmanb** [comment]
Matthew and Eric;
Sorry about the problem. I'm confused as to why conda would select the old version over the latest. Is it possible you have an older version of conda? You could do `conda install conda` to get the latest; I don't know of any specific past bugs but it's always an idea.

Also, I recently moved the conda package building to the bioconda project, so you can do:
```
conda install -c bioconda cnvkit
```
to get the latest 0.7.3 (and any future versions). I'm trying to move contributions to this community project so will deprecate the bcbio specific channel. Hope either updating or using the new channel fixes the issue for you.

**Comment by mcast** [comment]
On Wed, Dec 02, 2015 at 10:31:59AM -0800, Eric Talevich wrote:

> Thanks for reporting this. Excellent question -- I don't know
> how/why conda would install the oldest version by default instead of
> the newest.

I should also say, I didn't try to reproduce the installation of the
old version.  At the time we just wanted the problem to go away, and
now I don't have access to the conda install.

> Is there a chance this user's conda installation is configured
> unusually?

I don't think so, but it was done by a third person assisting before I
arrived.  I believe it was just the obvious download and install.


On Wed, Dec 02, 2015 at 12:57:16PM -0800, Brad Chapman wrote:

> Sorry about the problem. I'm confused as to why conda would select
> the old version over the latest. Is it possible you have an older
> version of conda?

I'll report back with the version.

One thing that slowed down diagnosis of the problem is that cnvkit
doesn't seem to have a way to report its own version number, you have
to ask conda to do it.


> You could do `conda install conda` to get the latest; I don't know
> of any specific past bugs but it's always an idea.
> 
> Also, I recently moved the conda package building to the bioconda project, so you can do:
> ```
> conda install -c bioconda cnvkit
> ```

(Fixed by etal, thanks)

> to get the latest 0.7.3 (and any future versions). I'm trying to
> move contributions to this community project so will deprecate the
> bcbio specific channel. Hope either updating or using the new
> channel fixes the issue for you.

Well I fixed it with a manual build, so just wanted to make sure there
isn't a trap remaining for future users.

-- 
Matthew


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by mcast** [comment]
ugh, formatting fail from mail client, sorry.  can't seem to fix it from the web page.

**Comment by etal** [comment]
The older CNVkit did not have an easy way to report the version, but in newer releases you can use the `version` command. I've just added it to the docs, thanks for mentioning it:
http://cnvkit.readthedocs.org/en/latest/importexport.html#version

**Comment by mcast** [comment]
Henry was running conda 3.18.3 (released [2015-10-15](https://github.com/conda/conda/releases)).

**Comment by chapmanb** [comment]
Matthew;
I'm totally stumped why it would do this with an up to date conda. Sorry, I wish I had some explanation or could reproduce. I appreciate the heads up and hope it'll do the right thing for you going forward.

**Comment by mcast** [comment]
Well our installation is fixed, so my only concern in this issue is that it doesn't bite anyone else.
Thanks,
