### ISSUE TITLE
unable to locate output file from scatter when running via Docker

### ISSUE THREAD

**Issue by aadamk** [etal/cnvkit#605]
Hello, 
this may be an error in my usage, but I am unable to locate the output of the `scatter` command when running via docker. 

I first start up an interactive session: 
`docker run -it --name cnvkit -v "$(pwd)":/home/ubuntu etal/cnvkit`

In the interactive session, I run: 
`cnvkit.py scatter be8f7404-0e99-4eaa-b989-8ab568d46405.cnr -s be8f7404-0e99-4eaa-b989-8ab568d46405.call.cns`

However, nothing gets printed to stdout and I am unable to locate the output file at my mount point. Is there something I am omitting in the above commands?

**Comment by tetedange13** [comment]
Hi @aadamk,

Not an author of CNVkit but if you check 1st paragraph of [this part of CNVkit's documentation](https://cnvkit.readthedocs.io/en/stable/plots.html#plots-and-graphics), you'll see that default behaviour of `cnvkit.py scatter` if to show an **interactive Matplotlib plot** 
=> NO output file are written unless you add option: `-o my_nice_plot.png` 
(complete =  `cnvkit.py scatter -o my_nice_plot.png my_sample.cnr` )

Hope this helps.
Have a nice day.
Felix.

**Comment by aadamk** [comment]
Thank you Felix. I missed that part of the documentation. The above resolved the issue.
