### ISSUE TITLE
Heatmap borders per sample

### ISSUE THREAD

**Issue by Aikaterini-Chatzipli** [etal/cnvkit#610]
Hello, 

I run CNVkit on targeted sequencing data and generated a CN heatmap. I plotted approximately 90 samples in the heatmap which would be very useful to visualize having lines as borders separating the data per sample across all chromosomes. It's not easy to see where the borders of each sample are when plotting many samples on the same heatmap. Is there currently an option not obvious to me doing what I am describing? Please advise.

Many thanks, 

Katerina

**Comment by tskir** [comment]
Hi @Aikaterini-Chatzipli! Your suggestion makes sense, but I'm afraid there isn't an option available to do this right now. I also only have a very limited time per week to dedicate to CNVkit, so it's unlikely that this is going to be implemented in the foreseeable future.

I'm going to leave this issue up as an enhancement with a help-wanted flag. In case we have any volunteers in the audience to dig into the CNVkit plotting system and add this feature, it would be very much appreciated!

**Comment by tetedange13** [comment]
Hi @tskir  (and @Aikaterini-Chatzipli ),

A possible easy way to do it, is to add :
`axis.axhline(i, color='k')`, right after [L92 of `heatmap.py`](https://github.com/etal/cnvkit/blob/15d21cf9aae07c0e3a33acfadfc24066b21a4c11/cnvlib/heatmap.py#L92)
=> Do you want me to do a PR for with just this line ? (I can try to create one if you tell me so)
=> I can also add a dedicated flag parameter to the `heatmap` subcommand, like `--delimit_samples` or so

Have a nice day.
Kind regards.
Felix

**Comment by Aikaterini-Chatzipli** [comment]
Many thanks to both for your responses!

Dear Felix, 

Yes, it would be great if you could please modify the code by adding an extra parameter to it. 

Thanks and best wishes, 

Katerina

**Comment by tetedange13** [comment]
Hi @Aikaterini-Chatzipli ,

I forked CNVkit and added a `--delimit_samples` parameter here: https://github.com/tetedange13/cnvkit
=> Please until someone from CNVkit answer, **ask your questions or reports bugs *about this fork* on the [`Issues` section of my fork](https://github.com/tetedange13/cnvkit/issues)** rather than here (to avoid messing up CNVkit's offical repo about an unofficial code)

Hope this helps.
Have a nice day.
Felix
