### ISSUE TITLE
Improve documentation for read_auto()

### ISSUE THREAD

**Issue by BJWiley233** [etal/cnvkit#618]
Hi Authors,

Please add documentation that the files being read in CANNOT have a header under documentation of [read_auto](https://github.com/etal/cnvkit/blob/master/skgenome/tabio/__init__.py#L96).  This should also be placed under documentation [here](https://cnvkit.readthedocs.io/en/v0.9.5/nonhybrid.html?highlight=batch%20wgs#whole-genome-sequencing-wgs).  Simply like "be aware annotations should not have header".  UCSC files are downloaded with headers and as such you get the error if you have a header like:
```
Detected file format: refflat
/Users/brian/anaconda3/envs/cnvkit/lib/python3.8/site-packages/cnvlib/target.py:20: DtypeWarning: Columns (4,5) have mixed types.Specify dtype option on import or set low_memory=False.
  annotation = tabio.read_auto(annotate)
```
Thank!

**Comment by etal** [comment]
Thanks for reporting. Let me see if I can fix read_auto to handle UCSC BED headers automatically instead. I'll mark this as a bug.

**Comment by tskir** [comment]
I can help with implementing this. @BJWiley233 could you please provide an example of a UCSC file which causes the issue, and also preferrably which CNVkit command you're running it through?

**Comment by BJWiley233** [comment]
Sure I will get you one by tomorrow or Monday.  Happy 4th of July.

**Comment by etal** [comment]
Now `read_auto` should handle these header lines without error.
