### ISSUE TITLE
Error building docker image

### ISSUE THREAD

**Issue by tea-kostic** [etal/cnvkit#619]
Hi! 

I am trying to build a docker image using the Dockerfile provided [here](https://github.com/etal/cnvkit/blob/master/docker/Dockerfile).
I am getting this error:

```
RUN cnvkit.py version:                                                                                                            
#10 1.690 Traceback (most recent call last):                                                                                               
#10 1.690   File "/usr/local/bin/cnvkit.py", line 4, in <module>                                                                           
#10 1.690     from cnvlib import commands                                                                                                  
#10 1.690   File "/usr/local/lib/python3.8/dist-packages/cnvlib/__init__.py", line 5, in <module>                                          
#10 1.690     from .commands import *
#10 1.690   File "/usr/local/lib/python3.8/dist-packages/cnvlib/commands.py", line 34, in <module>
#10 1.690     from . import (access, antitarget, autobin, batch, bintest, call, core,
#10 1.690   File "/usr/local/lib/python3.8/dist-packages/cnvlib/batch.py", line 8, in <module>
#10 1.690     from . import (access, antitarget, autobin, bintest, call, core, coverage,
#10 1.690   File "/usr/local/lib/python3.8/dist-packages/cnvlib/segmentation/__init__.py", line 17, in <module>
#10 1.690     from . import cbs, flasso, haar, hmm, none
#10 1.690   File "/usr/local/lib/python3.8/dist-packages/cnvlib/segmentation/hmm.py", line 11, in <module>
#10 1.690     import pomegranate as pom
#10 1.690   File "/usr/local/lib/python3.8/dist-packages/pomegranate/__init__.py", line 11, in <module>
#10 1.690     from .base import *
#10 1.690   File "pomegranate/base.pyx", line 1, in init pomegranate.base
#10 1.690 ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

executor failed running [/bin/sh -c cnvkit.py version]: exit code: 1
```

What may be causing this error? How should it be resolved?

Thank you in advance,
Tea

**Comment by tetedange13** [comment]
Hi @tea-kostic ,

Not an author of CNVkit, but it seems to look like [this issue](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp)
=> Could you please run `python -c "import numpy; print(numpy.__version__)"`, to know which Numpy version were installed in your Docker?

Hope this helps.
Have a nice day.
Felix.

**Comment by tea-kostic** [comment]
Hi @tetedange13 ,

You are right, it was an older version of numpy, and once I specified in the dockerfile numpy version 1.20.0 it solved the issue.

Thanks a lot!
Have a great day.
Tea

**Comment by tetedange13** [comment]
@tea-kostic I am happy this solved your problem
=> But could you please **reopen this issue**?
=> Because I may be wrong but I think CNVkit's Dockerfile could be made less sensible to such "Numpy version conflicts" issue
<br>

*Ideas:*
- Move Aptitude-installed Python packages (like Numpy, Matplolib...) to a **unifed pip command** ?
- And/or add `--no-binary :all:` or simply `--no-binary` flag at [L19](https://github.com/etal/cnvkit/blob/b05e57bbe8d226d15e428c9c0fb873243feb0641/docker/Dockerfile#L19) ?
- Make sure to have a recent version of `pip` and use a `requirements.txt` + the fact that [dependencies-resolving was set as default behaviour for `pip>=20.3`](https://github.com/pypa/pip/issues/988#issuecomment-735776472) ?

**Comment by etal** [comment]
Thanks @tea-kostic for reporting and @tetedange13 for testing the solution. I've updated the Dockerfile to first update pip itself, then use it to install the `cnvkit` package directly, which seems to work fine now.
