### ISSUE TITLE
Can I use output of featurecounts output to replace the input of import-rna?

### ISSUE THREAD

**Issue by deb0612** [etal/cnvkit#627]
Dear sir,
I had problem to get the RSEM produces. Should I use other programs to get the input of import-rna ?

**Comment by tetedange13** [comment]
Hi @deb0612 ,
<br>

Not an author of CNVkit + not an expert in RNA data/tools
=> However it is said in [CNVkit's documentation](https://cnvkit.readthedocs.io/en/stable/rna.html#import-rna):
> * Gene counts: Alternatively, the gene Ensembl IDs and per-gene read counts can be read from a simple 2-column, tab-delimited file. This format is used by TCGA level 2 RNA expression data. You can also create the equivalent on your own from the output of another RNA quantification tool like Salmon or Kallisto.

Is it not what you want?
=> In other words, try to transform `featureCounts`'s output, to obtain a simple 2-column tab-delimited file with your by-gene counts? (cannot help you on this, sorry...)
<br>

Hope this helps.
Have a nice day.
Felix.

**Comment by tskir** [comment]
Hi @deb0612,

What @tetedange13 says is correct, however, `import-rna` should also support RSEM output. Could you share some more details about your workflow please, e.g. which parameters you're running `import-rna` with?

**Comment by tskir** [comment]
Hi @deb0612, just wanted to check in with you to see if this issue is still relevant. If so, could you please provide the parameters you're running `import-rna` with?
