### ISSUE TITLE
diagram parameter

### ISSUE THREAD

**Issue by lmanchon** [etal/cnvkit#629]
--Hi all,

is there an option to plot diagram without gene labels ?
i have too much gene name on my chromo.

thank you --

**Comment by tetedange13** [comment]
Hi @lmanchon ,

Not an author of CNVkit, but ASKAIK, it is **not possible to disable them completely**
=> Maybe try to reduce the number of called CNV, as explained [here](https://cnvkit.readthedocs.io/en/stable/plots.html#reducing-cluttered-gene-labels) in CNVkit's documentation ?

Hope this helps.
Have a nice day.
Felix.

**Comment by tskir** [comment]
Hi @lmanchon!

The suggestion by @tetedange13 indeed makes a lot of sense. If you're having so many gene labels that they're interfering with the diagram, changes are that something went wrong in the process of calling the CNVs. Would you mind sharing the diagram so that we could see what could be the reason?

However, if you're certain that the calling parameters are correct and there is a valid reason for there to be so many CNVs (e.g. it's a highly mixed up tumour genome), I suppose we could add a flag to disable gene names, it shouldn't be too hard.

In the meanwhile, as a workaround, you can simply edit CNR/CNS file and to fill the `gene` column with dashes (`-`)

**Comment by lmanchon** [comment]
see below the plot generated with those commands:
cnvkit.py batch SRR6823378_recalibrated.bam -n -m amplicon --segment-method hmm-germline -f Homo_sapiens_hg38.fasta --annotate refFlat.txt --short-names -t exome.bed -d OUTPUT_CNV -p 0 --drop-low-coverage --target-avg-size 300
cnvkit.py scatter -s OUTPUT_CNV/SRR6823378_recalibrated.cn{s,r} --y-max 5 --y-min -5 --title SRR6823378 -o OUTPUT_CNV/SRR6823378_CNV_scatter-log2.pdf
cnvkit.py diagram -s OUTPUT_CNV/SRR6823378_recalibrated.cn{s,r} -t 1 -o OUTPUT_CNV/SRR6823378_CNV_diagram.pdf



![diagram](https://user-images.githubusercontent.com/3015749/123225773-538efd80-d4d3-11eb-9c72-c7461a92ad8b.png)
![scatter](https://user-images.githubusercontent.com/3015749/123225775-54279400-d4d3-11eb-8ddf-09e56951bf53.png)

**Comment by tetedange13** [comment]
Hi @lmanchon ,
<br>

You have a **WES germline dataset**, so no particular reason for you to have many CNV I guess? (I mean regarding @tskir remark)
=> However are you really on an "amplicon" method? If yes, have you try to stop marking duplicate reads, as you were suggested in #628 ?

You also are setting a lot of custom values for parameters. Any particular reason for that? Have you tested different things?
=> For example [Germline Analysis](https://cnvkit.readthedocs.io/en/stable/germline.html) part of CNVkit documentation says using `--drop-low-coverage` can be risky in your case
=> And "hmm*" segmenting methods usually produce more small segments (to detect more focal CNV), so maybe it comes from there" ?
<br>

Hope this helps.
Have nice day.
Felix.

**Comment by lmanchon** [comment]
--Hello @tetedange13,

as you suggested i'm going to try using another parameters, also i use this bed file:
https://www.twistbioscience.com/sites/default/files/resources/2019-06/Twist_Exome_Target_hg38.bed

what do you mean by "amplicon" method ? is WES analysis an amplicon method or not ?

thank you so much--

**Comment by tetedange13** [comment]
To sum up, except for WGS any NGS method requires an enrichment step, to get regions of interest (eg: panel of genes, whole exome *etc*)
=> To do so several methods exist, with their own properties, such as:
* *Amplicon*, where you PCR-amplify your regions with specify primers
* *(hybrid-)capture*, where you add probes designed to catch your desired targets

CNVkit can handle all 3 methods but was primarily designed for hybrid-capture data (see [this part of CNVkit's documentation](https://cnvkit.readthedocs.io/en/stable/nonhybrid.html) for detailed behaviour depending on the method)
=> Also I see you are working on this [public dataset](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR6823378) right? In metadata I saw it is obtained with "Agilent SureSelect XT Human All Exon Kit V5" and not Twist Exome...
=> So you should rather use one of [these BED files](https://github.com/AstraZeneca-NGS/reference_data/tree/master/hg38/bed), supposing your BAM were made against hg38 ?

Anyway your biggest problem is setting `-m amplicon` when you have sequencing data made with hybrid-capture method (both Twist's and Agilent's exomes are)
=> Simply remove this (default method is `-m hybrid(-capture)`), stick with default parameters to start and see if this is better
<br>

Best,
Felix.

**Comment by lmanchon** [comment]
--Hi,

i have tried again with the commands below and with or without mark duplicates, i obtain the attached results(see pictures)
![scatter](https://user-images.githubusercontent.com/3015749/123769586-bca6b480-d8c9-11eb-97cc-aa70f631b4c5.png)

cnvkit.py batch SRR6823378.bam -n -m hybrid -f Homo_sapiens_hg38.fasta -t Exome-Agilent_V5.bed -d OUTPUT_CNV -p 0
cnvkit.py scatter -s OUTPUT_CNV/SRR6823378.cn{s,r} --y-max 5 --y-min -5 --title SRR6823378 -o OUTPUT_CNV/SRR6823378_CNV_scatter-log2.pdf
cnvkit.py diagram -s OUTPUT_CNV/SRR6823378.cn{s,r} -o OUTPUT_CNV/SRR6823378_CNV_diagram.pdf

i have less points on the scatter but too much labels on diagram.

![scatter](https://user-images.githubusercontent.com/3015749/123769668-d2b47500-d8c9-11eb-8152-6a77f82c3922.png)
![diagram](https://user-images.githubusercontent.com/3015749/123769670-d34d0b80-d8c9-11eb-89d8-68774d9aa19c.png)

**Comment by tetedange13** [comment]
Hi @lmanchon ,
<br>

Looks way better to me, compared to your previously shared scatter plot !
=> **But someone else might confirm ?**

Regarding your `diagram`:
* Please be certain that you are plotting from correct new both ".cn{r,s}", not the old ones (can be easy to mix things up)
* I noticed in your new commands that **you are not setting `-t/--threshold` parameter to `1` anymore**, even though you used to (and default value for this param is 0.5) --> **hard to compare**

Anyway if you are still having a lot of CNV, a quick workaround could be to simply change to `diagram -s OUTPUT_CNV/SRR6823378.call.cns` (this one has **call** in its name)
=> This ".call.cns" file should be present in your output directory if you are running latest CNVkit version (which I advice you to) and has been **post-processed to remove some likely false-positive CNV** (see [here for details](https://github.com/etal/cnvkit/releases/tag/v0.9.7.b1))
=> And as said before, you should find details in [CNVkit's documentation](https://cnvkit.readthedocs.io/en/stable/plots.html#reducing-cluttered-gene-labels) about this topic

Also a flag to disable gene_name labels should be available anytime soon
<br>

Kind regards.
Felix.

**Comment by lmanchon** [comment]
ok thank you, i'm investigating some change. In attachment here the result file from SRR6823378 analysis.
btw another parameter would be usefull: possibility to plot diagram for only one chromosome (as scatter option)
[Uploading SRR6823378.zip…]()

**Comment by lmanchon** [comment]
cnvkit.py version
0.9.9

ok thank you, i'm investigating some change. 
btw another parameter would be usefull: possibility to plot diagram for only one chromosome (as scatter option)
In attachment the result file from SRR6823378 analysis.
[Uploading SRR6823378.zip…]()

**Comment by lmanchon** [comment]
cnvkit.py version
0.9.9

ok thank you, i'm investigating some change. 
btw another parameter would be usefull: possibility to plot diagram for only one chromosome (as scatter option)
In attachment the result file from SRR6823378 analysis.
[SRR6823378.zip](https://github.com/etal/cnvkit/files/6735727/SRR6823378.zip)

**Comment by tskir** [comment]
Reopening the issue until #634 is merged
