### ISSUE TITLE
CNVkit exon del detection

### ISSUE THREAD

**Issue by skose82** [etal/cnvkit#654]
Hi all,

I've produced two scatter plots from two different samples. I am looking for an exon 2 deletion in the SUFU gene in sample 2. I produced a scatter plot of sample 1 as a control as this sample does not have any known exon 2 deletions. The output of the plots are quite different. 

1. Is there a way to zoom in on chr10 to the SUFU exon 2 region to see if a deletion is present in sample 2?
2. Why are these plots so different in general? e.g. why is the orange baseline slightly lower in sample 2?
3. Is there a better plot to use than scatter? 

Any advice would be greatly appreciated.

Best wishes
![sample1_scatter](https://user-images.githubusercontent.com/32903403/127477493-125996f4-4769-420b-86a0-d7daedadfdb5.jpg)
![sample2_scatter](https://user-images.githubusercontent.com/32903403/127477951-07966086-8f32-484f-91ad-2f732188cdd1.jpg)

**Comment by enes-ak** [comment]
Hi, 
I am not an author of cnvkit but I have some experience with this tool. 

you can use that code if you know the exact location of your interested exon
`cnvkit.py scatter -s Sample.cn{s,r} -c chr10:start_loc-end_loc` 

or you can use that code
`cnvkit.py scatter -s Sample.cn{s,r} -c chr10 -g SUFU`

Are you sure about the select true bed file for analysis? target regions and your experiment bed file should be the same to take reliable results.

**Comment by skose82** [comment]
Thanks enes-ak, I ended up using a different program in the end which was a little more straightforward.

**Comment by DineshRavindraRaju** [comment]
@skose82 , Can you share which programs you used to detect CNVs in WES data?
