### ISSUE TITLE
PKD1 gene show negative log2CN with high coverage.

### ISSUE THREAD

**Issue by zhuhenan** [etal/cnvkit#659]
Hi,

I got confused about the deletion of the PKD1 gene found in some of my samples. The cns files show a breakpoint in the PKD1 gene suggesting a completed deletion of 1/3 gene. But when I check the cnn and cnr files, the coverage of the PKD1 is ~300x. So I am not sure why the pipeline suggests a deletion in this region. 

I have attached the chr16 of cnn, cnr, and cns files from one of my samples. 

Best,
Henan

[chr16.rename.zip](https://github.com/etal/cnvkit/files/7173198/chr16.rename.zip)

**Comment by tetedange13** [comment]
Hi @zhuhenan,
<br>

Thanks for sharing your files, but it can be hard to explain your results without knowing how you generated them (exact CNVkit commands you used)

I will assume you have WES data and in a case with both normal and tumor samples
=> When CNVkit is used this way, [`fix`](https://cnvkit.readthedocs.io/en/stable/pipeline.html#fix) step will calculate a log_ratio value per region/bin, by comparing coverage in current tumor sample ("antitargetcoverage.cnn", "targetcoverage.cnn") with coverage on same region from a reference produced with all "normal" samples you gave ("reference.cnn") 
=> Following [`segment`](https://cnvkit.readthedocs.io/en/stable/pipeline.html#segment) step will use these log_ratio values to determine boundaries of segments with same log_ratio and their corresponding height

So looking at an individual value of coverage of some sample will not actually give you a lot of information
=> If you have for this region a log_ratio=-1.4 and coverage=~300X , it means there you have ***several bins where 300X can be considered a lower coverage regarding you reference coverage there***
=> I suggest you to look also at your "reference.cnn" file, how are covered these regions overlapping your deleted segment?
Also if you visualise your cnr,cns files with `scatter` (exact parameters: ` --by-bin -c chr16:2089716-3136227 -s chr16.rename.cns chr16.rename.cnr`)
=> You see this deleted orange segment on PDK1 looks justified, based on associated gray probes position (lower in this genomic area):
![Figure_1](https://user-images.githubusercontent.com/26798040/133791574-585529ec-79f7-4066-ba0c-b94ca27dadb9.png)
<br>

I hope this answered your question.
Have a nice day.
Felix.

**Comment by zhuhenan** [comment]
Hi @tetedange13,

You are marvelous. This is exactly the answer I am expecting. 

Best,
Henan
