### ISSUE TITLE
Can i use tumor samples to generate reference files?

### ISSUE THREAD

**Issue by weizhiting** [etal/cnvkit#676]
Hi, thanks for this wonderful tool.
I have bam files of two groups patients, A group and B group. Every patient has normal sample and tumor sample.  I want to get genes that are enriched in B group compared to A group.  One way to do this is:  compare A group tumor to A group normal,  compare B group tumor to B group normal.  and use the segment file to run gistic2, separately.  Finally, genes enriched in B and not in A is the results.
Another way is to use A group tumor sample as reference directly,  and  compared it with B group tumor sample.  then run gistic2 with the segment file. So i want to ask is this method reasonable?
Thanks for your reply!

**Comment by philtat** [comment]
Yes, the -n option will do this

https://cnvkit.readthedocs.io/en/stable/quickstart.html#build-a-reference-from-normal-samples-and-infer-tumor-copy-ratios

from the link above:
"If you have no normal samples to use for the reference, you can create a “flat” reference which assumes equal coverage in all bins by using the --normal/-n flag without specifying any additional BAM files:"

**Comment by weizhiting** [comment]
Sorry for that i did not make it clear.
I want to make sure if can i use the command
`cnvkit.py reference  *Tumor.coverage.cnn  -f  ref.fasta -o  Reference.cnn`
to build reference,  which  Tumor.coverage.cnn  is the tumor sample coverage.

**Comment by etal** [comment]
Yes: giving these tumor samples as input to the `reference` command will work the same as giving these samples to `batch -n`.
