### ISSUE TITLE
Inconsistency in Docs?

### ISSUE THREAD

**Issue by kyleabeauchamp** [etal/cnvkit#68]
So the documentation on batch (http://cnvkit.readthedocs.org/en/latest/pipeline.html) suggests that batch runs `cnvkit targets` as one of its steps.  However, as far as I can tell, `targets` takes a BED as input and outputs a new BED---while `batch` does not output a new BED file for the targets.  This has implications when you pass the `--annotate` flag, as no annotation is actually done via `batch` as far as I can tell.  

Let me know if I'm mis-reading something here.

**Comment by etal** [comment]
Yes, it should write the new targets to a file with the suffix `.target.bed` if `--annotate` (or `--split` or `--short-names`) is given. This should be in the same output directory as the other files. Can you show the command line you used?

**Comment by kyleabeauchamp** [comment]
OK, I can confirm that the new file is written when I add back in the annotate command.  I guess I was surprised that the `target` step basically does nothing in the case that none of those extra flags are given.  You can close this issue, although it may be worth adding a line in the docs about this.

**Comment by kyleabeauchamp** [comment]
Maybe something like "If any of these three flags are used, a new target BED file will be created; otherwise, the provided target BED file will be used as-is."

**Comment by kyleabeauchamp** [comment]
See #69
