### ISSUE TITLE
LOH: Read germline SNPs from paired tumor-normal VCF

### ISSUE THREAD

**Issue by etal** [etal/cnvkit#7]
The functions to plot loss-of-heterozygosity (LOH) take allele frequencies from a given VCF file. LOH is only visible in germline SNPs that are also present in the tumor sample. Currently, all SNVs in the VCF are plotted, so this works best if the user had the foresight to separately filter the tumor variants for germline SNPs first.

VCFs from MuTect, FreeBayes and other variant callers will list the SNPs/SNVs in a matched tumor-normal pair together; this makes it feasible for CNVkit to parse this VCF and extract only the allele frequencies of SNPs for plotting.

The tumor sample name can be specified with `-i` now. *Next:*
- Add `-n` to specify the normal sample name in the same VCF.
- If `-n` is unspecified and there are 2 or more samples, look for "NORMAL" (case-insensitive); if `-i`is unspecified, look for "TUMOR".
- Fall back to current behavior if none of this magic works.

**Comment by Lenbok** [comment]
You could also pick up the normal and tumor sample names as commonly denoted in the VCF header:

    ##PEDIGREE=<Derived=tumorName,Original=normalName>

**Comment by etal** [comment]
With 9730f89, we're mostly there. Remaining work:

1. In the FreeBayes and MuTect files I'm working with, the SNPs we need for this plot are marked "REJECT" in the FILTER column, so I've added an option to keep these lines by default, which I suspect might break something in bcbio-nextgen (holla @chapmanb @roryk) -- any suggestions for a better method would be greatly appreciated.

2. For tumor-only VCFs, or paired T/N VCFs with lingering noise, it would be nice to take another VCF of known SNPs from 1000 Genomes, dbSNP 129, ESP 6500, etc. and further filter the variants in the given sample.

3. @Lenbok - Which callers add the PEDIGREE line? I'll add a check for it if I can do so reliably.

**Comment by Lenbok** [comment]
It is in section 5.4.11 of the VCF specification. RTG somatic and pedigree callers add PEDIGREE headers, I don't know about others.

Currently the RTG somatic caller only outputs sites where it thinks point mutations have occurred or where it looks like loss-of-heterozygosity may be the cause (i.e. normal != tumor), but for picking up actual LOH runs you also need the regular germline calls to be output too -- we're currently improving that.

**Comment by etal** [comment]
CNVkit handles the standard PEDIGREE tag and MuTect's GATK-specific header tag along with the command-line options `-i` and `-n` with reasonable thoroughness now.

I'll put the feature for 1000 Genomes VCF filtering in another issue.
