### ISSUE TITLE
ERROR: test_metrics (__main__.CommandTests)

### ISSUE THREAD

**Issue by yech1990** [etal/cnvkit#70]
```python
ERROR: test_metrics (__main__.CommandTests)
The 'metrics' command.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cnvlib.py", line 369, in test_metrics
    resids = cnarr.residuals(segments)
AttributeError: 'CopyNumArray' object has no attribute 'residuals'

======================================================================
ERROR: test_segmetrics (__main__.CommandTests)
The 'segmetrics' command.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cnvlib.py", line 403, in test_segmetrics
    lo, hi = commands._segmetric_interval(segarr, cnarr, func)
  File "/usr/local/lib/python2.7/dist-packages/cnvlib/commands.py", line 1367, in _segmetric_interval
    out_vals_lo[i], out_vals_hi[i] = func(bins, k)
TypeError: <lambda>() takes exactly 1 argument (2 given)

======================================================================
ERROR: test_autosomes (__main__.GaryTests)
Test selection of autosomes.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cnvlib.py", line 53, in test_autosomes
    autox = self.ex_cnr.autosomes(also='chrX')
TypeError: autosomes() got an unexpected keyword argument 'also'

----------------------------------------------------------------------
Ran 31 tests in 10.987s

FAILED (errors=3)
```

**Comment by yech1990** [comment]
```python
In [1]: import cnvkit 

Warning message:
In local({ : bytecode version mismatch; using eval
Error in objects(db.pos, all.names = TRUE) : 
  3 arguments passed to .Internal(ls) which requires 2
Error in .Internal(getOption(x)) : 
  there is no .Internal function 'getOption'
During startup - Warning message:
unable to restore saved data in .RData 
```

**Comment by etal** [comment]
First error: It looks like your installed version of `cnvlib` is not the up-to-date one in your copy of the git repository. The test suite is using the current API, but your installation of CNVkit is older. Try installing it in-place:

    pip install -e .

**Comment by etal** [comment]
Second message: Try `import cnvlib` (anywhere but the top level of the source repo) instead of `import cnvkit`.

I can't explain why `import cnvkit` tries to load R code, but the Python library you want is `cnvlib`. Does that work for you?

**Comment by yech1990** [comment]
the first error was solved by ``pip install -e .``

```bash
----------------------------------------------------------------------
Ran 31 tests in 17.804s

OK

```

**Comment by yech1990** [comment]
``import cnvlib`` does not return error message.
But I wonder what's the difference between ``cnvlib`` and ``cnvkit``.

**Comment by etal** [comment]
When you run `import cnvkit` from the top level of the source tree, instead of importing the intended library `cnvlib` (under the directory of the same name), it finds the script `cnvkit.py` in the same directory and imports it as a module. However, that script isn't intended to be used as a module, so it doesn't do anything useful when imported this way.

**Comment by yech1990** [comment]
```bash
cnvkit.py scatter -h
```
```bash
Warning message:
In local({ : bytecode version mismatch; using eval
Error in objects(db.pos, all.names = TRUE) : 
  3 arguments passed to .Internal(ls) which requires 2
Error in .Internal(getOption(x)) : 
  there is no .Internal function 'getOption'
During startup - Warning message:
unable to restore saved data in .RData
```

**Comment by yech1990** [comment]
how to fix this problem?

**Comment by etal** [comment]
There is something unusual about your installation. Can you tell me how you installed CNVkit on your machine, and check how cnvkit.py is being run?

To see where the script was installed:

    which cnvkit.py

To see the first line of that script as it was installed (should be `/usr/bin/python` or similar):

    head -n1 `which cnvkit.py`

Also try deleting the file `.RData` in the current directory and see if the message still appears.

**Comment by yech1990** [comment]
###  the installation process:

- Firstly, I just run `pip install cnvkit`, but failed in running `python test_cnvlib.py`.

- Then I clone this respiratory into my local directory, and execute `pip install -e .` . The testing succeed. 

----

```bash
$ which cnvkit.py

/usr/local/bin/cnvkit.py
```


```bash
$ head -n1 `which cnvkit.py`

#!/usr/bin/python
```

**Comment by etal** [comment]
The installation looks normal to me. After you've removed .RData and changed to a different directory, does CNVkit seem to run successfully? If you change to the `test/` diretory and type `make`, does the pipeline run?

If so, I guess we're OK. Otherwise, you could try uninstalling CNVkit with pip and reinstalling with Miniconda, which should also handle the R dependencies automatically now.
