### ISSUE TITLE
Is there any good ideas about  which options/method of  cnvkit would be recommended  when calling CNAs in ctDNA samples? Due to unknown sample purity ,I hava got so much genes and segments in my ctDNA sample with subcommand genemetrics.

### ISSUE THREAD

**Issue by whiffen-cann** [etal/cnvkit#701]
I have used the following options :
subcommand：

- segment    --drop-low-coverage --drop-outliers 

- call -filer ci ,sem ,ampdel,cn

**Comment by whiffen-cann** [comment]
hi @etal,the sequencing method for my ctDNA samples  is enriching the whole exome.


> It depends on the type of sequencing you're doing for these ctDNA samples. Are you capturing/amplifying a gene panel, enriching the whole exome, or sequencing the whole genome?
> 
> You can estimate tumor fraction with PureCN; that might help. Generally, `segmetrics --ci --alpha .1 --drop-low-coverage` and `call --filter ci` should help.



> It depends on the type of sequencing you're doing for these ctDNA samples. Are you capturing/amplifying a gene panel, enriching the whole exome, or sequencing the whole genome?
> 
> You can estimate tumor fraction with PureCN; that might help. Generally, `segmetrics --ci --alpha .1 --drop-low-coverage` and `call --filter ci` should help.

**Comment by whiffen-cann** [comment]
Hi @etal,the sequencing method for my cfDNA samples is enriching the whole exome。

**Comment by etal** [comment]
Answered: PureCN for fraction, segmetrics --ci + call --filter ci. Closing as answered — please reopen, or open a new issue, if a concrete problem remains.

For general usage questions, we now use GitHub Discussions (Q&A): https://github.com/etal/cnvkit/discussions
