### ISSUE TITLE
Expose MIN_MAPQ in batch?

### ISSUE THREAD

**Issue by kyleabeauchamp** [etal/cnvkit#71]
1.  Is this hyperparameter something that you've played with?
2.  Is it worth exposing as an option in `batch`?  I see it's already exposed in `coverage`.

**Comment by etal** [comment]
I've tested this parameter using the `coverage` command. MAPQ filtering seems to make the results significantly worse, even if the filter is as low as `-q 1`. So the ambiguously mapped reads do seem to provide a useful indicator of copy number, in aggregate at least. (This is based on mappings from bwa-mem.)

The CNVnator team found the [same result](http://genome.cshlp.org/content/21/6/974.long) (see Methods / Read placement) with MAQ, BWA's predecessor.

**Comment by kyleabeauchamp** [comment]
Cool, sounds like it's best to keep it hidden for most users.
