### ISSUE TITLE
Replace ngfrills.faidx with pyfaidx

### ISSUE THREAD

**Issue by etal** [etal/cnvkit#73]
Use the better, still-lightweight implementation [pyfaidx](https://github.com/mdshw5/pyfaidx).

Adds a dependency on `six`, but that was probably due to happen eventually anyway for #3.

**Comment by kyleabeauchamp** [comment]
FWIW, it looks like we have `pyfaidx` in bioconda:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pyfaidx/meta.yaml

**Comment by etal** [comment]
Closed via #73. It will be in the next CNVkit release (not today's v0.7.10).
