### ISSUE TITLE
How is generated the heatmap?

### ISSUE THREAD

**Issue by msubirana** [etal/cnvkit#732]
Hi!

I want to generate a heatmap with de CNV generated by cnvkit and cluster them using hierarchical clustering (Ward.D2 algorithm). My question is about how do you define the bins or the segments in the x axis (genome) for plotting the heatmap in your package. I mean. how I can end up with a dataframe with position and log2 of the cnv if every sample have different positions of the cnvs?

**Comment by tetedange13** [comment]
Hi @msubirana ,
<br>

I do not think the internal matrix can be easily exported for now
=> A few points about the `heatmap` command:
* It be generated from several ".cnr" and these files all have same "x-axis" (if obtained running CNVkit with same "baits" BED)
=> In this case, I guess you could obtain a matrix using Unix's `paste` with all your ".cnr" ? (probably simplier than trying to export it from CNVkit internal objects)

* It can also be generated from several ".cns" that, as you said, can show different CNV so different coordinates ("x-axis")
=> I will have to check the code to see how it is handled internally
=> Even if you can obtain such matrix, it will by nature be a "sparse" one (with "null" values at several coefficients), so are you sure this a proper input for a clustering algorithm ? (I am not an expert at all)
<br>

Hope this helped a bit !
Have a nice day.
Felix.

**Comment by dudududu12138** [comment]
> Hi!
> 
> I want to generate a heatmap with de CNV generated by cnvkit and cluster them using hierarchical clustering (Ward.D2 algorithm). My question is about how do you define the bins or the segments in the x axis (genome) for plotting the heatmap in your package. I mean. how I can end up with a dataframe with position and log2 of the cnv if every sample have different positions of the cnvs?

Hello,I have the same question as you. Do you know how to do it later? Thank you very much!
