### ISSUE TITLE
Error using docker image for CNVkit 0.9.9 on DNAnexus

### ISSUE THREAD

**Issue by mwarrier123** [etal/cnvkit#747]
I tried loading the docker image for the latest version of CNVkit (0.9.9) and was getting the following error on this command:

docker run -v /home/dnanexus:/workdir -w /workdir etal/cnvkit:0.9.9 cnvkit.py version

Error message:
<img width="706" alt="Screen Shot 2022-07-12 at 5 45 07 PM" src="https://user-images.githubusercontent.com/52429099/178624592-d63d4297-20cf-4f6b-a34c-6bc533105712.png">

<img width="1068" alt="Screen Shot 2022-07-12 at 5 45 38 PM" src="https://user-images.githubusercontent.com/52429099/178624629-e2ebd891-d95a-4d26-979f-6de1e6e1d970.png">

Any troubleshooting ideas would be much appreciated! Thank you!

**Comment by etal** [comment]
I've uploaded the fixed 0.9.9 image to Docker hub: https://hub.docker.com/repository/docker/etal/cnvkit/general
