### ISSUE TITLE
how to make CNVkit use a defined local Version of R/ Rscript in a local install

### ISSUE THREAD

**Issue by claus-h-g** [etal/cnvkit#757]
Hi,
many thanks for providing CNVkit.

On xUbuntu 18.04 I would like to use a local installaton of CNA kit not using the local preinstalled system R but a R version I did install in addition to the existing one, so I can run a version pinning without (hopefully) affecting any other  analysis steps on this machine.
After following the instruction for a local installation
git clone https://github.com/etal/cnvkit
    cd cnvkit/
    pip install -e .
and the installation of dependencies,

I did adjust the Makefile in /cnvkit/test so the correct Rscipt is used.
After running
 make
The test completed without any error message.

How do I transfer the modifications to the Makefile to the CNVkit config for analyzing real samples?

**Comment by claus-h-g** [comment]
A friend suggested to expand the $PATH in the activate for  my Python virtual (!= conda) environment. That seems to do the trick. sorry for posting

**Comment by whiffen-cann** [comment]
add the path of  Rscript to your $PATH，for my conda installtion , it's same as the path of cnvkit.py .For example,whent I execute my cnvkit.py ,I execute "  export PATH=/data1/software/install-miniconda3/envs/cnvkit/bin/:$PATH  "
