### ISSUE TITLE
Docker needed

### ISSUE THREAD

**Issue by kopardev** [etal/cnvkit#769]
the latest docker at https://hub.docker.com/r/etal/cnvkit/ is for version 0.9.8...can you upload one for 0.9.9?

**Comment by marrip** [comment]
Does this one help: `docker pull quay.io/biocontainers/cnvkit:0.9.9--pyhdfd78af_0`?

**Comment by etal** [comment]
I've pushed the 0.9.9 image to Docker Hub: https://hub.docker.com/repository/docker/etal/cnvkit/general#
