### ISSUE TITLE
Optionally consider PAR1/2 as diploid in male samples due to reference genome masking

### ISSUE THREAD

**Issue by rollf** [etal/cnvkit#784]
Hi,

I'd like to address a problem that was already mentioned by @gabeng in this [issue](https://github.com/etal/cnvkit/issues/267). The pseudoautosomal regions in chr Y are masked (by `N`) in hg38 and it also common practice to do so in hg19/GRCh37-based pipelines (see for reference this [GATK blog entry](https://gatk.broadinstitute.org/hc/en-us/articles/360035890951-Human-genome-reference-builds-GRCh38-or-hg38-b37-hg19)). In consequence, the coverage of male samples within the PAR1/2 on chromosome X appears 'doubled'. For example, I have a couple of whole exome samples where one can clearly see this based on the cnn coverage file:

![male01 targetcoverage cnn log2 X0-2500](https://user-images.githubusercontent.com/58295931/213410501-ecc270cf-c947-42a5-ad0e-667352344aef.png)
![male01 targetcoverage cnn depth X0-2500](https://user-images.githubusercontent.com/58295931/213410493-867ba2e7-6594-426c-a865-7a236521c106.png)

The plots show the first 2500 target regions. In contrast, see a female sample:

![female01 targetcoverage cnn depth X0-2500](https://user-images.githubusercontent.com/58295931/213411697-70850d85-0e2c-48d0-8974-582e37f24d43.png)

--- 

Feeding a male-only pool through the usual cnvkit workflow (`reference`, `fix`, `segment`), the previously doubled coverage in PAR1 within the male samples gets lost. The sample has log2 ~ -1 across the whole chromosome.

![male01 cnr master log2 X0-2500](https://user-images.githubusercontent.com/58295931/213410894-2fa14666-8730-49ea-9328-74b816eca588.png)

Furthermore, feeding a mixed pool (5 male, 5 female samples) into the pipeline, the PAR1 region in both samples gets biased. Male samples have log2 ~ -0.5 (i.e. higher than in the male-only pool) and female samples have log2 ~ -0.5 (i.e. lower than in a female-only pool), too (in PAR1 only):

![male01 mixed cnr master log2 X0-2500](https://user-images.githubusercontent.com/58295931/213411490-bbb50bcc-60a1-4685-af7c-0d6e75f970a2.png)
![female01 mixed cnr master log2 X0-2500](https://user-images.githubusercontent.com/58295931/213411533-657b74fe-940f-4c07-97af-df6821e2564d.png)

---

All of this is quite understandable as chromosome X is simply considered haploid for males samples. This is of course correct from a genetics point of view. However, technically, the healthy male samples are expected to be diploid within PAR1/2 because all reads from chr Y in PAR1/2 are aligned to chr X (due to the masking). The results above make it hard to diagnose copy number aberrations within PAR1/2.
For testing purposes, I have implemented some changes in current code base of cnvkit to consider PAR1 as diploid. Namely, [`GenomicArray.autosomes()`](https://github.com/etal/cnvkit/blob/8af9b166165594a1e0df10e6d263f356c26ecce7/skgenome/gary.py#L208) includes PAR1 and sex-related code paths referring to [chr X](https://github.com/etal/cnvkit/blob/8af9b166165594a1e0df10e6d263f356c26ecce7/cnvlib/cnary.py#L38) exclude PAR1. This yields the results as expected from the coverage data. Male samples have log2 ~ 0 for PAR1 (for both male-only and mixed pools) and female samples stay at log2 ~ 0 in PAR1 even for mixed pools:

![male01 mixed cnr xwop log2 X0-2500](https://user-images.githubusercontent.com/58295931/213662384-970309de-77eb-4f28-aa5e-e907ee663d6a.png)
![female01 mixed cnr xwop log2 X0-2500](https://user-images.githubusercontent.com/58295931/213414967-29337b3c-7eb8-4bef-88f5-55e3f92fc5ff.png)

I would be interested in integrating this change into cnvkit. This could be an optional feature, of course. I'm happy to provide an initial draft PR in order to discuss this from a more technical point of view. Please let me know if you're interested in this.

**Comment by rollf** [comment]
Hey @etal,

any feedback on this from your side? As I said, I'm happy to do the actual work given green lights from your side.

**Comment by etal** [comment]
This makes sense to me. Sure, I'd love to see a PR.

**Comment by rollf** [comment]
Closing this the issues was solved by #789
