### ISSUE TITLE
cnvkit metrics fails when no segments given

### ISSUE THREAD

**Issue by kyleabeauchamp** [etal/cnvkit#79]
Pretty easy fix: check for None before calling `len()`.  There is a question of intent, though--do you intend for segments to be optional?  Not clear unless I dig in the code a bit more.

```
cnvkit.py metrics *.cnr
[...]
Traceback (most recent call last):
  File "~/opt/bin/cnvkit.py", line 11, in <module>
    args.func(args)
  File "~/opt/lib/python2.7/site-packages/cnvlib/commands.py", line 1359, in _cmd_metrics
    if (len(args.cnarrays) > 1 and len(args.segments) > 1 and
TypeError: object of type 'NoneType' has no len()
```

**Comment by etal** [comment]
Just struggling with argparse. I thought `nargs='+'` would make an argument required, but apparently not. Thanks for catching it.
