### ISSUE TITLE
cnvkit reference doesn't expose fix parameters?

### ISSUE THREAD

**Issue by kyleabeauchamp** [etal/cnvkit#80]
This is based on my limited understanding, so I may need some correction here.  It seems like `cnvkit.py reference` is doing some GC / probeshape / mappability corrections (https://github.com/etal/cnvkit/blob/master/cnvlib/reference.py#L99).  However, the `reference` command does not expose the options to disable the individual corrections, while the `fix` command does expose these options. 

Three questions:

1.  What, exactly, then is the log2 column?  Is it the median across samples?  Does it contain the bias corrections?  When exactly do the bias corrections get added?
2.  Am I correct that this could lead to strange behavior if one constructed the reference but then called fix with a different set of bias correction flags?

Once I figure these out, I suppose we can add some discussion of the exact column meanings here: http://cnvkit.readthedocs.org/en/latest/pipeline.html#reference

**Comment by etal** [comment]
1. Basically [yes](https://github.com/etal/cnvkit/blob/master/cnvlib/reference.py#L130) (Tukey's biweight location, a weighted average that drops outliers); yes; before taking the weighted average. In the `fix` command the bias corrections are applied before subtracting the reference log2 values.
2. Yes, that's true, `fix` would overcorrect for the biases skipped in `reference`. I'll add those options to the `reference` command and update the docs.

Thanks for spotting the issue.
