### ISSUE TITLE
cnvkit batch overwrites clashing samples?

### ISSUE THREAD

**Issue by kyleabeauchamp** [etal/cnvkit#81]
Suppose you have two directories of normal samples, where the filenames sometimes overlap.  

```
./bams1/A.bam
./bams2/A.bam
```

When you call `cnvkit batch [...] --normal */*.bam --output ./out/`, cnvkit will use the base filenames for labeling the coverage files.  This means that cnvkit will overwrite outputs when base filenames are the same.  

I think there are two possible solutions:

1. Raise a ValueError if the base filenames are non-unique
2.  Uniquify the base filenames before outputting, say by adding a numerical index.  

I guess I personally prefer option (1) based on my experience with bcl2fastq, which does (2).

**Comment by etal** [comment]
Youch. How about checking for unique base names before `batch` does any processing, and by default raising an error; the error message can suggest an option (e.g. `--uniquify-names`) to explicitly rename files to avoid conflicts. The new name can be some function of full filename, directory name, and numerical index, maybe (e.g. `A_bams1.*.cnn` and `A_bams2.*.cnn`).

The pipeline commands other than `batch` operate on one sample at a time, so this functionality doesn't need to be shared.

**Comment by kyleabeauchamp** [comment]
Sounds good to me.

**Comment by kyleabeauchamp** [comment]
Thanks for the fix.  I did notice that the error is also raised if you have a sample that overlaps between your control and non-control groups.  Not a big deal, but it might surprise someone who was just globbing  their input files.
