### ISSUE TITLE
Running individual commands instead of 'batch' does not yield same *.cns file

### ISSUE THREAD

**Issue by nriMH** [etal/cnvkit#87]
Hi,

I am doing some parameter optimization with CNVkit (v0.7.5), which is why I replaced the 'batch' command by the individual commands as described in the documentation:

- target
- antitarget
- coverage
- reference
- fix
- segment

When running these with default parameters, they generate the same files as the batch command does, until the *.cnr file generated by the 'fix' command. The *cnr files are almost the same, except for the log2 values which are very similar, as for example:

< chr1	1146873	1147108	TNFRSF4	-0.84963	0.588972
< chr1	1147108	1147343	TNFRSF4	-0.74046	0.588972
< chr1	1147343	1147578	TNFRSF4	-0.97845	0.588972
< chr1	1147982	1148222	TNFRSF4	-1.20474	0.601504
< chr1	1148302	1148542	TNFRSF4	-1.24132	0.601504
< chr1	1148706	1148946	TNFRSF4	-1.21758	0.601504
< chr1	1148983	1149223	TNFRSF4	-1.19841	0.601504
< chr1	1149294	1149574	TNFRSF4	-1.06558	0.701754
---
> chr1	1146873	1147108	TNFRSF4	-0.851124	0.588972
> chr1	1147108	1147343	TNFRSF4	-0.822549	0.588972
> chr1	1147343	1147578	TNFRSF4	-0.984025	0.588972
> chr1	1147982	1148222	TNFRSF4	-1.19129	0.601504
> chr1	1148302	1148542	TNFRSF4	-1.24459	0.601504
> chr1	1148706	1148946	TNFRSF4	-1.21221	0.601504
> chr1	1148983	1149223	TNFRSF4	-1.19624	0.601504
> chr1	1149294	1149574	TNFRSF4	-1.06491	0.701754

The major issue, though, is that based on this very similar *.cnr file, the 'segment' command (cnvkit.py segment myfile.cnr -o myfile.cns) yields a totally different amount of regions (compared to the batch command) in the resulting *.cns file! Am I missing a default parameter? I tried adding some (like --drop-outliers) but to no avail.

Thanks a lot!

**Comment by etal** [comment]
Which parameters have you been changing in the steps before segmentation?

Have you tried plotting the .cnn, .cnr and .cns files with the `scatter` command to investigate where the extra variation or noise is happening? The log2 columns of the .cnr files might not look very different numerically, but the CBS algorithm is sensitive to the amount of noise in the input dataset.

You may also find it worth your while to update to the latest version of CNVkit, v0.7.9, which exposes some more parameter options. The release notes for all versions are [here](https://github.com/etal/cnvkit/releases).

**Comment by nriMH** [comment]
Hi Eric, thanks a lot for the quick reply!
I have not been changing any parameters yet, which is why I am a bit puzzled. I just followed the documentation to change the 'batch' command into individual commands.

Basically I am running the following:

cnvkit.py target ${BED_FILE} --split -o ${OUTDIR}/${BED_FILE_SUFFIX}.target.bed

cnvkit.py antitarget ${OUTDIR}/${BED_FILE_SUFFIX}.target.bed --access ${GENOME2ACCESS} -o ${OUTDIR}/${BED_FILE_SUFFIX}.antitarget.bed

cnvkit.py coverage ${INDIR_TUMOR}/${TUMOR_BAM}.bam ${OUTDIR}/${BED_FILE_SUFFIX}.target.bed -o ${OUTDIR}/${TUMOR_BAM}.targetcoverage.cnn --min-mapq 0

cnvkit.py coverage ${INDIR_TUMOR}/${TUMOR_BAM}.bam ${OUTDIR}/${BED_FILE_SUFFIX}.antitarget.bed -o ${OUTDIR}/${TUMOR_BAM}.antitargetcoverage.cnn --min-mapq 0

cnvkit.py reference -o ${OUTDIR}/reference.cnn -y -f ${REFERENCE_FASTA} -t ${OUTDIR}/${BED_FILE_SUFFIX}.target.bed -a ${OUTDIR}/${BED_FILE_SUFFIX}.antitarget.bed

cnvkit.py fix ${OUTDIR}/${TUMOR_BAM}.targetcoverage.cnn ${OUTDIR}/${TUMOR_BAM}.antitargetcoverage.cnn ${OUTDIR}/reference.cnn -o ${OUTDIR}/${TUMOR_BAM}.cnr

cnvkit.py segment ${OUTDIR}/${TUMOR_BAM}.cnr -o ${OUTDIR}/${TUMOR_BAM}.cns

Then, on the same data, as a comparison, I ran:

cnvkit.py batch ${INDIR_TUMOR}/${TUMOR_BAM}.bam --normal --targets ${BED_FILE} --fasta ${REFERENCE_FASTA} --split --access ${GENOME2ACCESS} --male-reference --output-dir ${OUTDIR}

The .cnn files are the same in both cases (batch cmd / no batch cmd), but from the cnr on things are different. Am I missing something here?

I will also look into the scatter command.

Thanks a lot!

**Comment by nriMH** [comment]
Hi Eric,

I've had a look at the scatter command outputs of the respective cn{r,s} files. It does show more noise in the files generated with the individual commands (no batch). However, I still don't understand how the exact same dataset leads to different output files. It looks like there is a threshold applied during the batch command that is not included in the individual commands. Can you help?

**Comment by etal** [comment]
I think there may be a difference in default settings between `batch` and either `fix` or `reference`. I'll see if I can find it; sorry for the trouble and delay.

**Comment by nriMH** [comment]
Thanks a lot!

**Comment by etal** [comment]
I've checked the defaults for `batch` and the other commands, and I can't find a difference in the code. There may have been a discrepency in v0.7.5, but it doesn't appear to be there now. Could you confirm with the current version of CNVkit? If the `.cnr` files or `reference.cnn` files are still different, could you send them to me, or post the scatter plots here? Also, could you check if the difference still persists if the `-p 1` option is used (to disable parallel processing)?

My guess is that one of both of these is happening:

1. There may have been a difference between `batch` and `fix` or `reference` in how the bias filters or the `--drop-low-coverage` option were applied to the samples in CNVkit v0.7.5. I think this has been corrected since then.
2. There is some randomness in how the bias corrections are implemented, and the random seed could be set or reset differently in `batch` versus `fix`. In the section of the .cnr file you showed here, I don't see any "Background" bins. If your dataset is from target amplicon capture, where no off-target bins are available, then the coverage values are generally noisier and there are fewer data points than with hybrid captures. Speculatively, in this case segmentation could be more sensitive to relatively small differences in log2 values and, especially in combination with guess 1,  produce substantially different segmentation results.

**Comment by nriMH** [comment]
Indeed, there were no off-target bins available in my test dataset, which was probably a poor choice. I did the comparison with another dataset (hybrid capture) but got similar issues. However, with the newest version (v0.7.10), while there are still slight differences in the log2 and other values displayed (both cnr and cns file), the total number and genomic positions of the CNVs called are the same between batch and no batch, which was not the case in v.0.7.5. 
Issue solved I guess! Thanks a lot for your help!

**Comment by etal** [comment]
Great to hear.

**Comment by andyjslee** [comment]
I would like to suggest why there is a discrepancy between running the 'batch' command and following the series of commands listed below "The pipeline executed by the batch command is equivalent to:" on the [readthedocs.io page](https://cnvkit.readthedocs.io/en/stable/pipeline.html).

When you run autobin using 'batch' command, the '--bp-per-bin' parameter gets set to 50,000 (line 73 in batch.py), whereas the default value for this parameter is 100,000 (line 25 in autobin.py). This difference probably leads to creation of different reference.cnn files, and ultimately affects generation of different cns files.

@etal Dr. Talevich, could you please confirm whether this is right? Thank you.
