### ISSUE TITLE
dockerhub link is dead (typo)

### ISSUE THREAD

**Issue by nickhsmith** [etal/cnvkit#875]
you link the docker image as https://registry.hub.docker.com/u/etal/cnvkit/ but I think it should be https://registry.hub.docker.com/r/etal/cnvkit/  

a **/r/** instead of **/u/**

**Comment by etal** [comment]
Thanks, looks like Docker Hub changed their routes at some point. Fixed here: https://github.com/etal/cnvkit/pull/878/commits/9dec3899b2e17a25f4faf9ad1c6cce072cd868ca
