### ISSUE TITLE
Huge PDF files from scatter and diagram

### ISSUE THREAD

**Issue by messersc** [etal/cnvkit#92]
Hello,

I have just started using cnvkit and generated my first results. However, I have the following problem: The PDF files generated with ```scatter``` and ```diagram``` are huge (80M and 200M) and take quite long to load into a PDF viewer.

Now, is this normal behavior or am I missing something?

**Comment by etal** [comment]
Yes, these PDF files can be huge, especially for exome or WGS. They're tolerable for target panels.

- For `scatter`, a manual workaround would be to run the command without specifying the output filename (`-o`), so the interactive plot appears on your screen, and then use the matplotlib controls in that window to save the file as PNG.
- For `diagram`, PDF is the only output option, but you can skip the .cnr file to show just the segments.

(Newer versions of matplotlib and reportlab might be able to generate more space-efficient PDFs, but I haven't checked this and am only speculating.)

Potential enhancements to CNVkit to address these problems:

- In `scatter`, allow PNG output by checking whether the specified output filename ends with ".png".
- In `diagram`, show gene names in CNVs when plotting only segments (.cns).

**Comment by messersc** [comment]
For use on a compute cluster, I can't use the interactive option.

My workaround for now is to just convert to a friendlier format:
```
 ls -1 *.pdf | parallel -j 4 --eta convert -density 150 '{}' -quality 90 '{.}.png'
```

One can add
```
-background white -alpha remove
```
to ```convert``` to add a white background to the diagram, apparently.
http://stackoverflow.com/questions/2322750/replace-transparency-in-png-images-with-white-background

**Comment by etal** [comment]
OK, thanks for letting me know. I'll file the two enhancement ideas as separate issues.
