### ISSUE TITLE
Heatmap chromosomes in a different natural order [error]

### ISSUE THREAD

**Issue by jgarces02** [etal/cnvkit#920]
Hi, I'm getting a weird heatmap with the chromosomes ordered in an unusual way. This only happens when multiple samples are plotted together, not one by one. Am I missing something?

<img width="463" alt="image" src="https://github.com/user-attachments/assets/43f8a9fd-9734-4d70-a501-a080e2127ec8">

Thanks!

**Comment by etal** [comment]
Is that the order they appear in your .cns file? Does that vary in these samples?

**Comment by jgarces02** [comment]
Sorry, but I removed the folder with the analysis 😓 . I'll let you know next time I run it.

Thanks!
