### ISSUE TITLE
scatter: optional PNG output instead of PDF

### ISSUE THREAD

**Issue by etal** [etal/cnvkit#93]
When writing the output image from matplotlib, check whether the specified output filename ends with ".png". If it does, write a PNG file instead of a PDF. This should result in a much smaller output file, especially for exome and WGS datasets.

(via #92)

**Comment by etal** [comment]
Fixed with #120

**Comment by sagarutturkar** [comment]
I am using **CNVkit/0.9.4** and I am able to get the PNG output with filename ending .png. However, the file size is huge similar to PNG. This is WGS data. A workaround I used to generate smaller size PNG was the linux command:   

`convert -density 300 -depth 8 -quality 100 -background white -alpha remove diagram.pdf   diagram.png`  
 
However, is there a way to avoid this extra step and get smaller size PNG through CNVkit?
