### ISSUE TITLE
Why cnvkit run with output error

### ISSUE THREAD

**Issue by gaihua559** [etal/cnvkit#96]
I install cnvkit recently and try to fun it, my command is:

    python2.7 /Software/cnvkit/cnvkit.py batch /Projects/P46-tumor.sorted.bam --normal /Projects/P46-blood.sorted.bam \
        --processes 0 --targets /APP/Panel2.bed --fasta /Data/HG19/hg19.fa \
        --split --access /Software/cnvkit/data/access-5k-mappable.hg19.bed \
        --output-reference /Work/P46/varscan0/tumor_blood.cnn --output-dir /Work/diagnosis2/P46/varscan0/

Then several minutes later, it show me following reports and I don't know why. Could any one help me? Thanks very much!

    Traceback (most recent call last):
    File "Software/cnvkit/cnvkit.py", line 11, in <module> args.func(args) 
    File "/Software/cnvkit/cnvlib/commands.py", line 97, in _cmd_batch args.processes, args.count_reads) 
    File "/Software/cnvkit/cnvlib/commands.py", line 182, in batch_make_reference male_reference) 
    File "/Software/cnvkit/cnvlib/commands.py", line 522, in do_reference do_gc, do_edge, False) 
    File "/Software/cnvkit/cnvlib/reference.py", line 40, in combine_probes cnarr1 = CNA.read(filenames[0]) 
    File "/Software/cnvkit/cnvlib/gary.py", line 460, in read dtype={'chromosome': 'string'}, 
    File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 529, in parser_f return _read(filepath_or_buffer, kwds) 
    File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 295, in _read parser = Text
    FileReader(filepath_or_buffer, *kwds) 
    File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 612, in __init__ self._make_engine(self.engine) 
    File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 747, in _make_engine self._engine = CParserWrapper(self.f, *self.options) 
    File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1119, in __init__ self._reader = _parser.TextReader(src, **kwds) 
    File "pandas/parser.pyx", line 353, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3246) 
    File "pandas/parser.pyx", line 591, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6111) 
    IOError: File varscan0/P46-blood.targetcoverage.cnn does not exist

**Comment by etal** [comment]
Do you have the complete log messages from this run? Further up, before the exception and error message, you should see a log message like "Wrote varscan0/P46-blood.targetcoverage.cnn". You should see other "Wrote ..." messages, too, and that may show you what's going wrong.

Is your current working directory (where you ran this command) `/Work/P46/`? Does the subdirectory `varscan0/` exist, and does it have permissions where your command should be able to write? If it doesn't exist, does the current directory `/Work/P46` have user-level permissions set to allow creating subdirectories? I see you have several different top-level directories in your command line, so if any of these directories have restricted permissions or are mounted on another physical volume, you may need to check each and adjust the permissions so that CNVkit is able to create the subdirectory and files within it.

**Comment by gaihua559** [comment]
Hi Eric,

Besides the error message show you yesterday, there are no "*.cnn" file
under "varscan0". However, there are "*.target.bed" and "*.antitarget.bed"
under "varscan0".
I tried to give "varscan0" authority 777 today. However, it still run
like yesterday.

Then I use "sudo" run this program, it still not work.

Wrote /work-a/Work/diagnosis2/P46/varscan0/Panel2.target.bed with 18900
regions
Detected file format: BED
Detected file format: BED
Skipping untargeted chromosome chrM
Wrote /work-a/Work/diagnosis2/P46/varscan0/Panel2.antitarget.bed with 29519
regions
Building a copy number reference from normal samples...
Processing reads in P46-blood.sorted.bam
Processing reads in P46-blood.sorted.bam
Loading /work-a/Work/diagnosis2/P46/varscan0/P46-blood.targetcoverage.cnn
Traceback (most recent call last):
  File "/work-a/Software/cnvkit/cnvkit.py", line 11, in <module>
    args.func(args)
  File "/work/Software/cnvkit/cnvlib/commands.py", line 97, in _cmd_batch
    args.processes, args.count_reads)
  File "/work/Software/cnvkit/cnvlib/commands.py", line 182, in
batch_make_reference
    male_reference)
  File "/work/Software/cnvkit/cnvlib/commands.py", line 522, in do_reference
    do_gc, do_edge, False)
  File "/work/Software/cnvkit/cnvlib/reference.py", line 40, in
combine_probes
    cnarr1 = CNA.read(filenames[0])
  File "/work/Software/cnvkit/cnvlib/gary.py", line 460, in read
    dtype={'chromosome': 'string'},
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line
529, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line
295, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line
612, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line
747, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line
1119, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 353, in pandas.parser.TextReader.__cinit__
(pandas/parser.c:3246)
  File "pandas/parser.pyx", line 591, in
pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6111)
IOError: File
/work-a/Work/diagnosis2/P46/varscan0/P46-blood.targetcoverage.cnn does not
exist


Thanks,
Gaihua



2016-04-15 1:26 GMT+08:00 Eric Talevich <notifications@github.com>:

> Do you have the complete log messages from this run? Further up, before
> the exception and error message, you should see a log message like "Wrote
> varscan0/P46-blood.targetcoverage.cnn". You should see other "Wrote ..."
> messages, too, and that may show you what's going wrong.
>
> Is your current working directory (where you ran this command) /Work/P46/?
> Does the subdirectory varscan0/ exist, and does it have permissions where
> your command should be able to write? If it doesn't exist, does the current
> directory /Work/P46 have user-level permissions set to allow creating
> subdirectories? I see you have several different top-level directories in
> your command line, so if any of these directories have restricted
> permissions or are mounted on another physical volume, you may need to
> check each and adjust the permissions so that CNVkit is able to create the
> subdirectory and files within it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/etal/cnvkit/issues/96#issuecomment-210063673>
>



-- 

Address: Mayo Clinic, Jacksonville, FL (32224)

               Griffin Building, 2# 251

Tel:         904-515-6128

**Comment by etal** [comment]
Are you using a recent version of CNVkit, e.g. v0.7.9 or v0.7.10? If you're not sure, you can find out with `cnvkit.py version` -- and if that command doesn't exist, then it's an old version of CNVkit.

The `batch` procedure should have written the .cnn files and logged "Wrote ...targetcoverage.cnn" just before the log message "Loading ...targetcoverage.cnn". Since those messages are missing, this might be the elusive bug #55. Could you tell me more about the platform you're using, e.g. operating system & version? Then, could you try running the same command without "--processes 0" so that parallelism is disabled?

**Comment by gaihua559** [comment]
0.7.9.dev0
#64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64
GNU/Linux
I else have used command without "--processes 0".
I think it is not the bug #55.

Thanks!

2016-04-16 13:15 GMT+08:00 Eric Talevich <notifications@github.com>:

> Are you using a recent version of CNVkit, e.g. v0.7.9 or v0.7.10? If
> you're not sure, you can find out with cnvkit.py version -- and if that
> command doesn't exist, then it's an old version of CNVkit.
>
> The batch procedure should have written the .cnn files and logged "Wrote
> ...targetcoverage.cnn" just before the log message "Loading
> ...targetcoverage.cnn". Since those messages are missing, this might be the
> elusive bug #55 <https://github.com/etal/cnvkit/issues/55>. Could you
> tell me more about the platform you're using, e.g. operating system &
> version? Then, could you try running the same command without "--processes
> 0" so that parallelism is disabled?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/etal/cnvkit/issues/96#issuecomment-210738470>
>



-- 

Address: Mayo Clinic, Jacksonville, FL (32224)

               Griffin Building, 2# 251

Tel:         904-515-6128

**Comment by gaihua559** [comment]
OK, I have installed 0.7.11.dev0.
It seems it works.

Thank you!

2016-04-18 8:54 GMT+08:00 Gaihua Zhang <gaihua559@gmail.com>:

> 0.7.9.dev0
> #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64
> GNU/Linux
> I else have used command without "--processes 0".
> I think it is not the bug #55.
>
> Thanks!
>
> 2016-04-16 13:15 GMT+08:00 Eric Talevich <notifications@github.com>:
>
>> Are you using a recent version of CNVkit, e.g. v0.7.9 or v0.7.10? If
>> you're not sure, you can find out with cnvkit.py version -- and if that
>> command doesn't exist, then it's an old version of CNVkit.
>>
>> The batch procedure should have written the .cnn files and logged "Wrote
>> ...targetcoverage.cnn" just before the log message "Loading
>> ...targetcoverage.cnn". Since those messages are missing, this might be the
>> elusive bug #55 <https://github.com/etal/cnvkit/issues/55>. Could you
>> tell me more about the platform you're using, e.g. operating system &
>> version? Then, could you try running the same command without "--processes
>> 0" so that parallelism is disabled?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/etal/cnvkit/issues/96#issuecomment-210738470>
>>
>
>
>
> --
>
> Address: Mayo Clinic, Jacksonville, FL (32224)
>
>                Griffin Building, 2# 251
>
> Tel:         904-515-6128
>



-- 

Address: Mayo Clinic, Jacksonville, FL (32224)

               Griffin Building, 2# 251

Tel:         904-515-6128

**Comment by etal** [comment]
Great to hear.

**Comment by gaihua559** [comment]
At last, it delivers as following error:

Processing target: P46-tumor
Traceback (most recent call last):
  File "./cnvkit.py", line 11, in <module>
    args.func(args)
  File "/Software/cnvkit-master/cnvlib/commands.py", line 118, in _cmd_batch
    args.diagram, args.rlibpath, args.count_reads))
  File "/Software/cnvkit-master/cnvlib/parallel.py", line 14, in apply_async
    func(*args)
  File "/Software/cnvkit-master/cnvlib/commands.py", line 212, in
batch_run_sample
    cnarr = do_fix(raw_tgt, raw_anti, _CNA.read(ref_fname))
  File "/Software/cnvkit-master/cnvlib/commands.py", line 607, in do_fix
    do_gc, do_edge, False)
  File "/Software/cnvkit-master/cnvlib/fix.py", line 23, in
load_adjust_coverages
    ref_matched = match_ref_to_probes(ref_pset, pset)
  File "/Software/cnvkit-master/cnvlib/fix.py", line 91, in
match_ref_to_probes
    % (num_missing, probes.sample_id))
ValueError: Reference is missing 18900 bins found in P46-tumor

However, there are some *.cnn file under varscan0:
P46-blood.antitargetcoverage.cnn
P46-blood.targetcoverage.cnn
P46-tumor.antitargetcoverage.cnn
P46-tumor.targetcoverage.cnn
tumor_blood.cnn

I think "tumor_blood.cnn" may enough for me.

Thank you!


2016-04-18 9:51 GMT+08:00 Eric Talevich <notifications@github.com>:

> Great to hear.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/etal/cnvkit/issues/96#issuecomment-211152259>
>



-- 

Address: Mayo Clinic, Jacksonville, FL (32224)

               Griffin Building, 2# 251

Tel:         904-515-6128

**Comment by gaihua559** [comment]
Hi, it seems it not works for:
cnvkit.py reference /work-c/P46-blood.sorted.bam -t
/work-a/P46/varscan0/Panel2.target.bed -a
/work-a/varscan0/Panel2.antitarget.bed -f /work-a/Data/HG19/hg19.fa -o
P46-blood.cnn

Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 5, in <module>
    pkg_resources.run_script('CNVkit==0.7.11.dev0', 'cnvkit.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in
run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in
run_script
    exec(script_code, namespace, namespace)
  File
"/usr/local/lib/python2.7/dist-packages/CNVkit-0.7.11.dev0-py2.7.egg/EGG-INFO/scripts/cnvkit.py",
line 11, in <module>

  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 481, in
_cmd_reference

AssertionError: Give .cnn samples OR targets and antitargets.

Thanks!

2016-04-18 10:15 GMT+08:00 Gaihua Zhang <gaihua559@gmail.com>:

> At last, it delivers as following error:
>
> Processing target: P46-tumor
> Traceback (most recent call last):
>   File "./cnvkit.py", line 11, in <module>
>     args.func(args)
>   File "/Software/cnvkit-master/cnvlib/commands.py", line 118, in
> _cmd_batch
>     args.diagram, args.rlibpath, args.count_reads))
>   File "/Software/cnvkit-master/cnvlib/parallel.py", line 14, in
> apply_async
>     func(*args)
>   File "/Software/cnvkit-master/cnvlib/commands.py", line 212, in
> batch_run_sample
>     cnarr = do_fix(raw_tgt, raw_anti, _CNA.read(ref_fname))
>   File "/Software/cnvkit-master/cnvlib/commands.py", line 607, in do_fix
>     do_gc, do_edge, False)
>   File "/Software/cnvkit-master/cnvlib/fix.py", line 23, in
> load_adjust_coverages
>     ref_matched = match_ref_to_probes(ref_pset, pset)
>   File "/Software/cnvkit-master/cnvlib/fix.py", line 91, in
> match_ref_to_probes
>     % (num_missing, probes.sample_id))
> ValueError: Reference is missing 18900 bins found in P46-tumor
>
> However, there are some *.cnn file under varscan0:
> P46-blood.antitargetcoverage.cnn
> P46-blood.targetcoverage.cnn
> P46-tumor.antitargetcoverage.cnn
> P46-tumor.targetcoverage.cnn
> tumor_blood.cnn
>
> I think "tumor_blood.cnn" may enough for me.
>
> Thank you!
>
>
> 2016-04-18 9:51 GMT+08:00 Eric Talevich <notifications@github.com>:
>
>> Great to hear.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/etal/cnvkit/issues/96#issuecomment-211152259>
>>
>
>
>
> --
>
> Address: Mayo Clinic, Jacksonville, FL (32224)
>
>                Griffin Building, 2# 251
>
> Tel:         904-515-6128
>



-- 

Address: Mayo Clinic, Jacksonville, FL (32224)

               Griffin Building, 2# 251

Tel:         904-515-6128

**Comment by etal** [comment]
For the `reference` command, to build a reference from one blood sample, try it like this:

    cnvkit.py reference varscan0/P46-blood.targetcoverage.cnn varscan0/P46-blood.antitargetcoverage.cnn -f /work-a/Data/HG19/hg19.fa -o P46-blood.cnn

Then, to process your tumor sample using the matched blood reference:

    cnvkit.py fix P46-tumor.targetcoverage.cnn P46-tumor.antitargetcoverage.cnn P46-blood.cnn -o P46-tumor.cnr
    cnvkit.py segment P46-tumor.cnr

If this doesn't work for you, could you send me the .cnn and .bed files for this pair, preferably as a ZIP file? A Dropbox link or e-mail attachment is fine.

**Comment by etal** [comment]
I just fixed a bug that might have been causing your problem. Can you pull the latest from Github and try the commands I suggested above? If `reference` and `fix` work for you now, then could you try `batch` and see if it works for you too?

**Comment by gaihua559** [comment]
$ cnvkit.py reference /work-c/merged/P46-blood.sorted.bam -t
/work-a/P46/varscan0/Panel2.target.bed -a
/work-a/P46/varscan0/Panel2.antitarget.bed -f /work-a/Data/HG19/hg19.fa -o
P46-blood.cnn
Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 5, in <module>
    pkg_resources.run_script('CNVkit==0.7.11.dev0', 'cnvkit.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in
run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in
run_script
    exec(script_code, namespace, namespace)
  File
"/usr/local/lib/python2.7/dist-packages/CNVkit-0.7.11.dev0-py2.7.egg/EGG-INFO/scripts/cnvkit.py",
line 11, in <module>

  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 481, in
_cmd_reference

AssertionError: Give .cnn samples OR targets and antitargets.


$ cnvkit.py reference /work-c/merged/P46-blood.sorted.bam
/work/P46/varscan0/P46-blood.targetcoverage.cnn
/work/P46/varscan0/P46-blood.antitargetcoverage.cnn -f
/work-a/Data/HG19/hg19.fa -o /work/P46/P46-blood.cnn
Number of target and antitarget files: 2, 1
Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 5, in <module>
    pkg_resources.run_script('CNVkit==0.7.11.dev0', 'cnvkit.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in
run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in
run_script
    exec(script_code, namespace, namespace)
  File
"/usr/local/lib/python2.7/dist-packages/CNVkit-0.7.11.dev0-py2.7.egg/EGG-INFO/scripts/cnvkit.py",
line 11, in <module>

  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 500, in
_cmd_reference

  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 514, in
do_reference

  File "build/bdist.linux-x86_64/egg/cnvlib/core.py", line 97, in
assert_equal
ValueError: Unequal number of target and antitarget files given:
antitargets = 1, targets = 2


It seems it is the same.
Here I use a special panel for DNA capture and sequencing. Then I tried to
detect CNV from these samples. Some fragments maybe only 100bp. The
inter-region between some fragments maybe less than 100 bp.
Then the hg19.fa was downloaded from UCSC database.

So would the fault from the special fragment size and location?

Thanks,
Gaihua




2016-04-20 13:27 GMT+08:00 Eric Talevich <notifications@github.com>:

> I just fixed a bug that might have been causing your problem. Can you pull
> the latest from Github and try the commands I suggested above? If
> reference and fix work for you now, then could you try batch and see if
> it works for you too?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/etal/cnvkit/issues/96#issuecomment-212265343>
>



-- 

Address: Mayo Clinic, Jacksonville, FL (32224)

               Griffin Building, 2# 251

Tel:         904-515-6128

**Comment by etal** [comment]
Try the commands I showed you. The `reference` command doesn't take a BAM file (see the [documentation](http://cnvkit.readthedocs.org/en/latest/pipeline.html#reference)). Instead, it works either of two ways:

1. Give it all the .targetcoverage.cnn and .antitargetcoverage.cnn from your blood/normal samples. It constructs a paired or pooled reference.
2. Give it only the target and antitarget BED files. (No sample .cnn or .bam files.) It constructs a "flat" reference with the genomic coordinates and GC/RepeatMasker information from the BED and FASTA files.

I'm recommending option 1 since you have a paired blood sample.

**Comment by gaihua559** [comment]
Hi Eric,

It works very well now.
Thank you very much!

Gaihua

2016-04-20 22:37 GMT+08:00 Eric Talevich <notifications@github.com>:

> Try the commands I showed you. The reference command doesn't take a BAM
> file (see the documentation
> <http://cnvkit.readthedocs.org/en/latest/pipeline.html#reference>).
> Instead, it works either of two ways:
>
>    1. Give it all the .targetcoverage.cnn and .antitargetcoverage.cnn
>    from your blood/normal samples. It constructs a paired or pooled reference.
>    2. Give it only the target and antitarget BED files. (No sample .cnn
>    or .bam files.) It constructs a "flat" reference with the genomic
>    coordinates and GC/RepeatMasker information from the BED and FASTA files.
>
> I'm recommending option 1 since you have a paired blood sample.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/etal/cnvkit/issues/96#issuecomment-212450675>
>



-- 

Address: Mayo Clinic, Jacksonville, FL (32224)

               Griffin Building, 2# 251

Tel:         904-515-6128

**Comment by etal** [comment]
Great to hear.
