### ISSUE TITLE
b-allele frequencies /loh and plotting

### ISSUE THREAD

**Issue by sarmadym** [etal/cnvkit#99]
Hi,

Is there a way to calculate b-allele frequencies and plot them?
 
Thanks
Mahdi

**Comment by etal** [comment]
Yes, if you have SNV calls in a VCF file you can plot them with the scatter
command using the -v option. The online docs show an example of this.

**Comment by sarmadym** [comment]
Thank you. So having the vcf of somatic SNVs is a must, correct? Does it work well for tumor only samples where vcf is a mix of germline and somatic variants?

Fantastic tool by the way! We just started working it it. Thanks!

**Comment by etal** [comment]
Yes, you do need the tumor sample VCF. Unpaired, tumor-only calling will
work OK usually; you can filter out some of the non-germline SNVs by
intersecting your VCF with a set of known population SNPs, e.g.  dbSNP or
1000 Genomes.
